### ISSUE TITLE
[Bug]无法正常使用

### ISSUE THREAD

**Issue by Azusa-Lover** [Harry-zklcdc/go-proxy-bingai#1]
**泰！裤！辣！**
但是又出Bug力（悲
在服务选择里Bing官方于Cloud flare正常
但是我一旦输入任何东西就提示“很抱歉，似乎出现错误。 让我们重新开始吧。”
~~哼哼哼啊啊啊啊啊啊啊啊啊啊啊啊~~
反复一键重置，填用户Cookie什么的都没用。
有什么办法解决吗

**Comment by Azusa-Lover** [comment]
@Harry-zklcdc ？

**Comment by Harry-zklcdc** [comment]
看起来像是你的服务端问题（不是cloudflare），无法创建对话
