### ISSUE TITLE
windows部署本地链接显示本站可用，非本地连接本站就失效了

### ISSUE THREAD

**Issue by Nothingness-Void** [Harry-zklcdc/go-proxy-bingai#10]
如题，
本地连接时
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/55913486/a08555ad-a453-4de9-9730-90b3e3f71088)

远程连接时
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/55913486/c8bcc212-302e-4d50-80c5-d565eaaa44a0)

服务是我跟linux服务器一样用caddy转成Https的

**Comment by Harry-zklcdc** [comment]
没有配置 `WebSocket` 转发设置，`caddy` 的配置我不熟悉，`Nginx` 我有一套配置，参考: https://github.com/adams549659584/go-proxy-bingai/issues/282#issuecomment-1605262801

**Comment by Harry-zklcdc** [comment]
没有配置 `WebSocket` 转发设置，`caddy` 的配置我不熟悉，`Nginx` 我有一套配置，参考: https://github.com/adams549659584/go-proxy-bingai/issues/282#issuecomment-1605262801

**Comment by Nothingness-Void** [comment]
> 没有配置 `WebSocket` 转发设置，`caddy` 的配置我不熟悉，`Nginx` 我有一套配置，参考: [adams549659584#282 (comment)](https://github.com/adams549659584/go-proxy-bingai/issues/282#issuecomment-1605262801)
大佬我把配置文件加进去提示这个  
nginx: [emerg] unknown "proxy_add_forwarded" variable
我问了Bing说是要改东西
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/55913486/64e5dca5-0059-4d34-8c47-b129580b797e)
没用过nginx没把握，还请大佬帮忙看看

配置文件如下

`
#user  nobody;
worker_processes  1;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    proxy_cache_path /tmp/nginx/temp/cache_one levels=1:2 keys_zone=cache_one:100m inactive=7d max_size=30g;
   
    map $http_upgrade $connection_upgrade {
      default upgrade;
        '' close;
            }


    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    server {
        listen       443 ssl;
        server_name  localhost;

        ssl_certificate      C:/Users/NothingnessVoid/Desktop/nginx-1.25.1/ai.nothingnessvoid.tech.cer;
        ssl_certificate_key  C:/Users/NothingnessVoid/Desktop/nginx-1.25.1/ai.nothingnessvoid.tech.key;

        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;

        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;

        location / {
		proxy_pass http://127.0.0.1:8080;
 		proxy_http_version        1.1;
 		proxy_cache_bypass     $http_upgrade;

 		# Proxy headers
 		proxy_set_header Upgrade                   $http_upgrade;
 		proxy_set_header Connection               $connection_upgrade;
 		proxy_set_header Host                          $host;
 		proxy_set_header X-Real-IP                  $remote_addr;
 		proxy_set_header Forwarded                $proxy_add_forwarded;
 		proxy_set_header X-Forwarded-For      $proxy_add_x_forwarded_for;
 		proxy_set_header X-Forwarded-Proto   $scheme;
 		proxy_set_header X-Forwarded-Host    $host;
 		proxy_set_header X-Forwarded-Port     $server_port;

 		# Proxy timeouts
 		proxy_connect_timeout         60s;
 		proxy_send_timeout              60s;
 		proxy_read_timeout              60s;

 		proxy_buffers                         256 256k;  
 		proxy_buffer_size                  256k;

 		#Set Nginx Cache
 		add_header X-Cache $upstream_cache_status;
 		if ( $uri ~* "\.(gif|png|jpg|css|js|woff|woff2)$" )
 		{
 		 	expires 10080m;
 		}
 		proxy_ignore_headers Set-Cookie Cache-Control expires;
 		proxy_cache cache_one;
 		proxy_cache_key $host$uri$is_args$args;
 		proxy_cache_valid 200 304 301 302 1m;
	}
    }

}
`

**Comment by Nothingness-Void** [comment]
我参考了https://github.com/adams549659584/go-proxy-bingai/issues/195内的nginx配置 运行完之后本站依旧不可用
