### ISSUE TITLE
[访问部署的该服务，一直提示正在尝试重新连接] 🐛 

### ISSUE THREAD

**Issue by sunzongjian** [Harry-zklcdc/go-proxy-bingai#100]
### Describe the bug

Failed to load resource: the server responded with a status of 404 
WebSocket connection to 'wss://sydney.bing.com/sydney/ChatHub' failed: 

### Steps to reproduce

在部署的newbing的搜索引擎框，输入内容发送就会报如上问题

### Expected behavior

根据输入内容，成功响应并返回结果

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/24264891/b50a7e5e-f836-49a0-ac83-71d8dcfdc926)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/24264891/f0f3d0d5-045d-4f03-ba74-b98b71b93d4a)

### Versions

newbing 最新版本

**Comment by Harry-zklcdc** [comment]
聊天服务设置为本站

**Comment by sunzongjian** [comment]
我的域名是在阿里云注册的mianf免费域名，并将dns绑定到了cloudflare上面，这里提示无效域是什么意思啊，不能用免费域名吗？
这是选择本站访请求时的错误，还请大佬帮忙看看
![QQ图片20230807081535](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/24264891/86589de4-9465-42c3-836c-3e622602e733)

**Comment by Harry-zklcdc** [comment]
无效域的问题搜一下issue，解决办法我在整理了

**Comment by sunzongjian** [comment]
好的，谢谢大佬

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: zklcdc ***@***.***>
发送时间: Monday, August 7, 2023 9:38:55 AM
收件人: Harry-zklcdc/go-proxy-bingai ***@***.***>
抄送: sunzongjian ***@***.***>; Author ***@***.***>
主题: Re: [Harry-zklcdc/go-proxy-bingai] [访问部署的该服务，一直提示正在尝试重新连接] 🐛 (Issue #100)


无效域的问题搜一下issue，解决办法我在整理了

**Comment by Xqh-Cxy** [comment]
> 我的域名是在阿里云注册的免费域名，并将dns绑定到了cloudflare上面，这里提示无效域是什么意思啊，不能用免费域名吗？ 这是选择本站访请求时的错误，还请大佬帮忙看看 ![QQ图片20230807081535](https://usercontent.githubfast.com/user-images/24264891/258673366-86589de4-9465-42c3-836c-3e622602e733.png)

免费域名？怎么获得的

**Comment by sunzongjian** [comment]
去阿里云服务器申请

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Xqh-Cxy ***@***.***>
发送时间: Monday, August 7, 2023 2:21:03 PM
收件人: Harry-zklcdc/go-proxy-bingai ***@***.***>
抄送: sunzongjian ***@***.***>; Author ***@***.***>
主题: Re: [Harry-zklcdc/go-proxy-bingai] [访问部署的该服务，一直提示正在尝试重新连接] 🐛 (Issue #100)


我的域名是在阿里云注册的免费域名，并将dns绑定到了cloudflare上面，这里提示无效域是什么意思啊，不能用免费域名吗？ 这是选择本站访请求时的错误，还请大佬帮忙看看 [QQ图片20230807081535] <https://camo.githubusercontent.com/bb2499b36887a6ffe07a4307dc65f8bcc995c10a9427362c85f919acfc6b6d42/68747470733a2f2f75736572636f6e74656e742e676974687562666173742e636f6d2f757365722d696d616765732f32343236343839312f3235383637333336362d38363538396465342d393436352d343263332d383336632d3365363232363032653733332e706e67>

免费域名？怎么获得的
