### ISSUE TITLE
早上还正常运行，可以正常回答。下午打开一直转圈圈打不开了，不知道啥原因，重装操纵系统，重新也是这样。正确设置了3个值。

### ISSUE THREAD

**Issue by ccodingfundddd** [Harry-zklcdc/go-proxy-bingai#101]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/139052477/6f85659a-863f-453d-9660-f5cbbb3d98a7)

**Comment by ccodingfundddd** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/139052477/bd817a64-1478-4587-8916-43bdb3cb8c6e)

**Comment by Harry-zklcdc** [comment]
服务器IP被封了，访问不了newbing
