### ISSUE TITLE
[教程]简易问题解决路径

### ISSUE THREAD

**Issue by SokWith** [Harry-zklcdc/go-proxy-bingai#103]
常见问题有3个:重新开始吧，人机验证，无效域，通常由3个原因引起:
1，GET create失败，主要是核心API没有被加载，需要从网路上找原因。
2，人机验证和无效域，通常是IP锁和ID锁了，可以如下判定:
ID锁，科学验证；
IP锁，用NewBingGoGo插件版使用服务器做魔法链接魔法聊天，失败一般都是IP锁了。
现在cf 的IP锁发生率还是很低的，最大的难题还是ID cookie一般只有1天的有效期，大大限制了普通用户的使用。

**Comment by SokWith** [comment]
我3个测试站点:

https://vercel.nbing.eu.org
https://replit.nbing.eu.org
https://cfwk.nbing.eu.org

后端都是用的cf的workes，内置ID，一般只需要科学验证后就可以稳定公开一天。

**Comment by xkwjyu** [comment]
> 我3个测试站点:
> 
> https://vercel.nbing.eu.org https://replit.nbing.eu.org https://cfwk.nbing.eu.org
> 
> 后端都是用的cf的workes，内置ID，一般只需要科学验证后就可以稳定公开一天。

workes的代码能否发给我qq385897零，或者q邮箱也可以，我的部署完后，用不了，出现：正在尝试连接，请稍候，一直都是这样，

**Comment by SokWith** [comment]
> > 我3个测试站点:
> > https://vercel.nbing.eu.org https://replit.nbing.eu.org https://cfwk.nbing.eu.org
> > 后端都是用的cf的workes，内置ID，一般只需要科学验证后就可以稳定公开一天。
> 
> workes的代码能否发给我qq385897零，或者q邮箱也可以，我的部署完后，用不了，出现：正在尝试连接，请稍候，一直都是这样，

https://github.com/Harry-zklcdc/go-proxy-bingai/issues/71#issuecomment-1665678322
代码没有改变，改变的是前端核心API加载方式

**Comment by xkwjyu** [comment]
> > > 我3个测试站点:
> > > https://vercel.nbing.eu.org https://replit.nbing.eu.org https://cfwk.nbing.eu.org
> > > 后端都是用的cf的workes，内置ID，一般只需要科学验证后就可以稳定公开一天。
> > 
> > 
> > workes的代码能否发给我qq385897零，或者q邮箱也可以，我的部署完后，用不了，出现：正在尝试连接，请稍候，一直都是这样，
> 
> [#71 (comment)](https://github.com/Harry-zklcdc/go-proxy-bingai/issues/71#issuecomment-1665678322) 代码没有改变，改变的是前端核心API加载方式
好吧，谢谢

**Comment by SokWith** [comment]
内置ID的24小时用量还是太少了，才19:00，vercel replit两个站点都超量了。看cf上的用量，还非常的少

**Comment by SokWith** [comment]
感谢参与测试的朋友，若可能，可以用自己的ID去测试看看什么时候触发IP锁？

**Comment by SokWith** [comment]
> 我3个测试站点:
> 
> https://vercel.nbing.eu.org https://replit.nbing.eu.org https://cfwk.nbing.eu.org
> 
> 后端都是用的cf的workes，内置ID，一般只需要科学验证后就可以稳定公开一天。

3个测试站点基本说明:
有参与测试的朋友创新的以聊天记录作为聊天界面进行交流，也有朋友认为共享聊天记录涉及隐私，所以，再说明一下:
1，3个站点都内置ID，3个不同的小号ID。无论有没有显示聊天记录，ID内都有聊天记录，特别是replit和cfwk，由于没有显示，所以不能主动删除。但是，仅仅只是一个聊天记录，只能说明世界上有那么个人询问了那么个事，我没有代码编写能力，用的都是免费版的站点，查阅不到任何log，更谈不上追踪终端。共享聊天记录反而体验多样的人生际遇。
2，replit能够使用的原因，是在cf里面追加了/turing的路由，由于没有添加image等其它路由，所以不能作文画画。
3，cfwk能直接使用的原因，是手动下载了核心js文件手动替换域名后放在web目录下初始化时主动加载的。
4，最最核心的测试，我在cf里面写死了IP转发，主要是测试这种写死IP写死ID的站点存活性能。这是方便分享给一般没有计算机基础的朋友的简单方式。

**Comment by SokWith** [comment]
由于8月9日晚旅行的地方没有电脑能去更新ID锁，10日3个站点的表现大相径庭:
1.表现最初的是replit，重置更新到1.11.4版本后失去缓存的支持，完全不能进行聊天了。
2.cfwk站点重置更新后，本站服务器不能解ID锁，只能使用bing官方服务器展开聊天。
3.表现优异的是vercel站点，使用本站服务器，居然将9日晚已经锁了的ID自行验证解锁了，下面这个参与测试的朋友一定会特异功能，中了彩蛋了。
![IMG_20230810_164818](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/38e9105d-03cc-4e58-a8b6-3d3a6b5564b0)
![IMG_20230810_164840](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/8002ce46-beff-448d-bdf7-936ac2bae076)

**Comment by SokWith** [comment]
嘿嘿嘿，我也触发彩蛋了。
发现无效域后，我手机一键重置，点击讽刺后居然解锁了。
后面发问的是哪个朋友?
![IMG_20230810_171015](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/e3038522-2b17-4fa8-83c1-fe9e0758c609)

**Comment by SokWith** [comment]
对参与测试的朋友们说明一下，聊天记录只是默认为关闭，手动打开后就可以看见了。

**Comment by SokWith** [comment]
> 嘿嘿嘿，我也触发彩蛋了。 发现无效域后，我手机一键重置，点击讽刺后居然解锁了。 后面发问的是哪个朋友? ![IMG_20230810_171015](https://user-images.githubusercontent.com/129967025/259690116-e3038522-2b17-4fa8-83c1-fe9e0758c609.jpg)

感觉应该是激励我那位朋友触发的彩蛋，我只是刚好接上了😓

**Comment by SokWith** [comment]
旅行了几个地方，发现一些网络差异：
1、有些地方居然可以直接使用官方服务器：https://sydney.bing.com，大多数地方是不可以的。
2、能使用官方服务器的地方，有几率直接过人机验证，比如科学上网后。
3、原本以为replit站点down了几天，回来发现居然昨天还活着，难道是测试的朋友一直用的缓存？
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/76d227a0-57a9-4ba1-9775-9d174ca12aba)

4、cfwk站点居然只科学上网就通过了人机验证，都没有去官网走一圈。
5、vercel的内置id最终只坚持了3天，最终还是得去官网人机验证。

6、都没有ip锁。
