### ISSUE TITLE
还是有反人类验证

### ISSUE THREAD

**Issue by Aoan2011** [Harry-zklcdc/go-proxy-bingai#104]
每次使用作者的演示站都有人机验证，虽然是成功，但验证了 30 次都没有用，还要验证？

我就是一个人类为什么还要验证这么多次？

**Comment by Harry-zklcdc** [comment]
教程待发布

**Comment by Harry-zklcdc** [comment]
已发布：
https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/%E8%A7%A3%E5%86%B3-%E6%97%A0%E6%95%88%E5%9F%9F&%E4%BA%BA%E6%9C%BA%E9%AA%8C%E8%AF%81
