### ISSUE TITLE
[Help] 🤔 “完整cookie”要怎么填写？

### ISSUE THREAD

**Issue by FangZirui-E5** [Harry-zklcdc/go-proxy-bingai#105]
### Describe the help wanted

在[Releases](https://github.com/Harry-zklcdc/go-proxy-bingai/releases)的最新发行版本的说明中提到了“教程待补充”，但我看到距离v1.11.3发布后的五个小时之后还是没有教程，（或许是我比较急），所以想在这里提前先问一下“完整cookie”要如何填写。
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129593198/d333bbec-ac77-4895-a914-820f8bec0ac2)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129593198/06457d27-e120-4985-a9e2-e3229c6c1865)

### Steps to behave

无

### Expected behavior

加入Harry不介意的话可以在这里提前和我说一下（如何介意就算了，我就老实等待教程发布）

### Screenshots

无

### Versions

- OS: <Windows 10>
- Browser & Version: <都一样>
- GoProxiBing Version: <1.11.3>

**Comment by Harry-zklcdc** [comment]
https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/%E8%8E%B7%E5%8F%96-Cookie

**Comment by FangZirui-E5** [comment]
好的，谢谢Thanks♪(･ω･)ﾉ

**Comment by FangZirui-E5** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129593198/be24b7c9-31f3-49e5-be80-a1bd55ef0b84)

**Comment by Harry-zklcdc** [comment]
对，而且要发送对话之后才有

**Comment by FangZirui-E5** [comment]
好的
