### ISSUE TITLE
VPS部署的突然打开不了网页了，升级也不行。之前好好的，突然就打不开了。辛苦作者看一下了。

### ISSUE THREAD

**Issue by ccodingfundddd** [Harry-zklcdc/go-proxy-bingai#106]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/139052477/d1e0297c-28f5-46d1-8bf8-d50f3401dff4)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/139052477/40b6e26e-9df6-4015-ba4c-c80d38343af0)

**Comment by Harry-zklcdc** [comment]
服务器问题？不明确，需要更多信息

**Comment by SokWith** [comment]
https://github.com/Harry-zklcdc/go-proxy-bingai/issues/103#issue-1838485571
三步走，首要排除官方的封锁

**Comment by renqabs** [comment]
adguard插件的问题？？？

**Comment by ccodingfundddd** [comment]
好的，谢谢，我看看。
