### ISSUE TITLE
[Feature] 🌈 解决 无效域/人机验证

### ISSUE THREAD

**Issue by Harry-zklcdc** [Harry-zklcdc/go-proxy-bingai#108]
查看 [wiki/解决 无效域&人机验证](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/%E8%A7%A3%E5%86%B3-%E6%97%A0%E6%95%88%E5%9F%9F&%E4%BA%BA%E6%9C%BA%E9%AA%8C%E8%AF%81)

**Comment by cutexiaoguigui** [comment]
请问为什么我一直都在验证呢？
<img width="1080" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/131460253/2883f914-5f47-4ef8-8d32-ac14c124fcb0">

**Comment by sunzongjian** [comment]
我也是

**Comment by sunzongjian** [comment]
你最好贴下控制台代码

**Comment by Harry-zklcdc** [comment]
完整描述一下你的操作

**Comment by cutexiaoguigui** [comment]
就是根据wiki/解决无效域&人机验证操作后，访问时就出现了这样的问题
控制台的代码是：
<img width="1080" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/131460253/e1a60e95-1152-4c17-891b-764135567c8f">

**Comment by Harry-zklcdc** [comment]
试一下演示站，我昨天是用演示站实验的

**Comment by Harry-zklcdc** [comment]
你的whistle的配置是啥

**Comment by cutexiaoguigui** [comment]
我的是
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/131460253/46ee371a-8028-4031-9096-ee68bb522acf)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/131460253/267849c7-dd6e-403e-9cb2-ba0c8f60664c)

**Comment by Harry-zklcdc** [comment]
> 我的是 [image](https://user-images.githubusercontent.com/131460253/258958778-46ee371a-8028-4031-9096-ee68bb522acf.png) [image](https://user-images.githubusercontent.com/131460253/258958790-267849c7-dd6e-403e-9cb2-ba0c8f60664c.png)

看一下proxy的配置，在左上角 `whistle` - `proxy`

**Comment by cutexiaoguigui** [comment]
<img width="343" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/131460253/93b18622-4df6-497a-9cf6-3d850362cf68">

**Comment by cutexiaoguigui** [comment]
<img width="341" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/131460253/e000f416-86ad-40ba-9819-61162b07b9c9">

**Comment by Harry-zklcdc** [comment]
看起来没啥问题，我等会试试吧

**Comment by Harry-zklcdc** [comment]
是个bug，用完全Cloudflare Worker部署的是正常的，用其他方式的就不行

等我后期把简化版的客户端开发完成后再试试吧

**Comment by luckyEason** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/109937362/85f8383a-dbba-4423-8a38-cc09a3a33173)
额，这是什么情况

**Comment by standee2023** [comment]
如需访问Bing， 关闭 whistle-client 即可
打开bing后，没有chat选项

**Comment by Harry-zklcdc** [comment]
> ![image](https://user-images.githubusercontent.com/109937362/258982898-85f8383a-dbba-4423-8a38-cc09a3a33173.png) 额，这是什么情况

看这个 [wiki/FAQ](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/FAQ#q-sorry-your-network-dont-support-this-feature--%E6%AD%A3%E5%9C%A8%E5%B0%9D%E8%AF%95%E8%BF%9E%E6%8E%A5-%E8%AF%B7%E7%A8%8D%E5%90%8E)

**Comment by Harry-zklcdc** [comment]
> 如需访问Bing， 关闭 whistle-client 即可 打开bing后，没有chat选项

？描述一下具体操作，你关了 whistle-client 就等于回到 cn.bing 了

**Comment by FangZirui-E5** [comment]
用了演示站也是一样啊
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129593198/0b91378f-78fb-4561-8a4f-3dde185b2059)

**Comment by Harry-zklcdc** [comment]
> 用了演示站也是一样啊 [image](https://user-images.githubusercontent.com/129593198/258988860-0b91378f-78fb-4561-8a4f-3dde185b2059.png)

不是这个，用这个Cloudflare Worker的 bingai-cfwk.xiao-gy.tk

**Comment by Xqh-Cxy** [comment]
> 查看 [wiki/解决 无效域&人机验证](https://githubfast.com/Harry-zklcdc/go-proxy-bingai/wiki/%E8%A7%A3%E5%86%B3-%E6%97%A0%E6%95%88%E5%9F%9F&%E4%BA%BA%E6%9C%BA%E9%AA%8C%E8%AF%81)

手机端呢

**Comment by 7noemo** [comment]
> > 查看 [wiki/解决 无效域&人机验证](https://githubfast.com/Harry-zklcdc/go-proxy-bingai/wiki/%E8%A7%A3%E5%86%B3-%E6%97%A0%E6%95%88%E5%9F%9F&%E4%BA%BA%E6%9C%BA%E9%AA%8C%E8%AF%81)
> 
> 手机端呢

手机自己去官方bing聊几句就能解决无效域了

**Comment by Harry-zklcdc** [comment]
> 手机端呢

手机端等简化方法出来后再想想怎么做，而且很大可能会没有手机端，Android&iOS对第三方证书管理现在太严格了

**Comment by shui063** [comment]
其实可以用稳定的t先上官网过掉人机验证，再用cookie登录镜像站使用

**Comment by Harry-zklcdc** [comment]
> 其实可以用稳定的t先上官网过掉人机验证，再用cookie登录镜像站使用

我的想法是想要**不需要**魔法/梯子什么的就可以直接过验证，这样更方便大众使用，不然就像某个人说的“脱裤子放屁”

**Comment by SokWith** [comment]
> > 其实可以用稳定的t先上官网过掉人机验证，再用cookie登录镜像站使用
> 
> 我的想法是想要**不需要**魔法/梯子什么的就可以直接过验证，这样更方便大众使用，不然就像某个人说的“脱裤子放屁”

现在这个项目太难了，许多时候即使科学验证微软都能整得不科学，也经常出现“sorry，looks”或者一直验证的情况，都是因为行为风控所致。
还是感谢大佬持续更新前端功能，并实现了我一早给原作者提议的纯cf部署，至少，通过多开几个workers，能保证多终端基本不用科学上网。

**Comment by shui063** [comment]
> > 其实可以用稳定的t先上官网过掉人机验证，再用cookie登录镜像站使用
> 
> 我的想法是想要**不需要**魔法/梯子什么的就可以直接过验证，这样更方便大众使用，不然就像有人说的“脱裤子放屁”

于是我弄好站点后，大家一有问题，我就得帮他们过人机验证。。。电脑上有三个edge。。。

**Comment by luckyEason** [comment]
> > > 其实可以用稳定的t先上官网过掉人机验证，再用cookie登录镜像站使用
> 
> > 
> 
> > 我的想法是想要**不需要**魔法/梯子什么的就可以直接过验证，这样更方便大众使用，不然就像有人说的“脱裤子放屁”
> 
> 
> 
> 于是我弄好站点后，大家一有问题，我就得帮他们过人机验证。。。电脑上有三个edge。。。

哈哈😃，同道中人😭

**Comment by FangZirui-E5** [comment]
> > 用了演示站也是一样啊 [image](https://user-images.githubusercontent.com/129593198/258988860-0b91378f-78fb-4561-8a4f-3dde185b2059.png)
> 
> 不是这个，用这个Cloudflare Worker的 bingai-cfwk.xiao-gy.tk

情况貌似也差不多😥
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129593198/fdcb203d-067c-4bb8-9eb0-c9d7e44d68c4)

**Comment by Harry-zklcdc** [comment]
> 情况貌似也差不多😥 ![image](https://user-images.githubusercontent.com/129593198/259024260-fdcb203d-067c-4bb8-9eb0-c9d7e44d68c4.png)

奇了怪了，那为啥我是正常的😂

**Comment by SokWith** [comment]
> > 情况貌似也差不多😥 ![image](https://user-images.githubusercontent.com/129593198/259024260-fdcb203d-067c-4bb8-9eb0-c9d7e44d68c4.png)
> 
> 奇了怪了，那为啥我是正常的😂

猜测是由于cf每次重置的转发IP不同所致。被转发到了封控的IP上了。多重置几次看看。不断验证一般都是IP锁+ID锁双重封控所致。

**Comment by SokWith** [comment]
还有就是要清缓存，非常重要。

**Comment by FangZirui-E5** [comment]
> 是个bug，用完全Cloudflare Worker部署的是正常的，用其他方式的就不行
> 
> 等我后期把简化版的客户端开发完成后再试试吧

希望这个bug可以早点修好

**Comment by FangZirui-E5** [comment]
刚刚在不登录账户、多次重置的情况下凑到了一回
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129593198/14c4d888-7af7-40e5-8d53-922db33295e0)

**Comment by FangZirui-E5** [comment]
还遇到了这样的情况
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129593198/7441a34b-81e3-43df-934d-52833e20c82c)

**Comment by luckyEason** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/109937362/4ad1236c-3963-4998-9e41-ad311680fa0c)
我要疯了

**Comment by luckyEason** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/109937362/8fce52c8-1786-4265-8e16-8972fbc5c485)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/109937362/4b41fda7-b514-419f-85a7-ca8d8f1171b6)
直接搜索有概率绕过人机验证，可是再继续聊天就不行了
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/109937362/46112d6d-1292-4415-a143-f06b42323df8)

**Comment by luckyEason** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/109937362/8fce52c8-1786-4265-8e16-8972fbc5c485)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/109937362/4b41fda7-b514-419f-85a7-ca8d8f1171b6)
直接搜索有概率绕过人机验证，可是再继续聊天就不行了
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/109937362/46112d6d-1292-4415-a143-f06b42323df8)

**Comment by FangZirui-E5** [comment]
不知道Harry目前有没有想出什么办法

**Comment by SokWith** [comment]
> 不知道Harry目前有没有想出什么办法

自建cf服务器，写死转发IP，避免跳到有锁的IP上。

**Comment by FangZirui-E5** [comment]
怎么写死IP？（我不懂）

**Comment by SokWith** [comment]
> 怎么写死IP？（我不懂）

![Uploading IMG_20230808_184613.jpg…]()

**Comment by SokWith** [comment]
![IMG_20230808_184613](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/fb627edd-63d7-46d4-8a5a-dfe5b199c36b)

**Comment by Harry-zklcdc** [comment]
> 不知道Harry目前有没有想出什么办法

我想想能不能搞在Azure的IP范围内，然后人机验证到时候开发个App吧，手机App暂时不考虑了，原因参考https://github.com/Harry-zklcdc/go-proxy-bingai/issues/108#issuecomment-1668961139

**Comment by FangZirui-E5** [comment]
好的，慢慢来
我就静静地等着😀

**Comment by SokWith** [comment]
> > 不知道Harry目前有没有想出什么办法
> 
> 我想想能不能搞在Azure的IP范围内，然后人机验证到时候开发个App吧，手机App暂时不考虑了，原因参考[#108 (comment)](https://github.com/Harry-zklcdc/go-proxy-bingai/issues/108#issuecomment-1668961139)

嘿嘿嘿，我是直接写的bing的IP，看看是不是个隐藏彩蛋😃

**Comment by chengdada925** [comment]
我也是一直弹验证，期待解决，感谢大佬

**Comment by tian1326** [comment]
> 其实可以用稳定的t先上官网过掉人机验证，再用cookie登录镜像站使用

我就这样但是每天要重新获取cookie好麻烦

**Comment by Harry-zklcdc** [comment]
> 我就这样但是每天要重新获取cookie好麻烦

其实可以不用每天换Cookie，通过验证就行

**Comment by tian1326** [comment]
> > 我就这样但是每天要重新获取cookie好麻烦
> 
> 其实可以不用每天换Cookie，通过验证就行

但是我发现cookie的_U变了，就换cookie了

**Comment by ccodingfundddd** [comment]
我用的Azure的香港的服务器，新开的账户绑定的信用卡，免费的1个月，随机填了100个Cookie（_U），还是比较稳的，目前没啥问题。

**Comment by ccodingfundddd** [comment]
> > 不知道Harry目前有没有想出什么办法
> 
> 我想想能不能搞在Azure的IP范围内，然后人机验证到时候开发个App吧，手机App暂时不考虑了，原因参考[#108 (comment)](https://github.com/Harry-zklcdc/go-proxy-bingai/issues/108#issuecomment-1668961139)

我用的Azure的香港的服务器，新开的账户绑定的信用卡，免费的1个月，随机填了100个Cookie（_U），还是比较稳的，目前没啥问题。

**Comment by ccodingfundddd** [comment]
也没有人机验证这类问题出现，

**Comment by qinguoluo** [comment]
> > > 不知道Harry目前有没有想出什么办法
> > 
> > 
> > 我想想能不能搞在Azure的IP范围内，然后人机验证到时候开发个App吧，手机App暂时不考虑了，原因参考[#108 (comment)](https://github.com/Harry-zklcdc/go-proxy-bingai/issues/108#issuecomment-1668961139)
> 
> 我用的Azure的香港的服务器，新开的账户绑定的信用卡，免费的1个月，随机填了100个Cookie（_U），还是比较稳的，目前没啥问题。

随机填100个Cookie（_U）是什么意思，不太懂。

**Comment by ccodingfundddd** [comment]
> > > > 不知道Harry目前有没有想出什么办法
> > > 
> > > 
> > > 我想想能不能搞在Azure的IP范围内，然后人机验证到时候开发个App吧，手机App暂时不考虑了，原因参考[#108 (comment)](https://github.com/Harry-zklcdc/go-proxy-bingai/issues/108#issuecomment-1668961139)
> > 
> > 
> > 我用的Azure的香港的服务器，新开的账户绑定的信用卡，免费的1个月，随机填了100个Cookie（_U），还是比较稳的，目前没啥问题。
> 
> 随机填100个Cookie（_U）是什么意思，不太懂。

我用chatgpt帮我生成的100条长度15随机字符串，把这些信息填写到docker-compose.yml文件中，都是用docker-compose up -d安装，就Azure的服务器目测能这样搞，随便乱填cookie都能用。其他厂商仅设置cookie美国我有两台服务器，香港有一台，不行。估摸跟风控登记有关，azure的服务器风控等级较低。

**Comment by SokWith** [comment]
> > > 不知道Harry目前有没有想出什么办法
> > 
> > 
> > 我想想能不能搞在Azure的IP范围内，然后人机验证到时候开发个App吧，手机App暂时不考虑了，原因参考[#108 (comment)](https://github.com/Harry-zklcdc/go-proxy-bingai/issues/108#issuecomment-1668961139)
> 
> 嘿嘿嘿，我是直接写的bing的IP，看看是不是个隐藏彩蛋😃

友情提醒，有彩蛋哟！

**Comment by FangZirui-E5** [comment]
所以这个具体是要怎么操作

**Comment by FangZirui-E5** [comment]
> ![IMG_20230808_184613](https://user-images.githubusercontent.com/129967025/259078002-fb627edd-63d7-46d4-8a5a-dfe5b199c36b.jpg)
> 
> 具体用哪个IP要自己试一试，网络上搜索美国IP地址池里面找。

这个也没有把全部代码给写出来啊😯

**Comment by SokWith** [comment]
> 看图感觉没这么简单

旅途中，打字不便。你可以按图试一下。或者用我的cfwk测试站点随便输token看看

**Comment by FangZirui-E5** [comment]
图中没有显示完整吧（应该是这样吧，我不懂代码）

**Comment by Harry-zklcdc** [comment]
目前来说，Azure的风控等级是仅高于家宽，在所有IDC中最低了

有兴趣想白嫖的可以研究一下 Azure学生（）

**Comment by Harry-zklcdc** [comment]
有想帮忙实验无效域验证的可以把QQ号发我邮箱 `zklcdc@qq.com`，我拉个群

**Comment by FangZirui-E5** [comment]
教育邮箱我试过，没成功😢
我之前白嫖OneDrive就是因为教育邮箱没成功所以改用了E5来白嫖

**Comment by Harry-zklcdc** [comment]
> 这个是不是得先去一些高校的官网上骗一个教育邮箱

你是正经大学生都能过的

**Comment by FangZirui-E5** [comment]
可我是中学生

**Comment by FangZirui-E5** [comment]
> > 这个是不是得先去一些高校的官网上骗一个教育邮箱
> 
> 你是正经大学生都能过的

你所在的大学有经过微软认证的教育邮箱吗？

**Comment by SokWith** [comment]
> 图中没有显示完整吧（应该是这样吧，我不懂代码）

中学生呀，学业为重哟。
![IMG_20230809_202259](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/55f87bda-b1b6-40d1-8f4b-b902e9c91848)

**Comment by sunzongjian** [comment]
群建好了吗？要不你发群号？我qq号已发你邮箱  但没收到进群通知

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: zklcdc ***@***.***>
发送时间: Wednesday, August 9, 2023 4:58:16 PM
收件人: Harry-zklcdc/go-proxy-bingai ***@***.***>
抄送: sunzongjian ***@***.***>; Comment ***@***.***>
主题: Re: [Harry-zklcdc/go-proxy-bingai] [Feature] 🌈 解决 无效域/人机验证 (Issue #108)


有想帮忙实验无效域验证的可以把QQ号发我邮箱 ***@***.***，我拉个群

**Comment by Harry-zklcdc** [comment]
> 群建好了吗？要不你发群号？我qq号已发你邮箱 但没收到进群通知

我回复你消息了

**Comment by FangZirui-E5** [comment]
> > 图中没有显示完整吧（应该是这样吧，我不懂代码）
> 
> 中学生呀，学业为重哟。 ![IMG_20230809_202259](https://user-images.githubusercontent.com/129967025/259404806-55f87bda-b1b6-40d1-8f4b-b902e9c91848.jpg)

好的，谢谢😀

**Comment by FangZirui-E5** [comment]
> > 群建好了吗？要不你发群号？我qq号已发你邮箱 但没收到进群通知
> 
> 我回复你消息了

我也没收到（邮件我也发了）

**Comment by sunzongjian** [comment]
我下午五点就给你发了，我刚又去qq邮箱看了下，也没收到消息，qq也没收到邀请消息

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 方梓瑞 ***@***.***>
发送时间: Wednesday, August 9, 2023 9:45:32 PM
收件人: Harry-zklcdc/go-proxy-bingai ***@***.***>
抄送: sunzongjian ***@***.***>; Comment ***@***.***>
主题: Re: [Harry-zklcdc/go-proxy-bingai] [Feature] 🌈 解决 无效域/人机验证 (Issue #108)


群建好了吗？要不你发群号？我qq号已发你邮箱 但没收到进群通知

我回复你消息了

我也没收到（邮件我也发了）

**Comment by Harry-zklcdc** [comment]
又试了一遍，我还是可以用

**Comment by Harry-zklcdc** [comment]
Commit: 8e3176e13fb2124e96ecedaf5915fac2b0a08831

把IP范围全换到Azure去了，我这还一堆IP Range，有兴趣可以帮我提一下PR，增加更多的IP Range

去这下就行：[https://www.microsoft.com/en-us/download/details.aspx?id=56519](https://www.microsoft.com/en-us/download/details.aspx?id=56519)

找两个关键词 `AzureCloud`、`WindowsVirtualDesktop`

**Comment by FangZirui-E5** [comment]
好的，感谢

**Comment by FangZirui-E5** [comment]
呃
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129593198/0fde7c0b-54d7-4044-ac73-ef1c3bfa65e8)

**Comment by FangZirui-E5** [comment]
有什么操作被我漏掉吗（我更新了一下worker代码）

**Comment by Harry-zklcdc** [comment]
> 有什么操作被我漏掉吗（我更新了一下worker代码）

进群吧，我给你远程看看

**Comment by sunzongjian** [comment]
我拉取了最新worker.js在cf上重新部署下，可以访问了，就是没有聊天记录（已登录账号）843437251拉我进下群，谢谢

**Comment by sunzongjian** [comment]
微软好恶心啊，就部署成功第一访问成功了，又不行了  好恶心啊
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/24264891/a28e6315-bc16-43ec-a995-0c2dbb83a841)

**Comment by sunzongjian** [comment]
> > > 群建好了吗？要不你发群号？我qq号已发你邮箱 但没收到进群通知
> > 
> > 
> > 我回复你消息了
> 
> 我也没收到（邮件我也发了）
艹，被拦截了，导致没看到信息
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/24264891/e60552dd-604c-49de-b39c-3cdc6ebf4075)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/24264891/3ce5f9e6-930d-4cb0-a2e2-362eeabb3e36)

**Comment by FangZirui-E5** [comment]
> 进群吧，我给你远程看看

好的

**Comment by FangZirui-E5** [comment]
可是我没有收到进群邀请或者好友申请啊

**Comment by FangZirui-E5** [comment]
有可能是出了点问题，我昨天的邮件可能没发出去🤣

**Comment by SokWith** [comment]
> > > > 不知道Harry目前有没有想出什么办法
> > > 
> > > 
> > > 我想想能不能搞在Azure的IP范围内，然后人机验证到时候开发个App吧，手机App暂时不考虑了，原因参考[#108 (comment)](https://github.com/Harry-zklcdc/go-proxy-bingai/issues/108#issuecomment-1668961139)
> > 
> > 
> > 嘿嘿嘿，我是直接写的bing的IP，看看是不是个隐藏彩蛋😃
> 
> 友情提醒，有彩蛋哟！

https://github.com/Harry-zklcdc/go-proxy-bingai/issues/103#issuecomment-1672820768

今天是谁在测试触发了彩蛋？

**Comment by FangZirui-E5** [comment]
可是我这里没看出什么异常🤨

**Comment by Harry-zklcdc** [comment]
你们试试添加以下值，可否使用

**Comment by SokWith** [comment]
> 可是我这里没看出什么异常🤨

感谢反馈。这个ID昨晚10点后手机端就异常了。目前接近48小时没有更新了，之前必须24小时科学验证一下。最近也没机会更新它，看看最终能坚持多久吧。

**Comment by FangZirui-E5** [comment]
![006E991C](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129593198/d1dd4c12-eeaf-4d3c-8dcc-c43479bd8feb)

**Comment by Harry-zklcdc** [comment]
祭：8.16 21:44 巨硬升级了人机验证策略，此方法废

**Comment by Harry-zklcdc** [comment]
好像，又复活了

**Comment by Harry-zklcdc** [comment]
而且我试了一下，好像所有部署方法都可以用了这个方法过验证了

**Comment by SokWith** [comment]
> Commit: [8e3176e](https://github.com/Harry-zklcdc/go-proxy-bingai/commit/8e3176e13fb2124e96ecedaf5915fac2b0a08831)
> 
> 把IP范围全换到Azure去了，我这还一堆IP Range，有兴趣可以帮我提一下PR，增加更多的IP Range
> 
> 去这下就行：https://www.microsoft.com/en-us/download/details.aspx?id=56519
> 
> 找两个关键词 `AzureCloud`、`WindowsVirtualDesktop`

ip地址转发后，replit也可以直接部署了

```
你好，这是Bing。根据你的问题，我使用了我的搜索工具来查找相关的信息。以下是我找到的一些结果：

- 现在的时间是：**2023年8月22日星期二，下午4:46:58**¹。你所在的时区是**中欧夏令时间（CEST）**，与世界标准时间（UTC）相差**2小时**¹。你所在的地点是**阿姆斯特丹，北荷兰，尼德兰**¹。
- 你的IP地址是：**52.[1](https://bing.com/search?q=current+time+in+Amsterdam)67.[1](https://bing.com/search?q=current+time+in+Amsterdam)44.[1](https://bing.com/search?q=current+time+in+Amsterdam)60**²。这个IP地址属于**Microsoft Corporation**²，它的主机名是**msnbot-5[2](https://www.timeanddate.com/worldclock/netherlands/amsterdam)-167-144-160.search.msn.com**²。这个IP地址的地理位置是**美国，弗吉尼亚州，博伊顿**²⁵。这可能意味着你正在使用一个代理服务器或者VPN来隐藏你的真实位置。
- 你的IP地址的归属地是：**美国**⁵。根据IP地址分配机构（ARIN）的数据库，这个IP地址是由**Microsoft Corporation**注册和管理的⁵。你可以通过[ARIN Whois](^1^)来查询更多关于这个IP地址的信息。

我希望这些信息对你有帮助。如果你有其他问题，欢迎继续和我聊天。😊

```

**Comment by SokWith** [comment]
> Commit: [8e3176e](https://github.com/Harry-zklcdc/go-proxy-bingai/commit/8e3176e13fb2124e96ecedaf5915fac2b0a08831)
> 
> 把IP范围全换到Azure去了，我这还一堆IP Range，有兴趣可以帮我提一下PR，增加更多的IP Range
> 
> 去这下就行：https://www.microsoft.com/en-us/download/details.aspx?id=56519
> 
> 找两个关键词 `AzureCloud`、`WindowsVirtualDesktop`

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/b82c97da-d777-4cf4-bc8a-04cefed8d669)

微软云也不安全,建议把ip压缩到微软自家的服务器群里面而不是扩大范围.一个微软服务器的ip可以顶全部其他ip的.

**Comment by Harry-zklcdc** [comment]
@SokWith 帮我试试最新版的Replit部署可以用不，加了浏览器指纹，可能会降低触发人机验证的概率，帮我试验一下

**Comment by SokWith** [comment]
> @SokWith 帮我试试最新版的Replit部署可以用不，加了浏览器指纹，可能会降低触发人机验证的概率，帮我试验一下

https://replit.nbing.eu.org 已更新到1.12.0，订正回纯replit本地运行，没有过cf workers代理。
目前运行正常，内置3个ID待继续观察。
```
[您好，这是 Bing。您的消息似乎是关于一个名为 BingAI 的项目的版本发布信息。根据我从网络上搜索到的结果，BingAI 是一个基于微软 New Bing 的聊天机器人，使用 Vue3 和 Go 语言开发，支持 ChatGPT 提示词，国内可用，无需登录即可畅聊](https://github.com/xbzstudio/BingAI-Client/releases)¹²。

[1](https://github.com/xbzstudio/BingAI-Client/releases).1[2](https://github.com/adams549659584/go-proxy-bingai).0 bingai/releases 是该项目的最新版本，于 2023 年 8 月 25 日发布，包含以下更新内容：

- [修复了一些 bug 和依赖问题](about:blank#)¹
- 新增了 Windows amd64/arm64 版本打包¹
- 新增了图像创建功能，可以使用 /create images 指令生成图像¹
- 新增了 markdown 渲染和代码高亮功能¹
- 新增了 Socks 环境变量配置²
- 移除了单次对话次数限制²

如果您对该项目感兴趣，您可以访问其[官方 GitHub 仓库](^[1](https://github.com/xbzstudio/BingAI-Client/releases)^)或[演示站点](^3^)进行体验。请注意，该项目并非由微软官方开发或支持，而是由第三方开发者创建和维护的。如果您在使用过程中遇到任何问题或建议，请直接联系项目开发者。谢谢！😊

源: 与必应的对话， 2023/8/25
```

**Comment by SokWith** [comment]
@Harry-zklcdc 大佬，有没有方法部署远程的whistle服务器，VPS可能吗？但比如在replit、vercel等服务商的部署都是在它们的内网上的，我试着在replit安装了whistle，再反代127.0.0.1:8899，结果是重定向次数过多，没能成功部署。

**Comment by luckykid814** [comment]
为什么我安装并配置好了whistle后，用浏览器访问www.bing.com还是会重定向回国内的cn.bing.com？

**Comment by SokWith** [comment]
@Harry-zklcdc 大佬，这是什么技术？
```
[域名前置技术是一种隐藏连接真实端点来规避互联网审查的技术。它可以让用户通过HTTPS连接到被屏蔽的服务，而表面上像在与另一个完全不同的站点通信。](about:blank#)¹³

域名前置技术的原理是利用CDN（内容分发网络）的特性，将用户的网络请求转发到目标网站，从而绕过网络审查和限制。²⁴

具体来说，域名前置技术在不同的通信层使用不同的域名。在明文的DNS请求和TLS服务器名称指示（SNI）中使用无害的域名来初始化连接、公布给审查者，而实际要连接的「敏感」域名仅在建立加密的HTTPS连接后发出，使其不以明文暴露给网络审查者。¹²⁴

这种技术在被封锁的站点与无害站点为同一个大型服务提供商时较为可行，例如由CDN提供的服务。¹²⁴ 此时审查者通常很难区分被伪装流量与合法流量的特点，迫使审查者选择放行所有看似无害的流量，或者选择彻底封锁此域的流量。而彻底封锁可能带来显著的附加损害。¹

如果您想了解如何使用域名前置技术来规避互联网审查，您可以参考以下步骤：

- 注册一个匿名的域名，例如使用[Freenom]提供的免费域名服务。
- 注册一个免费的CDN服务，例如[Cloudflare]，并将您的域名添加到CDN中。
- 配置CDN服务，选择一个合适的SSL/TLS加密方式，并开启CDN代理模式。
- 在CDN服务中找到一个高信誉且与您使用相同CDN服务商的域名，例如[www.baidu.com]。
- 配置您的C2服务器或其他被屏蔽的服务，使其能够接收并处理来自CDN代理的请求。
- 配置您的C2客户端或其他需要访问被屏蔽服务的程序，使其能够通过HTTPS连接到高信誉域名，并在Host头中指定您自己的域名。
- 运行您的C2客户端或其他程序，享受自由地访问被屏蔽服务吧！

```
具体来说就是   无忧行插件  的服务器是怎么建立的？

**Comment by Harry-zklcdc** [comment]
已经完全简化，Commit: 148156a662393ddfcbd0f2b85da155a7c39dde1c

**Comment by slowJoker2023** [comment]
本地部署完一直提示重新开始怎么搞啊

**Comment by slowJoker2023** [comment]
不管是用vercel还是用cloudflare不输出来都是这样 ，也输入了自己的cookie

**Comment by Harry-zklcdc** [comment]
> 不管是用vercel还是用cloudflare不输出来都是这样 ，也输入了自己的cookie

开个issue，提供对应的详细信息，包括截图什么的
