### ISSUE TITLE
请问完整用户cookie是通过什么方式得到呢？

### ISSUE THREAD

**Issue by shui063** [Harry-zklcdc/go-proxy-bingai#110]
### Describe the help wanted

请问完整用户cookie是通过什么方式得到呢？

### Steps to behave

按照最新的修复提示通过whistle可以获取到完整cookie，但是还是没有弄懂

### Expected behavior

使用完整用户cookie就可以避免过多的人机验证吗？求作者解答。原谅我没有智商（实在不懂）打扰了谢谢！
我已经使用容器和cloud flare分别搭建好了，也确实使用whistle给cloud flare workers的使用，希望详细点打扰了谢谢！
打扰了谢谢！！！！

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by FangZirui-E5** [comment]
[获取完整cookie](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/%E8%8E%B7%E5%8F%96-Cookie)

**Comment by Harry-zklcdc** [comment]
> 使用完整用户cookie就可以避免过多的人机验证吗？

不能，具体原因查看FAQ
