### ISSUE TITLE
[Feature] 🌈 增加 Docker 镜像

### ISSUE THREAD

**Issue by rakaki** [Harry-zklcdc/go-proxy-bingai#113]
### Describe the help wanted

我想部署在northflank上，但是northflank似乎只支持url的镜像。

### Steps to behave

部署在northflank

### Expected behavior

将镜像上传至dockerhub

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/88972415/caf43fc4-d6bf-4625-b2e2-5a7b3fe32f06)

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by Xqh-Cxy** [comment]
可以用，ghcr

**Comment by Xqh-Cxy** [comment]
我在写dockerfile

**Comment by rakaki** [comment]
> 可以用，ghcr

请问可以具体说下地址吗

**Comment by Xqh-Cxy** [comment]
> > 可以用，ghcr
> 
> 请问可以具体说下地址吗

我还在研究

**Comment by Xqh-Cxy** [comment]
> ### Describe the help wanted
> 我想部署在northflank上，但是northflank似乎只支持url的镜像。
> 
> ### Steps to behave
> 部署在northflank
> 
> ### Expected behavior
> 将镜像上传至dockerhub
> 
> ### Screenshots
> ![image](https://usercontent.githubfast.com/user-images/88972415/259082426-caf43fc4-d6bf-4625-b2e2-5a7b3fe32f06.png)
> 
> ### Versions
> * OS:
> * Browser & Version:
> * GoProxiBing Version:
> 
> ### Additional context
> _No response_

dockerfile和docker-compose写好了，我在想办法变成docker镜像（https://github.com/chixinyan/go-proxy-bingai-docker-image/

**Comment by Xqh-Cxy** [comment]
> ### Describe the help wanted
> 我想部署在northflank上，但是northflank似乎只支持url的镜像。
> 
> ### Steps to behave
> 部署在northflank
> 
> ### Expected behavior
> 将镜像上传至dockerhub
> 
> ### Screenshots
> ![image](https://usercontent.githubfast.com/user-images/88972415/259082426-caf43fc4-d6bf-4625-b2e2-5a7b3fe32f06.png)
> 
> ### Versions
> * OS:
> * Browser & Version:
> * GoProxiBing Version:
> 
> ### Additional context
> _No response_

终于写好推送好了，ghcr.io/xqh-cxy/go-proxy-bingai:1.0.0，填进去部署看看

**Comment by Xqh-Cxy** [comment]
> ### Describe the help wanted
> 我想部署在northflank上，但是northflank似乎只支持url的镜像。
> 
> ### Steps to behave
> 部署在northflank
> 
> ### Expected behavior
> 将镜像上传至dockerhub
> 
> ### Screenshots
> ![image](https://usercontent.githubfast.com/user-images/88972415/259082426-caf43fc4-d6bf-4625-b2e2-5a7b3fe32f06.png)
> 
> ### Versions
> * OS:
> * Browser & Version:
> * GoProxiBing Version:
> 
> ### Additional context
> _No response_

试一下填写"ghcr.io/xqh-cxy/go-proxy-bingai:1.0.0"

**Comment by Harry-zklcdc** [comment]
下个版本我加个Docker镜像的构建

**Comment by xzy103** [comment]
> 下个版本我加个Docker镜像的构建

蹲一个大佬的docker，之前一直是在自己的VPS上用docker启，原项目停更后一直没找到很好的替代。

**Comment by YuenSzeHong** [comment]
> 下个版本我加个Docker镜像的构建

希望可以传一下docker hub

**Comment by Xqh-Cxy** [comment]
> > 下个版本我加个Docker镜像的构建
> 
> 蹲一个大佬的docker，之前一直是在自己的VPS上用docker启，原项目停更后一直没找到很好的替代。

docker pull ghcr.io/xqh-cxy/go-proxy-bingai:1.0.0

**Comment by Xqh-Cxy** [comment]
> > 下个版本我加个Docker镜像的构建
> 
> 希望可以传一下docker hub

ghcr.io/xqh-cxy/go-proxy-bingai:1.0.0

**Comment by Harry-zklcdc** [comment]
已增加，`zklcdc/go-proxy-bingai:latest`

**Comment by dongmuhds** [comment]
docker run -d -p 8080:8080 --name go-proxy-bingai --restart=unless-stopped zklcdc/go-proxy-bingai:latest

**Comment by Harry-zklcdc** [comment]
> 为什么我docker安装完不是最新版1.14，而是1.13

啊？我看看

**Comment by xiangdeyue** [comment]
网页进不去，一直在加载中

**Comment by xzy103** [comment]
> 网页进不去，一直在加载中

多半是因为没有使用https
