### ISSUE TITLE
bingai 居然这么精准的知道这个项目～～

### ISSUE THREAD

**Issue by skyfly2000** [Harry-zklcdc/go-proxy-bingai#114]
哈哈哈😂bingai 居然这么精准的知道这个项目～～
<img width="1414" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/57341809/19207950-3ade-46d8-b039-55b5d1da611d">
繁忙之余，找点乐子

**Comment by Sisyphean-a** [comment]
在小众的项目它都会知道的，对ai来说几十星和几千星没什么区别
