### ISSUE TITLE
部署到HuggingFace（8/16日可用）

### ISSUE THREAD

**Issue by MkStoler** [Harry-zklcdc/go-proxy-bingai#115]
# 部署到HuggingFace（目前可用） - 1

# 本项目是基于Bilibili@神烦老狗的视频总结，别谢我，去谢视频作者去！

# [快速链接到他的Bilibili主页](https://space.bilibili.com/46377861)

# [快速链接到他的博客主页](https://www.laogou717.com/)

## 0. 阅读前警告（想让连接长寿一点的都好好看！）：

# <font color=CC0000>**希望你永远看不见我讲的内容！**</font>

> 1. Docker<font color=CC0000>**易崩溃**</font>，可能要**重启**。
> 
> 2. 如果你出现了<font color=CC0000>**奇怪的错误**</font>，**先回忆一下步骤做对了吗**。
> 
> 3. 解决方案见<font color=CC0000>**Error Fix - 底方用户手册**</font>。
> 
> 4. 不知道什么时候会被封，大家贴出来自己部署的，共享一下，咱不要注册太多，多了微软封这个服务！

## 1. 注册：

1. 打开[这个网址](https://huggingface.co/ "点击跳转到HuggingFace")

2. 右上角`sign up`；

3. 填写一个能查收邮件的邮箱；

4. 填写信息：
   
   - `Username`：用户名<mark>**（必填）**</mark>；
   
   - `Full name`：全名<mark>**（必填）**</mark>；
   
   - `Avatar`：头像（下面的是上传图片文件）；
   
   - `GitHub username`：GitHub用户名；
   
   - `Homepage`：个人网站或博客地址；
   
   - `Twitter username`：推特用户名；
   
   - `Research interests`：感兴趣的研究方向；

5. 查收邮件，完成账户激活（完成后会有条绿色横幅告诉你成功了）。

## 2. 建立Space：

1. 点击上栏`Space`

2. 右方`New Space`

3. 参建以下要求建立：
   
   1. `Space Name`填写你自己想要的名称；
   
   2. `License`输入`mit`；
   
   3. `Select the Space SDK`选`Docker`，`Choose a Docker template`选`Blank`
   
   4. `Space Hardware`下的`Public`和`Private`：
      
      - `Public`——不在你组织或未登录的人能访问你的Space（公用）。
      
      - `Private`——不在你组织或未登录的人不能能访问你的Space（私有）。
   
   5. 点`Create Space`。

## 3. 部署Dockerfile

1. 下滑，有个<u>**create**</u>，点击一下；

2. 在打开的页面的文本编辑器里输入以下内容：
   
   ```Dockerfile
   # Build Stage
   # 使用 golang:alpine 作为构建阶段的基础镜像
   FROM golang:alpine AS builder 
   
   # 添加 git，以便之后能从GitHub克隆项目
   RUN apk --no-cache add git
   
   # 从 GitHub 克隆 go-proxy-bingai 项目到 /workspace/app 目录下
   RUN git clone https://github.com/Harry-zklcdc/go-proxy-bingai.git /workspace/app 
   
   # 设置工作目录为之前克隆的项目目录
   WORKDIR /workspace/app
   
   # 编译 go 项目。-ldflags="-s -w" 是为了减少编译后的二进制大小
   RUN go build -ldflags="-s -w" -tags netgo -trimpath -o go-proxy-bingai main.go
   
   # Runtime Stage
   # 使用轻量级的 alpine 镜像作为运行时的基础镜像
   FROM alpine
   
   # 设置工作目录
   WORKDIR /workspace/app
   
   # 从构建阶段复制编译后的二进制文件到运行时镜像中
   COPY --from=builder /workspace/app/go-proxy-bingai .
   
   # 设置环境变量——Cookies"_U"，此处为随机字符
   ENV Go_Proxy_BingAI_USER_TOKEN_1="kJs8hD92ncMzLaoQWYtX5rG6bE3fZ4iO"
   
   # 暴露8080端口
   EXPOSE 8080
   
   # 容器启动时运行的命令
   CMD ["/workspace/app/go-proxy-bingai"]
   ```

3. 底下点击按钮**Commit new file to** `main`

4. **不要**等待部署完成，接着点击上方的`Files`；

5. 点击`Readme.md`；

6. 点工具栏（文本编辑器框上的）`Edit`；

7. 在`license: mit`后回车输入（或复制）：
   
   ```markdown
   app_port: 8080
   ```

8. 底下点击按钮**Commit new file to** `main`

## 4. 验证成功OR失败

1. 观察你的页面上有没有以下图标之一：
   
   <font color=green>**● Running**</font>——**祝贺你，成功了！**
   
   <font color=4444ff>**● Building**</font>——**等一会，稍安勿躁，还没部署完！**
   
   <font color=9b870c>**No application file**</font>——**dockerfile忘记保存了吧？**
   
   <font color=CC0000>**Build error**</font>或 <font color=CC0000>**Runtime error**</font>——**出错了~~去结尾看一看故障排查！**

## 5. 获取地址（`Public`专享）

1. 点击上栏的`App`，进入APP主界面。

2. 看，应该是启动了。

3. 这个时候点击右上角**齿轮——服务选择**

4. 记下本站的网址，大改长这样：
   
   ### https://你的名字-Space名称.hf.space/

**Comment by yangjianchuan** [comment]
这个是我已经部署好的，各位可以测试

https://dongsiqie-bing.hf.space

**Comment by Harry-zklcdc** [comment]
可以加一下操作图嘛？谢谢，我给放到 Wiki 里面，

**Comment by SokWith** [comment]
您好，这是Bing。感谢您的提问。😊

[Hugging Face是一个专注于自然语言处理的公司，它提供了一个开源的Transformers库，一个在线的模型和数据集仓库，以及一个基于云的推理API服务](https://azure.microsoft.com/en-us/solutions/hugging-face-on-azure/)¹。Hugging Face与微软有着紧密的合作关系，它们共同推出了一个新的AI服务，叫做Hugging Face on Azure²。这个服务可以让用户在Azure机器学习平台上轻松地部署和使用Hugging Face的预训练模型²。

所以，Hugging Face用的是微软云服务吗？答案是：部分是。Hugging Face的推理API服务是由Hugging Face自己提供的，它不依赖于微软云服务²。但是，Hugging Face on Azure服务是基于微软云服务的，它可以让用户在自己的Azure账户中创建和管理Hugging Face模型的端点²。

我希望这个回答能够满足您的好奇心。如果您还有其他问题，欢迎继续提问。😊

源: 与必应的对话， 2023/8/9
([1](https://azure.microsoft.com/en-us/solutions/hugging-face-on-azure/)) Hugging Face on Azure – Huggingface Transformers | Microsoft Azure. https://azure.microsoft.com/en-us/solutions/hugging-face-on-azure/.
([2](https://techcrunch.com/2022/05/24/hugging-face-collaborates-with-microsoft-for-new-ai-powered-azure-service/)) Hugging Face collaborates with Microsoft for new AI-powered Azure .... https://techcrunch.com/[2](https://techcrunch.com/2022/05/24/hugging-face-collaborates-with-microsoft-for-new-ai-powered-azure-service/)0[2](https://techcrunch.com/2022/05/24/hugging-face-collaborates-with-microsoft-for-new-ai-powered-azure-service/)[2](https://techcrunch.com/2022/05/24/hugging-face-collaborates-with-microsoft-for-new-ai-powered-azure-service/)/05/24/hugging-face-collaborates-with-microsoft-for-new-ai-powered-azure-service/.
(3) A startup called Hugging Face is becoming the GitHub of AI - Quartz. https://qz.com/hugging-face-microsoft-artificial-intelligence-1850490270.
(4) Hugging Face库使用教程 - 知乎 - 知乎专栏. https://zhuanlan.zhihu.com/p/621423712.

**Comment by luckyEason** [comment]
这个其实还可以自定义域名，但是目前发现自定义域名后，授权码机制出现问题

**Comment by MkStoler** [comment]
> 可以加一下操作图嘛？谢谢，我给放到 Wiki 里面，


Ok，我去编word

**Comment by Harry-zklcdc** [comment]
> Ok，我去编word

好的好的，谢谢

**Comment by MkStoler** [comment]
Word我是编出来了，但是这一版内容里面有问题，图片我都有，然后委托你扔到markdown里面吧。

**Comment by MkStoler** [comment]
算了，我自己改了就行

**Comment by MkStoler** [comment]
图片部分：https://4wb5rx-my.sharepoint.com/:f:/g/personal/sunguangxuan_edicdn_eu_org/EibiR1ayqGhHrmwnuQ45QpQBCxwZEmeSRI6UIp0rMYO3gA?e=jJwIXF

**Comment by Harry-zklcdc** [comment]
> 图片部分：https://4wb5rx-my.sharepoint.com/:f:/g/personal/sunguangxuan_edicdn_eu_org/EibiR1ayqGhHrmwnuQ45QpQBCxwZEmeSRI6UIp0rMYO3gA?e=jJwIXF

好的好的

**Comment by MkStoler** [comment]
[huggedface-utf-8.md](https://github.com/Harry-zklcdc/go-proxy-bingai/files/12319297/huggedface-utf-8.md)

**Comment by Harry-zklcdc** [comment]
好的好的，感谢，我这两天抽空加上去一下

**Comment by SokWith** [comment]
> 这个是我已经部署好的，各位可以测试
> 
> https://dongsiqie-bing.hf.space

IP被BAN了？
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/a9608182-6f1d-4231-87bf-51ee28e055f9)

**Comment by SokWith** [comment]
> > 这个是我已经部署好的，各位可以测试
> > https://dongsiqie-bing.hf.space
> 
> IP被BAN了？ ![image](https://user-images.githubusercontent.com/129967025/260293832-a9608182-6f1d-4231-87bf-51ee28e055f9.png)

多测几遍，偶尔抽疯。
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/6f6b5b37-41c5-4dcd-8e00-7b83fc9796cb)

**Comment by yangjianchuan** [comment]
写了一个一键部署的链接 [点击一键部署到HuggingFace](https://huggingface.co/login?next=%2Fspaces%2Fdongsiqie%2Fbing%3Fduplicate%3Dtrue%26visibility%3Dpublic)

**Comment by FangZirui-E5** [comment]
我刚刚测出来已经挂了？
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129593198/1946318d-d7bd-4506-bcfe-b9e999e82c84)

**Comment by yangjianchuan** [comment]
不要设置 cookie，直接用

**Comment by FangZirui-E5** [comment]
我的cookie是乱填的

**Comment by Harry-zklcdc** [comment]
已经更新上了
[https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/HuggingFace-部署](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/HuggingFace-部署)

**Comment by yangjianchuan** [comment]
什么都不要填写，直接用

**Comment by SokWith** [comment]
我这个项目以及bingo项目部署的两个hf站点今日都失效了。
巨硬的ip锁策略是越来越智能化了。
