### ISSUE TITLE
[Bug] 🐛 完整cookie读取错误

### ISSUE THREAD

**Issue by YuenSzeHong** [Harry-zklcdc/go-proxy-bingai#117]
### Describe the bug

`_U`和`_RwBf` 里面带`=`，如果用一般cookie字串读取的方式会出问题
我自己是用js读取document.cookie

### Steps to reproduce

用js读取document.cookie
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/40477634/23b4d2f8-9541-4ef7-ad84-2e9332d5c648)

粘贴到`完整cookie`
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/40477634/9f4e7052-138c-4986-812a-f386b9fe9307)

保存之后切换回去
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/40477634/a1db5006-e4d3-451c-801b-3b28acfc7fc1)

### Expected behavior

应该取得完整`_RwBf`

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/40477634/23b4d2f8-9541-4ef7-ad84-2e9332d5c648)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/40477634/9f4e7052-138c-4986-812a-f386b9fe9307)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/40477634/a1db5006-e4d3-451c-801b-3b28acfc7fc1)

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by Harry-zklcdc** [comment]
我这不会呀，代码我测试过的

**Comment by Harry-zklcdc** [comment]
提供一下你的浏览器信息，我代码 `=` 分割的在第二步，第一步是 `;` 分割

**Comment by Harry-zklcdc** [comment]
是个bug，我这边复现了，修复中
