### ISSUE TITLE
[Help] 🤔 在获取bing的cookie没有KievRPSSecAuth 的值

### ISSUE THREAD

**Issue by jerryliang122** [Harry-zklcdc/go-proxy-bingai#118]
### Describe the help wanted

在获取bing的cookie中发现没有KievRPSSecAuth 的值。

### Steps to behave

在传统的bing的网页中输入对话后在应用程序中查看。

### Expected behavior

是否更换了cookie？

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/25032918/33c9200e-5fc0-401b-a0a6-6bb7dabd4117)

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version: 

### Additional context

无

**Comment by Xqh-Cxy** [comment]
需要去国际站，要翻墙

**Comment by jerryliang122** [comment]
是在国际站。聊天界面

**Comment by Harry-zklcdc** [comment]
重新登陆一下？

**Comment by jerryliang122** [comment]
试试看看看能不能搞出来

**Comment by skyfly2000** [comment]
要有登录过程

**Comment by jerryliang122** [comment]
发现问题了。有一部分请求没有完全响应所以有些cookie没有正常的显示出来。
