### ISSUE TITLE
[Bug] 🐛 1.10.3一键重置不了

### ISSUE THREAD

**Issue by skyfly2000** [Harry-zklcdc/go-proxy-bingai#122]
### Describe the bug

1、经测试，1.10.3一键重置不了，输入完整Cookie后重置不起作用，重置后跳到KievRPSSecAuth和_U的值仍然存在，RwBf值只出现ilt。测试环境 iPhone 的 safair 端和mac 的safair 端、chrome 端；
2、1.10.3只在部署时输入KievRPSSecAuth值，打开页面时没法成功建立对话提示：”不停的出现人机验证”，必须输入完整Cookie或_U和RwBf；
3、感觉1.10.3是一种倒退（存粹提建议，请不要多想），本来私有化部署的目的是给不懂架梯子或者架梯子有困难的人用，但1.10.3必须输入完整Cookie，KievRPSSecAuth和_U的值，聊天记录是就会同步出来，有隐私风险。
<img width="1291" alt="iShot_2023-08-10_02 50 53" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/57341809/0ed39b2f-e6b2-4402-a081-69e2f11009bb">
<img width="1170" alt="iShot_2023-08-10_02 59 08" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/57341809/891ddc11-f148-4eed-8637-19efd88022d9">

### Steps to reproduce

输入完整Cookie后重置不起作用，重置后跳到KievRPSSecAuth和_U的值仍然存在，RwBf值只出现ilt。
测试环境 iPhone 的 safair 端和mac 的safair 端、chrome 端；
1.10.3只在部署时输入KievRPSSecAuth值，打开页面时没法成功建立对话提示：”需要重新连接“，必须输入完整Cookie或_U和RwBf；

### Expected behavior

像 1.10.2一样自由实用，不需要输入那么多东西；
网页界面不需要输入Cookie，部署时输入KievRPSSecAuth或者完整Cookie，就可以正常使用；
如果可行，考虑项目内置自行获取完整Cookie，然后分权限开关对话记录，「此点工作量比较多，可以无视」

### Versions

- OS: <macOS Ventura版本13.4.1（c）>
- Browser & Version: < Safari浏览器、Google Chrome -->
- GoProxiBing Version: <e.g. 1.10.3 >

**Comment by luckyEason** [comment]
你如果将网站映射到www.bing.com就会有这种情况，你可以手动删除cookie

**Comment by luckyEason** [comment]
而且不一定必须输入完整Cookie或_U和RwBf
