### ISSUE TITLE
iframe嵌套后授权码机制异常

### ISSUE THREAD

**Issue by luckyEason** [Harry-zklcdc/go-proxy-bingai#123]
如题，使用iframe嵌套后，授权码无论这么输都是错误的（即使输的对的），始终无法通过验证

**Comment by luckyEason** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/109937362/70b95d8c-9bd9-4ea1-85cd-df47ef80bc8c)

**Comment by luckyEason** [comment]
授权码是对的，访问抱脸分配的域名是可以通过验证的，但iframe嵌套后就不可用

**Comment by Harry-zklcdc** [comment]
有空看一下

**Comment by luckyEason** [comment]
> 有空看一下

谢谢大佬🙏

**Comment by gzz2000** [comment]
猜测是因为cookie的SameSite

**Comment by glaw1984** [comment]
画图错误

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/128808448/0c9a98d6-a8a9-48d2-92b1-c92f0ae0007a)

**Comment by luckyEason** [comment]
> > 有空看一下
> 
> 
> 
> 17.0确实有这问题，正确的授权码无法通过网页验证

在Harry接手之前就有这个问题了

**Comment by Harry-zklcdc** [comment]
这个没法解决，拿不到 Cookie/Storge，现在浏览器的限制太大了
