### ISSUE TITLE
[Bug] 🐛 我用docker部署的bing ai在cloudflare和本站服务器选择一直在验证

### ISSUE THREAD

**Issue by cengzhijie3** [Harry-zklcdc/go-proxy-bingai#124]
### Describe the bug

我用docker部署的bing ai在cloudflare和本站服务器选择一直在验证

### Steps to reproduce

用docker搭建然后部署域名+反代

### Expected behavior

修复问题

### Screenshots

我用docker部署的bing ai在cloudflare和本站服务器选择一直在验证

### Versions

- OS: oracle debian11
- Browser & Version: Chrome 115
- GoProxiBing Version: latest docker

### Additional context

<img width="1067" alt="截圖 2023-08-10 上午10 43 28" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/89333400/963a4cd5-0b9d-475f-9f6b-ebf0a396c2e1">
<img width="1067" alt="截圖 2023-08-10 上午10 45 39" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/89333400/58123072-f3f8-4cee-b5dd-3b116ac56aec">

**Comment by Harry-zklcdc** [comment]
https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/FAQ#q-%E6%97%A0%E6%95%88%E5%9F%9F-%E8%AF%B7%E8%81%94%E7%B3%BB%E7%AE%A1%E7%90%86%E5%91%98%E5%90%8E%E9%87%8D%E8%AF%95--%E4%BA%BA%E6%9C%BA%E9%AA%8C%E8%AF%81
