### ISSUE TITLE
[Help] 🤔 我在运行docker时报错

### ISSUE THREAD

**Issue by cengzhijie3** [Harry-zklcdc/go-proxy-bingai#125]
### Describe the help wanted

在运行docker run时报错：docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/root/go-proxy-bingai" to rootfs at "/app/go-proxy-bingai": mount /root/go-proxy-bingai:/app/go-proxy-bingai (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.

### Steps to behave

docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/root/go-proxy-bingai" to rootfs at "/app/go-proxy-bingai": mount /root/go-proxy-bingai:/app/go-proxy-bingai (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.

### Expected behavior

请帮我解决下

### Screenshots

docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/root/go-proxy-bingai" to rootfs at "/app/go-proxy-bingai": mount /root/go-proxy-bingai:/app/go-proxy-bingai (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.

### Versions

- OS: oracle debian 11
- Browser & Version: 
- GoProxiBing Version:

**Comment by Harry-zklcdc** [comment]
试一下最新的

**Comment by Harry-zklcdc** [comment]
https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/Docker-%E9%83%A8%E7%BD%B2#%E9%83%A8%E7%BD%B2

**Comment by pandoradevin** [comment]
> 按照下边这个链接安装了竟然不是V1.14，而是1.13

**Comment by glaw1984** [comment]
https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/Docker-%E9%83%A8%E7%BD%B2#%E9%83%A8%E7%BD%B2

**Comment by Harry-zklcdc** [comment]
好的，我检查一下

**Comment by pandoradevin** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/125889247/fca6ce7b-b9a3-4faf-b000-42b58734c75d)
这个是w什么错误？

**Comment by Harry-zklcdc** [comment]
> 我执行docker安装后也是V1.11.13，并非1.11.14最新版，我还专门加了:latest也一样 [image](https://user-images.githubusercontent.com/128808448/260606720-5959264a-7fec-474d-8db7-d1a304dc6c33.png)

已修复

**Comment by cengzhijie3** [comment]
> > 我執行docker安裝後也是V1.11.13，不是1.11.14最新版本，我還專門加了：最新也一樣的[鏡像](https://user-images.githubusercontent.com/128808448/260606720-5959264a-7fec-474d-8db7-d1a304dc6c33.png)
> 
> 已修復

你好，我试了下docker run，还是v1.1.3

**Comment by Harry-zklcdc** [comment]
> 你好，我试了下docker run，还是v1.1.3

dokcer pull 一下

**Comment by cengzhijie3** [comment]
> > 你好，我試了下docker run，還是v1.1.3
> 还是不行，没有用
> docker pull 一下
<img width="810" alt="截圖 2023-08-17 下午6 26 26" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/89333400/d4c41683-ca28-4d32-bc5e-b1967b276c9c">


<img width="810" alt="截圖 2023-08-17 下午6 26 14" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/89333400/e109d295-b8b4-4af7-ac61-0ad168869def">

**Comment by Harry-zklcdc** [comment]
然后重新创建容器

**Comment by glaw1984** [comment]
画图错误

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/128808448/427fe158-4d7a-4f8b-bafd-b11b4bdd7056)
