### ISSUE TITLE
[Help] 🤔 你好，我已经按照要求把cookie都填写了，但是仍然显示不能用

### ISSUE THREAD

**Issue by cengzhijie3** [Harry-zklcdc/go-proxy-bingai#126]
### Describe the help wanted

你好，我已经按照要求把cookie都填写了，但是仍然显示不能用，一直不断的进行认证
<img width="1061" alt="截圖 2023-08-10 下午2 28 29" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/89333400/19086ee4-d246-4cc4-8640-8d1bb93f5150">
<img width="1061" alt="截圖 2023-08-10 下午2 28 46" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/89333400/6154e631-940f-4d3b-9c5c-aa425f1f1af6">
进行ren zheng认证
<img width="1061" alt="截圖 2023-08-10 下午2 28 22" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/89333400/1f39e19a-dcb6-4ac5-8430-990bdfb8e2bd">

### Steps to behave

你好，我已经按照要求把cookie都填写了，但是仍然显示不能用，一直不断的进行认证
<img width="1067" alt="截圖 2023-08-10 上午10 45 39" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/89333400/cf06cdb8-740a-4309-ad79-4f2fe3f1ce44">

### Expected behavior

你好，我已经按照要求把cookie都填写了，但是仍然显示不能用，一直不断的进行认证

### Screenshots

<img width="1061" alt="截圖 2023-08-10 下午2 28 22" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/89333400/a990d8ca-ec05-4b33-8447-ccfa8eaa9233">
<img width="1061" alt="截圖 2023-08-10 下午2 28 29" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/89333400/bff548a9-a913-423e-9739-f3c4a9f48387">
<img width="1061" alt="截圖 2023-08-10 下午2 28 46" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/89333400/41a790e5-fbc6-4be2-b763-149a27355ed1">

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by Harry-zklcdc** [comment]
https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/FAQ#q-%E6%97%A0%E6%95%88%E5%9F%9F-%E8%AF%B7%E8%81%94%E7%B3%BB%E7%AE%A1%E7%90%86%E5%91%98%E5%90%8E%E9%87%8D%E8%AF%95--%E4%BA%BA%E6%9C%BA%E9%AA%8C%E8%AF%81
