### ISSUE TITLE
[Feature] 🌈 添加子路径配置

### ISSUE THREAD

**Issue by Dandjinh** [Harry-zklcdc/go-proxy-bingai#129]
### Describe the problem related to the feature request

希望添加通过环境变量设置反代的子路径。
现在貌似只能在'/'下访问，不能在nginx的子路径下访问。

### Describe the solution you'd like

Go_Proxy_BingAI_BASEURL=xxx

**Comment by Harry-zklcdc** [comment]
不考虑支持, 有需求自行修改
