### ISSUE TITLE
我部署的CF服务器貌似没办法国内直连……

### ISSUE THREAD

**Issue by landones** [Harry-zklcdc/go-proxy-bingai#13]
RT，我貌似没办法直接连接，需要翻墙过后次啊能链接欸。不知道为什么，有大佬能解答一下吗？
![1](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/67811286/e0bfe96b-65f5-4a00-b20f-0c41fffc8584)

**Comment by CKylinMC** [comment]
workers.dev网址有的地方有屏蔽，自己注册个域名绑定就行了
