### ISSUE TITLE
[Help] 🤔 NAS部署不加载历史记录

### ISSUE THREAD

**Issue by YuenSzeHong** [Harry-zklcdc/go-proxy-bingai#130]
### Describe the help wanted

我是NAS docker部署，服务选过官方的也不行，不知道是https问题还是docker问题，我那个https证书是synlogy签署的

### Steps to behave

填入任何cookie，打开记录之后刷新

### Expected behavior

加载历史记录

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/40477634/f46a2b6b-f585-448e-9d5d-d42e5578d931)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/40477634/b32c357c-37c0-4270-ac0c-fc59ceb35796)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/40477634/a73d6ed6-680b-414f-bca0-d386e3c774c1)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/40477634/1259714d-793a-4a72-8747-6f555e3b817c)

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by YuenSzeHong** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/40477634/022fed6e-ce5a-4b65-a824-9ef1bfdb835c)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/40477634/3e70f124-a314-4ca8-8142-75a2471708bd)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/40477634/0745b96d-8e9b-442a-9aa7-c072d7b32c62)
补充，NAS反代设置

**Comment by Harry-zklcdc** [comment]
你nas开代理了嘛

**Comment by YuenSzeHong** [comment]
> 你nas开代理了嘛

我在香港，不用代理，聊天啥的都正常，就历史记录不行

**Comment by Harry-zklcdc** [comment]
> 我在香港，不用代理，聊天啥的都正常，就历史记录不行

多试几次，多刷新刷新，刚登陆上好像不会有聊天记录出现

**Comment by YuenSzeHong** [comment]
已经是禁用缓存刷新几次才求助🥹

**Comment by Harry-zklcdc** [comment]
> 已经是禁用缓存刷新几次才求助🥹

试试完整cookie？有可能又加了什么神奇的cookie，但是我自己用的还是只有这三个cookie，历史记录一切正常，刚开始可能刷新不出来，直接刷新（f5）几次就有了，我的三个站都是这样

**Comment by YuenSzeHong** [comment]
> > 已经是禁用缓存刷新几次才求助🥹
> 
> 试试完整cookie？有可能又加了什么神奇的cookie，但是我自己用的还是只有这三个cookie，历史记录一切正常，刚开始可能刷新不出来，直接刷新（f5）几次就有了，我的三个站都是这样

应该是我部署问题，在huggingface部署那个都正常，就nas那个不行

**Comment by YuenSzeHong** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/40477634/b33d9746-636e-4268-b7ee-4365d75066b8)
日志

**Comment by Harry-zklcdc** [comment]
> [image](https://user-images.githubusercontent.com/40477634/260455398-b33d9746-636e-4268-b7ee-4365d75066b8.png) 日志

感觉是你网络问题，你的网络可以正常使用NewBing吗？或者是NAS上配置了全局代理？

**Comment by YuenSzeHong** [comment]
可以存取newbing

**Comment by YuenSzeHong** [comment]
我换了oracle的vps部署，也是同一个问题

> > [image](https://user-images.githubusercontent.com/40477634/260455398-b33d9746-636e-4268-b7ee-4365d75066b8.png) 日志
> 
> 感觉是你网络问题，你的网络可以正常使用NewBing吗？或者是NAS上配置了全局代理？

**Comment by YuenSzeHong** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/40477634/c71ea6b3-f058-4f94-b20f-cc49a70e1905)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/40477634/4f324db9-e372-42c5-babf-2cd7ecd42fa4)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/40477634/de262e7e-9385-4c7c-bb79-cfdbb893fd4b)


> 我换了oracle的vps部署，也是同一个问题
> 
> > > [image](https://user-images.githubusercontent.com/40477634/260455398-b33d9746-636e-4268-b7ee-4365d75066b8.png) 日志
> > 
> > 
> > 感觉是你网络问题，你的网络可以正常使用NewBing吗？或者是NAS上配置了全局代理？

**Comment by YuenSzeHong** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/40477634/22f6ddb4-42d6-463b-90dc-aec2213be176)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/40477634/c910b1e3-88c7-4b3c-8afc-1545d9a2f40e)
神奇的是历史记录倒是有写入我账号的历史记录里

**Comment by Harry-zklcdc** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/199fdb80-dfa4-493c-8bae-dcc3cd8a42cc)
这个换成Http试试，不应该是https

**Comment by YuenSzeHong** [comment]
> ![image](https://user-images.githubusercontent.com/21104213/261536941-199fdb80-dfa4-493c-8bae-dcc3cd8a42cc.png) 这个换成Http试试，不应该是https

试过，没效果

**Comment by YuenSzeHong** [comment]
短暂显示过历史刷新之后又没了

**Comment by Harry-zklcdc** [comment]
现在呢？
