### ISSUE TITLE
[Help] 🤔 

### ISSUE THREAD

**Issue by ghost** [Harry-zklcdc/go-proxy-bingai#132]
### Describe the help wanted

这是为什么啊
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/139636224/9ef9c98e-bc80-4f03-a220-d6c4ad40ffe5)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/139636224/1d52c4de-6845-42c4-a425-df3ba1cd2bab)
这个也配置了

### Steps to behave

https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/%E8%A7%A3%E5%86%B3-%E6%97%A0%E6%95%88%E5%9F%9F&%E4%BA%BA%E6%9C%BA%E9%AA%8C%E8%AF%81
按照该方法使用

### Expected behavior

能完成人机验证

### Versions

- OS: win11
- Browser & Version: edge115.0.1901.200 
- GoProxiBing Version: 1.11.4

**Comment by luckyEason** [comment]
https://github.com/Harry-zklcdc/go-proxy-bingai/issues/108

**Comment by liyangmoney** [comment]
解决了吗？我也遇到同样问题

**Comment by Harry-zklcdc** [comment]
还没，还在找其他方式解决

**Comment by Harry-zklcdc** [comment]
最新版试试
