### ISSUE TITLE
已经疯狂到了每天必须换一组_RwBf和KievRPSSecAuth，

### ISSUE THREAD

**Issue by skyfly2000** [Harry-zklcdc/go-proxy-bingai#133]
已经疯狂到了每天必须换一组_RwBf和KievRPSSecAuth，刚注册的新号也是同样问题，Cloudflare Worker 部署，1.11.4.
每天必须折腾一次，你们怎么样？有更好的解决方式么？
![IMG_8989](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/57341809/d14f1858-01c0-4105-9687-adcefec0b1e6)

**Comment by lw1290537863** [comment]
你说的意思是每天换一个微软帐号的cookie，还是一组轮询池？

**Comment by FangZirui-E5** [comment]
你应该就算是cookie乱输也不会有问题吧（最好输的长一点、乱一点）

**Comment by FangZirui-E5** [comment]
或者试试一键重置和刷新

**Comment by skyfly2000** [comment]
每天必须换一组_RwBf和KievRPSSecAuth， Worker.js 里修改，换账号也不行，必须每天换_RwBf和KievRPSSecAuth

**Comment by FangZirui-E5** [comment]
加梯子是必须的，没办法

**Comment by FangZirui-E5** [comment]
我提起过一个类似的issue，[#83](https://github.com/Harry-zklcdc/go-proxy-bingai/issues/83)，你可以看看

**Comment by 7noemo** [comment]
手机端还没有有效的解决无效域的问题。
不过我在使用的时候就只填_U值，自部署的聊天服务器填KievRPSSecAuth(也一直没换过)。
隔天一般会出现无效域，这时候连上官方bing聊几句就能解决。即使是换_U也差不多1个月才换一次

判断是否需要更换_U，填入聊天服务网址和_U后刷新页面
如果能显示历史聊天记录但是无效域只需要去官方聊天即可
如果不显示历史聊天记录则需要重新获取_U值

**Comment by shui063** [comment]
> 已经疯狂到了每天必须换一组_RwBf和KievRPSSecAuth，刚注册的新号也是同样问题，Cloudflare Worker 部署，1.11.4. 每天必须折腾一次，你们怎么样？有更好的解决方式么？ ![IMG_8989](https://user-images.githubusercontent.com/57341809/260289600-d14f1858-01c0-4105-9687-adcefec0b1e6.PNG)

你这个问题问得，ai不出错才怪。。

**Comment by shui063** [comment]
> > 已经疯狂到了每天必须换一组_RwBf和KievRPSSecAuth，刚注册的新号也是同样问题，Cloudflare Worker 部署，1.11.4. 每天必须折腾一次，你们怎么样？有更好的解决方式么？ ![IMG_8989](https://user-images.githubusercontent.com/57341809/260289600-d14f1858-01c0-4105-9687-adcefec0b1e6.PNG)
> 
> 你这个问题问得，ai不出错才怪。。

（开玩笑的）(●—●)

**Comment by Harry-zklcdc** [comment]
Cookie可以不用每天换，大概过期时间是一周，每天去NewBing人机验证一下就行
