### ISSUE TITLE
聊天记录即使在设置关闭后，刷新网页后依然会出现

### ISSUE THREAD

**Issue by luckyEason** [Harry-zklcdc/go-proxy-bingai#134]
确定设置中聊天记录为关闭

**Comment by FangZirui-E5** [comment]
这也是个bug，并且你要是关闭了聊天记录、并不刷新网页的话就再也打不开历史记录了

**Comment by FangZirui-E5** [comment]
刷新是打开历史记录的唯一方式

**Comment by luckyEason** [comment]
> 刷新是打开历史记录的唯一方式

事实上，设置里关闭聊天记录后不一定要刷新才能打开

**Comment by FangZirui-E5** [comment]
看来新版已经修复了这个问题了

**Comment by FangZirui-E5** [comment]
我刚刚试了一下是没这个问题

**Comment by FangZirui-E5** [comment]
可我看在新版里面也没有你说的这个问题啊

**Comment by luckyEason** [comment]
> 可我看在新版里面也没有你说的这个问题啊

Windows端貌似没有这个问题，但iPad上实测是有的

**Comment by FangZirui-E5** [comment]
好吧

**Comment by Harry-zklcdc** [comment]
> Windows端貌似没有这个问题，但iPad上实测是有的

那就是Safari的问题

**Comment by pandoradevin** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/125889247/0d75d35c-d167-41e0-a1d8-b5ce180d5fb8)
这个是什么错误

**Comment by FangZirui-E5** [comment]
无效域啊

**Comment by FangZirui-E5** [comment]
这个问题早就有了，你可以去翻一下之前的issues
