### ISSUE TITLE
[Help] 🤔 使用NPM(nginx proxy manager)做反向代理无法成功

### ISSUE THREAD

**Issue by xzy103** [Harry-zklcdc/go-proxy-bingai#135]
### Describe the help wanted

尝试在自己的海外VPS服务器上使用docker部署，再使用npm做发反向代理，试了各种配置也无法成功。
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/40889019/a2c70afb-8040-4cc6-a2b0-463e6e62d68e)
提示信息：
WebSocket connection to 'wss://newbing.xxxxx.com/sydney/ChatHub' failed: ...index-b6ac8870.js:1765
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/40889019/77caf780-cec3-457c-81d7-dca9389769b6)

### Steps to behave

开启了https的，npm配置：
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/40889019/1f079593-78f5-4e82-ad7a-92fd810585c9)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/40889019/fdee4b95-cb27-4ce5-86e3-19cefcc38a0e)

### Expected behavior

尝试按照 #71 中关于nginx的配置进行，也无法成功。

### Versions

- OS: windows11
- Browser & Version: edge 115.0.1901.203
- GoProxiBing Version: 1.11.3

**Comment by skyfly2000** [comment]
两个同时必备条件：1、docker部署时环境变量要加入正确的_RwBf值；2、vps没有被ban。

**Comment by xzy103** [comment]
> 两个同时必备条件：1、docker部署时环境变量要加入正确的KievRPSSecAuth值；2、vps没有被ban。

vps的连接一直是通畅的，尝试在docker-compose.yml中增加环境变量，填入了USER_KievRPSSecAuth。
然后就：时可时不可
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/40889019/58264627-17f6-42d7-8673-3bfbb45d1a10)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/40889019/ea50d9f5-fb24-4bb1-85b9-cf767b1e6888)
但问答就从没成功过：
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/40889019/782fb244-077d-4c80-9bdb-321dd9410f56)

**Comment by Xqh-Cxy** [comment]
> ### Describe the help wanted
> 尝试在自己的海外VPS服务器上使用docker部署，再使用npm做发反向代理，试了各种配置也无法成功。 ![image](https://usercontent.githubfast.com/user-images/40889019/260309151-a2c70afb-8040-4cc6-a2b0-463e6e62d68e.png) 提示信息： WebSocket connection to 'wss://newbing.xxxxx.com/sydney/ChatHub' failed: ...index-b6ac8870.js:1765 ![image](https://usercontent.githubfast.com/user-images/40889019/260309222-77caf780-cec3-457c-81d7-dca9389769b6.png)
> 
> ### Steps to behave
> 开启了https的，npm配置： ![image](https://usercontent.githubfast.com/user-images/40889019/260309277-1f079593-78f5-4e82-ad7a-92fd810585c9.png) ![image](https://usercontent.githubfast.com/user-images/40889019/260309310-fdee4b95-cb27-4ce5-86e3-19cefcc38a0e.png)
> 
> ### Expected behavior
> 尝试按照 #71 中关于nginx的配置进行，也无法成功。
> 
> ### Screenshots
> _No response_
> 
> ### Versions
> * OS: windows11
> * Browser & Version: edge 115.0.1901.203
> * GoProxiBing Version: 1.11.3
> 
> ### Additional context
> _No response_

说明你的IP“中奖了”

**Comment by xzy103** [comment]
> > ### Describe the help wanted
> > ...
> 
> 说明你的IP“中奖了”

但是搭的其他代理（正向和反向）都可以正常访问，搭的newbing代理现在也能访问，但就是无法提问。

**Comment by Harry-zklcdc** [comment]
你试试填入完整Cookie试试

**Comment by duo2001y** [comment]
确实直接用抱脸域名可以问答，但用cloudflare workers反代无法进行问答。

**Comment by xzy103** [comment]
更新到最新的1.14.0后问题得以解决（至少在使用token的情况下能回话了，之前完全不行）
