### ISSUE TITLE
[Bug] 🐛 聊天次数限制

### ISSUE THREAD

**Issue by Aoan2011** [Harry-zklcdc/go-proxy-bingai#137]
### Describe the bug

当我跟必应聊天到第 10 轮以后时，会提示已到达单次主题对话限制，但底下仍然写着 30 个对话次数？

### Steps to reproduce

聊天 10 次以上

### Expected behavior

将单次对话拓宽到 30 次，或修复这个问题

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/136089405/eb3a758b-eb8d-4b47-8dc8-cea075e03ba7)

### Versions

- OS: macOS Monterey
- Browser & Version: Microsoft Edge 115
- GoProxiBing Version: v1.11.4

### Additional context

希望回复这个 #131

**Comment by luckyEason** [comment]
拓宽是要登录账号的，目前这个项目貌似无法判断cookie的真假，才出现了bug

**Comment by Harry-zklcdc** [comment]
这个感觉是NewBing那边的Bug

**Comment by pandoradevin** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/125889247/777e0b5d-0cdd-4cc3-91b2-4ab7acfd1633)
这个是什么错误
