### ISSUE TITLE
作者您好，能否研究下这个项目。

### ISSUE THREAD

**Issue by Xqh-Cxy** [Harry-zklcdc/go-proxy-bingai#138]
https://github.com/weaigc/bingo/
为什么这个可以正常回答？（但是有很多很多bug）

**Comment by FangZirui-E5** [comment]
这个项目的问题确实有一点（捂脸）

**Comment by Harry-zklcdc** [comment]
你看这个
[https://github.com/weaigc/bingo/#如何获取-bing_header](https://github.com/weaigc/bingo/#%E5%A6%82%E4%BD%95%E8%8E%B7%E5%8F%96-bing_header)

他是把我们的那个过人机验证的过程，放在了获取Cookie的过程上，所以本质上没有差别

**Comment by SokWith** [comment]
> https://github.com/weaigc/bingo/ 为什么这个可以正常回答？（但是有很多很多bug）

觉得就是它的 创建头文件去 get 官方 https://www.bing.com/turing/conversation/create  时的返回有所不同

**Comment by SokWith** [comment]
经vercel/replit部署测试，这个项目仍然不能部署在IP被封的服务器上。

**Comment by Harry-zklcdc** [comment]
> 经vercel/replit部署测试，这个项目仍然不能部署在IP被封的服务器上。

隔壁那个可以？把完整的Cookie填进去试试

**Comment by SokWith** [comment]
> > 经vercel/replit部署测试，这个项目仍然不能部署在IP被封的服务器上。
> 
> 隔壁那个可以？把完整的Cookie填进去试试

看中的是他的无cookie聊天，如果要cookie，就莫若你的cf服务器部署了，复制粘贴worker就可以部署一大堆服务器了，反正小团体用一天10万次的限制基本都够用的，大不了多申请几个cf账号。

**Comment by Harry-zklcdc** [comment]
> 看中的是他的无cookie聊天，如果要cookie，就莫若你的cf服务器部署了，复制粘贴worker就可以部署一大堆服务器了，反正小团体用一天10万次的限制基本都够用的，大不了多申请几个cf账号。

要实现无Cookie首先服务器IP要好，你看我新搭的Azure的演示站，也可以实现无Cookie聊天

**Comment by SokWith** [comment]
> > 看中的是他的无cookie聊天，如果要cookie，就莫若你的cf服务器部署了，复制粘贴worker就可以部署一大堆服务器了，反正小团体用一天10万次的限制基本都够用的，大不了多申请几个cf账号。
> 
> 要实现无Cookie首先服务器IP要好，你看我新搭的Azure的演示站，也可以实现无Cookie聊天

我发现cf部署的服务器也可以无cookie聊天，只要生成一长串随机字符串作为U值就可以了。但是会出现一个小bug，每次刷新页面后，在新主题里面第一次输入的聊天会出现无效域，必须先点击首页的提示聊天项目，就不会出现无效域，直接展开聊天。此后可以直接新主题刷新，再输入就正常使用了。一旦重置后就又得先点击提示项目，否则必出现无效域。跟踪发现是重置后的首次聊天不会主动再次创建 create句柄，需要点击提示聊天项就会先创建create。详细可以测试我的这个测试站点：
https://hfwk.nbing.eu.org
没有内置ID，纯cf部署了。

**Comment by SokWith** [comment]
> > > 看中的是他的无cookie聊天，如果要cookie，就莫若你的cf服务器部署了，复制粘贴worker就可以部署一大堆服务器了，反正小团体用一天10万次的限制基本都够用的，大不了多申请几个cf账号。
> > 
> > 
> > 要实现无Cookie首先服务器IP要好，你看我新搭的Azure的演示站，也可以实现无Cookie聊天
> 
> 我发现cf部署的服务器也可以无cookie聊天，只要生成一长串随机字符串作为U值就可以了。但是会出现一个小bug，每次刷新页面后，在新主题里面第一次输入的聊天会出现无效域，必须先点击首页的提示聊天项目，就不会出现无效域，直接展开聊天。此后可以直接新主题刷新，再输入就正常使用了。一旦重置后就又得先点击提示项目，否则必出现无效域。跟踪发现是重置后的首次聊天不会主动再次创建 create句柄，需要点击提示聊天项就会先创建create。详细可以测试我的这个测试站点： https://hfwk.nbing.eu.org 没有内置ID，纯cf部署了。

这个站点还有一个奇怪的地方，不开vpn可以正常聊天，开了vpn反而不能聊天了。

**Comment by SokWith** [comment]
避免误解，重新把测试站点改名为 ：  https://cfree.nbing.eu.org
纯cf部署，无内置ID（无U\K\R等）

**Comment by SokWith** [comment]
伪bug，避免误导，见此说明  https://github.com/Harry-zklcdc/go-proxy-bingai/issues/71#issuecomment-1684706162

**Comment by rakaki** [comment]
> 避免误解，重新把测试站点改名为 ： https://cfree.nbing.eu.org 纯cf部署，无内置ID（无U\K\R等）
 才发现移动居然解封了eu.org
