### ISSUE TITLE
为什么我回复是空白的，自己搭建的聊天服务器

### ISSUE THREAD

**Issue by simple003** [Harry-zklcdc/go-proxy-bingai#139]
![Screenshot_2023_0815_151145.png](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/142142844/3b8f551f-e432-4fe4-bd40-d40ae4f4273a)

![Screenshot_2023_0815_151210.png](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/142142844/511187a6-f829-4dea-9ad4-9fcef431802d)

**Comment by simple003** [comment]
之后点击新主题，发送内容未收到回复

**Comment by Harry-zklcdc** [comment]
你这是触发人机验证了

**Comment by simple003** [comment]
> 你这是触发人机验证了

哪怎么解决啊？

**Comment by Harry-zklcdc** [comment]
https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/FAQ#q-%E6%97%A0%E6%95%88%E5%9F%9F-%E8%AF%B7%E8%81%94%E7%B3%BB%E7%AE%A1%E7%90%86%E5%91%98%E5%90%8E%E9%87%8D%E8%AF%95--%E4%BA%BA%E6%9C%BA%E9%AA%8C%E8%AF%81

**Comment by simple003** [comment]
> https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/FAQ#q-%E6%97%A0%E6%95%88%E5%9F%9F-%E8%AF%B7%E8%81%94%E7%B3%BB%E7%AE%A1%E7%90%86%E5%91%98%E5%90%8E%E9%87%8D%E8%AF%95--%E4%BA%BA%E6%9C%BA%E9%AA%8C%E8%AF%81

我试了一下，还是一样，咋办啊
