### ISSUE TITLE
如何解决海外VPS服务器IP被ban的问题，大家可以探讨下？

### ISSUE THREAD

**Issue by fenger7** [Harry-zklcdc/go-proxy-bingai#14]

**Comment by Harry-zklcdc** [comment]
* 换IP
* 换地区
* IP代理池
* Cookie

**Comment by fenger7** [comment]
海外VPS链接服务器配置这个KievRPSSecAuth参数，能有用吗？换IP，换地区成本都太高，IP代理池免费好用的很少，Cookie支持用户太少。如果考虑配置CloudFlare Wrap，实现服务器代理，然后VPS服务器内的聊天服务器配置KievRPSSecAuth参数，不知道理论上能不能成功解决这个问题？

**Comment by Harry-zklcdc** [comment]
理论上可以

**Comment by ccodingfundddd** [comment]
发现一个新的有趣的现象，如果VPS的IP没有被ban的话，如果不想在前端页面输入_U值的话，可以在docker-compose中随意输入一个_U值，DDDDDDDDDD。我部署好后，发给朋友发现可以一起用。但是似乎存在一个小小问题，在线人数多了，会提示重新登录，然后重新打开页面又好了，估摸可能是同一用户会话有什么限制。作者要是可以在docker-compose中加个配置，布尔类型，允许随机一个_U值就好了，给不同用户分配不同的_U，应该能解决这个问题。

version: '3'

services:
  go-proxy-bingai:
    # 镜像名称
    image: adams549659584/go-proxy-bingai
    # 容器名称
    container_name: go-proxy-bingai  
    # 自启动
    restart: always
    volumes:
      # 将编译好的二进制文件 (linux-amd64) 放到和 docker-compose.yml 同个文件夹, 并赋予可执行权限 (`chmod +x go-proxy-bingai`)
      - $PWD/go-proxy-bingai:/app/go-proxy-bingai
    ports:
      - 8080:8080
    environment:
        - Go_Proxy_BingAI_USER_TOKEN_1=DDDDDDDDDD
    #   - Go_Proxy_BingAI_SOCKS_URL=192.168.0.88:1070
    #   - Go_Proxy_BingAI_SOCKS_USER=xxx
    #   - Go_Proxy_BingAI_SOCKS_PWD=xxx
    #   - Go_Proxy_BingAI_USER_TOKEN_1=xxx
    #   - Go_Proxy_BingAI_USER_TOKEN_2=xxx

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/139052477/6003bd7a-66ad-4767-adf9-9e7501b9a8f3)

**Comment by ccodingfundddd** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/139052477/6e3ac441-3b7f-42d7-b07e-4db041bdc4bf)

**Comment by Harry-zklcdc** [comment]
> 发现一个新的有趣的现象，如果VPS的IP没有被ban的话，如果不想在前端页面输入_U值的话，可以在docker-compose中随意输入一个_U值，DDDDDDDDDD。我部署好后，发给朋友发现可以一起用。但是似乎存在一个小小问题，在线人数多了，会提示重新登录，然后重新打开页面又好了，估摸可能是同一用户会话有什么限制。作者要是可以在docker-compose中加个配置，布尔类型，允许随机一个_U值就好了，给不同用户分配不同的_U，应该能解决这个问题。
> 
> version: '3'
> 
> services: go-proxy-bingai: # 镜像名称 image: adams549659584/go-proxy-bingai # 容器名称 container_name: go-proxy-bingai # 自启动 restart: always volumes: # 将编译好的二进制文件 (linux-amd64) 放到和 docker-compose.yml 同个文件夹, 并赋予可执行权限 (`chmod +x go-proxy-bingai`) - $PWD/go-proxy-bingai:/app/go-proxy-bingai ports: - 8080:8080 environment: - Go_Proxy_BingAI_USER_TOKEN_1=DDDDDDDDDD # - Go_Proxy_BingAI_SOCKS_URL=192.168.0.88:1070 # - Go_Proxy_BingAI_SOCKS_USER=xxx # - Go_Proxy_BingAI_SOCKS_PWD=xxx # - Go_Proxy_BingAI_USER_TOKEN_1=xxx # - Go_Proxy_BingAI_USER_TOKEN_2=xxx
> 
> [image](https://user-images.githubusercontent.com/139052477/255229852-6003bd7a-66ad-4767-adf9-9e7501b9a8f3.png)

那个 `Go_Proxy_BingAI_USER_TOKEN_*` 的配置就是让你用来填 `_U` 的

**Comment by WaiterGin** [comment]
在VPS上部署Cloudflare Warp之后，可以隐藏服务器真实IP地址，VPS所有出站连接都走Warp的IP，我试了效果还不错。
我用的是甬哥的CFwarp一键脚本：
https://gitlab.com/rwkgyg/CFwarp
意外收获是，如果VPS上还部署了梯子，那所有梯子出站也走Warp IP，使用这个梯子也可以直接访问官网服务。

**Comment by Harry-zklcdc** [comment]
> 在VPS上部署Cloudflare Warp之后，可以隐藏服务器真实IP地址，VPS所有出站连接都走Warp的IP，我试了效果还不错。 我用的是甬哥的CFwarp一键脚本： https://gitlab.com/rwkgyg/CFwarp 意外收获是，如果VPS上还部署了梯子，那所有梯子出站也走Warp IP，使用这个梯子也可以直接访问官网服务。

其实可以直接用官方的那个 `warp-cli`，然后配置成 proxy 模式，
