### ISSUE TITLE
[Feature] 🌈 新方法获取完整用户cookie！同时完成人机验证操作（不需要whistle）

### ISSUE THREAD

**Issue by shui063** [Harry-zklcdc/go-proxy-bingai#140]
### Describe the problem related to the feature request

首先打开微软 new bing 的人机验证网站进行人机验证（前提bing.com需要登陆好能够使用new bing的账号并且挂t）https://www.bing.com/turing/captcha/challenge
![PKD81}M5))$)U)FZ$TK X1T](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/141022490/85e59de3-a690-4c18-8c4c-536307b53923)

### Describe the solution you'd like

然后验证完后在浏览器开发者工具中找到如图位置，就能获取到当前账号的完整cookie了（目前不知道会不会更新）
![@Q6VITF~U73}M5BG30}J_@O](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/141022490/0422f763-fff5-4c51-9ac6-389b86df23a0)

**Comment by Harry-zklcdc** [comment]
这样还是需要代理，我的想法是不通过代理直接获取到Cookie

**Comment by shui063** [comment]
> 这样还是需要代理，我的想法是不通过代理直接获取到Cookie

有没有办法让反代实现自动提取新cookie并更新？

**Comment by shui063** [comment]
> 这样还是需要代理，我的想法是不通过代理直接获取到Cookie

不通过代理好像过不了人机验证，cookie就不知道了，没有试

**Comment by Harry-zklcdc** [comment]
> 不通过代理好像过不了人机验证，cookie就不知道了，没有试

可以看看这个 #108 , 部分人已经尝试成功了（包括我自己），但是我还是可能需要更多的人来实验，测试其人机验证机制

**Comment by shui063** [comment]
> > 不通过代理好像过不了人机验证，cookie就不知道了，没有试
> 
> 可以看看这个 #108 , 部分人已经尝试成功了（包括我自己），但是我还是可能需要更多的人来实验，测试其人机验证机制

嗯嗯

**Comment by qinguoluo** [comment]
> ### Describe the problem related to the feature request
> 首先打开微软 new bing 的人机验证网站进行人机验证（前提bing.com需要登陆好能够使用new bing的账号并且挂t）https://www.bing.com/turing/captcha/challenge ![PKD81}M5))$)U)FZ$TK X1T](https://user-images.githubusercontent.com/141022490/260669452-85e59de3-a690-4c18-8c4c-536307b53923.png)
> 
> ### Describe the solution you'd like
> 然后验证完后在浏览器开发者工具中找到如图位置，就能获取到当前账号的完整cookie了（目前不知道会不会更新） ![@Q6VITF~U73}M5BG30}J_@O](https://user-images.githubusercontent.com/141022490/260669591-0422f763-fff5-4c51-9ac6-389b86df23a0.png)
> 
> ### Describe alternatives you've considered
> _No response_
> 
> ### Additional context
> _No response_

是不是挂一次t，获得完整cookie之后，以后就不会出现隔一天要人机验证了？

**Comment by Harry-zklcdc** [comment]
> 是不是挂一次t，获得完整cookie之后，以后就不会出现隔一天要人机验证了？

并不是，这个得看你的账号风险还有IP风险，基本上平均下来还是一天一次

**Comment by qinguoluo** [comment]
那么如果要完全绕开一天一次的验证，目前还是要用你创造的方法，使用whistle吗？

**Comment by qinguoluo** [comment]
> > 是不是挂一次t，获得完整cookie之后，以后就不会出现隔一天要人机验证了？
> 
> 并不是，这个得看你的账号风险还有IP风险，基本上平均下来还是一天一次

那么如果要完全绕开一天一次的验证，目前还是要用你创造的方法，使用whistle吗？

**Comment by pandoradevin** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/125889247/2811c852-b219-46e3-ba55-3f4745290435)
这个是w什么错误？

**Comment by shui063** [comment]
> ![image](https://user-images.githubusercontent.com/125889247/260897344-2811c852-b219-46e3-ba55-3f4745290435.png) 这个是w什么错误？

也是无效域吧？

**Comment by glaw1984** [comment]
画图错误

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/128808448/184d5c27-bbf6-422b-a8f1-2268ca5c69e1)
