### ISSUE TITLE
[Feature] 🌈 通过微软虚拟机拿Cookie

### ISSUE THREAD

**Issue by yangjianchuan** [Harry-zklcdc/go-proxy-bingai#141]
### Describe the problem related to the feature request

# 通过微软虚拟机拿Cookie

## 登陆微软虚拟机

地址：[微软虚拟机](https://learn.microsoft.com/zh-cn/training/modules/implement-common-integration-features-finance-ops/10-exercise-1)

按照网页中的图文教程登陆到虚拟机，大概步骤如下：

- 选择**启动 VM 模式**。
- 在实验侧边栏上的**Resources**选项卡中，在 **MININT** 框中选择**密码**旁边的 **T** 图标，以便为您输入虚拟机的管理员密码。

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/104043801/342e9c88-0f5f-497b-8933-e9f5812e46df)

- 打开新版Edge浏览器。

## 登陆Bing

- 在虚拟机的新版Edge浏览器中打开Bing。

进入首页网址点击 CHAT。
```
https://www.bing.com
```
 
或者直接打开聊天网址：
```
https://www.bing.com/search?q=Bing+AI&showconv=1&FORM=hpcodx
```

- 点击 Sign in 登陆自己的微软账号。

- 随便发送一句话进行聊天。

- 获取cookie。

  详见 [获取cookie教程](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/%E8%8E%B7%E5%8F%96-Cookie)。

### Describe the solution you'd like

微软虚拟机可以访问www.bing.com，每次可以使用2小时。

**Comment by FangZirui-E5** [comment]
登录账户并验证之后出现如下情况
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129593198/b895d8ad-98fe-42c3-accb-7c82080d1848)
并且获取到的cookie是没用的
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129593198/80f9144d-71c6-4495-9260-fc19fb72ca28)

**Comment by FangZirui-E5** [comment]
可是我不管怎么说，他反正就在验证完之后来一个“出现错误”

**Comment by FangZirui-E5** [comment]
好像确实是这样，刚刚我在官网也聊不了了

**Comment by FangZirui-E5** [comment]
澳，因为开了whistle

**Comment by FangZirui-E5** [comment]
难道在微软虚拟机里也是这个问题？（雾）

**Comment by FangZirui-E5** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129593198/915a8c7c-0eca-42f1-a5f5-e1cf928dd7c3)
事实证明，微软虚拟机里不是这个问题

**Comment by FangZirui-E5** [comment]
我觉得是微软虚拟机被动过手脚，导致其网络设置无法使用新必应

**Comment by FangZirui-E5** [comment]
包括我用其系统提供的账号登录时就是直接告诉我禁用了bing

**Comment by yangjianchuan** [comment]
应该是账号问题吧，我的账号可以在里面直接用，甚至机器人验证都没有出来

**Comment by FangZirui-E5** [comment]
如果是机器人验证都没有出来的话就说明你的账号已经验证过了，并且验证还没有过期

**Comment by Harry-zklcdc** [comment]
已更新至Wiki

[https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/通过微软虚拟机过人机验证](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/通过微软虚拟机过人机验证)
