### ISSUE TITLE
[Bug] 🐛 图像生成的位置

### ISSUE THREAD

**Issue by Aoan2011** [Harry-zklcdc/go-proxy-bingai#143]
### Describe the bug

每当我让它生成图片时，生成图片的框会跑到原本输出框的上面。
大致是：

生成图像框

正在为你生成答案...

这是一个 xx 图片，希望你喜欢。

### Steps to reproduce

叫他生成一次图片

### Expected behavior

跑到下面👇🏻

### Versions

- OS: macOS Monterey 12
- Browser & Version: Microsoft Edge 115
- GoProxiBing Version: v1.11.4

**Comment by Harry-zklcdc** [comment]
截个图看看
