### ISSUE TITLE
[Feature] 🌈 Github Action 部署

### ISSUE THREAD

**Issue by Harry-zklcdc** [Harry-zklcdc/go-proxy-bingai#145]
查看此仓库: [Harry-zklcdc/go-proxy-bingai-ga](https://github.com/Harry-zklcdc/go-proxy-bingai-ga)

且用且珍惜

![72854224967688b81b83d3e47414f8a2](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/05679177-8be8-4fc4-8e73-25c7df192a73)

**Comment by whx1024** [comment]
感谢大大

**Comment by Xqh-Cxy** [comment]
action是不是有时间限制

**Comment by Harry-zklcdc** [comment]
> action是不是有时间限制

是的，所以我加了那个计划任务，每6小时自动启动

**Comment by Xqh-Cxy** [comment]
> > action是不是有时间限制
> 
> 是的，所以我加了那个计划任务，每6小时自动启动

但是action好像有限制每个月能执行多久。

**Comment by luckyEason** [comment]
要怎么用啊？

**Comment by 2531178480** [comment]
虽然但是
滥用action也不好
搞不好哪天GitHub就关闭action了

**Comment by Harry-zklcdc** [comment]
> 虽然但是 滥用action也不好 搞不好哪天GitHub就关闭action了

雀食，所以不建议用这个部署
