### ISSUE TITLE
[Feature] 🌈 Github CodeSpace 部署

### ISSUE THREAD

**Issue by Harry-zklcdc** [Harry-zklcdc/go-proxy-bingai#147]
演示站: https://bingai-cs.xiao-gy.tk

教程待更新

**Comment by Xqh-Cxy** [comment]
codespace有时间限制，每个月最低配置最多用60小时

**Comment by Xqh-Cxy** [comment]
action好像没有限制时间

**Comment by Harry-zklcdc** [comment]
> action好像没有限制时间

是的，但是容易被封号

**Comment by 2531178480** [comment]
codespace很简单吧好像
可以直接发一个只有新版release的库，然后直接跑
