### ISSUE TITLE
[Bug] 🐛 无法画画

### ISSUE THREAD

**Issue by glaw1984** [Harry-zklcdc/go-proxy-bingai#148]
### Describe the bug

画画提示如下需要搭梯子登陆才能操作

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/128808448/a1372347-e8fd-4db9-ac29-c69f49cdc884)

### Steps to reproduce

画画提示如下需要搭梯子登陆才能操作

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/128808448/a1372347-e8fd-4db9-ac29-c69f49cdc884)

### Expected behavior

画画提示如下需要搭梯子登陆才能操作

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/128808448/a1372347-e8fd-4db9-ac29-c69f49cdc884)

### Screenshots

画画提示如下需要搭梯子登陆才能操作

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/128808448/a1372347-e8fd-4db9-ac29-c69f49cdc884)

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version: 

### Additional context

画画提示如下需要搭梯子登陆才能操作

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/128808448/a1372347-e8fd-4db9-ac29-c69f49cdc884)

**Comment by luckyEason** [comment]
这不是bug，画图本身就要登陆
