### ISSUE TITLE
点击“/”触发提示词点击不可用

### ISSUE THREAD

**Issue by ilolita945** [Harry-zklcdc/go-proxy-bingai#15]
![image_2023-07-21_13-25-03](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/49525838/e2551838-c46e-4782-bec5-35c4c6dc5a2d)

手机浏览器 识图菜单样式异常
![QQ截图20230721132642](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/49525838/c32a05a9-3713-423e-ad27-caec0eedcd85)

**Comment by Harry-zklcdc** [comment]
待修复

**Comment by Harry-zklcdc** [comment]
> ![image_2023-07-21_13-25-03](https://user-images.githubusercontent.com/49525838/255080289-e2551838-c46e-4782-bec5-35c4c6dc5a2d.png)

已修复 https://github.com/Harry-zklcdc/go-proxy-bingai/releases/tag/v1.9.1

**Comment by ilolita945** [comment]
> > ![image_2023-07-21_13-25-03](https://user-images.githubusercontent.com/49525838/255080289-e2551838-c46e-4782-bec5-35c4c6dc5a2d.png)
> 
> 已修复 https://github.com/Harry-zklcdc/go-proxy-bingai/releases/tag/v1.9.1

大佬真棒，谢谢完善～

**Comment by qinguoluo** [comment]
我重新部署了怎么还是1.9.0？

**Comment by qinguoluo** [comment]
> > 我重新部署了怎么还是1.9.0？
> 
> 你操作问题

我是在vercel删除项目之后重新部署的。没搞懂问题出在哪里，请不吝赐教！

**Comment by Sisyphean-a** [comment]
> > ![image_2023-07-21_13-25-03](https://user-images.githubusercontent.com/49525838/255080289-e2551838-c46e-4782-bec5-35c4c6dc5a2d.png)
> 
> 已修复https://github.com/Harry-zklcdc/go-proxy-bingai/releases/tag/v1.9.1

这个修复现在是直接把提示词发送出去了，而不是放入到输入框中可以继续补充，有什么解决方案吗
例如，我的提示词是下面这个：
请使用通俗的语言和形象的比喻解释下面这个概念：

**Comment by Harry-zklcdc** [comment]
> 这个修复现在是直接把提示词发送出去了，而不是放入到输入框中可以继续补充，有什么解决方案吗 例如，我的提示词是下面这个： 请使用通俗的语言和形象的比喻解释下面这个概念：

你别按回车，直接点那个关键词，他就会自动到输入框中，回车我还想办法修

**Comment by Harry-zklcdc** [comment]
> 你操作问题

别乱说，是PWA的事情，更新后需要等待新版本下发之后，才会显示新版本
