### ISSUE TITLE
[Feature] 🌈 通过Github Codespaces获取Cookie以及过人机验证

### ISSUE THREAD

**Issue by innovateplus** [Harry-zklcdc/go-proxy-bingai#150]
# 通过Github Codespaces获取Cookie以及过人机验证
闲来无事自己摸索出了一个方法获取BingAI的Cookie以及过人机验证。

**此方法优势：Codespaces永久有效，以便之后重新获取cookie，避免每次都要登录。**

图文教程如下 ↓
### 1.点击 https://github.com/codespaces 并创建空白codespaces
![1](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/78544816/cb3c9286-fbd4-4fbd-b02e-7d993c111f94)

### 2.创建好后在webIDE的“终端”处输入以下指令并按回车：
```
docker run -p 8080:80 dorowu/ubuntu-desktop-lxde-vnc
```
![2](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/78544816/fdae2ece-62df-4931-866d-ab761fbf1dda)

### 3.首次使用会加载一两分钟，加载完后在页面右下角弹窗点击“在浏览器中打开”
![3](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/78544816/7fb4536f-fc04-40a8-9fb4-b6fa04728a1b)

会进入这样一个远程服务器桌面
![4](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/78544816/0e899d39-30bf-4362-994d-5ed2f5ac65b3)

### 4.配置FireFox
在左下角启动菜单处打开FireFox火狐浏览器
![5](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/78544816/c8d3108a-cfc3-416f-b4dc-c1696ad04ce8)

> 注意：这里只能使用自带的火狐浏览器，Edge和Chrome安装不上，可以通过插件让FireFox支持BingAI。

复制下面网址，打开网页左侧工具栏，粘贴到“剪贴板”，通过剪贴板实现复制。
```
https://addons.mozilla.org/en-US/firefox/addon/enable-bing-chat/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search
```
![6](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/78544816/64e6603e-ee16-463f-92db-04c5afd66045)

粘贴到地址栏并访问
![7](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/78544816/2ab35970-4c30-465b-b623-45414e343f13)

安装Bing插件
![8](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/78544816/7424f81b-30a1-4166-8c9b-6e1601cee624)
![9](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/78544816/58cc32a2-5726-407b-90f6-b6bd30281cb8)

### 5.访问 `www.bing.com` 并点击Sign in登录微软账号，中途可能会要求验证邮箱，按照他的提示操作即可。
![10](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/78544816/91334d1d-e104-4a04-bfae-3ee5ccb2dd68)

### 6.登录后点击 “Chat” 打开BingAI
![11](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/78544816/6b8fad2c-7718-42fa-85cc-113ef6a89ba0)

### 7.按F12打开开发者工具，如果F12呼出了外部浏览器的开发者工具，则从菜单栏打开。 
![12](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/78544816/22c9942e-532b-4f7a-9708-87a74a51f8d5)
![13](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/78544816/fa073553-ed9a-47cb-978d-d7dd87ec0e22)

### 8.找到“Storage”中的“Cookies”
![14](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/78544816/17836259-f952-4995-b74f-d7ac0beabfc4)

查找这两个cookies并在“Value”处双击后点复制
![15](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/78544816/5d06684a-5df4-46f0-8de8-6fe8b64ab943)
![16](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/78544816/adfec9a4-7a95-4f62-9cf5-2f88797e7f48)

cookie会复制到剪贴板中，自行复制出来使用即可
![17](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/78544816/0792e5c1-5b30-4a9a-9649-024709914c65)

## 非首次使用
1.点击 https://github.com/codespaces 找到你创建过的codespaces
2.直接运行 ```docker run -p 8080:80 dorowu/ubuntu-desktop-lxde-vnc``` 即可快速打开桌面

### 备注

此方法类似于微软虚拟机，Codespaces安装桌面环境后就相当于是一个永久境外云电脑，可以访问外网。Codespaces每个月最多免费用60小时，已经足够了

**Comment by SokWith** [comment]
我就把账户做进cf纯部署里面，科学上网或者打开微软培训，打开部署，选官方服务器，随便聊天就过认证了。不用登录微软。

**Comment by ghhuang482** [comment]
多谢大佬，可以了

**Comment by ohmyivan** [comment]
你这办法比打开科学上网软件慢得多··

**Comment by innovateplus** [comment]
> 你这办法比打开科学上网软件慢得多··

免费，无需软件啊

**Comment by SokWith** [comment]
> 你这办法比打开科学上网软件慢得多··

有些地方不方便科学上网，所以远程虚拟机还是很不错的

**Comment by FangZirui-E5** [comment]
太棒了

**Comment by FangZirui-E5** [comment]
> 你这办法比打开科学上网软件慢得多··

这个毕竟不算违法，可以光明正大的去传播😂

**Comment by innovateplus** [comment]
> > 你这办法比打开科学上网软件慢得多··
> 
> 这个毕竟不算违法，可以光明正大的去传播😂

对，最好还是少滥用codespaces，偶尔登录一次没问题的

**Comment by 2531178480** [comment]
github.dev的域名国内不稳定
应该挂上域名

**Comment by innovateplus** [comment]
> github.dev的域名国内不稳定
> 应该挂上域名

了解
https://github.com/dotnetcore/FastGithub

**Comment by ddkwork** [comment]
直接在space的系统内的浏览器内聊天不得行？

**Comment by Harry-zklcdc** [comment]
后面我整理到wiki里面
