### ISSUE TITLE
发现一个奇特的现象

### ISSUE THREAD

**Issue by luckyEason** [Harry-zklcdc/go-proxy-bingai#151]
自从我上次填写了KievRPSSecAuth和token，上次人机验证已有14天，可我到现在还没再遇到人机验证，cookie是拿出来共享的，基本每天都会达到24h限制

**Comment by luckyEason** [comment]
huggingface和cf的服务器都能用

**Comment by luckyEason** [comment]
vercel部署

**Comment by SokWith** [comment]
自从随机IP压缩到微软云后，就出现了这些彩蛋。
共享ID的好处是，有些地方是可以连第一个官方服务器的，会造成共享ID一直被官方认证。
现在认证ID非常方便，每个账户搞个cf部署，要认证的时候科学上网后选官方服务器，打开部署随便点击一下就过认证了。

**Comment by Harry-zklcdc** [comment]
🤔有点意思

**Comment by luckyEason** [comment]
> 🤔有点意思

这个号是上个月注册的新号，我懒得做人机验证，结果发现了这个现象

**Comment by SokWith** [comment]
> 自从随机IP压缩到微软云后，就出现了这些彩蛋。 共享ID的好处是，有些地方是可以连第一个官方服务器的，会造成共享ID一直被官方认证。 现在认证ID非常方便，每个账户搞个cf部署，要认证的时候科学上网后选官方服务器，打开部署随便点击一下就过认证了。
![IMG_20230822_123801](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/e54db1ae-1369-405d-b57c-67cf1c48a8cb)
刚才通过手机上官方服务器过认证

**Comment by Harry-zklcdc** [comment]
越来越有意思了🤣

**Comment by luckyEason** [comment]
> 越来越有意思了🤣
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/109937362/914486f4-902b-4e7b-b38c-d35645610c7e)
直到现在他还能用，只是24h了

**Comment by luckyEason** [comment]
没限制的时候是可以用，可以绘画的

**Comment by Harry-zklcdc** [comment]
试试新版本？

**Comment by luckyEason** [comment]
> 试试新版本？

如果要无cookie登录能升级新版本吗？

**Comment by karlcrane2015** [comment]
今天早上发现单次会话只有5次了，即使cookie登录了也一样
