### ISSUE TITLE
[Bug] 🐛 移动端Ads展示超出屏幕

### ISSUE THREAD

**Issue by ghost** [Harry-zklcdc/go-proxy-bingai#152]
### Describe the bug

移动端Ads展示超出屏幕

### Steps to reproduce

触发ad推荐

### Expected behavior

适应屏幕

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/131362758/89a40ce8-a0e5-41d8-9e99-41a02717838c)

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by Harry-zklcdc** [comment]
我尝试修复一下

提供一下你的问题

**Comment by nihao975** [comment]
> 我尝试修复一下
> 
> 提供一下你问的问题

1.茶杯犬 寿命 2.茶杯犬有哪些常见健康问题？ 弹出仅针对中国以外账号（可能随缘）

**Comment by Harry-zklcdc** [comment]
尝试一下最新版，我这边没法出现广告
