### ISSUE TITLE
[Feature] 🌈 使用Github Actions加Cloudflare Tunnel的方式部署

### ISSUE THREAD

**Issue by yangjianchuan** [Harry-zklcdc/go-proxy-bingai#153]
### Describe the problem related to the feature request

# 使用Cloudflare Tunnel的方式部署·

## 演示站点
以下站点随缘启动，我没有运行自动执行脚本
https://bing1.dongsiqie.me
## 注意事项

- 可能会被封号，请使用Github小号进行测试
- Cloudflare Tunnel 验证令牌需要Cloudflare账号
- 在Cloudflare有托管的域名
- Cloudflare需要绑定信用卡或者PayPal，不会扣款，只是验证
- 只建议个人临时使用，不建议用来搭建镜像

## 1.获取Cloudflare Tunnel 验证令牌

进入cloudflare首页，点击左侧的`Zero Trust`

```
https://dash.cloudflare.com/
```

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/104043801/5a4a47f8-f7fc-4fa2-853f-fb33e7da2489)

点击展开左侧的`Access`，点击`Tunels`，然后在中间点击`Create a tunnel`

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/104043801/494183b1-4c07-4432-b5ca-0bf3c6006149)

填写`Tunnel name`，比如填写为`bingai`，然后点击`Save tunnel`

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/104043801/57eb54a2-f6ad-45c2-8f2f-c9bec550d297)

然后在界面中找到`Run the following command:`这句话，从里面提取出来自己的验证令牌

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/104043801/57d7dcf7-3cbf-4272-9a5a-a6899ec2e893)

记录好另外，用于后续填写到 `CFT_AUTH_TOKEN` 中

## 2.fork项目

项目地址

```
https://github.com/Harry-zklcdc/go-proxy-bingai-ga/fork
```

## 3.新增两个机密环境变量

路径 `settings-Security-Secrets and variables-Actions`

点击`New repository secret`新增两个变量，`TYPE` 和 `CFT_AUTH_TOKEN` 

`TYPE`的值设置为`CFT`

 `CFT_AUTH_TOKEN` 的值为第一步中获取的内容

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/104043801/bb20bb43-cb7c-477c-a79e-cee0d1d5fc46)

## 4.启动工作流
备注：这个只是单次启动，单次只能运行6小时。如果后续还需要使用，需要再次启动工作流。

fork成功后，在自己的项目中点击 Actions

点击 `I understand my workflows, go ahead and enable them`

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/104043801/b3d67765-508d-4d6f-94ab-bd59ab24041f)

选择左侧的 `BingAI`，然后点击右侧的`Run workflow`

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/104043801/5316d045-4977-40d5-bf39-eff6442d3bdf)

然后点击弹出信息中的`Run workflow`

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/104043801/fe952c48-1ad0-4286-bb2a-21fd1e877e44)

## 4.1.设置工作流自动运行【可选步骤】
想要自动运行请取消下面的注释, 但是会增加被封号的风险
文件路径
```
.github/workflows/bingai.yml
```

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/104043801/f3a2ce3e-13a7-4fa3-9950-8b897980a9a4)

## 5.绑定自定义域名

找到通道`bingai`，点击对应的名称，然后在右侧弹出页面点击`Configure`

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/104043801/2d9f33a2-c3a6-4def-8623-069c73615aa8)

选择`Public Hostname`，然后点击`add a public hostname`

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/104043801/f4dc5a09-c2d7-4ac2-9f02-58e76afeb4f0)

然后按照下图填写域名相关信息，保存后等域名发布完成即可访问

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/104043801/4dd0e31d-1b49-479a-b249-10f0264b5051)

**Comment by Xqh-Cxy** [comment]
这个只能叫用cloudflare tunnel内网穿透吧

**Comment by yangjianchuan** [comment]
同步一下消息，被封号了，这个方案不建议使用
