### ISSUE TITLE
[Help] 🤔 无法获取会话ID

### ISSUE THREAD

**Issue by ningguoxu** [Harry-zklcdc/go-proxy-bingai#154]
### Describe the help wanted

无法获取会话ID

### Steps to behave

部署后访问发现无法正常聊天

### Expected behavior

正常使用

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/87106666/ccf0f164-f1a4-4a2d-8a2e-88ef242c56ab)

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by Harry-zklcdc** [comment]
你的网络不支持newbing
