### ISSUE TITLE
[Bug] 🐛 很抱歉，你已达到可在 24 小时内发送到必应的邮件限制。请稍后回来查看!

### ISSUE THREAD

**Issue by huangkaoya** [Harry-zklcdc/go-proxy-bingai#156]
### Describe the bug

上传图片后，报错 很抱歉，你已达到可在 24 小时内发送到必应的邮件限制。请稍后回来查看!

### Steps to reproduce

上传图片

### Expected behavior

应该能正常分析图片

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/29002330/d847fac0-1856-406d-85d7-7e061eb1da61)

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by huangkaoya** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/29002330/7485ee55-6ae9-4335-8327-8fcfc56369da)

**Comment by luckyEason** [comment]
账号200次主题限制，退出登录即可解决
