### ISSUE TITLE
[Bug] 🐛 运行release，但无法聊天

### ISSUE THREAD

**Issue by hyj120309** [Harry-zklcdc/go-proxy-bingai#157]
### Describe the bug

无论怎么样，都显示错误
![Screenshot_20230824_103236](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/123804488/4bd04e06-0663-40fc-a758-75b1b414f732)

### Steps to reproduce

运行release，访问localhost:8080，聊天，报错

### Expected behavior

应该能用才对啊啊啊啊

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by hyj120309** [comment]
聊天服务器没问题

**Comment by hyj120309** [comment]
这个好像能起到帮助：localhost发送的响应无效
![Screenshot_20230824_110725](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/123804488/5e620dd7-08c0-4a8a-a471-f5e85e8f40e9)
![Uploading Screenshot_20230824_110823.jpg…]()

**Comment by hyj120309** [comment]
这个好像能起到帮助：localhost发送的响应无效
![Screenshot_20230824_110725](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/123804488/5e620dd7-08c0-4a8a-a471-f5e85e8f40e9)
![Screenshot_20230824_110823](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/123804488/3a6ceaf9-3d03-46e7-bcfc-f8f1072c00b9)

**Comment by Harry-zklcdc** [comment]
本机你要配置代理才能运行

**Comment by hyj120309** [comment]
> 本机你要配置代理才能运行

怎么配置代理（socks？）

**Comment by hyj120309** [comment]
> > 本机你要配置代理才能运行
> 
> 怎么配置代理（socks？）
外网？

**Comment by Harry-zklcdc** [comment]
是这样的
