### ISSUE TITLE
[Bug] docker 部署后网站无法打开

### ISSUE THREAD

**Issue by listener-He** [Harry-zklcdc/go-proxy-bingai#160]
### Describe the bug

<img width="1274" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/39252579/ee014dd6-20cc-4362-8c71-f39261b323b2">

配置： 
<img width="859" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/39252579/488ecf8c-2781-4218-b01a-dec575243476">

### Steps to reproduce

在VPS服务器上使用docker-compose 部署

### Expected behavior

修复或有大佬解答

### Versions

- OS: Mac os
- Browser & Version: 
- GoProxiBing Version: 1.11.5

**Comment by yangjianchuan** [comment]
现在这个版本用哪种方式部署都是有问题的，等作者更新吧
或者你使用一个历史版本，用类似命令回到特定版本
```
git clone https://github.com/Harry-zklcdc/go-proxy-bingai.git /workspace/app
cd /workspace/app && git reset --hard 693fb7b0600ba05a5895bc174bd9530ba6c1c784
```

**Comment by Harry-zklcdc** [comment]
docker可以把后面的标签先换到 v1.11.5,

**Comment by Harry-zklcdc** [comment]
修好了
