### ISSUE TITLE
[Bug] 🐛 replit部署后运行错误

### ISSUE THREAD

**Issue by haohongwei** [Harry-zklcdc/go-proxy-bingai#161]
### Describe the bug

sh -c go build -o main .
go: downloading github.com/andybalholm/brotli v1.0.5
go: downloading github.com/refraction-networking/utls v1.4.3
go: downloading github.com/gaukas/godicttls v0.0.4
go: downloading github.com/klauspost/compress v1.16.7
go: downloading github.com/quic-go/quic-go v0.38.0
go: downloading golang.org/x/crypto v0.12.0
go: downloading golang.org/x/sys v0.11.0
../go/pkg/mod/github.com/refraction-networking/utls@v1.4.3/handshake_client.go:11:2: package crypto/ecdh is not in GOROOT (/nix/store/akhjsmrrsakcnj8x3xgygvizhccbyn0v-go-1.19.3/share/go/src/crypto/ecdh)
exit status 1

### Steps to reproduce

部署后直接运行

### Expected behavior

正常运行

### Versions

1.12

**Comment by SokWith** [comment]
问bing，说是版本低了，shell下载最新版go1.21以上版本
```
wget https://golang.google.cn/dl/go1.21.0.linux-amd64.tar.gz

```

**Comment by Harry-zklcdc** [comment]
不要Build

**Comment by haohongwei** [comment]
嗯，我先回退到1.11.4部署了，怎么在replit下直接运行二进制文件我还得找找看怎么弄

**Comment by Harry-zklcdc** [comment]
看这个 #164
