### ISSUE TITLE
[Help] 🤔 新建的会话无法继续进行对话，但是老对话可以进行下去，官网也是

### ISSUE THREAD

**Issue by yihaoshiyan** [Harry-zklcdc/go-proxy-bingai#162]
### Describe the help wanted

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/97588063/12a51346-5cc0-45fb-92a6-7964ef28c0b5)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/97588063/bc2db96f-20bc-410e-8a6b-7eccd0a07bf8)

### Steps to behave

就是直接访问官网，新开一个话题无法继续，使用老话题就可以继续进行聊天

### Expected behavior

望各位大佬帮忙

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version: 
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/97588063/27576f39-abbe-463c-873d-65d20e7a00ce)

**Comment by yihaoshiyan** [comment]
> 

版本如下
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/97588063/0b876530-f63d-4e72-845e-58d387409983)

**Comment by SokWith** [comment]
微软自己的虚拟机无登录都要验证及协议，所以目前绝大多数ip都躲不开要登录了
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/062eba3b-9f4a-4414-af15-8f2bfb6e2ce6)

**Comment by Harry-zklcdc** [comment]
那就说明巨硬写了bug

**Comment by Harry-zklcdc** [comment]
已修复
