### ISSUE TITLE
[Help] 🤔 新版本的环境变量的代理地址，代理的密码怎么填？

### ISSUE THREAD

**Issue by rakaki** [Harry-zklcdc/go-proxy-bingai#163]
### Describe the help wanted

新版本的ehrjk变量的代理地址，密码怎么填？

### Steps to behave

以前有个变量是代理的密码现在没有了

### Expected behavior

无

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by rakaki** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/88972415/c6985493-f5a7-4f50-a578-e19bcae2c1c1)
另一机器上旧版本的代理似乎还可以使用

**Comment by rakaki** [comment]
最后试了下，不带https://就没问题了
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/88972415/b31bb650-8844-4ca5-abc5-9b5c80276b49)

**Comment by Harry-zklcdc** [comment]
使用HTTP代理，值就为
~~~bash
http://用户名:密码@代理地址:代理端口

# 如果为https协议
https://用户名:密码@代理地址:代理端口
~~~

Socks 代理为
~~~bash
socks://用户名:密码@代理地址:代理端口
~~~
