### ISSUE TITLE
我的Dockerfile里面内置了Cookie,但还是不能用

### ISSUE THREAD

**Issue by MEMZ-FYS** [Harry-zklcdc/go-proxy-bingai#166]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/121286073/4cbd3810-6190-416a-9715-419eb1f474e0)

**Comment by MEMZ-FYS** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/121286073/534acdcf-6ff0-4c50-9c53-1d15cb52124c)

**Comment by Harry-zklcdc** [comment]
已修复
