### ISSUE TITLE
[Bug] 🐛 不能打开聊天记录和删除聊天记录

### ISSUE THREAD

**Issue by ningguoxu** [Harry-zklcdc/go-proxy-bingai#167]
### Describe the bug

无法打开聊天记录，删除聊天记录后刷新还在

### Steps to reproduce

部署后

### Expected behavior

可以打开聊天记录

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/87106666/4898327c-bfe5-4bc8-9ace-d8494c85ce01)

### Versions

- OS: Windows10
- Browser & Version: chrome114
- GoProxiBing Version: 1.13.2

**Comment by Harry-zklcdc** [comment]
更新到最新版本，然后删除浏览器缓存 或 一键重置试试，这个问题我昨天修复了
