### ISSUE TITLE
大佬，能不能教一下KievRPSSecAuth值的差找方法呀，死活找不到在哪呀

### ISSUE THREAD

**Issue by s181462537** [Harry-zklcdc/go-proxy-bingai#17]
大佬，能不能教一下KievRPSSecAuth值的差找方法呀，死活找不到在哪呀

**Comment by fenger7** [comment]
在EDGE浏览器，访问newbing，然后按F12，打开开发者助手，选择Tab->应用程序，左边找到Cookie这一栏，找到newbing的网络链接，从右边的列表中就可以找到这个值了。

**Comment by s181462537** [comment]
> 在EDGE浏览器，访问newbing，然后按F12，打开开发者助手，选择Tab->应用程序，左边找到Cookie这一栏，找到newbing的网络链接，从右边的列表中就可以找到这个值了。

但是我在这个位置，并没有找到KievRPSSecAuth，名称是不是显示成别的？

**Comment by Harry-zklcdc** [comment]
> 但是我在这个位置，并没有找到KievRPSSecAuth，名称是不是显示成别的？

退出重新登录一下

**Comment by s181462537** [comment]
> > 但是我在这个位置，并没有找到KievRPSSecAuth，名称是不是显示成别的？
> 
> 退出重新登录一下

重登就有了，万分感谢！！！
