### ISSUE TITLE
[Help] 🤔 KievRPSSecAuth 没有找到

### ISSUE THREAD

**Issue by Musicminion** [Harry-zklcdc/go-proxy-bingai#172]
### Describe the help wanted

没有找到KievRPSSecAuth字段的Cookie？

### Steps to behave

<img width="309" alt="截屏2023-08-28 00 53 40" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/84625273/117cd7e9-e6d7-4ff4-b195-69d5aac112dc">

### Expected behavior

找到KievRPSSecAuth字段的Cookie？

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by 7noemo** [comment]
+1 又是bing的新策略吧 等大大更新

**Comment by qinguoluo** [comment]
我也是。一台电脑有这个字段，一台没有。

**Comment by ningguoxu** [comment]
重新登陆一下试试

**Comment by qinguoluo** [comment]
新版v1.14.0更新后用不了。很抱歉，似乎出现错误。 让我们重新开始吧。

**Comment by Harry-zklcdc** [comment]
和账号有关系，海外账号没有这个参数

**Comment by Musicminion** [comment]
那海外账号应该填写什么呢？在 2023年8月28日，13:44，zklcdc ***@***.***> 写道：﻿
和账号有关系，海外账号没有这个参数

**Comment by Harry-zklcdc** [comment]
> 那海外账号应该填写什么呢？

不填

**Comment by qinguoluo** [comment]
我的账号不是海外账号。家里的电脑没有KievRPSSecAuth这个参数，以前是有的。单位的电脑有这个参数。另外我发现只是在vercel上设置了4个参数浏览器端不设置是用不了的。提示错误：让我们重新开始。必须在浏览器端把参数填完整才能正常使用。所以我干脆把vercel上的参数都删除了。

**Comment by Harry-zklcdc** [comment]
填入随机值
