### ISSUE TITLE
[Bug] 🐛 一直重新连接

### ISSUE THREAD

**Issue by ningguoxu** [Harry-zklcdc/go-proxy-bingai#173]
### Describe the bug

设置用户后一直重新连接

### Steps to reproduce

部署最新版本后

### Expected behavior

修复

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/87106666/43526d25-0872-458c-9483-f6cc38e4ddea)

### Versions

- OS: Windows
- Browser & Version: chrome114
- GoProxiBing Version: 1.14.0

**Comment by qinguoluo** [comment]
检查一下聊天服务器的设置，是不是设成Bing 官方了。

**Comment by ningguoxu** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/87106666/eb50990e-02bb-4d88-9b89-da45b39e0cdc)
是本站

**Comment by qinguoluo** [comment]
这两天不知道是网络还是版本的原因一直不正常。现在又链接不上了，说 让我们重新开始吧。点开又是： Sorry, this version of your browser is not supported. Please update your browser to the latest version to continue.我用的是edge最新版。搞不懂了。

**Comment by qinguoluo** [comment]
这两天不知道是网络还是版本的原因一直不正常。现在又链接不上了，说 让我们重新开始吧。点开又是： Sorry, this version of your browser is not supported. Please update your browser to the latest version to continue.我用的是edge最新版。搞不懂了。

**Comment by Harry-zklcdc** [comment]
> 这两天不知道是网络还是版本的原因一直不正常。现在又链接不上了，说 让我们重新开始吧。

看看你的 `create` 请求的响应头（官网的和go-proxy-bing上的都看看）

我的是这样的
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/0b59ff01-a605-4d64-bad8-cf7593b263e1)
是有包含 `X-Sydney-Conversationsignature` 和 `X-Sydney-Encryptedconversationsignature` 这两个响应头的

尝试刷新浏览器缓存后，填写完整Cookie，然后再次尝试

> 点开又是： Sorry, this version of your browser is not supported. Please update your browser to the latest version to continue.我用的是edge最新版。搞不懂了。

有这个情况？

**Comment by Harry-zklcdc** [comment]
刚才试了一下，这个特性似乎已经全量更新了

**Comment by qinguoluo** [comment]
已经在vercel上设置了四个环境变量，为什么每轮聊天只能问5个问题，超过就要求登陆？
![屏幕截图 2023-08-28 212327](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/92149037/8cca73e6-f49b-47c4-a5c0-cc30d9882521)
![屏幕截图 2023-08-28 212415](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/92149037/12c2d0d7-f3a6-4326-a009-fe382c507c16)

**Comment by Harry-zklcdc** [comment]
前段也要配置Cookie，因为后端没法拿到前端的设置，所以只能让前端也需要配置Cookie了🤣，或者我搞个设置项？设置是否共享Cookie?

**Comment by qinguoluo** [comment]
如果前端还需要配置cookie才行，后端设置变量有什么意义？不太明白，请教一下。

**Comment by jhzroot** [comment]
原來1.12.0版本一点问题都没有

**Comment by qinguoluo** [comment]
> 前段也要配置Cookie，因为后端没法拿到前端的设置，所以只能让前端也需要配置Cookie了🤣，或者我搞个设置项？设置是否共享Cookie?

如果能共享Cookie应该不错。

**Comment by ningguoxu** [comment]
奇怪，我换个域名就可以正常使用了🤔

**Comment by Harry-zklcdc** [comment]
起了怪了，有些人是正常的，有些人就没法使用😅，还没弄懂Bing的策略是啥

**Comment by 7noemo** [comment]
不知道是不是我的问题，新版v1.14.0在vercel不能用，旧版v1.11.5还正常。

**Comment by ningguoxu** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/87106666/a5db0121-6e71-441d-a7d4-9f87030ae7b6)
Failed to get WelcomeScreen Suggestion: SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON这是报错信息

**Comment by Mrycp** [comment]
遇到相同的问题配置cookie后提示重新连接，使用完整的cookie也一样。清除cookie后问题数变为了5

**Comment by luckyEason** [comment]
发现刷新网页后就用不了了，服务器用zeabur的亚马逊区，cookie是随机的，一键重置完可以聊5句，但刷新后就一直正在出现连接![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/109937362/f11003c6-8115-4461-a268-35a275a3bb26)

**Comment by Harry-zklcdc** [comment]
我到时候看看

**Comment by luckyEason** [comment]
@Harry-zklcdc 劳烦您了

**Comment by Harry-zklcdc** [comment]
最新版呢？会吗？

**Comment by luckyEason** [comment]
感谢，一点问题也没有，天气预报可以也可以加载出来了
