### ISSUE TITLE
请问是否可以部署在自己的服务器宝塔上？[Help] 🤔 

### ISSUE THREAD

**Issue by myhyday** [Harry-zklcdc/go-proxy-bingai#176]
### Describe the help wanted

我目前是部署在hugging face上，可以使用，但是延时严重，回复内容卡顿。
我想问下，是否可以部署在自己服务器的宝塔上运行？

### Steps to behave

我在宝塔上安装好了docker管理器，使用终端连接宝塔，输入docker部署指令：
docker run -e USER_KievRPSSecAuth=kJs8hD92ncMzLaoQWYtX5rG6bE3fZ4iO -d -p 8080:8080 --name go-proxy-bingai --restart=always zklcdc/go-proxy-bingai

部署过程中，docker下载好了镜像，但是镜像下载好了之后，出现下面错误提示：
docker:Error response fromdaemon:failed to create task for container:failed to create shim task:OCI runtime create failed:unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v
2.task/moby/bf5ee07d6dffdc136bb21fd8e078b7fccb4371377abe5ad8377e71b7010902ca/log.json:no such file or directory):runc did notterminateSuccessfully:exit status 127:unknown.

### Expected behavior

请帮忙指导哈~

### Screenshots
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/137804274/74d2ad61-d7e4-448c-a8e7-d74100185ae0)

_No response_

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version: 
最新镜像

**Comment by Harry-zklcdc** [comment]
你的服务器能正常访问NewBing那就可以，或者在配置代理的情况下可以正常访问NewBing那也可以

**Comment by myhyday** [comment]
> 你的服务器能正常访问NewBing那就可以，或者在配置代理的情况下可以正常访问NewBing那也可以

但是我在服务器的宝塔上部署过程中，出现了错误，请您帮忙看下，具体见一楼详细描述部分

**Comment by skyfly2000** [comment]
看教程https://github.com/Harry-zklcdc/go-proxy-bingai/wiki
