### ISSUE TITLE
[Feature] 🌈 无限制对话轮数

### ISSUE THREAD

**Issue by tian1326** [Harry-zklcdc/go-proxy-bingai#177]
疑似bing新策略，在原站可以多次对话但是不显示余剩对话次数，之前是显示N共30的
<img width="1248" alt="屏幕截图 2023-08-30 110343" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/73376609/25000a34-c2f4-45e7-9441-6ce69b3651f9">
在镜像站上对话会显示N共5到了5之后就不能对话了，但是我再回到源站又可以继续对话
<img width="780" alt="屏幕截图 2023-08-30 110145" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/73376609/c8819b4b-76c8-41a6-9ef7-9a01034a3669">

**Comment by Harry-zklcdc** [comment]
哦？有这事🌈，我看看去，有的话就更新一波

**Comment by Harry-zklcdc** [comment]
我还有😅

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/d165de60-215b-4233-b152-fcbc48d49489)

**Comment by tian1326** [comment]
> Owner
> ###

额不显示剩余次数是忘记关脚本了，但是确实是镜像站5次，原站30次

**Comment by Harry-zklcdc** [comment]
> 额不显示剩余次数是忘记关脚本了，但是确实是镜像站5次，原站30次

镜像站登录了也5次？

源站不登录能有30次？！😯

**Comment by tian1326** [comment]
> > 额不显示剩余次数是忘记关脚本了，但是确实是镜像站5次，原站30次
> 
> 镜像站登录了也5次？
> 
> 源站不登录能有30次？！😯

登录了，聊天历史都同步了，是我用环境变量登录的原因

**Comment by chokiproai** [comment]
@Harry-zklcdc 尝试使用隐身选项卡或注销您的 bing 帐户并转到 https://bingai.zklcdc.xyz 。 您会看到网站上只剩下 5 个聊天记录。
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/128912789/d2ffdd80-6fdf-47a5-ab57-d3d02ec0e5fb)

**Comment by qinguoluo** [comment]
> > > 额不显示剩余次数是忘记关脚本了，但是确实是镜像站5次，原站30次
> > 
> > 
> > 镜像站登录了也5次？
> > 源站不登录能有30次？！😯
> 
> 登录了，聊天历史都同步了，是我用环境变量登录的原因？

使用环境变量能同步聊天记录，但只能聊5次，超过就让你登录。

**Comment by tian1326** [comment]
> 

是，我就是这样，但是之前是可以30次的，而且我换成填cookie也这样

**Comment by chokiproai** [comment]
@tian1326  我的网站使用了 cookie，但还是一样

**Comment by karlcrane2015** [comment]
目前无论登录与否都5次的限制问题能解决吗

**Comment by Harry-zklcdc** [comment]
用1.12.0，我大版本还是保持和bing一致

**Comment by Harry-zklcdc** [comment]
找到设置项了
https://github.com/Harry-zklcdc/go-proxy-bingai/blob/a976f555addc887c0d7de8f24b0d0f28522edfbd/frontend/public/js/bing/chat/config.js#L190

改一下这个就可以设置未登录账号的聊天次数了

**Comment by Harry-zklcdc** [comment]
最新版支持自定义聊天次数了
