### ISSUE TITLE
[Help] 🤔 如何设置不显示最近的聊天记录，进入网页就不显示

### ISSUE THREAD

**Issue by yihaoshiyan** [Harry-zklcdc/go-proxy-bingai#178]
### Describe the help wanted

如题

### Steps to behave

进入网页后就不会显示聊天记录

### Expected behavior

希望大佬能帮帮忙(;´༎ຶД༎ຶ`) 

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by luckyEason** [comment]
有登录吗，只有登录账号才会有聊天记录

**Comment by yihaoshiyan** [comment]
> 有登录吗，只有登录账号才会有聊天记录

对的，登陆了账号，但是不想让别人看到聊天记录，(;´༎ຶД༎ຶ`)

**Comment by yihaoshiyan** [comment]
部署的时候就把账号部署上去了

**Comment by luckyEason** [comment]
直接设置授权码吧，config不建议乱改，反正设置完授权码后，只有使用授权码才能用环境变量设置的账号

**Comment by luckyEason** [comment]
设置完环境变量后记得重新部署

**Comment by yihaoshiyan** [comment]
额，其实我就是想给朋友们都能使用，只是想保护他们的隐私，不被别人看到/(ㄒoㄒ)/~~

**Comment by luckyEason** [comment]
> 额，其实我就是想给朋友们都能使用，只是想保护他们的隐私，不被别人看到/(ㄒoㄒ)/~~
> 
> 
> 
> 

这个建议去问Harry

**Comment by yihaoshiyan** [comment]
就是想问一下啊大佬/(ㄒoㄒ)/~~

> > 额，其实我就是想给朋友们都能使用，只是想保护他们的隐私，不被别人看到/(ㄒoㄒ)/~~
> 
> 这个建议去问Harry

**Comment by Harry-zklcdc** [comment]
1. 先学习项目构建方法
2. 学习Vue3基本知识
3. 前端不显示聊天记录代码
https://github.com/Harry-zklcdc/go-proxy-bingai/blob/a976f555addc887c0d7de8f24b0d0f28522edfbd/frontend/src/stores/modules/user/index.ts#L83-L89
4. 有个是否上传聊天记录的设置，这个我要找一下

**Comment by yihaoshiyan** [comment]
> 1. 先学习项目构建方法
> 2. 学习Vue3基本知识
> 3. 前端不显示聊天记录代码
>    https://github.com/Harry-zklcdc/go-proxy-bingai/blob/a976f555addc887c0d7de8f24b0d0f28522edfbd/frontend/src/stores/modules/user/index.ts#L83-L89
> 4. 有个是否上传聊天记录的设置，这个我要找一下

感谢大佬，谢谢o(*￣▽￣*)ブ

**Comment by yihaoshiyan** [comment]
![JKCQW(BLFKEQ5D(U9RMHNXI](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/97588063/a01c155b-589e-4c95-8519-8e4a6281bb3e)，没消失(・∀・(・∀・(・∀・*)
