### ISSUE TITLE
b站上有个人拿这个项目当企业版赚钱

### ISSUE THREAD

**Issue by luckyEason** [Harry-zklcdc/go-proxy-bingai#179]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/109937362/d632b7b1-a820-48ef-9c9a-e6911fffba12)

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/109937362/a8ec39aa-282a-41b9-8725-6fafc389bf4d)

这个项目和别的项目都被修改源码拿去卖

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/109937362/45ccaee7-a6ac-49a9-9998-952853413df5)

这就很让人无语

**Comment by luckyEason** [comment]
不过这项目身价挺高的，299

**Comment by MEMZ-FYS** [comment]
哈哈哈，我加了他的微信，已经拉黑了哈哈哈

**Comment by Harry-zklcdc** [comment]
建议举报处理

**Comment by luckyEason** [comment]
> 如果删除相关版权信息，建议举报处理，MIT协议可以商用，但是要求就是保留原始版权信息

他把开源地址删了，改成了他的什么公司

**Comment by Harry-zklcdc** [comment]
> 他把开源地址删了，改成了他的什么公司

😅，啥时候给寄一封律师函过去
