### ISSUE TITLE
手机竖屏模式下添加图像菜单样式请求适配

### ISSUE THREAD

**Issue by ilolita945** [Harry-zklcdc/go-proxy-bingai#18]
![QQ截图20230721181245](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/49525838/db7c7a0a-da0d-4d1d-a90f-01f9499de557)

![QQ截图20230721181447](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/49525838/30f50d91-a576-4def-b1ad-7d1b9b455d7e)

部分显示不全

**Comment by Harry-zklcdc** [comment]
过两天搞，这两天有其他事情

**Comment by ilolita945** [comment]
> 



> 过两天搞，这两天有其他事情

谢谢

**Comment by Harry-zklcdc** [comment]
可能会后面在修，不影响使用就先不修了，最近在想办法把新版本的撰写给移植了，还有那个页面搜索功能，不确定能不能移植

**Comment by yifangyujason** [comment]
大佬，能再加一个ctrl+V 粘贴图片的功能吗？这样就不用保存到本地，然后再点击”从此设备上传“ 这么繁琐了

**Comment by Harry-zklcdc** [comment]
> 大佬，能再加一个ctrl+V 粘贴图片的功能吗？这样就不用保存到本地，然后再点击”从此设备上传“ 这么繁琐了

微软支持的话就做，主要是逻辑得写得好多，有空就搞吧

**Comment by Harry-zklcdc** [comment]
已修复
commit: https://github.com/Harry-zklcdc/go-proxy-bingai/commit/cfda2edaef68da8163b61167f3c8aea222cf4ec3
release: https://github.com/Harry-zklcdc/go-proxy-bingai/releases/tag/v1.10.0

**Comment by YuenSzeHong** [comment]
> 大佬，能再加一个ctrl+V 粘贴图片的功能吗？这样就不用保存到本地，然后再点击”从此设备上传“ 这么繁琐了

微软官方没支持，理论可行，因为微软也是传送base64，只是得粘贴的时候辨别是文本还是文件，文件就读取base64（还得识别是不是图🥹）
