### ISSUE TITLE
上传图片大概率失败

### ISSUE THREAD

**Issue by luckyEason** [Harry-zklcdc/go-proxy-bingai#180]
### Describe the help wanted

我上传图片总是失败，只有偶尔能成功

### Steps to behave

使用vercel部署，利用huggingface搭建聊天服务器，上传图片失败

### Expected behavior

解决这个问题

### Screenshots

 
![Uploading IM
![IMG_1899](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/109937362/a0b97ed1-4be2-4d56-b806-6db312e3e86a)
G_1899.jpe

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by chokiproai** [comment]
我也遇到了同样的问题
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/128912789/e228ebdb-78a6-449d-8010-adbf2e3a554d)

**Comment by Harry-zklcdc** [comment]
我这是正常的，需要更多信息

**Comment by luckyEason** [comment]
> 我这是正常的，需要更多信息

我电脑可以，移动设备不行

**Comment by chokiproai** [comment]
我使用 Huggingface  构建聊天服务器，但照片上传失败.@Harry-zklcdc 请修复此问题

**Comment by luckyEason** [comment]
在1.14.0上没有这个问题，但是，在1.12.0上确实有此问题。
@Harry-zklcdc 希望1.14.0能早日恢复正常的对话次数，不然1.12.0只能使用电脑上传图片

**Comment by Harry-zklcdc** [comment]
但是雀食是正常次数啊，bing官网现在就是，不登录5次，登录了30次，我这边只会和官网保持同步

**Comment by luckyEason** [comment]
为什么1.12.0可以聊10次呢🧐

**Comment by luckyEason** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/109937362/c4ca5067-9f7f-4e72-8ff1-17e0cf02b13c)

**Comment by Harry-zklcdc** [comment]
旧版本的API

**Comment by luckyEason** [comment]
@Harry-zklcdc 懂了，谢谢大佬

**Comment by luckyEason** [comment]
@Harry-zklcdc 话说1.14.0稳定性有点差，ipad每次聊到第3句网页就崩溃了，崩溃刷新后会出现正在出现连接的问题

**Comment by luckyEason** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/109937362/2d67297a-fa7d-4341-ac94-afd5c61aad96)

**Comment by SokWith** [comment]
> 旧版本的API

我测试了官方最新API，就是3CVA*****的那个js，加载到1.11.5版本上（详细测试站点见https://replit.nbing.eu.org），仍然是30次的；
我也把全cookie（也就是包括了M值的）投入到NewBingGoGo的测试站点（详细见https://cfweb.nbing.eu.org），也是显示30次的。
所以，推测还是1.14.0的前端让官方误认为没有登录，所以限制为5次了。
