### ISSUE TITLE
手机端跳转网页不用edge就不正常，但是可以长按[Help] 🤔 

### ISSUE THREAD

**Issue by hjx2289206** [Harry-zklcdc/go-proxy-bingai#182]
### Describe the help wanted

长按跳转在新标签页打开在任意浏览器都正常，不知道能不能改进一下

### Steps to behave

。

### Expected behavior

。

### Screenshots

![Screenshot_20230830_234950_com lemurbrowser exts](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/134860604/4e4efd71-718e-4150-bceb-dbce086108bb)

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by chokiproai** [comment]
https://github.com/Harry-zklcdc/go-proxy-bingai/issues/180#issue-1874713712

**Comment by hjx2289206** [comment]
这确实是正常情况，不过我比较好奇原作者的演示站点和binggo的跳转为什么不会出现http://edgeservices.bing.com的重定向问题

**Comment by Harry-zklcdc** [comment]
我没替换网址😂

**Comment by Harry-zklcdc** [comment]
而且我这没有这种情况，需要更多的信息

**Comment by hjx2289206** [comment]
估计是你没有用其他手机上的浏览器，如果用edge或挂T确实没有问题

**Comment by hjx2289206** [comment]
现在有办法修复这个http://edgeservices.bing.com的重定向问题，实现直接长按的效果吗？

**Comment by Harry-zklcdc** [comment]
这个我暂时没法修复，之后我看看有没有其他解决方法

**Comment by Harry-zklcdc** [comment]
已修复, Commit: 07ace09029ba6675ffe34bdaad750d816d43ff22
