### ISSUE TITLE
[Help] 🤔 聊天次数

### ISSUE THREAD

**Issue by hjx2289206** [Harry-zklcdc/go-proxy-bingai#184]
### Describe the help wanted

现在在官网聊天次数也只有5次了，且在1.14.0和1.20.0上都无法聊天

### Steps to behave

一开始这是挂t后总是出现错误，去官网后发现聊天次数也只有5次，且登录了账号

### Expected behavior

。

### Screenshots

![Screenshot_20230903_093219_com lemurbrowser exts](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/134860604/209b54da-b22c-4b32-ba08-25208b30ccee)

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by hjx2289206** [comment]
奇怪了，1.12.0非常正常，聊天次数官网5次，我在1.12.0的版本上聊了12次都可以继续聊

**Comment by luckyEason** [comment]
api不一样，1.12.0用的是旧的api

**Comment by luckyEason** [comment]
@hjx2289206 ![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/109937362/3ffa25f0-78d4-412b-9cdb-9378ff6979a3)

**Comment by luckyEason** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/109937362/1f10f7b1-11a3-4c98-932e-b7a91cbe8907)
我官网有30次

**Comment by hjx2289206** [comment]
我官网也是30次了
