### ISSUE TITLE
[Help] 🤔 replit部署后报Sorry, looks like your network settings are preventing access to this feature.

### ISSUE THREAD

**Issue by Samre** [Harry-zklcdc/go-proxy-bingai#185]
### Describe the help wanted

Sorry, looks like your network settings are preventing access to this feature.

### Steps to behave

直接一键部署的

### Expected behavior

该如何解决呢

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by shenyoujun666** [comment]
应该是被ban了

**Comment by Samre** [comment]
部署了几次都不行

**Comment by SokWith** [comment]
> 部署了几次都不行

检查ID，检查IP：
https://github.com/Harry-zklcdc/go-proxy-bingai/issues/103#issue-1838485571

**Comment by chokiproai** [comment]
如何在replit上运行

**Comment by Harry-zklcdc** [comment]
replit好像是被巨硬ban了
