### ISSUE TITLE
[Help] 🤔 FireFox 上加载不了历史聊天，但 Edge 可以。

### ISSUE THREAD

**Issue by CongYun22** [Harry-zklcdc/go-proxy-bingai#187]
### Describe the help wanted

FireFox 无法加载历史聊天。

### Steps to behave

新建、删除和重命名对话正常，但无法加载历史聊天。

### Expected behavior

FireFox 可以加载历史聊天。

### Screenshots

FireFox 上的网页截图：
![图片](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/115971962/b2c741db-9fde-41ed-8275-0039171a6a22)

### Versions

- OS: Windows 10 家庭中文版 22H2
- Browser & Version: FireFox  117.0（ 64 位 ），Edge 116.0.1938.69 (正式版本) (64 位)

**Comment by CongYun22** [comment]
可选 Cookie 是在 FireFox 上登录然后获取的，现在新建不了聊天了，但 Edge 依然可以正常使用。

**Comment by luckyEason** [comment]
问一下，你有登录吗？

**Comment by CongYun22** [comment]
> 问一下，你有登录吗？

分别在 FireFox 和 Edge 上登录后获取的 cookie，然后填在了各自的浏览器上，聊天用的 https://bingai.zklcdc.xyz/web/?showconv=1#/

**Comment by Harry-zklcdc** [comment]
无回复，暂时关闭此issue，有问题再重新打开
