### ISSUE TITLE
[Bug] 🐛 Huggingface 上的 bing 出现无法发送图片的问题

### ISSUE THREAD

**Issue by chokiproai** [Harry-zklcdc/go-proxy-bingai#188]
### Describe the bug

Huggingface 上的 bing 出现无法发送图片的问题

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/128912789/e4f345b2-5af2-4e7e-b890-fec76abb719b)

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by chokiproai** [comment]
cloudflare、vercel 不会发生这种情况...

**Comment by shenyoujun666** [comment]
我也是…

**Comment by shenyoujun666** [comment]
@Harry-zklcdc

**Comment by luckyEason** [comment]
我这边vercel也会

**Comment by luckyEason** [comment]
vercel用的是1.12.0，在zeabur也部署了一个，用1.14.0，可以上传。貌似是1.12.0有这个问题
