### ISSUE TITLE
 很抱歉，似乎出现错误。 让我们重新开始吧。

### ISSUE THREAD

**Issue by roiff** [Harry-zklcdc/go-proxy-bingai#189]
### Describe the bug

二进制部署，版本1.14.0
chat一直出现"很抱歉，似乎出现错误。 让我们重新开始吧。"

撰写文章和图片生成可以用。

更新解决办法：
一、服务器端环境变量中，只填写3项
USER_KievRPSSecAuth
USER_RwBf
USER_MUID

不填写Go_Proxy_BingAI_USER_TOKEN

在前端的设置中，填写token这一项。

目前这样的情况下，问题就解决了。

### Steps to reproduce

使用二进制部署
用了宝塔申请了ssl证书和反向代理。
总export增加了4个cooies环境变量后运行二进制
无其他操作

### Expected behavior

解决能够chat的问题

### Versions

- OS: macos 和 ios
- Browser & Version: Chrome 和 EDGE
- GoProxiBing Version: 1.14.0

**Comment by luckyEason** [comment]
目前的解决办法是，一键重置。但是刷新后问题复现。

**Comment by roiff** [comment]
> 目前的解决办法是，一键重置。但是刷新后问题复现。

目前基本知道如何解决了：

**Comment by roiff** [comment]
我目前找到了解决方法，实测有效：
一、服务器端环境变量中，只填写3项
USER_KievRPSSecAuth
USER_RwBf
USER_MUID

不填写Go_Proxy_BingAI_USER_TOKEN

在前端的设置中，填写token这一项。

目前这样的情况下，问题就解决了。

**Comment by iomke** [comment]
windows 出现很抱歉，似乎出现错误。 让我们重新开始吧。怎么解决大佬

**Comment by Harry-zklcdc** [comment]
具体操作为？输入内容之后开始聊天，然后出现的是吗？

**Comment by luckyEason** [comment]
> 具体操作为？输入内容之后开始聊天，然后出现的是吗？

输入内容之后开始聊天,刷新网页之后就出问题了

**Comment by luckyEason** [comment]
iPad有，Windows没有

**Comment by luckyEason** [comment]
说不定又是safari的问题

**Comment by Harry-zklcdc** [comment]
试试最新版

**Comment by Mrycp** [comment]
> 

如何在前段只填写token这一项呢？填写的时候有完整性校验

**Comment by Harry-zklcdc** [comment]
最新版试试
