### ISSUE TITLE
首次使用时会引发无效域问题

### ISSUE THREAD

**Issue by ilolita945** [Harry-zklcdc/go-proxy-bingai#19]
![QQ截图20230721210512](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/49525838/a6a6b68c-faa8-46e0-b901-abb10e6b5949)

复现方式：小号窗口或InPrivate窗口，直接提问就会报无效域错误，需要点击一键重置。

**Comment by Harry-zklcdc** [comment]
正常，巨硬加强了监管
