### ISSUE TITLE
[Help] 🤔 一直正在链接

### ISSUE THREAD

**Issue by MEMZ-FYS** [Harry-zklcdc/go-proxy-bingai#190]
### Describe the help wanted

一直正在链接

### Steps to behave

直接问

### Expected behavior

修复

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/121286073/fd47d201-89e4-4577-9d04-8c84268265f7)

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by Harry-zklcdc** [comment]
请提供更多信息
