### ISSUE TITLE
[Bug] 🐛 一键重置有几率报错

### ISSUE THREAD

**Issue by yangjianchuan** [Harry-zklcdc/go-proxy-bingai#191]
### Describe the bug

V1.15.1 一键重置有几率报错
```
嗯… 无法访问此页面网址为https://dongsiqie-bing.hf.space/web/?showconv=1#/ 的页面可能存在问题，或者已永久移动到新的网址。
ERR_FAILED

```

### Steps to reproduce

很可能是这个自动加上的参数导致的
```
?showconv=1#/
```

### Expected behavior

一键重置的时候忽略参数部分

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by Harry-zklcdc** [comment]
已修复
