### ISSUE TITLE
[Bug] 🐛 我的完整cookie加进去后不能上网

### ISSUE THREAD

**Issue by cengzhijie3** [Harry-zklcdc/go-proxy-bingai#192]
### Describe the bug

我的完整cookie加进去后不能上网

### Steps to reproduce

似乎在新版本任然有这种问题

### Expected behavior

不能用

### Screenshots

<img width="669" alt="截圖 2023-09-05 下午2 05 37" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/89333400/20853bb7-24b4-4573-964a-ceeccfc3b7c3">
<img width="942" alt="截圖 2023-09-05 下午2 05 44" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/89333400/5b8a8cd3-2e05-43f9-8060-b677695fedb3">
<img width="942" alt="截圖 2023-09-05 下午2 08 30" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/89333400/ef799170-e282-4351-9358-b01e3399f191">

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version: 

### Additional context

<img width="669" alt="截圖 2023-09-05 下午2 05 37" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/89333400/2c6c2181-433a-4f4a-a5ef-1793d890abce">
<img width="942" alt="截圖 2023-09-05 下午2 05 44" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/89333400/09ee42d1-f50a-4f7b-9b20-e9a1a628d867">
<img width="942" alt="截圖 2023-09-05 下午2 08 30" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/89333400/7d9c442d-de12-4808-9ca3-996bd96a63f1">

**Comment by Thot-null** [comment]
你都有梯子了为啥不直接用newbing,先确保cookie可以进入原版newbing，关了梯子试试

**Comment by cengzhijie3** [comment]
> 

我这个搭建的还是不行，cookie是一样的，没变过

**Comment by Thot-null** [comment]
> > 
> 
> 我这个搭建的还是不行，cookie是一样的，没变过

抱脸的可以用，刚刚升级

**Comment by RikkaLzw** [comment]
我也不行，用了抱脸和cf 都不行

**Comment by Thot-null** [comment]
> 我也不行，用了抱脸和cf 都不行

我用的抱脸，不要输入cookie,配置好之后先问个问题，如果不行，那就是配置问题或者你本地的网络问题，就使用它默认自带的本站服务，如果没有cookie可以用，那你是账户的问题

**Comment by RikkaLzw** [comment]
> 

没懂你的意思。。。我用梯子访问了bing是可以用的。但是用了复制的cookies在部署的上面就不行。抱脸我是直接复制的，也没更改过什么配置

**Comment by RikkaLzw** [comment]
没懂你的意思。。。我用梯子访问了bing是可以用的。但是用了复制的cookies在部署的上面就不行。抱脸我是直接复制的，也没更改过什么配置

**Comment by Thot-null** [comment]
> > 
> 
> 没懂你的意思。。。我用梯子访问了bing是可以用的。但是用了复制的cookies在部署的上面就不行。抱脸我是直接复制的，也没更改过什么配置

没有设置cookie的时候，抱脸部署好的也不能用吗？

**Comment by RikkaLzw** [comment]
> 

是的

**Comment by Thot-null** [comment]
> > 
> 
> 是的

那大概率没部署好，我现在使用的就是抱脸部署的项目，有没有cookie都可以用，没有挂梯子，使用的默认的服务，不要使用bing的服务

**Comment by RikkaLzw** [comment]
> > > 
> > 
> > 
> > 是的
> 
> 那大概率没部署好，我现在使用的就是抱脸部署的项目，有没有cookie都可以用，没有挂梯子，使用的默认的服务，不要使用bing的服务

你能帮你的给我复制一下吗

**Comment by Thot-null** [comment]
> > > > 
> > > 
> > > 
> > > 是的
> > 
> > 
> > 那大概率没部署好，我现在使用的就是抱脸部署的项目，有没有cookie都可以用，没有挂梯子，使用的默认的服务，不要使用bing的服务
> 
> 你能帮你的给我复制一下吗
是一键部署的嘛？如果是，那我也不太清楚这个问题

**Comment by RikkaLzw** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 是的
> > > 
> > > 
> > > 那大概率没部署好，我现在使用的就是抱脸部署的项目，有没有cookie都可以用，没有挂梯子，使用的默认的服务，不要使用bing的服务
> > 
> > 
> > 你能帮你的给我复制一下吗
> > 是一键部署的嘛？如果是，那我也不太清楚这个问题

是的，复制部署的。

**Comment by Thot-null** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 是的
> > > > 
> > > > 
> > > > 那大概率没部署好，我现在使用的就是抱脸部署的项目，有没有cookie都可以用，没有挂梯子，使用的默认的服务，不要使用bing的服务
> > > 
> > > 
> > > 你能帮你的给我复制一下吗
> > > 是一键部署的嘛？如果是，那我也不太清楚这个问题
> 
> 是的，复制部署的。

等等，看看作者会不会回复吧

**Comment by Harry-zklcdc** [comment]
你别选官方的聊天服务器，那个有问题，会导致非法请求，我到现在也不知道为啥会这样😂

**Comment by RikkaLzw** [comment]
> 

我最后用了vercel成功了，cf和抱脸怎么都不行，推测是MUID不生成造成的，vercel能生成muid。还有一个，如何设置一个默认的cookies呢，我用手机和电脑都要单独输入一次，想要只设置一次。

**Comment by cengzhijie3** [comment]
> 你别选官方的聊天服务器，那个有问题，会导致非法请求，我到现在也不知道为啥会这样😂

其他的也不行啊，一直验证
<img width="1000" alt="截圖 2023-09-05 下午8 10 59" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/89333400/3f37510a-3954-4f43-9c5b-2962c518783e">

**Comment by luckyEason** [comment]
卡bug了吧，正常是过不了验证的

**Comment by Harry-zklcdc** [comment]
试试最新版
