### ISSUE TITLE
[Bug] 🐛 1.14.0版本正常，升级到最新的1.15.1版本后无法使用

### ISSUE THREAD

**Issue by Winnie0408** [Harry-zklcdc/go-proxy-bingai#193]
### Describe the bug

在国内（广西，连接代理）、国外（美国，直连）服务器均进行了测试，1.14.0版本正常，1.15.1版本无法使用。

Nginx配置文件如下（我手动隐去了我的端口和域名）：
```
server {
  listen <PORT> ssl;
  server_name  <URL>;
  ssl_certificate /opt/certs/cert.pem;
  ssl_certificate_key /opt/certs/key.key;
  error_page 497 301 https://$http_host$request_uri;

  location / {
  proxy_pass http://127.0.0.1:8081;
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection $connection_upgrade;
  proxy_set_header Host $host;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header X-Forwarded-Host $host;
  proxy_set_header X-Forwarded-Port $server_port;
  }
}
```

1.14.0版本运行如下，控制台输出了“成功创建会话ID……”，可以正常聊天
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/42741874/8d89f59b-c115-4285-b963-15b79c9225bc)

1.15.1版本运行如下，控制台未输出“成功创建会话ID……”；且打开“服务选择”页面后，会在控制台输出“WebSocket connection to 'wss://sydney.bing.com/sydney/ChatHub' failed: ”，无法正常聊天
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/42741874/5b4f7ce8-b1eb-4f2b-b5e7-3fc638d0fdcd)

### Steps to reproduce

项目部署完成后，打开项目网站，发送任意一条消息

### Expected behavior

最新版本能够正常对话

### Screenshots

已在上方说明中给出截图

### Versions

- OS: Ubuntu 22.04 LTS
- Browser & Version: Microsoft Edge 116.0.1938.69 (正式版本) (64 位)
- GoProxiBing Version: 1.15.1、1.14.0

### Additional context

之前遇到的另一个问题：
1.14.0版本，在终端使用`export USER_KievRPSSecAuth=xxxxxxxx`给出Cookie值，直接打开网页，可以正常聊天（每轮对话只有5次）；
打开设置，填写完整Cookie，保存，刷新网页后，无法正常聊天。

**Comment by Harry-zklcdc** [comment]
最新版试试
