### ISSUE TITLE
[Help] 🤔 Hugging Face上的部署本周开始无法使用

### ISSUE THREAD

**Issue by WildPYPi** [Harry-zklcdc/go-proxy-bingai#196]
### Describe the help wanted

Hugging Face上的部署本周一开始无法使用，聊天服务器Sydney.bing.com显示无效，输入内容返回无效域。请问是HF的IP被微软封了么

### Steps to behave

打开HF部署链接，输入内容进行对话

### Expected behavior

正常访问聊天服务器

### Screenshots

![微信图片_20230907093224](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/119778219/5bbf1a1f-20e6-4144-be1c-5534fa85dd02)
![微信图片_20230905154558](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/119778219/0c32cff2-6354-450b-b4a0-fd637e3a5630)
![微信图片_20230905154607](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/119778219/60d8cb31-3631-4cbc-a9d7-6831dd1c0f99)

### Versions

- OS: Windows 10 
- Browser & Version: Microsoft Edge V_116.0.1938.69 
- GoProxiBing Version: v1.15.1

**Comment by s181462537** [comment]
发现Hugging  Face上部署的无法使用的原理可能是MUID的原因，输入自己有效的MUID后，随机的_u也能用，希望作者大大研究一下，能否解决MUID的问题，解决了应该就能正常使用了

**Comment by SokWith** [comment]
> 发现Hugging Face上部署的无法使用的原理可能是MUID的原因，输入自己有效的MUID后，随机的_u也能用，希望作者大大研究一下，能否解决MUID的问题，解决了应该就能正常使用了

MUID不是用户ID，似乎是机器ID，32个普通字符，相当于IPV6地址，随便写吧。下面是从微软虚拟机上搞下来的，尾数随便换都能用。
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/b0818998-3ed4-408a-a0c6-b5d9cf0bd0a6)

**Comment by s181462537** [comment]
> > 发现Hugging Face上部署的无法使用的原理可能是MUID的原因，输入自己有效的MUID后，随机的_u也能用，希望作者大大研究一下，能否解决MUID的问题，解决了应该就能正常使用了
> 
> MUID不是用户ID，似乎是机器ID，32个普通字符，相当于IPV6地址，随便写吧。下面是从微软虚拟机上搞下来的，尾数随便换都能用。 ![image](https://user-images.githubusercontent.com/129967025/266250074-b0818998-3ed4-408a-a0c6-b5d9cf0bd0a6.png)

试过了，随便写会触发验证，应该还是有一定规律的，弄虚拟机的是个好办法

**Comment by s181462537** [comment]
> > 发现Hugging Face上部署的无法使用的原理可能是MUID的原因，输入自己有效的MUID后，随机的_u也能用，希望作者大大研究一下，能否解决MUID的问题，解决了应该就能正常使用了
> 
> MUID不是用户ID，似乎是机器ID，32个普通字符，相当于IPV6地址，随便写吧。下面是从微软虚拟机上搞下来的，尾数随便换都能用。 ![image](https://user-images.githubusercontent.com/129967025/266250074-b0818998-3ed4-408a-a0c6-b5d9cf0bd0a6.png)

试过了，随便写会触发验证，应该还是有一定规律的，弄虚拟机的是个好办法

**Comment by SokWith** [comment]
> > > 发现Hugging Face上部署的无法使用的原理可能是MUID的原因，输入自己有效的MUID后，随机的_u也能用，希望作者大大研究一下，能否解决MUID的问题，解决了应该就能正常使用了
> > 
> > 
> > MUID不是用户ID，似乎是机器ID，32个普通字符，相当于IPV6地址，随便写吧。下面是从微软虚拟机上搞下来的，尾数随便换都能用。 ![image](https://user-images.githubusercontent.com/129967025/266250074-b0818998-3ed4-408a-a0c6-b5d9cf0bd0a6.png)
> 
> 试过了，随便写会触发验证，应该还是有一定规律的，弄虚拟机的是个好办法

不是完全随机的，只能0--9，A_F，相当于IPV6地址。

**Comment by yangjianchuan** [comment]
Hugging Face的问题，什么都不用调整，最近两天都是上午用不了，下午会自动恢复。

**Comment by SokWith** [comment]
> > > > 发现Hugging Face上部署的无法使用的原理可能是MUID的原因，输入自己有效的MUID后，随机的_u也能用，希望作者大大研究一下，能否解决MUID的问题，解决了应该就能正常使用了
> > > 
> > > 
> > > MUID不是用户ID，似乎是机器ID，32个普通字符，相当于IPV6地址，随便写吧。下面是从微软虚拟机上搞下来的，尾数随便换都能用。 ![image](https://user-images.githubusercontent.com/129967025/266250074-b0818998-3ed4-408a-a0c6-b5d9cf0bd0a6.png)
> > 
> > 
> > 试过了，随便写会触发验证，应该还是有一定规律的，弄虚拟机的是个好办法
> 
> 不是完全随机的，只能0--9，A_F，相当于IPV6地址。

```
您好，这是Bing。我可以帮您了解Bing Chat连接里面的MUID的编码规则。😊

[MUID是Machine Unique Identifier的缩写，它是一个32位的十六进制字符串，用来标识用户的设备](about:blank#)¹。它是由微软账号服务生成的，每个设备只有一个MUID²。

Bing Chat连接里面的MUID是用来识别用户和聊天机器人之间的会话的。它是由Bing Chat服务根据用户的设备和浏览器信息生成的，每个会话都有一个不同的MUID³。

Bing Chat连接里面的MUID的编码规则是这样的：

- 它是一个64位的十六进制字符串，由两个32位的十六进制字符串拼接而成。
- 前32位是用户设备的MUID，后32位是用户浏览器的MUID。
- 例如，如果用户设备的MUID是[1](https://zhuanlan.zhihu.com/p/627410762)[2](https://zhuanlan.zhihu.com/p/621936050)[3](https://zhuanlan.zhihu.com/p/612351471)4567890ABCDEF1234567890ABCDEF，用户浏览器的MUID是FEDCBA0987654321FEDCBA0987654321，那么Bing Chat连接里面的MUID就是1234567890ABCDEF1234567890ABCDEFFEDCBA0987654321FEDCBA0987654321。

这样，Bing Chat服务就可以根据MUID来区分不同的用户和会话，从而提供更好的聊天体验。👍

如果您还有其他问题，欢迎继续与我聊天。😊

```
@Harry-zklcdc

**Comment by SokWith** [comment]
> Hugging Face的问题，什么都不用调整，最近两天都是上午用不了，下午会自动恢复。

其实上午也是能用的，我的部署都是可以的，核心是要用有效的MUID，而且，和官网一样，只有10次会话，然后就得更换MUID了。而抱脸不能自动换MUID，只好重启部署。
到了下午，这些限制就解除了，感觉是西方上班了，有新的服务器开启了。这里面会有什么样的网络拓扑？

**Comment by Harry-zklcdc** [comment]
最新版试试
