### ISSUE TITLE
[Help] 🤔Cloudfalre Worker 部署出现“ 正在尝试连接，请稍候”

### ISSUE THREAD

**Issue by Propny** [Harry-zklcdc/go-proxy-bingai#197]
### Describe the help wanted

请问如何解决这个问题。

### Steps to behave

Cloudfalre Worker中的以下内容未填写参数。填了也一直提示“正在尝试连接，请稍候”。
KievRPSSecAuth = 
_RwBf = 
 MUID = 
_U = 

### Expected behavior

最近HF部署的也经常出现问题。只好使用CF部署的了。

### Screenshots

![C43D7887-08A2-452c-BFCF-37E6A4A43C8F](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/140315524/68bfce45-e5aa-4561-8264-ba6c8bd2ce7c)

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version: 

### Additional context

使用演示站点：https://bingai.zklcdc.xyz/web/index.html?showconv=1#/，却功能正常。

**Comment by SokWith** [comment]
```
Additional context
使用演示站点：[https://bingai.zklcdc.xyz/web/index.html?showconv=1#/，却功能正常。](https://bingai.zklcdc.xyz/web/index.html?showconv=1#/%EF%BC%8C%E5%8D%B4%E5%8A%9F%E8%83%BD%E6%AD%A3%E5%B8%B8%E3%80%82)
```
1、这个不是CF的演示站点；
2、CF部署需要修改asset目录下的一个js文件，将www.bing.com手动替换成自己的域名才可以用，查找替换很方便的；
欢迎访问我的部署进行测试：
https://nbing.eu.org
