### ISSUE TITLE
[Bug] 🐛 HuggingFace上部署新版本的代理问题

### ISSUE THREAD

**Issue by 2531178480** [Harry-zklcdc/go-proxy-bingai#198]
### Describe the bug

代理异常

### Steps to reproduce

我就和往常一样更新了一下版本
Then这货就罢工了
（详细调试在下方）

### Expected behavior

代理？
我哪里来的代理啊？
我梯子搭上又放下试了N遍了。

### 浏览器控制台Log

（这一段没甚鸟用）
~~Referrer 策略：针对跨站请求，忽略对其限制较宽松的 referrer 策略 - “origin-when-cross-origin”：https://www.googletagmanager.com/gtag/js?id=G-MM5J5X8QQC [js](https://www.googletagmanager.com/gtag/js?id=G-MM5J5X8QQC)
Referrer 策略：针对跨站请求，忽略对其限制较宽松的 referrer 策略 - “origin-when-cross-origin”：https://hm.baidu.com/hm.js?299c614daa53fbcede70f2d22df0a31b [index.html:37:19](https://mkstoler-bingai.hf.space/web/index.html)
鉴于已开启内容拦截功能，而这个请求来自跟踪器，已拦截“<URL>”对 Cookie 或存储空间的访问请求。 2
某些 Cookie 滥用推荐的“SameSite“属性 155
Referrer 策略：针对跨站请求，忽略对其限制较宽松的 referrer 策略 - “origin-when-cross-origin”：https://hm.baidu.com/hm.gif?cc=1&ck=1&cl=24-bit&ds=1536x864&vl=711&et=0&ja=0&ln=zh-cn&lo=0&lt=1694066870&rnd=1450421658&si=299c614daa53fbcede70f2d22df0a31b&v=1.3.0&lv=2&sn=52655&r=0&ww=1536&u=https%3A%2F%2Fmkstoler-bingai.hf.space%2Fweb%2Findex.html%23%2F&tt=BingAI%20-%20%E8%81%8A%E5%A4%A9 [hm.js:27:208](https://hm.baidu.com/hm.js?299c614daa53fbcede70f2d22df0a31b)~~

（正片开始）
GET https://mkstoler-bingai.hf.space/turing/conversation/create [HTTP/2 **404 Not Found** 770ms]

GET https://mkstoler-bingai.hf.space/turing/conversation/create [HTTP/2 **404 Not Found** 755ms]

GET https://mkstoler-bingai.hf.space/turing/conversation/create [HTTP/2 **404 Not Found** 692ms]

GET https://mkstoler-bingai.hf.space/turing/conversation/create [HTTP/2 **404 Not Found** 843ms]

GET https://mkstoler-bingai.hf.space/turing/conversation/create [HTTP/2 **404 Not Found** 693ms]

GET https://mkstoler-bingai.hf.space/turing/conversation/create [HTTP/2 **404 Not Found** 698ms]

……（往后全是**GET&404 Not Found**。好吗，全找不到了，绝对不是我的问题了。）

### 看见这个我就去终端翻阅Docker容器的Logs

结果本来就只懂一点，现在一看这个过于简洁的报错人就蒙了。

### 终端Log：

===== Application Startup at 2023-09-07 05:56:56 =====

2023/09/07 05:56:57 Starting BingAI Proxy At :8080
2023/09/07 05:57:21 **代理异常 ： context canceled**
2023/09/07 05:57:22 **代理异常 ： context canceled**
2023/09/07 05:59:52 **代理异常 ： context canceled**
2023/09/07 05:59:52 **代理异常 ： context canceled**
2023/09/07 06:01:03 **代理异常 ： context canceled**
2023/09/07 06:01:05 **代理异常 ： context canceled**

### Versions

- OS: Windows 11
- Browser & Version: FireFox 116
- GoProxiBing Version: 1.15.1
- Deployment Environment: HuggingFace Space

**Comment by Harry-zklcdc** [comment]
IP被墙了，HF太多人使用了，导致IP大面积被封
