### ISSUE TITLE
[Help] 🤔 如何将Hugging Face部署的项目自定义域名

### ISSUE THREAD

**Issue by Happy-clo** [Harry-zklcdc/go-proxy-bingai#199]
如题 希望支持在Hugging Face部署后使用cloudflare的workers来实现反向代理 并解决重新连接问题

### 功能实现

workers代码如下
```
const TRAGET_HOST='Hugging Face公开访问地址' 
export default {
  async fetch(request) {
    const uri = new URL(request.url);
    if (uri.protocol === 'http:') {
      uri.protocol = 'https:';
      return new Response('', {
        status: 301,
        headers: {
          location: uri.toString(),
        },
      })
    }
    uri.host = TRAGET_HOST
    return fetch(new Request(uri.toString(), request));
  },
};
```

### 报错
```
302
alt-svc:h3=":443"; ma=86400
cf-cache-status:DYNAMIC
cf-ray:803033170200a07b-SIN
connection:keep-alive
content-type:text/html; charset=utf-8
date:Thu, 07 Sep 2023 16:06:33 GMT
link:<https://huggingface.co/spaces/Project address>; rel="canonical"
location:/web/index.html
nel:{"success_fraction":0,"report_to":"cf-nel","max_age":604800}
report-to:{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=4VWpVo4aLRc54V8VrTZpx5AWQJxKYTiMNfqrzXCyBnDm4TlaBXvJFUXWB8adoSDDm06ro6jolbgds4k0%2BETJ7SSuAmosib9e6TaBunTG4cjNhzAF%2BBy%2BBm5B7Tkw0H5oM%2B3g9n%2B2fWKYiN8SAsCrNcTcec1mZoBw4sbl"}],"group":"cf-nel","max_age":604800}
server:cloudflare
transfer-encoding:chunked
vary:Accept-Encoding
x-proxied-host:http://10.19.106.130:8080
x-proxied-path:/
x-request-id:88b58164-2a2a-407c-8a05-de700edeac6e
<a href="/web/index.html">Found</a>.
```

### 版本

- OS: Windows 10 
- GoProxiBing Version: 1.15.1

**Comment by sugar1688** [comment]
![IMG_20230907_231950](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/134984318/000cc761-3218-4eba-a70f-3719f3cc0216)
![IMG_20230907_232012](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/134984318/1c0cd06b-1ee0-4271-9217-3465e1f36518)
自定义域名后出现无法连接怎么解决啊

**Comment by SokWith** [comment]
这个项目的核心API是调用微软官方的，任何反代都会出现跨域问题，所以是无解的。

NewBingGoGo项目和bingo项目是重写的核心，就可以反代。

最可惜的是GOGO项目，前端3个月没有维护了，造成目前只能使用平衡一种模式了，但其核心API和浏览器插件还能继续使用，只是必须要没有锁的ID；

这个项目使用核心API，唯一的好处是通过部署内置ID，选择官方服务器，若官方服务器可用（部分地区或者科学上网），则大概率直接验证ID锁。
所以，在我的测试域(https://nbing.eu.org)中,replit站点和gogo站点共用ID，依靠replit来解锁ID。

**Comment by sugar1688** [comment]
> 心

有没教程怎么操作，没听明白

**Comment by SokWith** [comment]
> > 心
> 
> 有没教程怎么操作，没听明白

就是这个项目不可能反代，也就是不能给hf自定义域名。
你可以查看我的测试域，其他都是自定义域名，唯独hf没有，都是折腾了许久的了

**Comment by Happy-clo** [comment]
好的谢谢解答

**Comment by Happy-clo** [comment]
@SokWith 问下老兄在vercel部署怎么用 直接不说会出现聊天服务器不可用

**Comment by SokWith** [comment]
> @SokWith 问下老兄在vercel部署怎么用 直接不说会出现聊天服务器不可用

手机打字不方便，见谅。你需要去原作者不是这个作者哟，项目的issues看置顶帖

**Comment by jsdianman** [comment]
https://githubfast.com/Harry-zklcdc/go-proxy-bingai/issues/205
