### ISSUE TITLE
现在哪种部署方式比较稳定

### ISSUE THREAD

**Issue by smalllazyxl** [Harry-zklcdc/go-proxy-bingai#20]
一键部署的方式基本都用不了了。都是连接不上服务器

**Comment by Harry-zklcdc** [comment]
自己买vps部署最稳定，一键部署我没用过，很大可能会有问题，我想想办法看看能不能修

**Comment by qinguoluo** [comment]
> 自己买vps部署最稳定，一键部署我没用过，很大可能会有问题，我想想办法看看能不能修

我是在vercel上部署的，为什么版本升级不到1.9.1？我看作者出新版后，就在vercel上删除了项目，然后把github上的仓库同步到最新与作者的一致，再从vercel导入我的仓库，部署成功后，发现版本号还是1.9.0，没有更新成功。不知道是怎么回事。本人对vercel还不熟，请大佬指点。

**Comment by Harry-zklcdc** [comment]
> 我是在vercel上部署的，为什么版本升级不到1.9.1？我看作者出新版后，就在vercel上删除了项目，然后把github上的仓库同步到最新与作者的一致，再从vercel导入我的仓库，部署成功后，发现版本号还是1.9.0，没有更新成功。不知道是怎么回事。本人对vercel还不熟，请大佬指点。

https://github.com/Harry-zklcdc/go-proxy-bingai/issues/15#issuecomment-1646499727
