### ISSUE TITLE
现在完全无法使用了

### ISSUE THREAD

**Issue by AthanaD** [Harry-zklcdc/go-proxy-bingai#200]
### Describe the bug

请看图片更直观

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/125889247/ab601693-6b1c-4298-a041-74cadb45b6bb)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/125889247/65a1b416-b89c-416a-8786-12412e8ebd8a)

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/125889247/3b3ab8e2-fa4c-49f9-90ea-ccaad591c7a9)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/125889247/542d5f07-482f-48da-bf05-18c0627f4b05)

### Steps to reproduce

XXXXXX

### Expected behavior

XXXXX

### Screenshots

XXXXX

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by pandoradevin** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/125889247/2198a1f7-5793-40e6-b1ce-f4b9ce039a59)

**Comment by SokWith** [comment]
看看我测试域里面的部署
https://nbing.eu.org
目前都是可以正常使用的

核心就是：IP没锁，ID也没锁
现在想无ID访问，只剩下hf的部署了。

**Comment by Harry-zklcdc** [comment]
> 那个刷新和重置确实有问题，重新充输入网址

这个我会解决

目前测试下来，还得是ip干净的服务器才能正常部署

**Comment by SokWith** [comment]
> > 那个刷新和重置确实有问题，重新充输入网址
> 
> 这个我会解决
> 
> 目前测试下来，还得是ip干净的服务器才能正常部署

几个部署下来，只有cfwk的部署不会刷新出错，而且cfwk的调整最方便。

目前转发ip都还算好，似乎ip锁很少了。
但是，对于部署ip，目前看来官方的策略已经调整增加了机器锁(MUID)了，在replit里面写入了MUID后刷新不会变化，造成聊天次数非常有限，一定次数后这个MUID就会被锁，体现为“重新开始吧”，这时候也可以换一个MUID仍然可以继续。
而且，即使抱脸部署里面没有写死MUID，不重启部署，MUID也是不自动刷新的。这一点还算CFWK部署好一些，每次刷新MUID都会变化。只是，一个ID，不停的变化IP/MUID，又会造成ID频繁上锁。
官方已经把路堵得太死了。感觉官方就在监控这个项目的进度，所有的突破都活不过太久，越来越鸡肋了。

**Comment by SokWith** [comment]
本来个人使用可以选择科学，就不用太折腾部署了。

部署的好处也就是方便手机使用了。

**Comment by Harry-zklcdc** [comment]
> 目前转发ip都还算好，似乎ip锁很少了。 但是，对于部署ip，目前看来官方的策略已经调整增加了机器锁(MUID)了，在replit里面写入了MUID后刷新不会变化，造成聊天次数非常有限，一定次数后这个MUID就会被锁，体现为“重新开始吧”，这时候也可以换一个MUID仍然可以继续。 而且，即使抱脸部署里面没有写死MUID，不重启部署，MUID也是不自动刷新的。这一点还算CFWK部署好一些，每次刷新MUID都会变化。只是，一个ID，不停的变化IP/MUID，又会造成ID频繁上锁。 官方已经把路堵得太死了。感觉官方就在监控这个项目的进度，所有的突破都活不过太久，越来越鸡肋了。

所以我在考虑之后的更新要不要开源了，不开源，不会被倒卖，也不会有泄露风险，但是有人会说不安全，开源的话就容易被官方盯上

**Comment by SokWith** [comment]
> > 目前转发ip都还算好，似乎ip锁很少了。 但是，对于部署ip，目前看来官方的策略已经调整增加了机器锁(MUID)了，在replit里面写入了MUID后刷新不会变化，造成聊天次数非常有限，一定次数后这个MUID就会被锁，体现为“重新开始吧”，这时候也可以换一个MUID仍然可以继续。 而且，即使抱脸部署里面没有写死MUID，不重启部署，MUID也是不自动刷新的。这一点还算CFWK部署好一些，每次刷新MUID都会变化。只是，一个ID，不停的变化IP/MUID，又会造成ID频繁上锁。 官方已经把路堵得太死了。感觉官方就在监控这个项目的进度，所有的突破都活不过太久，越来越鸡肋了。
> 
> 所以我在考虑之后的更新要不要开源了，不开源，不会被倒卖，也不会有泄露风险，但是有人会说不安全，开源的话就容易被官方盯上

感谢开源，至少方便了我这样不会代码的小白也能用上。

至于被倒卖，眼不见心不烦，不去了解就当着没有了。赚那份钱也是有风险的，容易被举报踩缝纫机的。我把自己的测试站点公开都战战兢兢的，其实也就只为了测试被上锁的速度。

**Comment by 2531178480** [comment]
其实官方在监控这个项目的进度的话，也就真的没办法了。
除非能做到自动更换cookie，要不就只能看看别的项目了。
可以实现和bingo这个项目一样（它直接curl下来cookie，这样就可以过了）的办法吗？

**Comment by 2531178480** [comment]
这个项目是这么说的：请使用 Edge 浏览器
[打开并登录 Bing](https://www.bing.com/)
，然后再打开
[Challenge 接口](https://www.bing.com/turing/captcha/challenge)
右键 》检查。打开开发者工具，在网络里面找到 Challenge 接口 》右键复制》复制为 cURL(bash)，粘贴到此处，然后保存。请使用 Edge 浏览器
打开并登录 Bing
，然后再打开
Challenge 接口
右键 》检查。打开开发者工具，在网络里面找到 Challenge 接口 》右键复制》复制为 cURL(bash)，粘贴到此处，然后保存。

**Comment by SokWith** [comment]
> 其实官方在监控这个项目的进度的话，也就真的没办法了。 除非能做到自动更换cookie，要不就只能看看别的项目了。 可以实现和bingo这个项目一样（它直接curl下来cookie，这样就可以过了）的办法吗？

bingo项目目前解决方案落后于本项目，它一直使用的是全cookie，本项目作者已经添加了这个选项。现在由于机器锁，全cookie反而容易被锁住不容易更换MUID。
bingo项目的作者应该按我的提示在更新2.0方案，大概率就是不停的换MUID，我目前测试域里面的部署都是快速换MUID，所以你会发现在聊天过程中的历史记录会突然消失，那是由于MUID发生变化引起的bug。

**Comment by 2531178480** [comment]
是的，我发现了
那其实现在就是找一个自动更新muid的方案

**Comment by 2531178480** [comment]
那有没有一种疯狂的方案，就是偷用微软的Lab去搞一个服务，然后自定义挂上自己的域名？
要不然就是用codespace开个Ubuntu再挂上一个反代（国内加速）？
但是codespace限时，也不好

**Comment by pandoradevin** [comment]
请问有你的QQ吗，咨询下搭建

**Comment by SokWith** [comment]
> 请问有你的QQ吗，咨询下搭建

搭建参考作者wiki，docker，二进制都是常规操作，vercel要按原作者的置顶贴。只有cfwk需要替换核心api的域名，稍微麻烦一点点。
我这些搭建都是云部署服务商，不是VPS，所以都不需要做反代，基本上都是一键部署了结的。

**Comment by SokWith** [comment]
> 请问有你的QQ吗，咨询下搭建

搭建参考作者wiki，docker，二进制都是常规操作，vercel要按原作者的置顶贴。只有cfwk需要替换核心api的域名，稍微麻烦一点点。
我这些搭建都是云部署服务商，不是VPS，所以都不需要做反代，基本上都是一键部署了结的。

**Comment by Harry-zklcdc** [comment]
尝试最新版本
