### ISSUE TITLE
[Help] 🤔 有谁知道如何让Hugging Face上的部署定时重启？

### ISSUE THREAD

**Issue by SokWith** [Harry-zklcdc/go-proxy-bingai#201]
### Describe the help wanted

目前1.15.1版本的Hugging Face上的部署，无cookie聊天的次数太少了，很快就达到了次数限制，需要重启部署后才会开始新的计数。
打算让部署每小时自动重启1次，该如何设置？

### Steps to behave

目前1.15.1版本的Hugging Face上的部署，无cookie聊天的次数太少了，很快就达到了次数限制，需要重启部署后才会开始新的计数。

### Expected behavior

打算让部署每小时自动重启1次，该如何设置？

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by goss1p** [comment]
我使用wiki里的按钮一键部署了hugging face(保持默认配置)，但是遇到了问题：

似乎出现了问题，
让我们重新开始吧。

**Comment by b1ghawk** [comment]
不是随机一个_U就行了吗？

**Comment by b1ghawk** [comment]
我想关于 https://github.com/Harry-zklcdc/go-proxy-bingai/issues/267#issuecomment-1852272971 
我应该是误会了什么。

我想表达的意思是，每当我启动一个docker，里面带有chrome和需要用到的扩展程序，并通过vnc或者x11连接到了docker内的图形管理器，完成了chrome刷新cookie和推送cookie的配置。

**然后每过n小时，docker会自动重启一次，我们之前在chrome上的配置丢失了**，这个假设是错误的。

🌝我混淆了Github Actions和Huggingface Space。。。。

Github Actions里面白嫖是需要定时重启的。
Hugging face space里的白嫖则可以一直运行，不需要定时重启来续命。
