### ISSUE TITLE
[Feature] 🌈 给大神提点建议

### ISSUE THREAD

**Issue by istudylove** [Harry-zklcdc/go-proxy-bingai#202]
### Describe the problem related to the feature request

功能升级

### Describe the solution you'd like

首先感谢大神的不断维护改进，作为一个普通用户想提点建议
1.可以改字数限制
2.可以防消息撤回
3.可以修改编辑回复的消息，即修改对话
4.可以调用edge接口朗读
好吧，其实我是从ChatSydney转过来的，希望大神能够做出一个大一统的客户端

**Comment by SokWith** [comment]
我觉得还是找大佬去把NewBingGoGo项目接过来维护，重新编写的核心API，一直可以使用，就是前端荒废了。
之前由于微软封ip厉害，造成作者无后端可用的部署服务器，目前微软放开了一些ip限制，可以接着使用了。
但作者似乎读书太忙了，已经弃了许久了，实在可惜。

**Comment by Harry-zklcdc** [comment]
这个不是我这个项目做的事情，但是仅能在能力范围内尝试，无限制对话轮数的功能在做了，能做出来的话就可以不限制对话轮数了，但是单轮对话还是限制4000字

**Comment by SokWith** [comment]
> 这个不是我这个项目做的事情，但是仅能在能力范围内尝试，无限制对话轮数的功能在做了，能做出来的话就可以不限制对话轮数了，但是单轮对话还是限制4000字

大佬能不能抽空看一下NewBingGoGo的前端代码，一个小小的需求，就是好像微软改了创造力和精确模式的调用方式，造成该项目目前只能使用平衡模式才有返回，另外两个模式就无响应了。
应该小小的改动代码就可以修复的。毕竟目前这个项目的插件版还是很有帮助的，它也可以直接使用本项目的后端服务器，只需要维护前端就能继续下去。
或者，大佬加油早日把这个项目的插件版搞出来。

**Comment by Harry-zklcdc** [comment]
> 改字数限制

这玩意就是掩耳盗铃，我这修改了就只是能输入更多的内容，然而实际上Chathub 并不能输入

> 可以防消息撤回、可以修改编辑回复的消息，即修改对话

请使用 [BingAPI](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/BingAPI)

> 可以调用edge接口朗读

#309 Commit: d2b187237c11e577f76b20c3a4bfac6838ca0750
