### ISSUE TITLE
[Bug] 🐛 V1.15.1 一键重置可能会报错，如何修复此错误

### ISSUE THREAD

**Issue by chokiproai** [Harry-zklcdc/go-proxy-bingai#204]
### Describe the help wanted

V1.15.1 一键重置可能会报错，如何修复此错误

嗯… 无法访问此页面网址为. 的页面可能存在问题，或者已永久移动到新的网址。
ERR_FAILED

### Steps to behave

很可能是这个自动加上的参数导致的

?showconv=1#/

### Expected behavior

一键重置的时候忽略参数部分

### Screenshots

![266550195-542d5f07-482f-48da-bf05-18c0627f4b05](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/128912789/05d2ad47-9f95-4b72-b666-6294106f1eef)

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by Harry-zklcdc** [comment]
下个版本修复，现在重心在开发无限制对话轮数的功能

**Comment by chokiproai** [comment]
@Harry-zklcdc  谢谢, 请继续开发无限对话回合功能
