### ISSUE TITLE
[Bug] 🐛 点击新主题重回bing人格，对话次数最多10次

### ISSUE THREAD

**Issue by Nanzhexi** [Harry-zklcdc/go-proxy-bingai#206]
### Describe the bug
只有刷新部署页面才是sydeny
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/98096340/dd63e3b5-fcce-4c43-90e7-4594ea26791a)
点击新主题
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/98096340/bac4b704-553c-492d-99ed-e2b98ad5eb0f)
最多10次对话，就算设置了100也没用
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/98096340/a7db3834-139d-49b5-bbb3-70f293ec1df3)

1.点击新主题时，人格回重回bing，需要重新刷新页面，才会重新进入新人格模式
2.(设置了超越30次的次数) 最多进行10次对话，对话限制比原版还少20次,经过多次测试不论是(企业版还是原版)        ps:这是因为应用了新人格吗？

### Steps to reproduce

1.点击新主题就行
2.到了第10次对话的时候就，会显示提示请点击新主题。

### Expected behavior

1.每次点击新主题时能不需要刷新页面也能与sydney进行对话
2.不说取消限制 (ps我觉得不现实，不然就无限长的token了）能恢复到原版的30次也行

### Versions

- OS:  Windows 11 
- Browser & Version:  Chrome 14.0.5804.203 
- GoProxiBing Version: v1.15.1

**Comment by skyfly2000** [comment]
…………
<img width="787" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/57341809/47d278f5-b658-40a9-8978-0e467494e737">

<img width="586" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/57341809/5486b5a5-c952-4d95-8057-610cf26da9db">

<img width="860" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/57341809/2ca44150-53b2-4539-aaef-c48b434385f9">

**Comment by Nanzhexi** [comment]
> ………… <img alt="image" width="787" src="https://user-images.githubusercontent.com/57341809/267666963-47d278f5-b658-40a9-8978-0e467494e737.png">
> 
> <img alt="image" width="586" src="https://user-images.githubusercontent.com/57341809/267667155-5486b5a5-c952-4d95-8057-610cf26da9db.png"> <img alt="image" width="860" src="https://user-images.githubusercontent.com/57341809/267667372-2ca44150-53b2-4539-aaef-c48b434385f9.png">

兄弟你试试，我这个调了100次，但最多10次。

**Comment by Nanzhexi** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/98096340/b534e1e2-13b8-401f-b6bc-aa06bb3669a2)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/98096340/f0138441-974b-4c30-b50b-1aeec6d5227c)

**Comment by skyfly2000** [comment]
正常的呀
<img width="1276" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/57341809/58baf899-da77-458e-b0eb-b339ece7f136">

**Comment by luckyEason** [comment]
`Chathub API`最多允许你不登录10次对话，登录30次

**Comment by Harry-zklcdc** [comment]
已修复，待发版
