### ISSUE TITLE
[Help] 🤔 微软云上面部署docker里面部署不行吗？

### ISSUE THREAD

**Issue by wangzhilin777** [Harry-zklcdc/go-proxy-bingai#209]
### Describe the help wanted

提示：很抱歉，似乎出现错误。 让我们重新开始吧。
输入cookie也不出历史记录。
用抱脸相同cookie能出历史记录，也能使用。

### Steps to behave

1

### Expected behavior

1

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by SokWith** [comment]
https://github.com/Harry-zklcdc/go-proxy-bingai/issues/207#issuecomment-1719070149

**Comment by Harry-zklcdc** [comment]
镜像站就是用Azure上然后docker部署的

**Comment by wangzhilin777** [comment]
我用cloudflare解析dns开启cnd又可以了，之前用的是dnspod的解析弄死不信。

**Comment by SokWith** [comment]
> 我用cloudflare解析dns开启cnd又可以了，之前用的是dnspod的解析弄死不信。

cf还是比较可信赖的，毕竟巨硬的人机验证都是走的cf的服务。
https://github.com/adams549659584/go-proxy-bingai/issues/387#issuecomment-1661535680
