### ISSUE TITLE
[Help] 🤔 请问是一定要部署在443端口吗？家庭宽带没开放80和443.

### ISSUE THREAD

**Issue by XianYuDaXian** [Harry-zklcdc/go-proxy-bingai#210]
### Describe the help wanted

如题，打算家庭服务器架设一个。无论是二进制还是docker，部署好后用群晖的反代到自己ddns上，端口是8080，聊天就报网络错误，测试服务那里也显示不可用。请问是只能部署在443吗？

### Steps to behave

如题，打算家庭服务器架设一个。无论是二进制还是docker，部署好后用群晖的反代到自己ddns上，端口是8080，聊天就报网络错误，测试服务那里也显示不可用。请问是只能部署在443吗？

### Expected behavior

如题，打算家庭服务器架设一个。无论是二进制还是docker，部署好后用群晖的反代到自己ddns上，端口是8080，聊天就报网络错误，测试服务那里也显示不可用。请问是只能部署在443吗？

### Versions

- OS: win11
- Browser & Version: chrome 116
- GoProxiBing Version: 1.15.1

**Comment by luckyEason** [comment]
一定要443，80也不行
