### ISSUE TITLE
[Help] 🤔 部署在racknerd的vps上，检测服务器可用但是一聊天就断开网络，请问该怎么解决？

### ISSUE THREAD

**Issue by XianYuDaXian** [Harry-zklcdc/go-proxy-bingai#211]
### Describe the help wanted

部署在racknerd的vps上，检测服务器可用但是一聊天就断开网络，请问该怎么解决？

### Steps to behave

部署在racknerd的vps上，检测服务器可用但是一聊天就断开网络，请问该怎么解决？

### Expected behavior

部署在racknerd的vps上，检测服务器可用但是一聊天就断开网络，请问该怎么解决？

### Screenshots

![_20230918113626](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/20138259/0a39d4b9-9e60-4c8c-b44f-4e178215d517)

### Versions

- OS: win10
- Browser & Version: Chrome 115
- GoProxiBing Version: 1.5

**Comment by Harry-zklcdc** [comment]
似乎触发IP锁，或者填入MUID试试吧

**Comment by XianYuDaXian** [comment]
> 似乎触发IP锁，或者填入MUID试试吧

部分cookies和完整的cookies我都试过 填或不填 他都是一点就网络断开。另一个bingo的项目我试过就可以正常用。

**Comment by wangzhilin777** [comment]
> > 似乎触发IP锁，或者填入MUID试试吧
> 
> 部分cookies和完整的cookies我都试过 填或不填 他都是一点就网络断开。另一个bingo的项目我试过就可以正常用。

我微软云vps一样，后来用cloudflare解析dns开启cdn就可以用了，你试试呢？

**Comment by Harry-zklcdc** [comment]
看起来像是不支持websocket
