### ISSUE TITLE
[Feature] 🌈 添加选择第三方Bing API

### ISSUE THREAD

**Issue by d4renk** [Harry-zklcdc/go-proxy-bingai#212]
### Describe the problem related to the feature request

添加选择第三方Bing API 使用Cloudflare Workers，可指定Workers IP，避免风控。

### Describe the solution you'd like

 在环境变量里添加选择第三方Bing API

**Comment by jsdianman** [comment]
直接改聊天服务器的代码不就行了吗？

**Comment by Harry-zklcdc** [comment]
> 直接改聊天服务器的代码不就行了吗？

正解

而且现在设置里面有自定义的接口呀

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/e4153ac3-78f1-48e4-9dd5-93195ee66383)
