### ISSUE TITLE
[Help] 🤔 部署在国内服务器上开启代理无效了

### ISSUE THREAD

**Issue by thunderning** [Harry-zklcdc/go-proxy-bingai#213]
### Describe the help wanted

大佬，我从之前那个项目主开始一直用的是国内服务器+SSR代理的方式，最近我看到您把common/env.go的代码中的socks相关的都删除了，好像项目就不能通过SSR代理转发了，想问一下现在想写入127.0.0.1:1080这个本地代理地址需要去哪里写呢？

### Steps to behave

本地开启SSR代理后运行go-proxy-bingai

### Expected behavior

代理正常运行

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by Harry-zklcdc** [comment]
[https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/环境变量#代理相关](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F#%E4%BB%A3%E7%90%86%E7%9B%B8%E5%85%B3)
