### ISSUE TITLE
[Help] 🤔 根据wiki教程在racknerd的vps上，使用docker部署，聊天服务器连接失败

### ISSUE THREAD

**Issue by Propny** [Harry-zklcdc/go-proxy-bingai#214]
### Describe the help wanted

请问怎么解决哈。

### Steps to behave

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/140315524/078f43f5-ba14-456b-8599-5107e27f621b)
根据wiki教程,使用docker部署

### Expected behavior

请问怎么解决哈。

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/140315524/c6913202-a15f-4d8c-82d4-d3a66af858b1)

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by jsdianman** [comment]
#211

**Comment by jsdianman** [comment]
也有可能是被ban了

**Comment by jsdianman** [comment]
![IMG_1942](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/143573972/f35eaa15-0bf9-499e-a80b-13d3124dce31)
az云可以用

**Comment by skyfly2000** [comment]
现在貌似azure之外都不好用……，我的已经连续运行一个多星期，好在azure现在有一年免费的

**Comment by Propny** [comment]
azure的个人版都要验证信用卡吗，不想弄这玩意。

**Comment by SokWith** [comment]
> 现在貌似azure之外都不好用……，我的已经连续运行一个多星期，好在azure现在有一年免费的

https://github.com/Harry-zklcdc/go-proxy-bingai/issues/207#issuecomment-1719070149

az现在也不安全了，现在几个公开测试的az部署时不时都被上锁

**Comment by Propny** [comment]
> > 现在貌似azure之外都不好用......，我的已经连续运行一个多星期，好在azure现在有一年免费的
> 
> [#207（评论）](https://github.com/Harry-zklcdc/go-proxy-bingai/issues/207#issuecomment-1719070149)
> 
> az现在也不安全了，现在几个公开测试的az部署时不时都被上锁

头痛哦。

**Comment by Propny** [comment]
看了老狗的视频，可以使用了

**Comment by SokWith** [comment]
> > 现在貌似azure之外都不好用……，我的已经连续运行一个多星期，好在azure现在有一年免费的
> 
> [#207 (comment)](https://github.com/Harry-zklcdc/go-proxy-bingai/issues/207#issuecomment-1719070149)
> 
> az现在也不安全了，现在几个公开测试的az部署时不时都被上锁

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/237248f8-f74d-4f6d-acfc-230d10f35eb5)
今日作者网站换一个MUID就可以用了
