### ISSUE TITLE
[Help] 🤔 腾讯云服务器搭建现在部分电脑无法使用

### ISSUE THREAD

**Issue by thunderning** [Harry-zklcdc/go-proxy-bingai#216]
### Describe the help wanted

使用腾讯云+SSR搭建，之前用的都没啥问题，更新后不知为什么，有些电脑进去就是就明显没连接上，历史记录接收不到，说话就是提示“很抱歉，似乎出现错误。让我们重新开始吧”。

我对比了可以说话和不能说话的电脑区别，无法说话的电脑会少交互一个“chats”数据包，即“/turing/conversation/chats”，但是我不太清楚这个问题是什么原因导致的

### Steps to behave

在服务器不变的情况下，有的电脑可以对话，大部分电脑都无法对话，甚至不写入cookie的情况下，可以对话的电脑都能对话，这样可以排除cookie的影响吧？

### Expected behavior

所有电脑都能对话

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by thunderning** [comment]
> 部分电脑不可以就是浏览器的问题吧，如果是项目的问题话，应该全部电脑都不能用才对

准确的说我现在只有一台电脑能正常对话，我测试了5台电脑，只有一台笔记本可以对话，我也很费解，但是我那些说不了话的电脑用项目主搭建的页面就可以正常说话，我现在很迷茫

**Comment by Harry-zklcdc** [comment]
配置代理了嘛？腾讯云的服务器是被封禁的
