### ISSUE TITLE
[Help] 🤔 报错：很抱歉，似乎出现错误。 让我们重新开始吧。

### ISSUE THREAD

**Issue by Arrest404** [Harry-zklcdc/go-proxy-bingai#217]
### Describe the help wanted

报错：很抱歉，似乎出现错误。 让我们重新开始吧。
一直连不上服务器，我在huggingface上面部署的，但是手机上可以用，电脑上就不行

### Steps to behave

报错：很抱歉，似乎出现错误。 让我们重新开始吧。
一直连不上服务器，我在huggingface上面部署的，但是手机上可以用，电脑上就不行

### Expected behavior

报错：很抱歉，似乎出现错误。 让我们重新开始吧。
一直连不上服务器，我在huggingface上面部署的，但是手机上可以用，电脑上就不行

### Screenshots

![屏幕截图 2023-09-25 182750](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/104551462/a7d2b23a-b32b-4e40-bac9-c4510c52071c)
![屏幕截图 2023-09-25 182840](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/104551462/01b50e3b-1f2e-4f8b-af0c-e498485524c5)

### Versions

v1.12.0

**Comment by Harry-zklcdc** [comment]
升级最新版试试，这个感觉是服务器被封IP了

**Comment by Arrest404** [comment]
> 升级最新版试试，这个感觉是服务器被封IP了

怎么升级最新版呀😂😂

**Comment by Harry-zklcdc** [comment]
> 怎么升级最新版呀😂😂

你咋部署的？

**Comment by chenjianan2023** [comment]
我也是一样，b站网站进来的

**Comment by maggieqnr** [comment]
我也是这样

**Comment by qiuyue520** [comment]
我也是这样

**Comment by Harry-zklcdc** [comment]
最新版试试

**Comment by Benson80** [comment]
最新版也是一样的情况！

**Comment by Harry-zklcdc** [comment]
服务器 IP 被巨硬拉黑了，换个服务器 IP
