### ISSUE TITLE
[Help] 🤔 找不到kievrpssecauth

### ISSUE THREAD

**Issue by pasical** [Harry-zklcdc/go-proxy-bingai#218]
### Describe the help wanted

如题，在cookie中找不到kievrpssecauth项
同时，完整cookie也没有用，依然显示“很抱歉，似乎出现错误。 让我们重新开始吧。”

### Steps to behave

依照Wiki上的顺序

### Expected behavior

help

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/112304778/4d4800d4-fe8d-4e98-b236-21446c55339e)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/112304778/ff446fd2-5665-4f1e-86c1-45723aef49c0)

### Versions

- OS: <Windows11>
- Browser & Version: <Microsoft Edge 117>
- GoProxiBing Version: <v1.12.0>

**Comment by Harry-zklcdc** [comment]
似乎和MUID值有关系

**Comment by ryanzhaorx** [comment]
你图2中的数据是 完整 Cookie 的参数，在 完整 Cookie 里输入

**Comment by Harry-zklcdc** [comment]
找不到的话尝试随机值
