### ISSUE TITLE
[Help] 🤔 请问下，怎么反向代理到二级目录？

### ISSUE THREAD

**Issue by wangzhilin777** [Harry-zklcdc/go-proxy-bingai#219]
### Describe the help wanted

**直接反代到：xxx.xxx.xxx 能正常访问。
我想代理到：xxx.xxx.xxx/bing  上，报404了，是我哪里没有配制子目录地址？刚把alist挂到子目录，也走了很多弯路。**
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/75417416/199b9d36-7226-4515-b63b-79f6ea9fe43c)

### Steps to behave

1

### Expected behavior

1

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by Harry-zklcdc** [comment]
没得办法，除了修改代码

**Comment by luckyEason** [comment]
可以尝试用iframe，说不定可以用
