### ISSUE TITLE
无法输入换行的问能解决一下吗？

### ISSUE THREAD

**Issue by Xqh-Cxy** [Harry-zklcdc/go-proxy-bingai#22]

**Comment by Harry-zklcdc** [comment]
我这边没有这个问题

**Comment by ilolita945** [comment]
> _No description provided._

设置输入法

**Comment by Harry-zklcdc** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/8e847a09-852d-42c2-84c0-da8b0c70ba39)
 
Shift + 回车键 换行
