### ISSUE TITLE
[Help] 🤔 

### ISSUE THREAD

**Issue by JmansoKing** [Harry-zklcdc/go-proxy-bingai#220]
### Describe the help wanted

想问一下我通过whistle配置好之后，之前可以用，今天再用就一直显示正在尝试连接，然后就显示重新开始，这个怎么解决呀，计算机小白求指点

### Steps to behave

想问一下我通过whistle配置好之后，之前可以用，今天再用就一直显示正在尝试连接，然后就显示重新开始，这个怎么解决呀，计算机小白求指点

### Expected behavior

想问一下我通过whistle配置好之后，之前可以用，今天再用就一直显示正在尝试连接，然后就显示重新开始，这个怎么解决呀，计算机小白求指点

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by 2531178480** [comment]
你用的是啥部署的
更新了没

**Comment by JmansoKing** [comment]
用的抱脸，请问一下怎么更新啊，重新部署嘛是？
也重新部署过了还是不行

**Comment by JmansoKing** [comment]
用的抱脸，请问一下怎么更新啊，重新部署嘛是？
也重新部署过了还是不行

**Comment by 2531178480** [comment]
重新部署啊

**Comment by 2531178480** [comment]
现在factory reboot不甚好使

**Comment by 2531178480** [comment]
然后
huggingface最近老抽风
你还要用huggingface

**Comment by 2531178480** [comment]
也是
别的部署更不好使

**Comment by JmansoKing** [comment]
别的也不会，请问有啥解决办法吗

**Comment by Harry-zklcdc** [comment]
尝试最新版
