### ISSUE TITLE
[Bug] 🐛 开启 企业版 模式，会提示 正在使用 Microsoft 帐户保存你的对话历史记录。下次使用个人帐户登录时，它将在此处显示。 而且无法查看历史记录

### ISSUE THREAD

**Issue by ryanzhaorx** [Harry-zklcdc/go-proxy-bingai#221]
### Describe the bug

huggingface部署的项目
当我开启 企业版 模式，会提示“正在使用 Microsoft 帐户保存你的对话历史记录。下次使用个人帐户登录时，它将在此处显示。切换用户配置”
且用huggingface部署的项目开启 公共 无法查看历史记录。

### Steps to reproduce

1.huggingface部署的项目
2.开启 公共
3.点上面的三个点（更多），然后再点 Embed this Space

一、企业版BUG
1.用3步骤的网址，开启 企业版
2.重新进入网站，会发现“正在使用 Microsoft 帐户保存你的对话历史记录。下次使用个人帐户登录时，它将在此处显示。切换用户配置”

二、历史记录BUG
1.对话
2.重新进入网站，会发现历史记录不见了

### Expected behavior

开启企业版不会提示“正在使用 Microsoft 帐户保存你的对话历史记录。下次使用个人帐户登录时，它将在此处显示。切换用户配置”
历史记录功能能正常查看

### Screenshots

企业版:

<img width="1440" alt="截屏2023-09-29 20 56 43" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/103013573/cfa41c64-2ea4-454e-a92b-21bc66dbd071">

聊天记录:
<img width="1426" alt="截屏2023-09-29 20 58 57" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/103013573/8b347d75-b9d1-40c3-99bc-5870a0dd476c">

<img width="1440" alt="截屏2023-09-29 20 59 28" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/103013573/fd387e0a-7ae3-41c5-ad4c-822962a7e2f1">

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by ryanzhaorx** [comment]
GoProxiBing Version: v1.15.1
Browser & Version: Chrome 117.0.5938.132
OS: macOs Ventura

**Comment by luckyEason** [comment]
微软不会保存企业版的聊天记录，企业版的聊天记录不会用于训练bing语言模型

**Comment by luckyEason** [comment]
并且不能保存聊天记录是因为Safari的特性，你必须登录才能保证聊天记录的功能

**Comment by luckyEason** [comment]
说实话，这个企业版貌似不是真正的企业版，因为不登录就能用

**Comment by ryanzhaorx** [comment]
> 并且不能保存聊天记录是因为Safari的特性，你必须登录才能保证聊天记录的功能

我用的是Chrome浏览器

**Comment by ryanzhaorx** [comment]
> 微软不会保存企业版的聊天记录，企业版的聊天记录不会用于训练bing语言模型

有什么方法把那个 “正在使用 Microsoft 帐户保存你的对话历史记录。下次使用个人帐户登录时，它将在此处显示。” 屏蔽掉?

**Comment by luckyEason** [comment]
> > 并且不能保存聊天记录是因为Safari的特性，你必须登录才能保证聊天记录的功能
> 
> 
> 
> 我用的是Chrome浏览器
> 
> 

没看到😓

**Comment by luckyEason** [comment]
> > 微软不会保存企业版的聊天记录，企业版的聊天记录不会用于训练bing语言模型
> 
> 
> 
> 有什么方法把那个 “正在使用 Microsoft 帐户保存你的对话历史记录。下次使用个人帐户登录时，它将在此处显示。” 屏蔽掉?

直接关闭历史记录

**Comment by luckyEason** [comment]
试了一下，没登录的话不会保存聊天记录，标签页还没关，侧栏的聊天记录就没了

**Comment by ryanzhaorx** [comment]
> > > 微软不会保存企业版的聊天记录，企业版的聊天记录不会用于训练bing语言模型
> > 
> > 
> > 有什么方法把那个 “正在使用 Microsoft 帐户保存你的对话历史记录。下次使用个人帐户登录时，它将在此处显示。” 屏蔽掉?
> 
> 直接关闭历史记录

试过，还是会显示，我打算加个规则(自动拦截)
怎么登录账户?

**Comment by luckyEason** [comment]
> > > > 微软不会保存企业版的聊天记录，企业版的聊天记录不会用于训练bing语言模型
> 
> > > 
> 
> > > 
> 
> > > 有什么方法把那个 “正在使用 Microsoft 帐户保存你的对话历史记录。下次使用个人帐户登录时，它将在此处显示。” 屏蔽掉?
> 
> > 
> 
> > 直接关闭历史记录
> 
> 
> 
> 试过，还是会显示，我打算加个规则(自动拦截)
> 
> 怎么登录账户?

cookie，详见wiki，要求没ID锁，服务器ip纯洁

**Comment by ryanzhaorx** [comment]
> > > > > 微软不会保存企业版的聊天记录，企业版的聊天记录不会用于训练bing语言模型
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 有什么方法把那个 “正在使用 Microsoft 帐户保存你的对话历史记录。下次使用个人帐户登录时，它将在此处显示。” 屏蔽掉?
> > 
> > 
> > > 
> > 
> > 
> > > 直接关闭历史记录
> > 
> > 
> > 试过，还是会显示，我打算加个规则(自动拦截)
> > 怎么登录账户?
> 
> cookie，详见wiki，要求没ID锁，服务器ip纯洁

thanks，我已经注册完国外的账号了，并且会登录了

**Comment by Harry-zklcdc** [comment]
企业版，你用普通账号登录，就不是企业版，必须得用企业账号的token登录才行

**Comment by ryanzhaorx** [comment]
> 企业版，你用普通账号登录，就不是企业版，必须得用企业账号的token登录才行

我知道了，谢谢你Owner。
