### ISSUE TITLE
[Help] 🤔 开启新对话时报错

### ISSUE THREAD

**Issue by Fan1K413** [Harry-zklcdc/go-proxy-bingai#223]
### Describe the help wanted

开启新对话时提示“很抱歉，似乎出现错误。 让我们重新开始吧。”
如果从bing官网开启新对话后用部署的项目可以继续对话

### Steps to behave

开启新对话时提示“很抱歉，似乎出现错误。 让我们重新开始吧。”
如果从bing官网开启新对话后用部署的项目可以继续对话

### Expected behavior

应可以开启新对话

### Screenshots

![屏幕截图 2023-10-01 175458](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/73202054/3b1016df-aa9e-40ab-be7e-c47e9b87d2b7)

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by zsanjin-p** [comment]
今天3个服务器部署的都这样了，昨天还好好的，不知道是不是被微软封杀了

**Comment by maggieqnr** [comment]
me too

**Comment by zsanjin-p** [comment]
> me too

之前稳定运行好久了

**Comment by strongasahorse** [comment]
我也是昨天运行还行 ,今天上午发现手机不能用了,下午回到电脑前,重新部署了,还是不行 .但是翻墙后官方的bing用的好好的,更新cookies后,再回来抱脸上的链接,依然无法使用 ......如果大量都这样的话,那只能说明抱脸的ip被微软封了.以后就只能翻墙用bing了.

**Comment by jokyo0** [comment]
> 我也是昨天运行还行 ,今天上午发现手机不能用了,下午回到电脑前,重新部署了,还是不行 .但是翻墙后官方的bing用的好好的,更新cookies后,再回来抱脸上的链接,依然无法使用 ......如果大量都这样的话,那只能说明抱脸的ip被微软封了.以后就只能翻墙用bing了.

https://github.com/Harry-zklcdc/go-proxy-bingai/issues/225#issuecomment-1748022088

**Comment by Harry-zklcdc** [comment]
same issue，closed
