### ISSUE TITLE
[Bug] 🐛 无法创建新对话

### ISSUE THREAD

**Issue by ningguoxu** [Harry-zklcdc/go-proxy-bingai#225]
### Describe the bug

无法创建新对话 很抱歉，似乎出现错误。 让我们重新开始吧。
演示网站也不可以
huggingface貌似也不能用

### Steps to reproduce

打开部署的网站

### Expected behavior

可以创建新对话

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/87106666/c5c65a8b-86ef-44bc-93a7-481c09aba511)

### Versions

- OS: Windows 10
- Browser & Version: e.g. Chrome 114
- GoProxiBing Version: 1.15.1

### Additional context

大佬修Bug辛苦了✿

**Comment by ningguoxu** [comment]
在https://www.croxy.network/_zh这个链接输入bing.com即使国内网络也有Chat

**Comment by luckyEason** [comment]
貌似必应有加强限制了，现在所有站点都遇到了这个问题

**Comment by SokWith** [comment]
> 貌似必应又加强限制了，现在所有站点都遇到了这个问题。登录账号后，不能创建新主题，以前的主题还能用。也不能生成图片了

看了一下，就是更新了核心api，对这个项目只能叫恶心了一下，改1行对核心api的调用代码就好了。见我的测试域（https://nbing.eu.org ）。
对其他自主重新编写核心api的项目（NewBingGoGo、bingo）就比较麻烦了，需要重写对wss的GET参数；也就间接判了NewBingGoGo项目死刑，得忍痛删除了。

**Comment by ningguoxu** [comment]
> > 貌似必应又加强限制了，现在所有站点都遇到了这个问题。登录账号后，不能创建新主题，以前的主题还能用。也不能生成图片了
> 
> 看了一下，就是更新了核心api，对这个项目只能叫恶心了一下，改1行对核心api的调用代码就好了。见我的测试域（https://nbing.eu.org ）。 对其他自主重新编写核心api的项目（NewBingGoGo、bingo）就比较麻烦了，需要重写对wss的GET参数；也就间接判了NewBingGoGo项目死刑，得忍痛删除了。

大佬，怎么改求教程

**Comment by luckyEason** [comment]
@SokWith 求教程

**Comment by SokWith** [comment]
> > > 貌似必应又加强限制了，现在所有站点都遇到了这个问题。登录账号后，不能创建新主题，以前的主题还能用。也不能生成图片了
> > 
> > 
> > 看了一下，就是更新了核心api，对这个项目只能叫恶心了一下，改1行对核心api的调用代码就好了。见我的测试域（https://nbing.eu.org ）。 对其他自主重新编写核心api的项目（NewBingGoGo、bingo）就比较麻烦了，需要重写对wss的GET参数；也就间接判了NewBingGoGo项目死刑，得忍痛删除了。
> 
> 大佬，怎么改求教程

我是小白，只会复制粘贴改配置。

核心API，顾名思义，就叫core.js
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/ad0e8915-42ec-44be-9796-1080ca20dea6)

**Comment by SokWith** [comment]
这个核心API微软天天都在更新，访问官网从开发者工具中查看create的发起程序来确认最新版本。小改动不影响项目大致运行，也没必要一直跟随。

**Comment by luckyEason** [comment]
@SokWith 感谢

**Comment by luckyEason** [comment]
开发者工具中怎么查看create啊？

**Comment by jsdianman** [comment]
看着头皮发麻
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/143573972/02cbac8c-af8b-44e5-9182-7c6da2535ad0)

**Comment by SokWith** [comment]
> 开发者工具中怎么查看create啊？

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/56593dfe-4908-40a3-9b9c-2a993dcb2ff8)

**Comment by ningguoxu** [comment]
不知道为什么改完之后历史记录打不开也删不掉？

**Comment by SokWith** [comment]
这个项目的原大佬一开始就铆定了bing的官方核心API，确保了项目始终是与官方同步的。其实质与其名字proxy相符，就是一个socks5代理服务器。

**Comment by ningguoxu** [comment]
改完后历史记录打不开也删不了

**Comment by ningguoxu** [comment]
> 改完后历史记录打不开也删不了

官方服务器可以打开，但是本站和自定义服务器打不开

**Comment by renqabs** [comment]
查看了下官方的js调用栈，好像核心API的js文件名又变化了，我改了下，暂时是好用的
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/130155002/f63c38a9-161c-4a47-b6c4-a7d30a0b7863)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/130155002/a4c62d0a-0bc4-4a6f-b7e6-f022e12429fe)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/130155002/86584e9c-ef2e-4cef-8069-ae924f95c0a5)

**Comment by Harry-zklcdc** [comment]
> 这个项目的原大佬一开始就铆定了bing的官方核心API，确保了项目始终是与官方同步的。其实质与其名字proxy相符，就是一个socks5代理服务器。
> 
> @Harry-zklcdc 大佬，能不能把core.js换一个思路，直接后端访问官网后把官网rp目录下的核心js文件统统缓存下来加载，实现代理服务器样的自动化跟随？

不好做，只能尝试

核心core又变化了？还在放假，没带电脑回来，回去后我更新一下吧

然后就是有人能用bing插件了嘛？这几个礼拜没更新就是一直在等插件功能上线。有能用的账号麻烦可以借我用一下账号

**Comment by Harry-zklcdc** [comment]
已更新，请尝试

**Comment by O-zhang** [comment]
> 已更新，请尝试

对话没问题，撰写功能是不是不能用？有没有其他人尝试过，或者仅是我的问题

**Comment by Harry-zklcdc** [comment]
> 对话没问题

OK

> 撰写功能是不是不能用？有没有其他人尝试过，或者仅是我的问题

我检查一下

**Comment by goss1p** [comment]
> > 貌似必应又加强限制了，现在所有站点都遇到了这个问题。登录账号后，不能创建新主题，以前的主题还能用。也不能生成图片了
> 
> 看了一下，就是更新了核心api，对这个项目只能叫恶心了一下，改1行对核心api的调用代码就好了。见我的测试域（https://nbing.eu.org ）。 对其他自主重新编写核心api的项目（NewBingGoGo、bingo）就比较麻烦了，需要重写对wss的GET参数；也就间接判了NewBingGoGo项目死刑，得忍痛删除了。

我看到你之前的一些发言，说`无ID`或者`没有ID锁`是什么意思？
bingo为什么不要求`KievRPSSecAuth`和`_RwBf`，而go-proxy-bingai则似乎必须加上这两个参数。

另外，你之前说连官方的服务器可以解ID锁又是什么意思，我试了，在每天go-proxy-bingai项目的Cookies过期之后(即开始无限跳验证框了)，切换到Bing官方服务器，仍然是无限验证，无法在go-proxy-bingai上完成验证，还是得去bing的官网重新获取的`KievRPSSecAuth`和`_RwBf`。

**Comment by SokWith** [comment]
> > > 貌似必应又加强限制了，现在所有站点都遇到了这个问题。登录账号后，不能创建新主题，以前的主题还能用。也不能生成图片了
> > 
> > 
> > 看了一下，就是更新了核心api，对这个项目只能叫恶心了一下，改1行对核心api的调用代码就好了。见我的测试域（https://nbing.eu.org ）。 对其他自主重新编写核心api的项目（NewBingGoGo、bingo）就比较麻烦了，需要重写对wss的GET参数；也就间接判了NewBingGoGo项目死刑，得忍痛删除了。
> 
> 我看到你之前的一些发言，说`无ID`或者`没有ID锁`是什么意思？ bingo为什么不要求`KievRPSSecAuth`和`_RwBf`，而go-proxy-bingai则似乎必须加上这两个参数。
> 
> 另外，你之前说连官方的服务器可以解ID锁又是什么意思，我试了，在每天go-proxy-bingai项目的Cookies过期之后(即开始无限跳验证框了)，切换到Bing官方服务器，仍然是无限验证，无法在go-proxy-bingai上完成验证，还是得去bing的官网重新获取的`KievRPSSecAuth`和`_RwBf`。

1、先申明一下，win7下官方服务器过验证的方式已失效了，由于api更新后，官方服务器已经不可以用了。之前我测试时，win10是不可以的，所以，如果你的官方服务器可以使用，建议在win7下测试，方法是：先用本站服务器激活验证框，然后再切换到官方服务器。如果你的机子速度快，可能来不及，但有时会出现确认打勾的场景，就可以从容切替。
2、bingo不是不要cookie，bingo是部署在特定的机器上可以匿名使用而已。如果部署在一般机器上，是需要cookie的，而且由于没有拆分，是全cookie连接的。由于自编核心没有处理MUID，而MUID有效期一天，所以必须每天重启服务。至于bingo2.0，目前没有代码放出来，过验证的方式不明。其实只要处理好create获取匿名连接id，就无需过验证而匿名使用了。可以参见我的测试域里面，replit和cf都可以匿名会话了。
3、要使用绘图等功能，必须提供ID，由于每天加锁，所以必须每天过验证。由于win7下官方服务器已失效，目前只有上官网过或者使用whistle等代理套改域名方式。bingo2.0从介绍上看是没有选择过验证的，所以提示不能绘图。

**Comment by goss1p** [comment]
> > > > 貌似必应又加强限制了，现在所有站点都遇到了这个问题。登录账号后，不能创建新主题，以前的主题还能用。也不能生成图片了
> > > 
> > > 
> > > 看了一下，就是更新了核心api，对这个项目只能叫恶心了一下，改1行对核心api的调用代码就好了。见我的测试域（https://nbing.eu.org ）。 对其他自主重新编写核心api的项目（NewBingGoGo、bingo）就比较麻烦了，需要重写对wss的GET参数；也就间接判了NewBingGoGo项目死刑，得忍痛删除了。
> > 
> > 
> > 我看到你之前的一些发言，说`无ID`或者`没有ID锁`是什么意思？ bingo为什么不要求`KievRPSSecAuth`和`_RwBf`，而go-proxy-bingai则似乎必须加上这两个参数。
> > 另外，你之前说连官方的服务器可以解ID锁又是什么意思，我试了，在每天go-proxy-bingai项目的Cookies过期之后(即开始无限跳验证框了)，切换到Bing官方服务器，仍然是无限验证，无法在go-proxy-bingai上完成验证，还是得去bing的官网重新获取的`KievRPSSecAuth`和`_RwBf`。
> 
> 1、先申明一下，win7下官方服务器过验证的方式已失效了，由于api更新后，官方服务器已经不可以用了。之前我测试时，win10是不可以的，所以，如果你的官方服务器可以使用，建议在win7下测试，方法是：先用本站服务器激活验证框，然后再切换到官方服务器。如果你的机子速度快，可能来不及，但有时会出现确认打勾的场景，就可以从容切替。 2、bingo不是不要cookie，bingo是部署在特定的机器上可以匿名使用而已。如果部署在一般机器上，是需要cookie的，而且由于没有拆分，是全cookie连接的。由于自编核心没有处理MUID，而MUID有效期一天，所以必须每天重启服务。至于bingo2.0，目前没有代码放出来，过验证的方式不明。其实只要处理好create获取匿名连接id，就无需过验证而匿名使用了。可以参见我的测试域里面，replit和cf都可以匿名会话了。 3、要使用绘图等功能，必须提供ID，由于每天加锁，所以必须每天过验证。由于win7下官方服务器已失效，目前只有上官网过或者使用whistle等代理套改域名方式。bingo2.0从介绍上看是没有选择过验证的，所以提示不能绘图。

如何确认是匿名状态的呢，看不出太大的区别。。

**Comment by SokWith** [comment]
会话含关键词 画图，有ID就会画图，匿名就会提示登录后才能画图，比如：发指令  draw car

**Comment by renqabs** [comment]
> 会话含关键词 画图，有ID就会画图，匿名就会提示登录后才能画图，比如：发指令 draw car

单论画图功能的话应该不用到www.bing验证，go-proxy-bingai下的图像创建功能只需要微软账号登陆后cookie中的_U值（www.bing或者cn.bing登录都可以，前提是账号已加入image creator）

**Comment by goss1p** [comment]
> > 会话含关键词 画图，有ID就会画图，匿名就会提示登录后才能画图，比如：发指令 draw car
> 
> 单论画图功能的话应该不用到www.bing验证，go-proxy-bingai下的图像创建功能只需要微软账号登陆后cookie中的_U值（www.bing或者cn.bing登录都可以，前提是账号已加入image creator），如果有办法让AI对话使用随机token，画图功能使用真实的_U值就好了

请问这几个值到底啥含义？
KievRPSSecAuth、MUID、_RwBf、_U，傻傻分不清楚。

**Comment by goss1p** [comment]
> > > > 貌似必应又加强限制了，现在所有站点都遇到了这个问题。登录账号后，不能创建新主题，以前的主题还能用。也不能生成图片了
> > > 
> > > 
> > > 看了一下，就是更新了核心api，对这个项目只能叫恶心了一下，改1行对核心api的调用代码就好了。见我的测试域（https://nbing.eu.org ）。 对其他自主重新编写核心api的项目（NewBingGoGo、bingo）就比较麻烦了，需要重写对wss的GET参数；也就间接判了NewBingGoGo项目死刑，得忍痛删除了。
> > 
> > 
> > 我看到你之前的一些发言，说`无ID`或者`没有ID锁`是什么意思？ bingo为什么不要求`KievRPSSecAuth`和`_RwBf`，而go-proxy-bingai则似乎必须加上这两个参数。
> > 另外，你之前说连官方的服务器可以解ID锁又是什么意思，我试了，在每天go-proxy-bingai项目的Cookies过期之后(即开始无限跳验证框了)，切换到Bing官方服务器，仍然是无限验证，无法在go-proxy-bingai上完成验证，还是得去bing的官网重新获取的`KievRPSSecAuth`和`_RwBf`。
> 
> 1、先申明一下，win7下官方服务器过验证的方式已失效了，由于api更新后，官方服务器已经不可以用了。之前我测试时，win10是不可以的，所以，如果你的官方服务器可以使用，建议在win7下测试，方法是：先用本站服务器激活验证框，然后再切换到官方服务器。如果你的机子速度快，可能来不及，但有时会出现确认打勾的场景，就可以从容切替。 2、bingo不是不要cookie，bingo是部署在特定的机器上可以匿名使用而已。如果部署在一般机器上，是需要cookie的，而且由于没有拆分，是全cookie连接的。由于自编核心没有处理MUID，而MUID有效期一天，所以必须每天重启服务。至于bingo2.0，目前没有代码放出来，过验证的方式不明。其实只要处理好create获取匿名连接id，就无需过验证而匿名使用了。可以参见我的测试域里面，replit和cf都可以匿名会话了。 3、要使用绘图等功能，必须提供ID，由于每天加锁，所以必须每天过验证。由于win7下官方服务器已失效，目前只有上官网过或者使用whistle等代理套改域名方式。bingo2.0从介绍上看是没有选择过验证的，所以提示不能绘图。

<img width="1352" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/148735875/0cf650f5-439c-41a8-b36f-cd7d64bebfd4">
HuggingFace的站点是正常工作的，但是CFWK的站点会无限跳验证框。

请问这个huggingface实现匿名聊天的方式是怎样的呢？我试了一下，清除了`KievRPSSecAuth`、`_RwBf`、`_U` （←并且不允许生成随机值），然后在微软Azure上获取MUID，但是会触发无限验证，而且在"服务器选择"的窗口里，"本站"没有ttl值，显示为"不可用"的状态。

**Comment by SokWith** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/5e212890-6adb-40ef-a6b8-5f9f79583cd0)
发生了什么？在家的网络里面cfwk又匿名会话了！

**Comment by SokWith** [comment]
![IMG_20231023_203736](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/01c2824f-d6fd-439d-b767-a9bc26682ca1)
vercel部署使用的是cf的wss，也匿名了

**Comment by SokWith** [comment]
> > ![image](https://user-images.githubusercontent.com/129967025/277333134-5e212890-6adb-40ef-a6b8-5f9f79583cd0.png) 发生了什么？在家的网络里面cfwk又匿名会话了！
> 
> 复现步骤： 我清理了所有的cookies， 然后打开 cfwk.nbing.eu.org， 再点击 设置-一键重置，选择 "本站"， 发送消息就会无限弹验证请求了。
> 
> ![Screenshot_2023-10-23-22-44-14-14_33f34bf0029ca15359ebd43d4b95def2](https://user-images.githubusercontent.com/148735875/277376831-3d0cecc4-238e-43b6-afa8-32a662ac94d4.jpg)

出现一直验证的情形，你是有科学环境吗？普通环境是直接验证失败后要求重新开始，科学环境则由于验证成功（假象）所以再次wss握手的时候会重新要求验证。

**Comment by SokWith** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/e844ecfc-a81f-4d19-af22-373808ae3ead)
刚刚无痕模式下匿名会话

**Comment by goss1p** [comment]
> ![image](https://user-images.githubusercontent.com/129967025/277380228-e844ecfc-a81f-4d19-af22-373808ae3ead.png) 刚刚无痕模式下匿名会话

![IMG_20231023_225714](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/148735875/60374bda-fd48-48b2-8af2-4324afa9c3c7)
![MTXX_PT20231023_230211080](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/148735875/c2d93a95-458e-4e61-b7f4-08e16df18f16)

**Comment by SokWith** [comment]
![IMG_20231023_232030](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/cd49cee5-649f-4324-abdd-5e2e694cf4a1)
手机上用的是edge浏览器，匿名会话成功率大约只有3成，点击重新开始就可以了。出现一直验证，应该还是网络能够连通www.bing.com，才会返回验证成功的信号。

**Comment by goss1p** [comment]
> ![IMG_20231023_232030](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/cd49cee5-649f-4324-abdd-5e2e694cf4a1)
> 手机上用的是edge浏览器，匿名会话成功率大约只有3成，点击重新开始就可以了。出现一直验证，应该还是网络能够连通www.bing.com，才会返回验证成功的信号。

你的cfwk站点我依然无法使用。

然后我自己搭建了一个cfwk站点(也想达到匿名，移除了所有的cookies)，发现`/sydney/ChatHub`连不上，随后使用ws连接工具进行测试，提示1006连接错误。

https://test01.b1ghawk.xyz/

然后我又测试了带cookies的站点(包括我的另一个cfwk站点)和匿名的站点，ws工具可以都连接它们的`/sydney/ChatHub`，这是什么情况呢，为什么移除了cookies就连接错误了呢？

**Comment by SokWith** [comment]
![电信数据 ok](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/fca5f9bf-989e-4d2a-a8ff-dbac2e7c79af)
![联通wifi-ng](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/084ac495-357a-4bb8-a4e4-d0c30ae4b52d)
奇了怪了，真的和客户端网络有关系。
公司是联通的网络，电脑和手机连接wifi后cf的wss都是要验证然后失败；家里和手机是电信网络基本上一半以上都不要验证就直接不断的try服务器然后就连上了。

**Comment by goss1p** [comment]
> ![电信数据 ok](https://user-images.githubusercontent.com/129967025/277513711-fca5f9bf-989e-4d2a-a8ff-dbac2e7c79af.jpg) ![联通wifi-ng](https://user-images.githubusercontent.com/129967025/277513746-084ac495-357a-4bb8-a4e4-d0c30ae4b52d.jpg) 奇了怪了，真的和客户端网络有关系。 公司是联通的网络，电脑和手机连接wifi后cf的wss都是要验证然后失败；家里和手机是电信网络基本上一半以上都不要验证就直接不断的try服务器然后就连上了。

请问匿名的情况下，`/sydney/ChatHub`这个wss连接要如何处理呢？我尝试注释了所有的cookie，无法连接。

**Comment by SokWith** [comment]
K值不需要，U值和MUID值故意用错误的。

**Comment by SokWith** [comment]
去官网测试可见，目前匿名会话的时候，create后就不断的在try chathub，建立起连接后才能稳定。但是1个对话后马上要求确认协议。所以，正常的普通网络，也得这样只有1个对话，下一个对话又重复create。表现大致如同replit的测试站点。
外网环境的匿名访问没有K值，所以不要加入cookie里面。

**Comment by Harry-zklcdc** [comment]
最新版试试
