### ISSUE TITLE
有没有办法添加人机验证功能

### ISSUE THREAD

**Issue by Cheny233** [Harry-zklcdc/go-proxy-bingai#23]
触发人机验证后会提示无效域，需要自行去官网认证才行。可不可以在站内直接完成人机验证呢

**Comment by Harry-zklcdc** [comment]
没有办法，域名不一样，没法通过人机验证，可查看Cloudflare的人机验证规则

**Comment by qinguoluo** [comment]
触发人机验证的原因是什么？

**Comment by FangZirui-E5** [comment]
> 触发人机验证的原因是什么？

他们定期（比如每隔一天）就会在你使用的时候来一次验证，没有任何其他原因😢

**Comment by Harry-zklcdc** [comment]
> 触发人机验证的原因是什么？

很正常，为了防止滥用，因为大家都知道这个是免费的接口
