### ISSUE TITLE
[Bug] 🐛 本地服务器始终无法连接一直提示不可用

### ISSUE THREAD

**Issue by ilolita945** [Harry-zklcdc/go-proxy-bingai#231]
### Describe the bug

最近1.10.2用不了了才更新到最新版1.16.0（自从1.12.0换了本地代理后就一直有问题），Docker也使用了系统代理环境变量（我参考这里设置了代理https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F）也始终提示本地服务不可用。

以下是我设置的代理（HTTP 10811；Socks5 10810；用户名 Guest；密码 #$%QWEASDzxc7412369；主机 192.168.0.140）：
HTTP_PROXY=Guest:#$%QWEASDzxc7412369@192.168.1.140:10811
HTTP_PROXY=http://Guest:#$%QWEASDzxc7412369@192.168.1.140:10811
HTTP_PROXY=socks5://Guest:#$%QWEASDzxc7412369@192.168.1.140:10810

HTTPS_PROXY=Guest:#$%QWEASDzxc7412369@192.168.1.140:10811
HTTPS_PROXY=https://Guest:#$%QWEASDzxc7412369@192.168.1.140:10811
HTTPS_PROXY=socks5://Guest:#$%QWEASDzxc7412369@192.168.1.140:10810

以上六组配置都选其一始终无法连接，以前的旧代理格式是正常的，在1.10.2版本下
Go_Proxy_BingAI_SOCKS_URL
Go_Proxy_BingAI_SOCKS_USER
Go_Proxy_BingAI_SOCKS_PWD

### Steps to reproduce

以下是我设置的代理（HTTP 10811；Socks5 10810；用户名 Guest；密码 #$%QWEASDzxc7412369；主机 192.168.0.140）：
HTTP_PROXY=Guest:#$%QWEASDzxc7412369@192.168.1.140:10811
HTTP_PROXY=http://Guest:#$%QWEASDzxc7412369@192.168.1.140:10811
HTTP_PROXY=socks5://Guest:#$%QWEASDzxc7412369@192.168.1.140:10810

HTTPS_PROXY=Guest:#$%QWEASDzxc7412369@192.168.1.140:10811
HTTPS_PROXY=https://Guest:#$%QWEASDzxc7412369@192.168.1.140:10811
HTTPS_PROXY=socks5://Guest:#$%QWEASDzxc7412369@192.168.1.140:10810

以上配置始终无法连接

### Expected behavior

恢复以前的三个变量
Go_Proxy_BingAI_SOCKS_URL
Go_Proxy_BingAI_SOCKS_USER
Go_Proxy_BingAI_SOCKS_PWD

### Screenshots

![QQ截图20231008124407](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/49525838/c588ba1e-62d8-4818-857e-a57c60323848)

### Versions

- OS: Windows 10
- Browser & Version: Edge 117
- GoProxiBing Version:

**Comment by ilolita945** [comment]
即便我用windows设置了进程全局代理也是同样问题

**Comment by Harry-zklcdc** [comment]
密码改改试试，别带特殊字符；或者不要账号密码试试

**Comment by ilolita945** [comment]
> 密码改改试试，别带特殊字符；或者不要账号密码试试

也不行，Windows下，我把整个进程设置走代理了 也不行，可否排查下

**Comment by Harry-zklcdc** [comment]
我自己本地Linux一直用的是配置 `http_proxy` 环境变量的方式来开发的，理论上应该没有问题

window好像得用
~~~shell
set HTTP_PROXY=http://xxxxx:xxx
set HTTPS_PROXY=http://xxxxx:xxx

然后执行
./go-proxy-bingai
~~~

**Comment by ilolita945** [comment]
> 我自己本地Linux一直用的是配置 `http_proxy` 环境变量的方式来开发的，理论上应该没有问题
> 
> window好像得用
> 
> ```shell
> set HTTP_PROXY=http://xxxxx:xxx
> set HTTPS_PROXY=http://xxxxx:xxx
> 
> 然后执行
> ./go-proxy-bingai
> ```

我是V2ray tun模式 指定这个进程走全局代理，按理来说也是没问题的

**Comment by Harry-zklcdc** [comment]
再试试最新版吧，有问题的话发一下邮箱，我远程看一下
