### ISSUE TITLE
[Bug] 🐛 撰写文章功能无法使用

### ISSUE THREAD

**Issue by O-zhang** [Harry-zklcdc/go-proxy-bingai#232]
### Describe the bug

文章撰写功能异常

### Steps to reproduce

打开[https://bingai.zklcdc.xyz/web/compose.html](https://bingai.zklcdc.xyz/web/compose.html)， 输入任何内容

### Expected behavior

修复bug或者提供修复思路

### Screenshots

![捕获](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/14349821/38abc56d-0c64-42df-9cf2-04628941e761)

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version: 

### Additional context

大佬辛苦

**Comment by Harry-zklcdc** [comment]
好的

**Comment by Harry-zklcdc** [comment]
我在官网也用不了，你的可以用吗

**Comment by O-zhang** [comment]
![捕获1](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/14349821/598ae0cf-c539-4506-bf7f-c6055f97aff5)
如果科学上网用edge是没有问题的。

**Comment by Harry-zklcdc** [comment]
> [捕获1](https://user-images.githubusercontent.com/14349821/275186195-598ae0cf-c539-4506-bf7f-c6055f97aff5.PNG) edge侧边栏是没有问题的，前提是科学上网。官网应该是只能用侧边栏啊，没有网页版

奇了怪了，我用不了

**Comment by O-zhang** [comment]
> > [捕获1](https://user-images.githubusercontent.com/14349821/275186195-598ae0cf-c539-4506-bf7f-c6055f97aff5.PNG) edge侧边栏是没有问题的，前提是科学上网。官网应该是只能用侧边栏啊，没有网页版
> 
> 奇了怪了，我用不了

是不是bing的账户的设置里没有修改地区为中国大陆以外地区
![捕获2](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/14349821/34f1a966-096d-469b-9284-29e44cef1921)

**Comment by Harry-zklcdc** [comment]
已修复
