### ISSUE TITLE
Replit部署显示本站不可用

### ISSUE THREAD

**Issue by jsdianman** [Harry-zklcdc/go-proxy-bingai#233]
如题，求助

**Comment by SokWith** [comment]
现在还有不可用的部署吗？
官方10月更新API后，似乎原来的许多限制都解除了，几乎没有IP锁和MUID锁了。
这个项目目前比较命苦，被render封杀了；隔壁bingo就可以部署在render上，而且还不需要验证账户。
目前replit、cf的部署需要验证账户，由于这个项目采用vercel部署需要走cf的create，所以，也会验证账户
