### ISSUE TITLE
[Bug] 🐛 这个最新版依然不能用

### ISSUE THREAD

**Issue by cengzhijie3** [Harry-zklcdc/go-proxy-bingai#235]
### Describe the bug

用docker更新最新版后依旧是这些问题尽管用了所谓的越狱和高级，要么就是重新连接，要么就是验证后直接解析不了

### Steps to reproduce

可以试试用docker

### Expected behavior

帮忙解决下

### Screenshots

<img width="1002" alt="截圖 2023-10-21 下午4 05 37" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/89333400/ec7a1b89-b5c3-462e-a614-75e60a1f2355">
<img width="1013" alt="截圖 2023-10-21 下午4 05 46" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/89333400/1d04d401-1bd5-4072-90cb-6b5110badf3b">
<img width="1013" alt="截圖 2023-10-21 下午4 05 56" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/89333400/d1181018-5d9d-4634-a072-515d7043a00e">
<img width="1013" alt="截圖 2023-10-21 下午4 06 12" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/89333400/225559ae-5b23-421e-b23c-c0701f6b07f0">

### Versions

- OS: MAC OS SONOMA
- Browser & Version: Firefox LATEST
- GoProxiBing Version: V 1.16.1

**Comment by luckyEason** [comment]
你一键重置了嘛？我用docker很好用啊

**Comment by yurhett** [comment]
目前正常使用 请自行排查

**Comment by cengzhijie3** [comment]
> 你一键重置了嘛？我用docker很好用啊

重置也没用，依然叫我重新开始
<img width="1013" alt="截圖 2023-10-22 下午2 03 31" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/89333400/794c43e3-9fd1-46c8-a4b7-ef12b1acdc14">
<img width="1013" alt="截圖 2023-10-22 下午2 03 44" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/89333400/776306ee-3100-4959-850e-67ee6307dff5">
<img width="1013" alt="截圖 2023-10-22 下午2 03 50" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/89333400/8b69b152-434e-419a-b519-2cad050e6832">

**Comment by yurhett** [comment]
建议F12看一下ChatHub返回的是什么数据，如果是微软的404页面，那么就是你的IP被微软ban了。

**Comment by cengzhijie3** [comment]
> 建议F12看一下ChatHub返回的是什么数据，如果是微软的404页面，那么就是你的IP被微软ban了。

返回的是101
<img width="1091" alt="截圖 2023-10-22 下午3 24 01" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/89333400/8383ca05-6301-46fb-8db3-7cc8f7ae997f">

**Comment by SokWith** [comment]
不要选用 官方 服务器

**Comment by cengzhijie3** [comment]
> 不要选用 官方 服务器

选其他也不行，都验证5分钟了都还在验证
<img width="1091" alt="截圖 2023-10-22 下午4 18 37" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/89333400/291fced1-5872-4cdb-bb4d-20a3dac7d7f4">
<img width="1091" alt="截圖 2023-10-22 下午4 21 09" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/89333400/8c0c289f-37df-4887-8712-e6faea43c8c1">
<img width="1091" alt="截圖 2023-10-22 下午4 21 16" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/89333400/a81f885d-f521-4e52-9a45-8151e98520fa">

**Comment by cengzhijie3** [comment]
企业版也一样
<img width="1091" alt="截圖 2023-10-22 下午4 32 41" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/89333400/55e17ee3-fb85-4d73-99af-4d3ed64cd79e">

**Comment by SokWith** [comment]
要确保你的cookie是有效的，最新的，部署的机器ip没有被官方封杀，最后这一点就像开盲盒了。

PS：简单的方法就是不要用自己的vps部署了，就用cf workers来部署，速度是几个免费云服务中最快的了。其次是vercel部署，也是可以匿名使用的，就是聊天会话不稳定。抱脸是最慢的，replit的流量太少了。

**Comment by SokWith** [comment]
还有，就是使用的时候不要科学环境，会造成一直验证。普通环境是直接失败重新开始。
有cookie的情况下还需要验证，通常都是cookie失效了。
一般而言，认证有效期是1天，U值有效期是2周，K值大约1个月。

**Comment by yurhett** [comment]
> > 建议F12看一下ChatHub返回的是什么数据，如果是微软的404页面，那么就是你的IP被微软ban了。
> 
> 返回的是101 <img alt="截圖 2023-10-22 下午3 24 01" width="1091" src="https://user-images.githubusercontent.com/89333400/277151191-8383ca05-6301-46fb-8db3-7cc8f7ae997f.png">

看内容，内容如果是一个网页，那就是IP被干了

**Comment by Harry-zklcdc** [comment]
最新版试试
