### ISSUE TITLE
为什么部署后版本为1.9.0

### ISSUE THREAD

**Issue by wurenzhiwen666** [Harry-zklcdc/go-proxy-bingai#24]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/139636224/316d5c8a-15eb-43b9-9750-1d9d9443eafe)
是部署操作方式有误吗？

**Comment by Harry-zklcdc** [comment]
是不是没下载最新的二进制文件 或 没有同步最新代码

**Comment by Harry-zklcdc** [comment]
已修复: https://github.com/Harry-zklcdc/go-proxy-bingai/commit/cee0073c254d84ec6b84c1b6388c651c13d6ebf3
