### ISSUE TITLE
[Bug] 🐛 System prompt not persisting when switching topics or resetting conversation in "Jailbreak Mode"

### ISSUE THREAD

**Issue by hycxnas** [Harry-zklcdc/go-proxy-bingai#243]
### Describe the bug

During the interaction with Bing AI, there is an issue with the system prompts in "Jailbreak Mode". When users enable "Jailbreak Mode" and optionally customize system prompt (e.g. "sydney"), it works initially. 
However, when clicking on "New Topic" or being forced to reset the conversation, the "Jailbreak Mode" settings seem not to persist as the AI introduces itself as Bing again instead of the role defined by system prompt, as known as sydney in this case.

### Steps to reproduce

1. Enable "Jailbreak Mode" and use default system prompt (e.g. "sydney").
2. Engage in a conversation with Bing AI, and it introduces itself as "sydney" at the moment.
3. Click on "New Topic" or reset the conversation ("start over again").
4. Observe that AI introduces itself as "Bing" instead of the custom system prompt, even though "Jailbreak Mode" is still enabled and the system prompt specify "sydney" as role.

### Expected behavior

When a system prompt is set and "Jailbreak Mode" is enabled, the system prompt should persist and be used throughout the conversation, even when switching topics or resetting the conversation.

### Versions

- OS: Windows 10
- Browser & Version: Edge 118
- GoProxyBing Version:  v1.16.2

### Additional context

Dear developer,

I hope my bug report was clear and concise. If you require more information or need further clarification, please don't hesitate to ask. Thank you for your hard work on this project. I appreciate your efforts and dedication to making it better and more efficient. Let's resolve this issue together and make the project even better!

Kind regards

**Comment by Harry-zklcdc** [comment]
Same as #206 , close this.
