### ISSUE TITLE
总是弹出“很抱歉，似乎出现错误。 让我们重新开始吧。”

### ISSUE THREAD

**Issue by qiuyue520** [Harry-zklcdc/go-proxy-bingai#244]
### Describe the bug

总是弹出“很抱歉，似乎出现错误。 让我们重新开始吧。”，不管说什么话都是这样

### Steps to reproduce

打开网站，随便和bing发一个消息

### Expected behavior

什么都没干

### Screenshots

![屏幕截图 2023-10-27 204242](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/123637587/544c696e-dd01-4dd1-aaf9-79ca3d3517c8)

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by Harry-zklcdc** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/496f0f5b-9076-40ab-8fc7-02ce99f0c5f3)

**Comment by Harry-zklcdc** [comment]
最新版试试

**Comment by Benson80** [comment]
最新版也是一样！
