### ISSUE TITLE
[Help] 🤔 在cloudfalre上部署work.js的时候出现Uncaught Error: No such module "bjs.js".   imported from "worker.js"

### ISSUE THREAD

**Issue by landones** [Harry-zklcdc/go-proxy-bingai#245]
### Describe the help wanted

完全复制了作者大大的代码，但是好像第一行报错？貌似把第一行删了就报错了，不能从外部加载函数库吗？

### Steps to behave

按照作者的教程赋值workjs代码并保存部署

### Expected behavior

明白为什么出错

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by Harry-zklcdc** [comment]
还有个`bjs.js`文件，左边工作区新建文件复制粘贴
