### ISSUE TITLE
Linux系统无法使用bing聊天

### ISSUE THREAD

**Issue by qiuyue520** [Harry-zklcdc/go-proxy-bingai#246]
### Describe the bug

我在Linux系统使用的时候，无论怎样都聊不了天

### Steps to reproduce

在linux系统打开那个网站

### Expected behavior

希望能在linux系统用bing

### Screenshots

![wenti](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/123637587/bb2fdbfe-9131-4716-b6fa-b4cb0e927f5f)

### Versions

- OS: <Linux kali 6.3.0-kali1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.3.7-1kali1 (2023-06-29) x86_64 GNU/Linux-->
- Browser & Version: <Firefox ESR-->

**Comment by k-ying** [comment]
同，今天在Manjaro下使用，也发现总是失败。

**Comment by Harry-zklcdc** [comment]
我得看看，因为我目前还没有 Linux 的桌面系统，全是纯命令行的 Linux

**Comment by Harry-zklcdc** [comment]
最新版再试试？
