### ISSUE TITLE
[Bug] 🐛 这个新版的docker一直在验证，而且验证了10分钟了还是在验证

### ISSUE THREAD

**Issue by cengzhijie3** [Harry-zklcdc/go-proxy-bingai#247]
### Describe the bug

这个新版的docker一直在验证，而且验证了10分钟了还是在验证

### Steps to reproduce

可以用台服务器搭建自己的域名来尝试

### Expected behavior

有没有什么指令可以用docker退回之前的版本呢

### Screenshots

<img width="1014" alt="截圖 2023-10-30 上午10 54 41" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/89333400/1bcf9bd9-5563-4949-b5e9-8d3e8b0e9655">

### Versions

- OS: mac os
- Browser & Version: firefox latest
- GoProxiBing Version: 1.16.3

**Comment by b1ghawk** [comment]
@SokWith 为什么我这边在官服上验证通过之后，切回三方服务没有效果呢？

https://github.com/Harry-zklcdc/go-proxy-bingai/assets/30652540/60fee293-45e1-45cc-a489-433404ed342e

**Comment by SokWith** [comment]
> @SokWith 为什么我这边在官服上验证通过之后，切回三方服务没有效果呢？ 这与你先前提到的不一致 [#234 (comment)](https://github.com/Harry-zklcdc/go-proxy-bingai/issues/234#issuecomment-1781042547)
> 
>  Kapture.2023-10-30.at.11.35.13.mp4

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/aacbce40-209a-48e8-8eef-8bc1fcd5915a)
@b1ghawk 你的部署里面没有内置帐号，你应该是通过本地部署的whistle匿名使用bing

随便继续提个请求，还是那个如何实现origin的功能，只要在科学下官服成功使用就好了。毕竟梯子易得cookie难填 @b1ghawk

**Comment by SokWith** [comment]
@b1ghawk 还有就是，把whistle部署在外部vps，通过插件进行开关控制，比部署在本地好使用得多。

**Comment by SokWith** [comment]
> ### Describe the bug
> 这个新版的docker一直在验证，而且验证了10分钟了还是在验证
> 
> ### Steps to reproduce
> 可以用台服务器搭建自己的域名来尝试
> 
> ### Expected behavior
> 有没有什么指令可以用docker退回之前的版本呢
> 
> ### Screenshots
> <img alt="截圖 2023-10-30 上午10 54 41" width="1014" src="https://user-images.githubusercontent.com/89333400/278926614-1bcf9bd9-5563-4949-b5e9-8d3e8b0e9655.png">
> ### Versions
> * OS: mac os
> * Browser & Version: firefox latest
> * GoProxiBing Version: 1.16.3
> 
> ### Additional context
> _No response_

一直都提这些问题，都不看看wiki，别把大佬给看瞎眼了。
ip，ip，还是ip！

测试时还是先用正常的帐号测试，匿名使用得拼人品的。

**Comment by SokWith** [comment]
> > @SokWith 为什么我这边在官服上验证通过之后，切回三方服务没有效果呢？ 这与你先前提到的不一致 [#234 (comment)](https://github.com/Harry-zklcdc/go-proxy-bingai/issues/234#issuecomment-1781042547)
> > Kapture.2023-10-30.at.11.35.13.mp4
> 
> ![image](https://user-images.githubusercontent.com/129967025/278941921-aacbce40-209a-48e8-8eef-8bc1fcd5915a.png) @b1ghawk 你的部署里面没有内置帐号，你应该是通过本地部署的whistle匿名使用bing
> 
> 顺便继续提个请求，还是那个如何实现origin的功能，只要在科学下官服成功使用就好了。毕竟梯子易得cookie难填 @b1ghawk

https://github.com/Harry-zklcdc/go-proxy-bingai/issues/248#issue-1967520428
我开新帖，在那边讨论吧

**Comment by Harry-zklcdc** [comment]
最新版试试
