### ISSUE TITLE
自动验证一直转圈

### ISSUE THREAD

**Issue by s181462537** [Harry-zklcdc/go-proxy-bingai#249]
昨天试了自动人机验证是成功可用的，但是今天再使用时，就一直在那转圈启动，无法通过，是不是搭建的验证服务器访问量太大出问题了呢？希望大佬能解决一下。

**Comment by SokWith** [comment]
@Harry-zklcdc 你不担心你单点服务器会由于太多ID过境被上锁吗？

**Comment by Harry-zklcdc** [comment]
> @Harry-zklcdc 你不担心你单点服务器会由于太多ID过境被上锁吗？

7个IP用来搞这个，之后估计会加上代理池

**Comment by Harry-zklcdc** [comment]
> 昨天试了自动人机验证是成功可用的，但是今天再使用时，就一直在那转圈启动，无法通过，是不是搭建的验证服务器访问量太大出问题了呢？希望大佬能解决一下。

我等会回去看看吧，现在估计是又掉了，我用我旧电脑部署的服务，要搞个内网穿透，估计是又掉了

**Comment by s181462537** [comment]
如果能简化方法，把这种服务器部署的教程弄出来，让大家用自己去弄服务器就不怕太多人用了，类似cloudflare服务代理那样，再弄个环境变量去配置服务器域名，我是小白，不知道这种有没有可能实现

**Comment by Harry-zklcdc** [comment]
> 如果能简化方法，把这种服务器部署的教程弄出来，让大家用自己去弄服务器就不怕太多人用了，类似cloudflare服务代理那样，再弄个环境变量去配置服务器域名，我是小白，不知道这种有没有可能实现

不是我不想开源，一开源很大几率隔天就用不了了，又得重新研究

**Comment by Harry-zklcdc** [comment]
顺带一提，二进制版本开发验证工作已通过

**Comment by s181462537** [comment]
好的，期待中
