### ISSUE TITLE
[Help] 🤔 发消息过后弹出一个空白弹窗，然后显示正在验证，最后就变成了很抱歉，让我们重新开始吧

### ISSUE THREAD

**Issue by landones** [Harry-zklcdc/go-proxy-bingai#250]
### Describe the help wanted

![1](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/67811286/2fb98f5a-0907-446b-b56e-6a850443df7f)
如图，弹出一个空白窗口，然后显示正在验证，然后瞬间就变成了很抱歉，让我们重新开始吧

### Steps to behave

正常复制各种数据，然后发消息

### Expected behavior

正常使用，或者搞明白自己到底哪里没搞对

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by SokWith** [comment]
不看wiki，你们会累死大佬的

**Comment by landones** [comment]
> 不看wiki，你们会累死大佬的

我看了wiki来着……用微软虚拟机通过人机验证，我用虚拟机发了消息但没出现验证窗口，而且不是更新自动通过人机验证了吗？一直都用不了。

**Comment by SokWith** [comment]
> > 不看wiki，你们会累死大佬的
> 
> 我看了wiki来着……用微软虚拟机通过人机验证，我用虚拟机发了消息但没出现验证窗口，而且不是更新自动通过人机验证了吗？一直都用不了。

现在还没有自动过验证，那个自动是让程序去过验证不用手工去官网验证，仍然需要手动去输入cookie并点击验证。
你要是没有帐号，想匿名使用，得拼人品，不是每次都成功的，也不是每个部署都可以的。

**Comment by dandandujie** [comment]
我输入了官网的cookie，但是点击自动验证还是一直转圈圈没反应，关掉页面重来也没有用

**Comment by SokWith** [comment]
> 我输入了官网的cookie，但是点击自动验证还是一直转圈圈没反应，关掉页面重来也没有用

自动验证还没有完善，用的是大佬的单点部署，容易出故障。
要验证帐号，目前还是去官网保险一些。当然，现在梯子也多，能部署的都能找到吧。

**Comment by b1ghawk** [comment]
> > > 不看wiki，你们会累死大佬的
> > 
> > 
> > 我看了wiki来着……用微软虚拟机通过人机验证，我用虚拟机发了消息但没出现验证窗口，而且不是更新自动通过人机验证了吗？一直都用不了。
> 
> 现在还没有自动过验证，那个自动是让程序去过验证不用手工去官网验证，仍然需要手动去输入cookie并点击验证。 你要是没有帐号，想匿名使用，得拼人品，不是每次都成功的，也不是每个部署都可以的。

不晓得为啥，我使用这个自动过验证，没有任何效果。

**Comment by SokWith** [comment]
> > > > 不看wiki，你们会累死大佬的
> > > 
> > > 
> > > 我看了wiki来着……用微软虚拟机通过人机验证，我用虚拟机发了消息但没出现验证窗口，而且不是更新自动通过人机验证了吗？一直都用不了。
> > 
> > 
> > 现在还没有自动过验证，那个自动是让程序去过验证不用手工去官网验证，仍然需要手动去输入cookie并点击验证。 你要是没有帐号，想匿名使用，得拼人品，不是每次都成功的，也不是每个部署都可以的。
> 
> 不晓得为啥，我使用这个自动过验证，没有任何效果。

我也只第一次成功过，后面就不行了。还是modheader方便些。

**Comment by Nothingness-Void** [comment]
你是部署在谁家的机器上啊

**Comment by Harry-zklcdc** [comment]
> 不晓得为啥，我使用这个自动过验证，没有任何效果。

再试试，之前服务器是部署在我的笔记本上，不太稳定，现在迁移了

**Comment by Harry-zklcdc** [comment]
> 现在还没有自动过验证，那个自动是让程序去过验证不用手工去官网验证，仍然需要手动去输入cookie并点击验证。 你要是没有帐号，想匿名使用，得拼人品，不是每次都成功的，也不是每个部署都可以的。

你别瞎说，我开发这个的目的就是为了人机验证，也就是为了无论是否登录账号都能使用，现在纯cfwk部署不就可以免登使用了？请理解后再发表言论，谢谢

**Comment by landones** [comment]
> > 现在还没有自动过验证，那个自动是让程序去过验证不用手工去官网验证，仍然需要手动去输入cookie并点击验证。 你要是没有帐号，想匿名使用，得拼人品，不是每次都成功的，也不是每个部署都可以的。
> 
> 你别瞎说，我开发这个的目的就是为了人机验证，也就是为了**无论是否登录账号**都能使用
> 
> 现在纯cf worker部署不就可以免登使用了？在你不登录的时候，直接点击验证，验证通过之后就可以免登使用了
> 
> 触发人机验证的机制我也基本上摸清了，就在`create ConversationID`的这一步。在这一步的时候，如果你的IP、Cookie、请求头等**信息可疑**，就会**被标记**需要人机验证，然后在 `Sydney ChatHub` 的时候返回需要人机验证，然后触发人机验证流程
> 
> 请理解后再发表言论，谢谢

所以我也不知道自己出什么错了，是我的账号被微软发现了吗？我使用微软虚拟机登陆账号以后发送消息给newbing过后成功获得了回复，但并没有弹出验证界面。然后我使用自己的cookie在项目上进行聊天时会弹出一个空白窗口，然后显示“验证中”，这个字只会出现一瞬间，然后项目就会出错，出现“很抱歉，让我们重新开始”，真是让人百思不得其解。希望大佬能在百忙中抽出一点时间回复我，帮助我解决这个问题。

**Comment by Harry-zklcdc** [comment]
> 所以我也不知道自己出什么错了，是我的账号被微软发现了吗？我使用微软虚拟机登陆账号以后发送消息给newbing过后成功获得了回复，但并没有弹出验证界面。然后我使用自己的cookie在项目上进行聊天时会弹出一个空白窗口，然后显示“验证中”，这个字只会出现一瞬间，然后项目就会出错，出现“很抱歉，让我们重新开始”，真是让人百思不得其解。希望大佬能在百忙中抽出一点时间回复我，帮助我解决这个问题。

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/b70eb9eb-8d0e-4699-b3c8-8ea63464ea4f)

**Comment by Nothingness-Void** [comment]
> > > 不看wiki，你们会累死大佬的
> > 
> > 
> > 我看了wiki来着……用微软虚拟机通过人机验证，我用虚拟机发了消息但没出现验证窗口，而且不是更新自动通过人机验证了吗？一直都用不了。
> 
> 现在还没有自动过验证，那个自动是让程序去过验证不用手工去官网验证，仍然需要手动去输入cookie并点击验证。 你要是没有帐号，想匿名使用，得拼人品，不是每次都成功的，也不是每个部署都可以的。

我现在部署就是匿名使用，稳定得很 主要看你ip干净不

**Comment by b1ghawk** [comment]
@Harry-zklcdc 

是这样的情况，没有成功…

https://github.com/Harry-zklcdc/go-proxy-bingai/assets/30652540/ba6daba3-1b29-4e78-9ade-cbb1da7781f7

**Comment by Harry-zklcdc** [comment]
> @Harry-zklcdc
> 
> 是这样的情况，没有成功…
> 
> https://bing.b1ghawk.xyz/
> 
>  lv_0_20231102193659.mp4

你这是部署在哪的？可能和人机验证的出口IP有关系

**Comment by Harry-zklcdc** [comment]
那说明可能有新的检测方式了

**Comment by SokWith** [comment]
> > 现在还没有自动过验证，那个自动是让程序去过验证不用手工去官网验证，仍然需要手动去输入cookie并点击验证。 你要是没有帐号，想匿名使用，得拼人品，不是每次都成功的，也不是每个部署都可以的。
> 
> 你别瞎说，我开发这个的目的就是为了人机验证，也就是为了**无论是否登录账号**都能使用
> 
> 现在纯cf worker部署不就可以免登使用了？在你不登录的时候，直接点击验证，验证通过之后就可以免登使用了
> 
> 触发人机验证的机制我也基本上摸清了，就在`create ConversationID`的这一步。在这一步的时候，如果你的IP、Cookie、请求头等**信息可疑**，就会**被标记**需要人机验证，然后在 `Sydney ChatHub` 的时候返回需要人机验证，然后触发人机验证流程
> 
> 请理解后再发表言论，谢谢

可能是我表达得不够清晰让你误解了。
我们理解的自动，其根本的含义就是无需人为干预，开箱即用，如果需要认证了，程序自动跳出来干预自动认证，就如同直接使用官网一样。
这里的自动，是得手动去启动认证，只是这个认证的过程是自动的。所以其实是不能算自动过认证的，改成手动过认证可能会减少许多歧义。

**Comment by b1ghawk** [comment]
> > @Harry-zklcdc
> > 
> > 是这样的情况，没有成功…
> > 
> > https://bing.b1ghawk.xyz/
> > 
> >  lv_0_20231102193659.mp4
> 
> 你这是部署在哪的？可能和人机验证的出口IP有关系

在cloudflare worker上的，纯cf部署。

**Comment by SokWith** [comment]
> > > > 不看wiki，你们会累死大佬的
> > > 
> > > 
> > > 我看了wiki来着……用微软虚拟机通过人机验证，我用虚拟机发了消息但没出现验证窗口，而且不是更新自动通过人机验证了吗？一直都用不了。
> > 
> > 
> > 现在还没有自动过验证，那个自动是让程序去过验证不用手工去官网验证，仍然需要手动去输入cookie并点击验证。 你要是没有帐号，想匿名使用，得拼人品，不是每次都成功的，也不是每个部署都可以的。
> 
> 我现在部署就是匿名使用，稳定得很 主要看你ip干净不

通过云部署就几乎没有什么干净的ip了。
今天上午我还能通过部署在render上的ws反代实现匿名使用，下午就给封了。
create使用的replit，replit使用本站服务器早就不能匿名了，但当时通过render的ws就可以，所以

**Comment by Harry-zklcdc** [comment]
> 在cloudflare worker上的，纯cf部署。 登录和不登录都测试过，之前这个版本刚发布我就试过(就是前几天的事)，和今天的结果一样，还是会跳验证。

纯CF部署有问题，我忘了更新 `worker.js` 的代码了，现在Cloudflare的控制台进不去，等能进去了我再测试更新

**Comment by Nothingness-Void** [comment]
> > > @Harry-zklcdc
> > > 是这样的情况，没有成功…
> > > https://bing.b1ghawk.xyz/
> > > lv_0_20231102193659.mp4
> > 
> > 
> > 你这是部署在哪的？可能和人机验证的出口IP有关系
> 
> 在cloudflare worker上的，纯cf部署。 登录和不登录都测试过，之前这个版本刚发布我就试过(就是前几天的事)，和今天的结果一样，还是会跳验证。

https://bing-sgp2.nothingnessvoid.top/  你用我搭的这个试试 应该能过

**Comment by b1ghawk** [comment]
> > > > @Harry-zklcdc
> > > > 是这样的情况，没有成功…
> > > > https://bing.b1ghawk.xyz/
> > > > lv_0_20231102193659.mp4
> > > 
> > > 
> > > 你这是部署在哪的？可能和人机验证的出口IP有关系
> > 
> > 在cloudflare worker上的，纯cf部署。 登录和不登录都测试过，之前这个版本刚发布我就试过(就是前几天的事)，和今天的结果一样，还是会跳验证。
> 
> https://bing-sgp2.nothingnessvoid.top/  你用我搭的这个试试 应该能过

emm..你这个我测不出来，因为我一打开就没有跳验证。

我指的是服务器被要求验证的情况下，点击一下设置里的那个过验证按钮，然后刷新页面就不会继续跳验证了。我指的是这种情况。

**Comment by hk1996yhx** [comment]
那个自动验证的虽然验证失败,但是去官网手动验证一条之后就能用了

**Comment by luckyEason** [comment]
IP够纯洁就不会跳验证，但只是匿名的情况，登录后大概率跳验证，并且无法通过

**Comment by Harry-zklcdc** [comment]
> 那个自动验证的虽然验证失败,但是去官网手动验证一条之后就能用了

自动验证还是不行嘛？

**Comment by SokWith** [comment]
> > 那个自动验证的虽然验证失败,但是去官网手动验证一条之后就能用了
> 
> 自动验证还是不行嘛？

除了第一次，后面都没有再成功过了

**Comment by jsdianman** [comment]
> > > 那个自动验证的虽然验证失败,但是去官网手动验证一条之后就能用了
> 
> > 
> 
> > 自动验证还是不行嘛？
> 
> 
> 
> 除了第一次，后面都没有再成功过了

你至少成功过，我一次都没成功，不管匿名还是登录，验证全部失败。不管是自己搭建的，还是Harry搭建的

**Comment by SokWith** [comment]
> > > > 那个自动验证的虽然验证失败,但是去官网手动验证一条之后就能用了
> > 
> > 
> > > 
> > 
> > 
> > > 自动验证还是不行嘛？
> > 
> > 
> > 除了第一次，后面都没有再成功过了
> 
> 你至少成功过，我一次都没成功，不管匿名还是登录，验证全部失败。不管是自己搭建的，还是Harry搭建的

还是modheader大法好用一些，暂时不折腾验证的事了

**Comment by Harry-zklcdc** [comment]
> 你至少成功过，我一次都没成功，不管匿名还是登录，验证全部失败。不管是自己搭建的，还是Harry搭建的

你再试试，我测试了一下API是没问题的，而且之前的验证机制应该是修改了，现在是双重验证，意思就是请求 `create ConversationID` 的时候，会检测Cookie；然后在 `ChatHub` 的时候，也换有Cookie、IP等检测

**Comment by b1ghawk** [comment]
> > 你至少成功过，我一次都没成功，不管匿名还是登录，验证全部失败。不管是自己搭建的，还是Harry搭建的
> 
> 你再试试，我测试了一下API是没问题的，而且之前的验证机制应该是修改了，现在是双重验证，意思就是请求 `create ConversationID` 的时候，会检测Cookie；然后在 `ChatHub` 的时候，也会有Cookie、IP等检测

我这里遇到了一样的问题。

**Comment by Harry-zklcdc** [comment]
已解决
