### ISSUE TITLE
[Featrue] 🎉 自动人机验证 / 解决无效域

### ISSUE THREAD

**Issue by Harry-zklcdc** [Harry-zklcdc/go-proxy-bingai#251]
人机验证服务器仓库: https://github.com/Harry-zklcdc/go-bingai-pass

代码不开源，并且已混淆加密

### **希望有能力的大佬请不要破解，为该方法多续一会命，谢谢**

部署示例仓库: https://huggingface.co/spaces/zklcdc/go-bingai-pass

**Comment by Nothingness-Void** [comment]
感谢大佬默默付出 想问一下这个验证服务器对ip有要求吗（用azure部署） 还是随便找个服务器/容器就能部署

**Comment by Harry-zklcdc** [comment]
> 感谢大佬默默付出 想问一下这个验证服务器对ip有要求吗（用azure部署） 还是随便找个服务器/容器就能部署

对出口IP有要求，不然过不了Cloudflare的人机验证。

IP在各大机房的话会出现无论如何都人机验证失败的情况

至于隐藏IP，我就不说我怎么做的了

**Comment by s181462537** [comment]
坐等大佬发布教程

**Comment by SokWith** [comment]
> 还是无效域了……出口IP是指哪个IP？

应该是最后一步发起连接www.bing.com/turing/*的那个ip。

顺道问一下， @Harry-zklcdc 可不可以在部署里面再添加全局代理？

**Comment by SokWith** [comment]
另外一个思路
https://github.com/Harry-zklcdc/go-proxy-bingai/issues/263#issuecomment-1826357465

**Comment by Harry-zklcdc** [comment]
> 另外一个思路 [#263 (comment)](https://github.com/Harry-zklcdc/go-proxy-bingai/issues/263#issuecomment-1826357465)

这种没意义，等于多步代理了

**Comment by SokWith** [comment]
> > 另外一个思路 [#263 (comment)](https://github.com/Harry-zklcdc/go-proxy-bingai/issues/263#issuecomment-1826357465)
> 
> 这种没意义，等于多步代理了

确实是套娃，只是套了一下后改变了出口IP，特别是针对cf的调用。上次就发现不同的网络调用cf的服务器有不同的反馈。

**Comment by SokWith** [comment]
不过，都在传下周微软就开放了，应该就没有IP锁了吧?BING_PROXY代理服务器就没有必要了吧？

**Comment by qinguoluo** [comment]
什么时候出教程哟

**Comment by SokWith** [comment]
> 什么时候出教程哟

全自动过验证的方法在这儿 https://github.com/Harry-zklcdc/go-proxy-bingai/issues/267#issue-2014528769
