### ISSUE TITLE
[Bug] 🐛 本站提供的服务不可用

### ISSUE THREAD

**Issue by internettrollwatt** [Harry-zklcdc/go-proxy-bingai#252]
### Describe the bug

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/125249612/8b2ad45b-cfb7-4691-a14d-7ae19deab1a9)
本站提供的服务不可用

### Steps to reproduce

今天晚间我打开作者分享在该项目的主页的链接后发现链接有所变化，且出现了如上图所示的本站提供的服务不可用的现象

### Expected behavior

本站提供的服务可用

### Versions

Microsoft Edge
版本 119.0.2151.44 (正式版本) stable应用，beta频道 (64 位)

**Comment by luckyEason** [comment]
延迟过高会显示不可用，实际上还是可以聊天的

**Comment by SokWith** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/6a4579c3-e847-485f-a765-1075c9d3f586)
看上去似乎是ip被上锁了。

**Comment by Harry-zklcdc** [comment]
我修复了，清除一下浏览器缓存
