### ISSUE TITLE
必应限制貌似又加强了

### ISSUE THREAD

**Issue by luckyEason** [Harry-zklcdc/go-proxy-bingai#255]
现在这个项目和bingo都用不了了

**Comment by Harry-zklcdc** [comment]
有空我更新一下

**Comment by luckyEason** [comment]
> API没有更新，只是封控加严了，但还不是最严的时候。
> 
> 10月之前最严的封控是：
> 
> 1、转发ip大都上锁，所以后来倚靠限制在微软云的ip里面才规避了。现在转发ip基本没有限制了；
> 
> 2、除cf外各大云服务商的ip全部上锁，表现为完全不能create；现在对ip的create基本没有限制，限制的是下一条：
> 
> 3、每个匿名的IP/MUID限制会话次数；（现在大约就是这个样子），所以一旦匿名站点被公布出来大家访问多了，很快就不能create了。
> 
> 现在新增的封控主要有：
> 
> 1、wss增加了跨域限制；
> 
> 2、wss同create一样增加了匿名IP/MUID封控；
> 
> 所以现在匿名访问很困难，bingo由于不好处理cookie主打匿名使用造成绝大多数站点都打不开，但它也可以使用本项目的服务器。我测试域里面的测试站点目前可用，用的就是本项目部署在cf上的服务器。bingo项目存在的意义在于它提供了其他客户端调用的API。

雀食，又可以用了😀

**Comment by renqabs** [comment]
> 现在这个项目和bingo都用不了了

bingo部分代码需要注释掉，据作者说这部分代码是用于他的演示站的，自行部署的话得注释掉，不然的话，好像只能API调用
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/130155002/2b5cd023-da7e-407a-88a3-626b8f7b3455)

**Comment by luckyEason** [comment]
> > 现在这个项目和bingo都用不了了
> 
> 
> 
> bingo部分代码需要注释掉，据作者说这部分代码是用于他的演示站的，自行部署的话得注释掉，不然的话，好像只能API调用
> 
> ![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/130155002/2b5cd023-da7e-407a-88a3-626b8f7b3455)
> 
> 

他的演示站也不能用

**Comment by SokWith** [comment]
> > > 现在这个项目和bingo都用不了了
> > 
> > 
> > bingo部分代码需要注释掉，据作者说这部分代码是用于他的演示站的，自行部署的话得注释掉，不然的话，好像只能API调用
> > ![image](https://user-images.githubusercontent.com/130155002/281583730-2b5cd023-da7e-407a-88a3-626b8f7b3455.png)
> 
> 他的演示站也不能用

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/ed928f05-8fbf-494d-8674-6cd9a9f51b1c)
这个效果还行吧！
这个后台使用的是bingo在replit上的编译部署，这个编译部署的wss服务器又是用的本项目在huggingface上的部署。
这个折腾原因是：
bingo可以提供标准的chatGPT的API，但是这个API的wss服务器要求必须能匿名访问。

**Comment by SokWith** [comment]
唉，总觉得项目被监控了，每次一说出来就活不过3天。感觉目前对create锁ip非常严重了，目前公开了的匿名VPS似乎都锁了，huggingface也需要靠人品。

最终，还是cf扛下了所有，cf虽然不能匿名，但用登录ID还是一直都比较稳健。说在这儿，就是看看cf也会不会被锁。

**Comment by b1ghawk** [comment]
> 唉，总觉得项目被监控了，每次一说出来就活不过3天。感觉目前对create锁ip非常严重了，目前公开了的匿名VPS似乎都锁了，huggingface也需要靠人品。
> 
> 最终，还是cf扛下了所有，cf虽然不能匿名，但用登录ID还是一直都比较稳健。说在这儿，就是看看cf也会不会被锁。

CF很稳啊。。。
https://bingface.b1ghawk.xyz

**Comment by SokWith** [comment]
> > 唉，总觉得项目被监控了，每次一说出来就活不过3天。感觉目前对create锁ip非常严重了，目前公开了的匿名VPS似乎都锁了，huggingface也需要靠人品。
> > 最终，还是cf扛下了所有，cf虽然不能匿名，但用登录ID还是一直都比较稳健。说在这儿，就是看看cf也会不会被锁。
> 
> CF匿名很稳啊。。。 https://bingface.b1ghawk.xyz

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/f37ac0fb-d555-4566-a4a3-f9efd1760cf1)

败人品啊败人品，访问你的站点和我的站点，ip地址有点差距

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/15a80a2d-f8bb-416a-b331-7ce4c7355385)

**Comment by SokWith** [comment]
> 唉，总觉得项目被监控了，每次一说出来就活不过3天。感觉目前对create锁ip非常严重了，目前公开了的匿名VPS似乎都锁了，huggingface也需要靠人品。
> 
> 最终，还是cf扛下了所有，cf虽然不能匿名，但用登录ID还是一直都比较稳健。说在这儿，就是看看cf也会不会被锁。

今日似乎cf也被锁了，采用cf的vle机场都不能匿名访问官网了
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/1ae20a6d-d42c-428d-9581-6c4084d47552)

**Comment by jsdianman** [comment]
> > 唉，总觉得项目被监控了，每次一说出来就活不过3天。感觉目前对create锁ip非常严重了，目前公开了的匿名VPS似乎都锁了，huggingface也需要靠人品。
> 
> > 
> 
> > 最终，还是cf扛下了所有，cf虽然不能匿名，但用登录ID还是一直都比较稳健。说在这儿，就是看看cf也会不会被锁。
> 
> 
> 
> 今日似乎cf也被锁了，采用cf的vle机场都不能匿名访问官网了
> 
> ![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/1ae20a6d-d42c-428d-9581-6c4084d47552)
> 
> 

中午用很稳啊，登了账号，可以用插件

**Comment by SokWith** [comment]
> > > 唉，总觉得项目被监控了，每次一说出来就活不过3天。感觉目前对create锁ip非常严重了，目前公开了的匿名VPS似乎都锁了，huggingface也需要靠人品。
> > 
> > 
> > > 
> > 
> > 
> > > 最终，还是cf扛下了所有，cf虽然不能匿名，但用登录ID还是一直都比较稳健。说在这儿，就是看看cf也会不会被锁。
> > 
> > 
> > 今日似乎cf也被锁了，采用cf的vle机场都不能匿名访问官网了
> > ![image](https://user-images.githubusercontent.com/129967025/282222140-1ae20a6d-d42c-428d-9581-6c4084d47552.png)
> 
> 中午用很稳啊，登了账号，可以用插件

登账号是可以的，匿名就无限create了

**Comment by jsdianman** [comment]
> > > > 唉，总觉得项目被监控了，每次一说出来就活不过3天。感觉目前对create锁ip非常严重了，目前公开了的匿名VPS似乎都锁了，huggingface也需要靠人品。
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 最终，还是cf扛下了所有，cf虽然不能匿名，但用登录ID还是一直都比较稳健。说在这儿，就是看看cf也会不会被锁。
> > > 
> > > 
> > > 今日似乎cf也被锁了，采用cf的vle机场都不能匿名访问官网了
> > > ![image](https://user-images.githubusercontent.com/129967025/282222140-1ae20a6d-d42c-428d-9581-6c4084d47552.png)
> > 
> > 
> > 中午用很稳啊，登了账号，可以用插件
> 
> 登账号是可以的，匿名就无限create了

雀食，但配上Whistle就很nice，除了好像没法直接登录
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/143573972/15edf1cf-3013-4c0e-9edc-21af4ae5fae3)
没有提前过人机验证，但edge可以，chrome不行

**Comment by Harry-zklcdc** [comment]
限制肯定会越来越强的，而且会越来越难搞

**Comment by SokWith** [comment]
> 限制肯定会越来越强的，而且会越来越难搞

他们总得挤牙膏吧？至少为了保住岗位

**Comment by luckyEason** [comment]
现在限制的方式貌似和以前不一样，现在同账号，不同IP，一个IP要验证，一个不用

**Comment by SokWith** [comment]
huggingface的间歇性障碍是越来越强了，匿名的羊毛不好薅了

**Comment by renqabs** [comment]
> huggingface的间歇性障碍是越来越强了，匿名的羊毛不好薅了 ![image](https://user-images.githubusercontent.com/129967025/283447653-e93b2c07-8c34-4202-97b8-f227b48aa06b.png) 白天一整天都不行，现在才活过来

以前上午多重启几次也就好了，现在上午基本上是废掉的状态，重启也不管用了
