### ISSUE TITLE
新的人机验证我已经在docker部署好了，点击自动人机验证也可以通过，但是发起对话还是一直人机验证

### ISSUE THREAD

**Issue by B1gCarr0t** [Harry-zklcdc/go-proxy-bingai#256]
这可如何是好啊，大哥

**Comment by B1gCarr0t** [comment]
我在容器云、vps、cloudflare都部署了，都是一样的情况

**Comment by Harry-zklcdc** [comment]
有空我更新一下，感觉是又有新的人机验证机制了

**Comment by lushangkan** [comment]
> 有空我研究一下，感觉是又有新的人机验证机制了

似乎bing使用了硬件ID，同一IP下(Cloudflare WARP)经常使用的电脑被送中，无论换什么ip浏览器都不行，而另一台设备则是正常的国际版bing

**Comment by Harry-zklcdc** [comment]
已解决
