### ISSUE TITLE
[Feature] 🌈 支持插件

### ISSUE THREAD

**Issue by litongjava** [Harry-zklcdc/go-proxy-bingai#257]
### Describe the problem related to the feature request

<img width="1079" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/31761981/9ada1683-0b0b-489e-bc61-319a5601f865">

最新版本已经支持插件,请速度支持

### Describe the solution you'd like

最新版本已经支持插件,请速度支持

**Comment by luckyEason** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/109937362/25c54b94-56c7-4e8e-839e-5588a96e2dd3)
其实有了，但是应该不能匿名
