### ISSUE TITLE
[Feature] 🌈支持插件系统

### ISSUE THREAD

**Issue by jsdianman** [Harry-zklcdc/go-proxy-bingai#258]
### Describe the problem related to the feature request

官网已向已登录账号开放插件系统，可以禁用搜索，希望本项目支持

### Describe the solution you'd like

支持插件系统

**Comment by Harry-zklcdc** [comment]
好的，过段时间吧，这段时间比较忙

**Comment by Harry-zklcdc** [comment]
已支持

**Comment by jsdianman** [comment]
> 已支持

牛👍如果能适配苹果设备就更好了，现在iPad要启用只能用英文true，还要开缩放才能显示完整列表
