### ISSUE TITLE
[Feature] 🌈 能否增加转成openai格式 api功能

### ISSUE THREAD

**Issue by Nothingness-Void** [Harry-zklcdc/go-proxy-bingai#259]
### Describe the problem related to the feature request

https://github.com/weaigc/bingo 这个项目有能够将bing转成api格式供第三方服务调用
但是部署没有本项目方便 不知能否跟进

### Describe the solution you'd like

增加外部api调用

**Comment by SokWith** [comment]
我的理解，这个项目的主要功能就是一个代理，搬运的是官网的API。要编写一个新的API，相当于另外再建一套代码。
君子善假于物，直接用隔壁的API就可以了。只要本项目可用，就可以当做隔壁bingo的create/wss服务器，反正做后端API用，它的前端就可以随便部署了。

**Comment by Harry-zklcdc** [comment]
暂不考虑，有空开发

**Comment by Harry-zklcdc** [comment]
Golang 的 NewBing 库我写好了，什么时候整合过来这边就行了

https://github.com/Harry-zklcdc/bing-lib
