### ISSUE TITLE
报错，显示让我们重新开始吧

### ISSUE THREAD

**Issue by zhyawy** [Harry-zklcdc/go-proxy-bingai#26]
![1690123833323](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/92937939/45585ade-1dd6-4efa-a4d5-a71327a8005c)
![1690123843082](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/92937939/05f35ac5-c67f-48a6-a909-d042a74d6b73)

**Comment by Stonewalling** [comment]
貌似代理都不行了

**Comment by Harry-zklcdc** [comment]
国内VPS要挂代理

**Comment by zhyawy** [comment]
我是本地部署的，也挂了梯子，还是显示这个

**Comment by Harry-zklcdc** [comment]
> 我是本地部署的，也挂了梯子，还是显示这个

请使用环境变量配置s5代理
