### ISSUE TITLE
[Help] 🤔 在docker部署后就一直在加载，进不去主页

### ISSUE THREAD

**Issue by KhashzM** [Harry-zklcdc/go-proxy-bingai#261]
### Describe the help wanted

一直在加载，不管是换网络还是换设备，重启，都是这样。重新部署之后也还是这样

### Steps to behave

.

### Expected behavior

.

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/97164526/3213141c-a63d-4752-889e-533de7228cae)

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by jsdianman** [comment]
有用443吗

**Comment by KhashzM** [comment]
> 有用443吗

用的8080

**Comment by jsdianman** [comment]
> > 有用443吗
> 
> 
> 
> 用的8080

必须443，不然打不开

**Comment by lingyust** [comment]
> > > 有用443吗
> > 
> > 
> > 用的8080
> 
> 必须443，不然打不开

8080可以打开的，反代设置使用ssl，问题是现在都打开了，cookies也都导入了，但是不能用了
