### ISSUE TITLE
[Bug]🐛插件系统显示问题

### ISSUE THREAD

**Issue by jsdianman** [Harry-zklcdc/go-proxy-bingai#262]
### Describe the bug

不开缩放时，插件系统只能显示前几个，不能向下滚动。以及Safari的UI有点问题

### Steps to reproduce

正常使用，只能显示前三个插件

### Expected behavior

修复这个bug

### Screenshots
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/143573972/5f2673b1-47c2-45b2-97f6-c9c6232decfc)

_No response_

### Versions

- OS: Windows 11
- Browser & Version: Chrome 119
- GoProxiBing Version: 1.17.0
以及
- OS: iPadOS17
- Browser & Version: Safari
- GoProxiBing Version: 1.17.0

**Comment by MEMZ-FYS** [comment]
确实不能用

**Comment by shadow-550w** [comment]
华为平板横屏只能看到前两个插件，但
![Uploading Screenshot_20231123_230134_com.huawei.browser.jpg…]()
![Uploading Screenshot_20231123_230139_com.huawei.browser.jpg…]()
竖屏可以看到所有插件，不知道电脑怎么样

**Comment by shadow-550w** [comment]
华为平板开启访问电脑版，横屏也只能看到前两个插件，但是竖屏可以看到全部插件，不知道电脑怎么样
![Uploading Screenshot_20231123_230139_com.huawei.browser.jpg…]()

**Comment by shadow-550w** [comment]
华为平板开启访问电脑版，横屏也只能看到前两个插件，但是竖屏可以看到全部插件，不知道电脑怎么样
![Uploading Screenshot_20231123_230139_com.huawei.browser.jpg…]()
![Uploading Screenshot_20231123_230134_com.huawei.browser.jpg…]()

**Comment by Harry-zklcdc** [comment]
已修复
