### ISSUE TITLE
[Help] 🤔 我在huggingface上部署的，无法进行人机验证

### ISSUE THREAD

**Issue by ryanzhaorx** [Harry-zklcdc/go-proxy-bingai#263]
### Describe the help wanted

我在 huggingface 上部署的无法完成人机验证，提示错误

### Steps to behave

我点击设置-自动人机验证的启动
过了一会儿显示错误
我的浏览器是Chrome 119.0.6045.159

### Expected behavior

如何成功的完成人机自动验证?

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by jsdianman** [comment]
也许你不知道，自动过人机验证早报废了

**Comment by SokWith** [comment]
欢迎使用我的测试域，https://nbing.eu.org
另外一个大佬给的代码，不要问我要，但是有惊喜

**Comment by jsdianman** [comment]
> 欢迎使用我的测试域，https://nbing.eu.org
> 
> 另外一个大佬给的代码，不要问我要，但是有惊喜
> 
> 
> 
> PS:只需要填cookie就可以了，不要点击启动

不能用

**Comment by SokWith** [comment]
> > 欢迎使用我的测试域，https://nbing.eu.org
> > 另外一个大佬给的代码，不要问我要，但是有惊喜
> > PS:只需要填cookie就可以了，不要点击启动
> 
> 不能用

![Screenshot_2023-11-25-10-24-22-882](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/733407f9-7d9e-4705-bb45-175af391460a)
刚刚手机上匿名使用

**Comment by jsdianman** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/143573972/2194256d-7d07-4af2-9977-c3b58b66654b)那就是我自己的网络问题了

**Comment by SokWith** [comment]
本站不可用有时候是假象，进入聊天后会自动多try几次的

**Comment by luckyEason** [comment]
@SokWith 能解释一下是如何实现的吗

**Comment by SokWith** [comment]
> @SokWith 能解释一下是如何实现的吗

机理不清楚，我也是找大佬要的代码抄上去的。似乎只有一种方式部署才有效。

**Comment by jsdianman** [comment]
> > @SokWith 能解释一下是如何实现的吗
> 
> 机理不清楚，我也是找大佬要的代码抄上去的。似乎只有一种方式部署才有效。
> 
> 部署方式我在测试域页面已说明了，不能在这里多说，怕被监视了
 看了一下你的代码，告诉你为什么编译出错吧
单引号只能包含一个字符，例如’b’ ,程序会输出98表示字符b的ascii码。

**Comment by SokWith** [comment]
> > > @SokWith 能解释一下是如何实现的吗
> > 
> > 
> > 机理不清楚，我也是找大佬要的代码抄上去的。似乎只有一种方式部署才有效。
> > 部署方式我在测试域页面已说明了，不能在这里多说，怕被监视了
> 
> 看了一下你的代码，告诉你为什么编译出错吧 单引号只能包含一个字符，例如’b’ ,程序会输出98表示字符b的ascii码。

我仓库里面的代码吗？我是代码小白，都是在里面瞎改的，大都没有去验证

**Comment by SokWith** [comment]
在huggingface上部署的后台wss还是1.16.4的版本

**Comment by jsdianman** [comment]
没发现每次都编译失败吗😂![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/143573972/3cb54f1c-aaec-43c9-9187-f8e3646a5edd)

**Comment by SokWith** [comment]
> 没发现每次都编译失败吗😂![image](https://private-user-images.githubusercontent.com/143573972/285565750-3cb54f1c-aaec-43c9-9187-f8e3646a5edd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4ODg1OTAsIm5iZiI6MTcwMDg4ODI5MCwicGF0aCI6Ii8xNDM1NzM5NzIvMjg1NTY1NzUwLTNjYjU0ZjFjLWFhZWMtNDNjOS05MTg3LWY4ZTM2NDZhNWVkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNVQwNDU4MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDc0YzdhMDI2MDVjMTE4MWI0NGUzNTM2NjAzZjkzNTczODczYzY0NmY1Y2RmMzM1YzA1M2M1YjRmMGFlMWUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iRUFoJe7E62IsuyuCWBDAiPrQHUNYgv_zf2OcAAaPDA)

我没注意到，是SRCHHPGUSR添加项吧？谢谢。主要是没有关心vercel上的结果，改配置主要是给cf提供前端页面选项

**Comment by SokWith** [comment]
由于我没有安装git，不能更新编译后的web代码，就给大家提供一个docker：
```
FROM jokyo3/probingai:v1.18.3
#ENV BING_PROXY_DM="https://cfree.nbing.eu.org"
#ENV SYDNEY_PROXY_DM="https://sokwith-nbing.hf.space"
#ENV Go_Proxy_BingAI_USER_TOKEN_1="ASDFGHJKLASDFQWERTVFRVDFBCBVXCXB"
ENV PORT 7860
EXPOSE 7860
CMD ["/app/go-proxy-bingai"]
```
新增了两个环境变量，见上面代码注释；
v1.18.3的docker版本内置了上面两个环境变量对应的服务器，采用这版docker会直接使用内置的服务器，速度会很慢。
v1.18.2的docker版本没有内置代理服务器，默认为官方的，所以就不能直接过验证。可以在环境变量中设置代理服务器。(但是，对能够过验证的BING_PROXY_DM服务器有特别的搭建要求，由于是别的大神的代码请原谅我不能提供。)如果不打算过验证只匿名使用，设置一个没有被封ip的BING_PROXY_DM可以规避不断create。

docker的源代码在这个仓库里：
https://github.com/jokyo3/probingai
原谅我是代码小白，反复折腾把仓库改得一团糟，其实最后就是加了个代理。

使用v1.18.3版docker的部署实例见：
https://sokwith-gobingai.hf.space
https://zby.zeabur.app

@Harry-zklcdc 不好意思哈，我直接把本版升到了v1.18了

**Comment by luckyEason** [comment]
> 由于我没有安装git，不能更新编译后的web代码，就给大家提供一个docker：
> 
> ```
> 
> FROM jokyo3/probingai:v1.18.3
> 
> #ENV BING_PROXY_DM="https://cfree.nbing.eu.org"
> 
> #ENV SYDNEY_PROXY_DM="https://sokwith-nbing.hf.space"
> 
> #ENV Go_Proxy_BingAI_USER_TOKEN_1="ASDFGHJKLASDFQWERTVFRVDFBCBVXCXB"
> 
> ENV PORT 7860
> 
> EXPOSE 7860
> 
> CMD ["/app/go-proxy-bingai"]
> 
> ```
> 
> 新增了两个环境变量，见上面代码注释；
> 
> v1.18.3的docker版本内置了上面两个环境变量对应的服务器，采用这版docker会直接使用内置的服务器，速度会很慢。当然，也可以自定义的。
> 
> v1.18.2的docker版本没有内置代理服务器，默认为官方的，所以就不能直接过验证。可以在环境变量中设置代理服务器。(但是，对能够过验证的BING_PROXY_DM服务器有特别的搭建要求，由于是别的大神的代码请原谅我不能提供。)如果不打算过验证只匿名使用，设置一个没有被封ip的BING_PROXY_DM可以规避不断create。
> 
> 
> 
> docker的源代码在这个仓库里：
> 
> https://github.com/jokyo3/probingai
> 
> 原谅我是代码小白，反复折腾把仓库改得一团糟，其实最后就是加了个代理。
> 
> 
> 
> 使用v1.18.3版docker的部署实例见：
> 
> https://sokwith-gobingai.hf.space
> 
> https://zby.zeabur.app  （ps：白嫖的站点随时会被删除）
> 
> 
> 
> @Harry-zklcdc 不好意思哈，我直接把版本升到了v1.18了

直接用gitpod不就行了吗😂或者我有空帮你编译

**Comment by SokWith** [comment]
> > 由于我没有安装git，不能更新编译后的web代码，就给大家提供一个docker：
> > ```
> > 
> > FROM jokyo3/probingai:v1.18.3
> > 
> > #ENV BING_PROXY_DM="https://cfree.nbing.eu.org"
> > 
> > #ENV SYDNEY_PROXY_DM="https://sokwith-nbing.hf.space"
> > 
> > #ENV Go_Proxy_BingAI_USER_TOKEN_1="ASDFGHJKLASDFQWERTVFRVDFBCBVXCXB"
> > 
> > ENV PORT 7860
> > 
> > EXPOSE 7860
> > 
> > CMD ["/app/go-proxy-bingai"]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 新增了两个环境变量，见上面代码注释；
> > v1.18.3的docker版本内置了上面两个环境变量对应的服务器，采用这版docker会直接使用内置的服务器，速度会很慢。当然，也可以自定义的。
> > v1.18.2的docker版本没有内置代理服务器，默认为官方的，所以就不能直接过验证。可以在环境变量中设置代理服务器。(但是，对能够过验证的BING_PROXY_DM服务器有特别的搭建要求，由于是别的大神的代码请原谅我不能提供。)如果不打算过验证只匿名使用，设置一个没有被封ip的BING_PROXY_DM可以规避不断create。
> > docker的源代码在这个仓库里：
> > https://github.com/jokyo3/probingai
> > 原谅我是代码小白，反复折腾把仓库改得一团糟，其实最后就是加了个代理。
> > 使用v1.18.3版docker的部署实例见：
> > https://sokwith-gobingai.hf.space
> > https://zby.zeabur.app  （ps：白嫖的站点随时会被删除）
> > @Harry-zklcdc 不好意思哈，我直接把版本升到了v1.18了
> 
> 直接用gitpod不就行了吗😂或者我有空帮你编译

谢谢。我说的编译后的web是指的那个仓库下的web目录是旧的，不能直接用来web部署，不是指BING_PROXY的代码。大神的代码我折腾了很久，发现只能在cf上起作用，所以也就不需要编译了。

**Comment by luckyEason** [comment]
> > > 由于我没有安装git，不能更新编译后的web代码，就给大家提供一个docker：
> 
> > > ```
> 
> > > 
> 
> > > FROM jokyo3/probingai:v1.18.3
> 
> > > 
> 
> > > #ENV BING_PROXY_DM="https://cfree.nbing.eu.org"
> 
> > > 
> 
> > > #ENV SYDNEY_PROXY_DM="https://sokwith-nbing.hf.space"
> 
> > > 
> 
> > > #ENV Go_Proxy_BingAI_USER_TOKEN_1="ASDFGHJKLASDFQWERTVFRVDFBCBVXCXB"
> 
> > > 
> 
> > > ENV PORT 7860
> 
> > > 
> 
> > > EXPOSE 7860
> 
> > > 
> 
> > > CMD ["/app/go-proxy-bingai"]
> 
> > > ```
> 
> > > 
> 
> > > 
> 
> > >     
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >     
> 
> > >   
> 
> > > 新增了两个环境变量，见上面代码注释；
> 
> > > v1.18.3的docker版本内置了上面两个环境变量对应的服务器，采用这版docker会直接使用内置的服务器，速度会很慢。当然，也可以自定义的。
> 
> > > v1.18.2的docker版本没有内置代理服务器，默认为官方的，所以就不能直接过验证。可以在环境变量中设置代理服务器。(但是，对能够过验证的BING_PROXY_DM服务器有特别的搭建要求，由于是别的大神的代码请原谅我不能提供。)如果不打算过验证只匿名使用，设置一个没有被封ip的BING_PROXY_DM可以规避不断create。
> 
> > > docker的源代码在这个仓库里：
> 
> > > https://github.com/jokyo3/probingai
> 
> > > 原谅我是代码小白，反复折腾把仓库改得一团糟，其实最后就是加了个代理。
> 
> > > 使用v1.18.3版docker的部署实例见：
> 
> > > https://sokwith-gobingai.hf.space
> 
> > > https://zby.zeabur.app  （ps：白嫖的站点随时会被删除）
> 
> > > @Harry-zklcdc 不好意思哈，我直接把版本升到了v1.18了
> 
> > 
> 
> > 直接用gitpod不就行了吗😂或者我有空帮你编译
> 
> 
> 
> 谢谢。我说的编译后的web是指的那个仓库下的web目录是旧的，不能直接用来web部署，不是指BING_PROXY的代码。大神的代码我折腾了很久，发现只能在cf上起作用，所以也就不需要编译了。

我用zeabur也有作用

**Comment by SokWith** [comment]
> > > > 由于我没有安装git，不能更新编译后的web代码，就给大家提供一个docker：
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > FROM jokyo3/probingai:v1.18.3
> > 
> > 
> > > >
> > 
> > 
> > > > #ENV BING_PROXY_DM="https://cfree.nbing.eu.org"
> > 
> > 
> > > >
> > 
> > 
> > > > #ENV SYDNEY_PROXY_DM="https://sokwith-nbing.hf.space"
> > 
> > 
> > > >
> > 
> > 
> > > > #ENV Go_Proxy_BingAI_USER_TOKEN_1="ASDFGHJKLASDFQWERTVFRVDFBCBVXCXB"
> > 
> > 
> > > >
> > 
> > 
> > > > ENV PORT 7860
> > 
> > 
> > > >
> > 
> > 
> > > > EXPOSE 7860
> > 
> > 
> > > >
> > 
> > 
> > > > CMD ["/app/go-proxy-bingai"]
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 新增了两个环境变量，见上面代码注释；
> > 
> > 
> > > > v1.18.3的docker版本内置了上面两个环境变量对应的服务器，采用这版docker会直接使用内置的服务器，速度会很慢。当然，也可以自定义的。
> > 
> > 
> > > > v1.18.2的docker版本没有内置代理服务器，默认为官方的，所以就不能直接过验证。可以在环境变量中设置代理服务器。(但是，对能够过验证的BING_PROXY_DM服务器有特别的搭建要求，由于是别的大神的代码请原谅我不能提供。)如果不打算过验证只匿名使用，设置一个没有被封ip的BING_PROXY_DM可以规避不断create。
> > 
> > 
> > > > docker的源代码在这个仓库里：
> > 
> > 
> > > > https://github.com/jokyo3/probingai
> > 
> > 
> > > > 原谅我是代码小白，反复折腾把仓库改得一团糟，其实最后就是加了个代理。
> > 
> > 
> > > > 使用v1.18.3版docker的部署实例见：
> > 
> > 
> > > > https://sokwith-gobingai.hf.space
> > 
> > 
> > > > https://zby.zeabur.app  （ps：白嫖的站点随时会被删除）
> > 
> > 
> > > > @Harry-zklcdc 不好意思哈，我直接把版本升到了v1.18了
> > 
> > 
> > > 
> > 
> > 
> > > 直接用gitpod不就行了吗😂或者我有空帮你编译
> > 
> > 
> > 谢谢。我说的编译后的web是指的那个仓库下的web目录是旧的，不能直接用来web部署，不是指BING_PROXY的代码。大神的代码我折腾了很久，发现只能在cf上起作用，所以也就不需要编译了。
> 
> 我用zeabur也有作用

不清楚你起作用的是不是我说的BING_PROXY代理服务器，你不能用我内置的代理服务器，如果换成你自己建立的代理服务器（你也拿到代码了?还是发现套娃的玄机了?）也可以，那就祈祷不要被监视了吧

**Comment by SokWith** [comment]
关于套娃的玄机，我曾经在replit上发现，先套娃，得到缓存，当然是不起作用的，再取消套娃，保留缓存，在缓存没更新前，就起作用了。可能是由于我的replit走的也是cf的缓存的缘故

**Comment by jsdianman** [comment]
https://githubfast.com/jsdianman/probingai
web编译好了

**Comment by jsdianman** [comment]
> 关于套娃的玄机，我曾经在replit上发现，先套娃，得到缓存，当然是不起作用的，再取消套娃，保留缓存，在缓存没更新前，就起作用了。可能是由于我的replit走的也是cf的缓存的缘故

我在zeabur上没加任何环境变量，达到了你的nbing的效果。

**Comment by jsdianman** [comment]
也没用cf

**Comment by SokWith** [comment]
今日huggingface很难，但是可以这样使用代理服务器
```
FROM jokyo3/probingai:v1.18.2

ENV BING_PROXY_DM="[https://proxybing.vercel.app"](https://proxybing.vercel.app%22/)
ENV SYDNEY_PROXY_DM="[https://eusydney.onrender.com"](https://eusydney.onrender.com%22/)
ENV Go_Proxy_BingAI_USER_TOKEN_1="ASDFGHJKLASDFQWERTVFRVDFBCBVXCXB"

ENV PORT 7860
EXPOSE 7860
CMD ["/app/go-proxy-bingai"]

```
综合了 huggingface、vercel、render等云商，虽然不能直接过验证，但是充分的白嫖各大免费资源。

**Comment by SokWith** [comment]
> @SokWith 能解释一下是如何实现的吗

https://github.com/Harry-zklcdc/go-proxy-bingai/issues/251#issuecomment-1826460533

我大致推测的就是套娃套得ip与host发生了变化，认证系统出现了混乱吧

**Comment by Harry-zklcdc** [comment]
已解决：https://github.com/Harry-zklcdc/go-proxy-bingai/issues/276#issuecomment-1890889229
