### ISSUE TITLE
[Bug] 🐛 演示站失效了

### ISSUE THREAD

**Issue by zhengqwe** [Harry-zklcdc/go-proxy-bingai#264]
### Describe the bug

一直显示“正在尝试重新连接...”

### Steps to reproduce

正常使用

### Expected behavior

修复这个bug

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/103168200/870504b9-0855-4376-8034-69d79c1e06c2)

### Versions

- OS: Windows 10
- Browser & Version: Edge 119.0.2151.72

### Additional context

服务用的本站，填了自己的cookies使用的
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/103168200/3b4d3609-3433-4d34-8959-9865c4ec03f4)

**Comment by SokWith** [comment]
太难了，现在行为封控很厉害，匿名使用多了就封IP了。

**Comment by SokWith** [comment]
> > 太难了，现在行为封控很厉害，匿名使用多了就封IP了。
> 
> 我是填了自己的cookie使用的

![Screenshot_2023-11-25-16-06-52-031](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/e4545ed9-9f7f-4095-af81-1d5f01f49a71)
刚刚匿名
