### ISSUE TITLE
[Bug] 🐛 插件不支持滑动，且只能查看和使用前三个。

### ISSUE THREAD

**Issue by ningguoxu** [Harry-zklcdc/go-proxy-bingai#265]
### Describe the bug

插件系统显示问题

### Steps to reproduce

部署本项目1.17.0版本后

### Expected behavior

可以查看和使用全部插件，插件支持滚动

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/87106666/d66eb83d-7f06-459a-b06b-874979aab321)

### Versions

- OS:  Windows 10 
- Browser & Version: Chrome 114
- GoProxiBing Version: 1.17.0

**Comment by luckyEason** [comment]
the same issue
这个issue已经提过了，Harry貌似很忙。建议通过缩放临时解决

**Comment by Harry-zklcdc** [comment]
已修复
