### ISSUE TITLE
微软似乎放开了

### ISSUE THREAD

**Issue by SokWith** [Harry-zklcdc/go-proxy-bingai#266]
今天huggingface几乎完全不设防，账户都可以直接登录
兜兜转转半年，一直不断的增加防御机制，结果一朝放开，宛如新冠 。

**Comment by SokWith** [comment]
s帅不过3秒，依然还是间歇性老问题

**Comment by b1ghawk** [comment]
账户免登录以及间歇性问题指的是啥？

**Comment by SokWith** [comment]
> 账户免登录以及间歇性问题指的是啥？

比如今天，huggingface又可以随便登录了，造成套娃huggingface的部署都直接过。

**Comment by b1ghawk** [comment]
> > 账户免登录以及间歇性问题指的是啥？
> 
> 比如今天，huggingface又可以随便登录了，造成套娃huggingface的部署都直接过。

随便登录是什么意思

**Comment by SokWith** [comment]
> > > 账户免登录以及间歇性问题指的是啥？
> > 
> > 
> > 比如今天，huggingface又可以随便登录了，造成套娃huggingface的部署都直接过。
> 
> 随便登录是什么意思，huggingface官网不是一直都可以登录么？

我这里说的随便登录是指，使用任意过期的id，不是匿名登录，登录部署后，直接过验证。
huggingface经常抽风，大多数是半天可用。大多数时候匿名可用，但偶尔就完全不可用。
