### ISSUE TITLE
[Help] 🤔 在基于宝塔面板的新加坡服务器按教程部署，无法连接到本地站点服务器

### ISSUE THREAD

**Issue by NikoCat233** [Harry-zklcdc/go-proxy-bingai#269]
### Describe the help wanted

版本 1.17.0 排查问题

### Steps to behave

启动二进制后按教程设置反向代理，能打开网页资源，无法连接到本地聊天服务器
Network发现请求 wss://***/sydney/ChatHub不通
对该网站撤销了宝塔防火墙，仍不通

### Expected behavior

修复本地服务器连接

### Screenshots

release二进制启动，控制台没有任何日志

### Versions

- OS:  CentOS 8.5.2111 x86_64(Py3.7.9)
- Browser & Version: e.g. Chrome 119 
- GoProxiBing Version:  1.17.0

**Comment by NikoCat233** [comment]
撤销了cloudflare进行直连，获得的wss请求如下
115.156* - - [05/Dec/2023:17:16:50 +0800] ＂GET /sydney/ChatHub HTTP/1.1＂ 200 0 ＂-＂ ＂Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Mobile Safari/537.36 EdgA/116.0.1938.58＂
115.156* - - [05/Dec/2023:17:16:54 +0800] ＂GET /sydney/ChatHub HTTP/1.1＂ 200 0 ＂-＂ ＂Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Mobile Safari/537.36 EdgA/116.0.1938.58＂
115.156* - - [05/Dec/2023:17:18:03 +0800] ＂GET /sydney/ChatHub HTTP/1.1＂ 200 0 ＂-＂ ＂Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Mobile Safari/537.36 EdgA/116.0.1938.58＂

**Comment by Harry-zklcdc** [comment]
应该是反代配置有问题
