### ISSUE TITLE
[Sponsor] 🍒 自愿赞助开发

### ISSUE THREAD

**Issue by Harry-zklcdc** [Harry-zklcdc/go-proxy-bingai#27]
### 开发不易, 如果您经济条件允许, 可自愿赞助我一点心意

<img src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/3094fb65-d490-420d-93db-54c609690a42" height="360px">

可注明`NewBing Proxy 赞助`

**Comment by FangZirui-E5** [comment]
赞助了3元😃

**Comment by Harry-zklcdc** [comment]
> 赞助了3元😃

谢谢😊

**Comment by CKylinMC** [comment]
已赞助，期待优化下历史记录侧栏

**Comment by bullkq** [comment]
已赞助大佬，求指导。

**Comment by Harry-zklcdc** [comment]
> 已赞助，期待优化下历史记录侧栏

谢谢，不过应该不会删除，不建议共享账号

**Comment by Harry-zklcdc** [comment]
> 已赞助大佬，求指导。

谢谢，有时间的话我可以看看

**Comment by CKylinMC** [comment]
> > 已赞助，期待优化下历史记录侧栏
> 
> 谢谢，不过应该不会删除，不建议共享账号

我不是共享账号，但是历史记录有点遮挡，有时候影响我复制自己发送的内容，而且其中的分享基本上是没法用的，好像也没办法真的切换回对应的历史对话，我不确定是不是只有我有这个问题，但是我只尝试了从代码上直接禁止这玩意儿显示...

**Comment by Harry-zklcdc** [comment]
> 我不是共享账号，但是历史记录有点遮挡，有时候影响我复制自己发送的内容，而且其中的分享基本上是没法用的，好像也没办法真的切换回对应的历史对话，我不确定是不是只有我有这个问题，但是我只尝试了从代码上直接禁止这玩意儿显示...

我这边不会有这样的问题，历史聊天记录都可以正常调用，之后我做个设置页吧

**Comment by skyfly2000** [comment]
@Harry-zklcdc 二维码的收款账号被限制了。尽快申请限制，我也近点绵薄之力。
1.95很好，谢谢你的努力。

**Comment by Sisyphean-a** [comment]
再支持一下，新版本很有用

**Comment by Harry-zklcdc** [comment]
> @Harry-zklcdc 二维码的微信收款账号被限制了。尽快申请限制，我支付宝支持了200。 1.95很好，谢谢你的努力。

好的，谢谢
微信收款那个我让我朋友试了一下是没有问题的

**Comment by Harry-zklcdc** [comment]
> 再支持一下，新版本很有用

谢谢支持😊

**Comment by Dxarch1980** [comment]
支持一下，感谢大神继续这个项目，

**Comment by Harry-zklcdc** [comment]
> 支持一下，感谢大神继续这个项目，

谢谢支持😊

**Comment by GforPG** [comment]
> > @Harry-zklcdc 二维码的微信收款账号被限制了。尽快申请限制，我支付宝支持了200。 1.95很好，谢谢你的努力。
> 
> 好的，感谢支持🌈 微信收款那个我让我朋友试了一下是没有问题的

我用微信也不行。

**Comment by ryanzhaorx** [comment]
> > > @Harry-zklcdc 二维码的微信收款账号被限制了。尽快申请限制，我支付宝支持了200。 1.95很好，谢谢你的努力。
> > 
> > 
> > 好的，感谢支持🌈 微信收款那个我让我朋友试了一下是没有问题的
> 
> 我用微信也不行。

是你的方式不对吧

**Comment by DoyoDia** [comment]
502了 微信和支付宝都报502

**Comment by Harry-zklcdc** [comment]
> 502了 微信和支付宝都报502

502 就 502 吧，已经不重要了（）

**Comment by DoyoDia** [comment]
那想给佬赞助一点点，该怎么赞助嘞
