### ISSUE TITLE
[Feature] 🌈 添加文件上传入口

### ISSUE THREAD

**Issue by ningguoxu** [Harry-zklcdc/go-proxy-bingai#270]
### Describe the problem related to the feature request

无法上传文件，Copilot已经支持上传文件了

### Describe the solution you'd like

增加上传文件入口

### Describe alternatives you've considered

![Screenshot_2023-12-07-20-02-29-43_32cba261fc08a501ce70de75bdbe2575](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/87106666/eb4c2bab-f95d-40f3-87bb-8bc6c8ea169e)

**Comment by Harry-zklcdc** [comment]
好的

**Comment by Harry-zklcdc** [comment]
我这账号没有上传文件的入口，可能是灰度测试？

**Comment by Harry-zklcdc** [comment]
已找到入口
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/136413eb-dadc-4d4a-99af-71bd90f80007)

但是使用会
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/ef4339f9-3d1f-4c99-ba30-1e260302abb3)

检查了一下 API，发现似乎 巨硬 并没有准备好推出此功能
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/357f78b0-ee0a-4174-8e15-fb51431835de)

**Comment by Harry-zklcdc** [comment]
已添加
