### ISSUE TITLE
切换Tab之后，输出暂停，切换回来，输出继续，浏览器自带的行为还是？

### ISSUE THREAD

**Issue by b1ghawk** [Harry-zklcdc/go-proxy-bingai#272]
是浏览器自带的行为么？

在碰到比较耗时的输出时，必须保持tab为激活状态，最小化该标签或者切换到其它的标签都会导致输出被暂停(切换到其它浏览器的其它窗口则不会发生暂停)，直到切回该标签之后，输出才会继续进行下去。

有什么办法能够处理这个问题么？

**Comment by b1ghawk** [comment]
在前端页面的<title>标签之后，插入下面的脚本即可解决：
https://cookie.b1ghawk.xyz/BeFluent.js

该脚本的代码：
` javascript
  (function (workerScript) {
    if (!/MSIE 10/i.test (navigator.userAgent)) {
      try {
        var blob = new Blob (["  var fakeIdToId = {};  onmessage = function (event) {    var data = event.data,      name = data.name,      fakeId = data.fakeId,      time;    if(data.hasOwnProperty('time')) {      time = data.time;    }    switch (name) {      case 'setInterval':        fakeIdToId[fakeId] = setInterval(function () {          postMessage({fakeId: fakeId});        }, time);        break;      case 'clearInterval':        if (fakeIdToId.hasOwnProperty (fakeId)) {          clearInterval(fakeIdToId[fakeId]);          delete fakeIdToId[fakeId];        }        break;      case 'setTimeout':        fakeIdToId[fakeId] = setTimeout(function () {          postMessage({fakeId: fakeId});          if (fakeIdToId.hasOwnProperty (fakeId)) {            delete fakeIdToId[fakeId];          }        }, time);        break;      case 'clearTimeout':        if (fakeIdToId.hasOwnProperty (fakeId)) {          clearTimeout(fakeIdToId[fakeId]);          delete fakeIdToId[fakeId];        }        break;    }  }  "]);
        // Obtain a blob URL reference to our worker 'file'.
        workerScript = window.URL.createObjectURL(blob);
      } catch (error) {
        /* Blob is not supported, use external script instead */
      }
    }
    var worker,
      fakeIdToCallback = {},
      lastFakeId = 0,
      maxFakeId = 0x7FFFFFFF, // 2 ^ 31 - 1, 31 bit, positive values of signed 32 bit integer
      logPrefix = 'HackTimer.js by turuslan: ';
    if (typeof (Worker) !== 'undefined') {
      function getFakeId () {
        do {
          if (lastFakeId == maxFakeId) {
            lastFakeId = 0;
          } else {
            lastFakeId ++;
          }
        } while (fakeIdToCallback.hasOwnProperty (lastFakeId));
        return lastFakeId;
      }
      try {
        worker = new Worker (workerScript);
        window.setInterval = function (callback, time /* , parameters */) {
          var fakeId = getFakeId ();
          fakeIdToCallback[fakeId] = {
            callback: callback,
            parameters: Array.prototype.slice.call(arguments, 2)
          };
          worker.postMessage ({
            name: 'setInterval',
            fakeId: fakeId,
            time: time
          });
          return fakeId;
        };
        window.clearInterval = function (fakeId) {
          if (fakeIdToCallback.hasOwnProperty(fakeId)) {
            delete fakeIdToCallback[fakeId];
            worker.postMessage ({
              name: 'clearInterval',
              fakeId: fakeId
            });
          }
        };
        window.setTimeout = function (callback, time /* , parameters */) {
          var fakeId = getFakeId ();
          fakeIdToCallback[fakeId] = {
            callback: callback,
            parameters: Array.prototype.slice.call(arguments, 2),
            isTimeout: true
          };
          worker.postMessage ({
            name: 'setTimeout',
            fakeId: fakeId,
            time: time
          });
          return fakeId;
        };
        window.clearTimeout = function (fakeId) {
          if (fakeIdToCallback.hasOwnProperty(fakeId)) {
            delete fakeIdToCallback[fakeId];
            worker.postMessage ({
              name: 'clearTimeout',
              fakeId: fakeId
            });
          }
        };
        worker.onmessage = function (event) {
          var data = event.data,
            fakeId = data.fakeId,
            request,
            parameters,
            callback;
          if (fakeIdToCallback.hasOwnProperty(fakeId)) {
            request = fakeIdToCallback[fakeId];
            callback = request.callback;
            parameters = request.parameters;
            if (request.hasOwnProperty ('isTimeout') && request.isTimeout) {
              delete fakeIdToCallback[fakeId];
            }
          }
          if (typeof (callback) === 'string') {
            try {
              callback = new Function (callback);
            } catch (error) {
              console.log (logPrefix + 'Error parsing callback code string: ', error);
            }
          }
          if (typeof (callback) === 'function') {
            callback.apply (window, parameters);
          }
        };
        worker.onerror = function (event) {
          console.log (event);
        };
      } catch (error) {
        console.log (logPrefix + 'Initialisation failed');
        console.error (error);
      }
    } else {
      console.log (logPrefix + 'Initialisation failed - HTML5 Web Worker is not supported');
    }
  }) ('beFluent.js');
`

**Comment by shenmidigua** [comment]
牛批

**Comment by Harry-zklcdc** [comment]
我研究一下有没有更优雅的方式

**Comment by SokWith** [comment]
> 在前端页面的<title>标签之后，插入下面这个脚本即可解决： @Harry-zklcdc @SokWith
> 
> [BeFluent.js](https://github.com/Harry-zklcdc/go-proxy-bingai/files/13682004/BeFluent.js.zip)

不好意思哈，我代码小白。
我把代码全部复制插入后在 cloudflare workers上的部署前端输出页面就成空白了，是哪儿操作不正确？

**Comment by SokWith** [comment]
> 在前端页面的<title>标签之后，插入下面这个脚本即可解决： @Harry-zklcdc @SokWith
> 
> [BeFluent.js](https://github.com/Harry-zklcdc/go-proxy-bingai/files/13682004/BeFluent.js.zip)

感谢。
