### ISSUE TITLE
发现官方wss可用了

### ISSUE THREAD

**Issue by jsdianman** [Harry-zklcdc/go-proxy-bingai#275]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/143573972/cc220118-b0e5-428c-8a55-1ac0aee69213)

**Comment by SokWith** [comment]
我8月在山西旅行的时候，发现那边一直可以，到了陕西就不行了。

**Comment by jsdianman** [comment]
好像跟网络环境有关，换移动的就不行了

**Comment by Harry-zklcdc** [comment]
应该会逐步放开，因为  Microsoft copilot 已经备案通过了，等 copilot 正式出来之后，这个项目基本上也不会怎么维护了

**Comment by SokWith** [comment]
> 应该会逐步放开，因为 Microsoft copilot 已经备案通过了，等 copilot 正式出来之后，这个项目基本上也不会怎么维护了

@Harry-zklcdc 大佬，抽空把套娃代理和推送拉取cookie的代码优化集成一下。特别是拉取cookie，能不能把拉取地址放在环境变量或者前端里面，便于通用部署？@b1ghawk

**Comment by SokWith** [comment]
> > 应该会逐步放开，因为 Microsoft copilot 已经备案通过了，等 copilot 正式出来之后，这个项目基本上也不会怎么维护了
> 
> 那是阉割版

没关系了。
这个项目主要是为了方便手机使用，只要微软不再加强封控，目前已经稳定的两种方法过验证就能够保证这个项目的长治久安。

**Comment by Harry-zklcdc** [comment]
> > 应该会逐步放开，因为 Microsoft copilot 已经备案通过了，等 copilot 正式出来之后，这个项目基本上也不会怎么维护了
> 
> @Harry-zklcdc 大佬，抽空把套娃代理和推送拉取cookie的代码优化集成一下。特别是拉取cookie，能不能把拉取地址放在环境变量或者前端里面，便于通用部署？@b1ghawk

你整理一下思路吧，我还是没太懂你的意思

**Comment by SokWith** [comment]
> > > 应该会逐步放开，因为 Microsoft copilot 已经备案通过了，等 copilot 正式出来之后，这个项目基本上也不会怎么维护了
> > 
> > 
> > @Harry-zklcdc 大佬，抽空把套娃代理和推送拉取cookie的代码优化集成一下。特别是拉取cookie，能不能把拉取地址放在环境变量或者前端里面，便于通用部署？@b1ghawk
> 
> 你整理一下思路吧，我还是没太懂你的意思

https://github.com/Harry-zklcdc/go-proxy-bingai/issues/276#issue-2054641233

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/ee61d468-c6fe-4f55-860c-261d15de1d1d)
目前拉取cookie是采用在首页index.html上加载script js来实现的；
https://github.com/Harry-zklcdc/go-proxy-bingai/issues/267#issuecomment-1842126326 之前想请你在主代码中开cookie接口，想来工作量大了，还是加载来得简洁。
但是，在静态页面直接写入，就没办法生成通用的docker了。
所以，还得找个办法来隐匿拉取服务器。

**Comment by Harry-zklcdc** [comment]
> ![image](https://private-user-images.githubusercontent.com/129967025/292623161-ee61d468-c6fe-4f55-860c-261d15de1d1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzOTIwOTcsIm5iZiI6MTcwMzM5MTc5NywicGF0aCI6Ii8xMjk5NjcwMjUvMjkyNjIzMTYxLWVlNjFkNDY4LWM2ZmUtNGY1NS04NjBjLTI2MWQxNWRlMWQxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNFQwNDIzMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODNiOGJmOWQ1ZWNhZWMxNTgxMjM0MGNhNTVhNjdiYjg5NTZkMjJhZTAyZmIwNTUxODNkOGRlYzZkZDQwODFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rUpCz0Xa2BsQKHkwAfEbu4j7Fri7n7DnvNPv3sgwUFI) 目前拉取cookie是采用在首页index.html上加载script js来实现的； [#267 (comment)](https://github.com/Harry-zklcdc/go-proxy-bingai/issues/267#issuecomment-1842126326) 之前想请你在主代码中开cookie接口，想来工作量大了，还是加载来得简洁。 但是，在静态页面直接写入，就没办法生成通用的docker了。 所以，还得找个办法来隐匿拉取服务器。
> 
> [#276 (comment)](https://github.com/Harry-zklcdc/go-proxy-bingai/issues/276#issue-2054641233)
> 
> PS：公开了这个拉取服务器地址，大家可以添加进自己的主页测试。 这个cookie服务器我目前推送了3个cookie，也欢迎大家推送自己的cookie到池子里面，推送地址： http s://cookie.nbing.eu.org/setKVCookies?pwd=123456 (修改了一下url，避免误点击推送无效cookie） 池子大了就成伪随机了。

就是说，你做了一个 Cookie 池的东西？然后每次加载的时候都会自动获取可用的 Cookie？
如果是这样的话，应该不太会合并，有安全风险，你可以考虑做个页面用于获取，这样更安全一些

**Comment by SokWith** [comment]
> > ![image](https://private-user-images.githubusercontent.com/129967025/292623161-ee61d468-c6fe-4f55-860c-261d15de1d1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzOTIwOTcsIm5iZiI6MTcwMzM5MTc5NywicGF0aCI6Ii8xMjk5NjcwMjUvMjkyNjIzMTYxLWVlNjFkNDY4LWM2ZmUtNGY1NS04NjBjLTI2MWQxNWRlMWQxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNFQwNDIzMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODNiOGJmOWQ1ZWNhZWMxNTgxMjM0MGNhNTVhNjdiYjg5NTZkMjJhZTAyZmIwNTUxODNkOGRlYzZkZDQwODFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rUpCz0Xa2BsQKHkwAfEbu4j7Fri7n7DnvNPv3sgwUFI) 目前拉取cookie是采用在首页index.html上加载script js来实现的； [#267 (comment)](https://github.com/Harry-zklcdc/go-proxy-bingai/issues/267#issuecomment-1842126326) 之前想请你在主代码中开cookie接口，想来工作量大了，还是加载来得简洁。 但是，在静态页面直接写入，就没办法生成通用的docker了。 所以，还得找个办法来隐匿拉取服务器。
> > [#276 (comment)](https://github.com/Harry-zklcdc/go-proxy-bingai/issues/276#issue-2054641233)
> > PS：公开了这个拉取服务器地址，大家可以添加进自己的主页测试。 这个cookie服务器我目前推送了3个cookie，也欢迎大家推送自己的cookie到池子里面，推送地址： http s://cookie.nbing.eu.org/setKVCookies?pwd=123456 (修改了一下url，避免误点击推送无效cookie） 池子大了就成伪随机了。
> 
> 就是说，你做了一个 Cookie 池的东西？然后每次加载的时候都会自动获取可用的 Cookie？ 如果是这样的话，应该不太会合并，有安全风险，你可以考虑做个页面用于获取，这样更安全一些

恰恰希望的就是不要做cookie池，希望能隐匿这个拉取地址，避免被不相干的利用。

我上面举例只是说明，像我这样在代码中显示了，或者即使编译成docker后公开docker，都会被公共利用。
当然，如果要做一个公共的服务，发扬开源奉献精神，大家也可以把无关紧要的cookie推送到cookie存储服务器上，人人为我我为人人，形成伪随机地址池，就可以保证服务的高可用性（官方规则是同一地址登录及匿名都是有数量限制的，若从多个地址推送到服务器，形成地址池，可用性就大大提高了）。

**Comment by Harry-zklcdc** [comment]
> > 就是说，你做了一个 Cookie 池的东西？然后每次加载的时候都会自动获取可用的 Cookie？ 如果是这样的话，应该不太会合并，有安全风险，你可以考虑做个页面用于获取，这样更安全一些
> 
> 恰恰希望的就是不要做cookie池，希望能隐匿这个拉取地址，避免被不相干的利用。
> 
> 我上面举例只是说明，像我这样在代码中显示了，或者即使编译成docker后公开docker，都会被公共利用。 当然，如果要做一个公共的服务，发扬开源奉献精神，大家也可以把无关紧要的cookie推送到cookie存储服务器上，人人为我我为人人，形成伪随机地址池，就可以保证服务的高可用性（官方规则是同一地址登录及匿名都是有数量限制的，若从多个地址推送到服务器，形成地址池，可用性就大大提高了）。
> 
> PS：说明一下，目前这个cookie存储服务器同时只能存储一组cookie，就是最近推送进去的那一个，只要不断的从不同地方往里面推送，就形成伪随机地址池了。

这样的话，其实可以做一个项目，专门用于获取新的 Cookie 和推送，而且挺好和这个结合的，这样更优雅一些

**Comment by b1ghawk** [comment]
> 
> > > 就是说，你做了一个 Cookie 池的东西？然后每次加载的时候都会自动获取可用的 Cookie？ 如果是这样的话，应该不太会合并，有安全风险，你可以考虑做个页面用于获取，这样更安全一些
> > 
> > 恰恰希望的就是不要做cookie池，希望能隐匿这个拉取地址，避免被不相干的利用。
> > 
> > 我上面举例只是说明，像我这样在代码中显示了，或者即使编译成docker后公开docker，都会被公共利用。 当然，如果要做一个公共的服务，发扬开源奉献精神，大家也可以把无关紧要的cookie推送到cookie存储服务器上，人人为我我为人人，形成伪随机地址池，就可以保证服务的高可用性（官方规则是同一地址登录及匿名都是有数量限制的，若从多个地址推送到服务器，形成地址池，可用性就大大提高了）。
> > 
> > PS：说明一下，目前这个cookie存储服务器同时只能存储一组cookie，就是最近推送进去的那一个，只要不断的从不同地方往里面推送，就形成伪随机地址池了。
> 
> 这样的话，其实可以做一个项目，专门用于获取新的 Cookie 和推送，而且挺好和这个结合的，这样更优雅一些

🙉感觉会变得很繁琐。

**Comment by Harry-zklcdc** [comment]
> 🙉感觉会变得很繁琐。

其实还好，而且这样来说更安全一些，不太想直接结合到项目中

**Comment by b1ghawk** [comment]
> > 🙉感觉会变得很繁琐。
> 
> 其实还好，而且这样来说更安全一些，不太想直接结合到项目中

😂我是说整个推送体系太过于繁琐。
无所谓结合到项目与否，
总之多出一个心智负担。
