### ISSUE TITLE
[Help] 🤔 cloudflare上部署到每天都要挂梯子验证一次

### ISSUE THREAD

**Issue by ikunfans** [Harry-zklcdc/go-proxy-bingai#277]
### Describe the help wanted

在cf部署的时候加了cookies，我用手机挂梯子登官方一次，所有设备都可以聊天了，有cookie的30次，没有的10次。但是第二天又开始验证，要再挂梯子重复一边·····是不是要把cookies删了只给自己用。。。
还有代码第一排必须删了才能部署。。。。

### Steps to behave

·

### Expected behavior

·

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by SokWith** [comment]
楼下就有2种自动过认证的方式哟：
https://github.com/Harry-zklcdc/go-proxy-bingai/issues/276#issue-2054641233

**Comment by Harry-zklcdc** [comment]
已修复: e00934c454e5897be99832df3a7b90f7abd96914
