### ISSUE TITLE
[Bug] 🐛 Docker里出现了Panic

### ISSUE THREAD

**Issue by b1ghawk** [Harry-zklcdc/go-proxy-bingai#279]
### Describe the bug
<img width="1096" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/30652540/6945347b-9714-442a-a416-26ff560e94c5">

adams549659584/go-proxy-bingai/common.NewSingleHostReverseProxy.func2(0xc0003be990)
	adams549659584/go-proxy-bingai/common/proxy.go:181 +0xc26
net/http/httputil.(*ReverseProxy).modifyResponse(0xc00020e1e0, {0xa406c8, 0xc000268c40}, 0xc0003be990, 0x0?)
	net/http/httputil/reverseproxy.go:324 +0x4a
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc00020e1e0, {0xa406c8, 0xc000268c40}, 0xc000326100)
	net/http/httputil/reverseproxy.go:490 +0xef5
adams549659584/go-proxy-bingai/api.Index({0xa406c8, 0xc000268c40}, 0xc000326100)
	adams549659584/go-proxy-bingai/api/index.go:21 +0xc5
net/http.HandlerFunc.ServeHTTP(0x440aa0?, {0xa406c8?, 0xc000268c40?}, 0x63ccfa?)
	net/http/server.go:2136 +0x29
net/http.(*ServeMux).ServeHTTP(0xd30940?, {0xa406c8, 0xc000268c40}, 0xc000326100)
	net/http/server.go:2514 +0x142
net/http.serverHandler.ServeHTTP({0xc00010e600?}, {0xa406c8?, 0xc000268c40?}, 0x6?)
	net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc0003be090, {0xa41410, 0xc00010e1b0})
	net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 1
	net/http/server.go:3086 +0x5cb

- GoProxiBing Version: 最新版

**Comment by Harry-zklcdc** [comment]
在访问什么的时候出现的？
如何复现？
