### ISSUE TITLE
版本号始终是1.9.0

### ISSUE THREAD

**Issue by qinguoluo** [Harry-zklcdc/go-proxy-bingai#28]
现在都1.9.2了，为什么我的版本号还停留在1.9.0？

**Comment by qinguoluo** [comment]
vercel上也更新了。
![屏幕截图 2023-07-25 094631](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/92149037/fb2419a5-d740-40c3-8cbb-9768155b6eb5)

**Comment by qinguoluo** [comment]
作者的workflow有2条失败的记录。会不会影响版本更新？
![屏幕截图 2023-07-25 094724](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/92149037/ec88cff3-00bf-48b2-8d27-f86ec6525495)

**Comment by wurenzhiwen666** [comment]
我也是

**Comment by Harry-zklcdc** [comment]
> 作者的workflow有2条失败的记录。会不会影响版本更新？ [屏幕截图 2023-07-25 094724](https://user-images.githubusercontent.com/92149037/255765389-ec88cff3-00bf-48b2-8d27-f86ec6525495.png)

不影响，那个是构建失败，后来发布的都正常了

**Comment by Harry-zklcdc** [comment]
我应该知道原因了，我没有修改`web文件夹`里面的代码，那个是前端代码，需要重新构建

由于我的 `Github Action` 里面的代码有含自动构建的代码，所以web的代码我都没有更新了

**Comment by Harry-zklcdc** [comment]
已修复: https://github.com/Harry-zklcdc/go-proxy-bingai/commit/cee0073c254d84ec6b84c1b6388c651c13d6ebf3

**Comment by qinguoluo** [comment]
感谢大神！
