### ISSUE TITLE
[Bug] 🐛 手机版无法聊天

### ISSUE THREAD

**Issue by Hansonwong47** [Harry-zklcdc/go-proxy-bingai#280]
### Describe the bug

手机版无法聊天

### Steps to reproduce

我每次问他的时候也会出错，只是这个bing项目才会出错，其他也不会。
例如bingo不会出错，正常聊天

### Expected behavior

希望手机版可以聊天，不会出错

### Screenshots

![70624A06-86BF-4B96-80AF-B7A5F5215FF3](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129591155/a3b19285-787d-4195-b8e1-21b8a155939b)

### Versions

iPhone 6s
浏览器是Safari

**Comment by jsdianman** [comment]
低iOS版本似乎会出现这种问题，iOS17没有。可以正常聊天

**Comment by SokWith** [comment]
出现不可以用时首先做的是清缓存，而且是在浏览器设置里面去清除缓存的哪种，一键重置不一定能清理干净。

**Comment by jsdianman** [comment]
> 首先，手机浏览器推荐还是edge。
> 
> 
> 
> 出现不可以用时首先做的是清缓存，而且是在浏览器设置里面去清除缓存的哪种，一键重置不一定能清理干净。

iOS的浏览器貌似都是用系统自带内核，edge的效果和Safari一样

**Comment by Harry-zklcdc** [comment]
目前我这边测试没有发现问题
