### ISSUE TITLE
[Help] 🤔 API的接口是什么

### ISSUE THREAD

**Issue by ryanzhaorx** [Harry-zklcdc/go-proxy-bingai#281]
### Describe the help wanted

API的接口地址是什么

### Steps to behave

NONE

### Expected behavior

NONE

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by Harry-zklcdc** [comment]
有 bug，在修，文档预计这几天整理一下

**Comment by Harry-zklcdc** [comment]
<img width="1378" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/2bc79a69-81e6-4d5d-988a-f71009ba0786">

测试地址：https://harry-zklcdc-chatgpt-next-web.hf.space/

**Comment by ryanzhaorx** [comment]
谢谢

**Comment by ryanzhaorx** [comment]
> <img alt="image" width="1378" src="https://private-user-images.githubusercontent.com/21104213/296616128-2bc79a69-81e6-4d5d-988a-f71009ba0786.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyOTAyMzMsIm5iZiI6MTcwNTI4OTkzMywicGF0aCI6Ii8yMTEwNDIxMy8yOTY2MTYxMjgtMmJjNzlhNjktODFlNi00ZDVkLTk4OGEtZjcxMDA5YmEwNzg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDAzMzg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5OWMxZDM3YmNkZGZlMWRjODc5MjIxNjczYmZiMjcwZDMwODMyMmQ1ZjM4YTg2MDU5ZDlhZmZiY2FkNmQyY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Md--PE-ExPzn14Rtt6H0R5O4R05ILXrlJNrdAKpwQiU">
> 测试地址：https://harry-zklcdc-chatgpt-next-web.hf.space/

谢谢

**Comment by Harry-zklcdc** [comment]
文档地址：https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/BingAPI

**Comment by jsdianman** [comment]
必须要设置apikey才能用吗

**Comment by Harry-zklcdc** [comment]
> 必须要设置apikey才能用吗

并不是，设置 APIKEY 之后会检查是否一致，如果没有设置，随便值都可以

**Comment by Harry-zklcdc** [comment]
已有文档，关闭此 issue
