### ISSUE TITLE
[Feature] 🌈 Make In English Please

### ISSUE THREAD

**Issue by Niansuh** [Harry-zklcdc/go-proxy-bingai#282]
### Describe the problem related to the feature request

[Feature] 🌈 Make In English Please

### Describe the solution you'd like

[Feature] 🌈 Make In English Please

### Describe alternatives you've considered

[Feature] 🌈 Make In English Please

### Additional context

[Feature] 🌈 Make In English Please

**Comment by jsdianman** [comment]
要改config.js吧

**Comment by Harry-zklcdc** [comment]
There is no plan to make this project in English.
Just because it would spend experience maintaining i18n.
You can use Translate Plugin to instead of offical i18n

**Comment by Niansuh** [comment]
please

**Comment by Niansuh** [comment]
make antoher repo https://github.com/Harry-zklcdc/go-proxy-bingai-en
