### ISSUE TITLE
更新1.18.5后报错

### ISSUE THREAD

**Issue by jsdianman** [Harry-zklcdc/go-proxy-bingai#283]
{"code":500,"message":"Post \"\": unsupported protocol scheme \"\"","data":null}![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/143573972/d0ebff7b-bf41-4181-ade5-710c2b022fe1)

vercel部署，wss是cloudflare的

**Comment by Harry-zklcdc** [comment]
配置 `BYPASS_SERVER` 人机验证接口了吗？
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/4029abbb-9301-423d-8617-31b32e349894)

人机验证部署例子：https://huggingface.co/spaces/zklcdc/go-bingai-pass
GPB+人机验证 一体化部署例子：https://huggingface.co/spaces/Harry-zklcdc/go-proxy-bingai

**Comment by viqbgrg** [comment]
这个不是非必填吗?

**Comment by Harry-zklcdc** [comment]
> 这个不是非必填吗?

是可选项，但是如果要能自动通过人机验证的话，就必须要填了

**Comment by viqbgrg** [comment]
并没有开始自动通过人机验证，默认的

**Comment by jsdianman** [comment]
配置了，还是不行

**Comment by jsdianman** [comment]
{"code":500,"message":"invalid character '\u003c' looking for beginning of value","data":null}

**Comment by Harry-zklcdc** [comment]
> 配置了，还是不行

你搭建人机验证服务器了嘛？

如果用我的那个要改一下地址

改为 `https://zklcdc-go-bingai-pass.hf.space/`

**Comment by jsdianman** [comment]
可以了，谢谢

**Comment by ningguoxu** [comment]
如何搭建自己的过人机验证服务呢

**Comment by Harry-zklcdc** [comment]
> 如何搭建自己的过人机验证服务呢

https://github.com/Harry-zklcdc/go-proxy-bingai/issues/251#issue-1972739940
