### ISSUE TITLE
[Feature] 🌈 新/旧版UI切换

### ISSUE THREAD

**Issue by bobandbrony** [Harry-zklcdc/go-proxy-bingai#284]
### Describe the problem related to the feature request

个人觉得旧版UI更好看一点，希望能增加切换新/旧版UI的功能
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129247570/af742227-c24b-4457-a096-f15d16d2e557)
这是旧版的

### Describe the solution you'd like

在右上角的设置那里进行切换

**Comment by Harry-zklcdc** [comment]
暂时没有计划支持

**Comment by Harry-zklcdc** [comment]
已提交代码, Commit: 966131cee6c3671f187012cc53816cd9099ce679
