### ISSUE TITLE
[Bug] 🐛 cloudflare 部署出错

### ISSUE THREAD

**Issue by potus2030** [Harry-zklcdc/go-proxy-bingai#286]
### Describe the bug

最新worker.js, 界面等一切正常。但是回答问题时报错，如图
![1](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/77405182/998f1996-77f0-4afa-b461-42c03c94ba86)

### Steps to reproduce

每次都报错

### Expected behavior

应该有回答

### Versions

- OS: 
- Browser & Version:  Edge

**Comment by Harry-zklcdc** [comment]
请参考 [wiki - 环境变量 - 人机验证接口](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F#%E4%BA%BA%E6%9C%BA%E9%AA%8C%E8%AF%81%E6%8E%A5%E5%8F%A3) 配置人机验证服务器地址
https://github.com/Harry-zklcdc/go-proxy-bingai/blob/968eccebbfe6ec2d13327f67ebbca82909c9b2fd/cloudflare/worker.js#L8
