### ISSUE TITLE
[Bug] 🐛 显示错误

### ISSUE THREAD

**Issue by gdfhlfkg** [Harry-zklcdc/go-proxy-bingai#287]
### Describe the bug

它真的认为我可以看懂

### Steps to reproduce
由cloudflare worker部署，1.18.8，edge
您可以尝试询问一些数学问题

### Expected behavior

更新显示模式

### Screenshots

![屏幕截图 2024-01-16 223834](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/104117637/a3295763-14df-4d43-b6c0-59a1e1b69669)
![屏幕截图 2024-01-16 223910](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/104117637/3b307c55-b849-4d59-9fc3-747a6e0af2d0)
![屏幕截图 2024-01-16 224421](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/104117637/4e2d95b5-fcab-4b4a-9260-84916a390d1e)
![屏幕截图 2024-01-16 224929](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/104117637/95422b60-fe65-453e-9505-ce7fd153c9af)

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by gdfhlfkg** [comment]
![屏幕截图 2024-01-16 230508](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/104117637/16ea6c1e-e620-4481-9dd9-6889a4f5a666)

**Comment by Harry-zklcdc** [comment]
请提供你询问的问题

**Comment by gdfhlfkg** [comment]
> 请提供你询问的问题

例：什么是标准形式的二次函数？
![屏幕截图 2024-01-16 232425](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/104117637/bfbb09cb-ba45-49da-b75a-00297b011550)

**Comment by gdfhlfkg** [comment]
> > 请提供你询问的问题
> 
> 例：什么是标准形式的二次函数？ ![屏幕截图 2024-01-16 232425](https://private-user-images.githubusercontent.com/104117637/297103081-bfbb09cb-ba45-49da-b75a-00297b011550.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MTg5ODQsIm5iZiI6MTcwNTQxODY4NCwicGF0aCI6Ii8xMDQxMTc2MzcvMjk3MTAzMDgxLWJmYmIwOWNiLWJhNDUtNDlkYS1iNzVhLTAwMjk3YjAxMTU1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQxNTI0NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzM0NDQyZTZjMDFmZWRlNzM0MTAyZTQ0NTEwZjhkYjRjYmQ3OTZhNzBkYjM5NjY3MDExZGFhY2U5MDQ4YTZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xQx3NH0X3VDel4Uym_lsK86-M3XsW17bzLsn6hmgSfY)

亦或：如何将二次函数一般式转换为标准形式？
![屏幕截图 2024-01-16 232706](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/104117637/0c67e896-3c24-4586-ba53-f873dc955083)

**Comment by Harry-zklcdc** [comment]
雀食有显示问题，我尝试修复一下吧

**Comment by Harry-zklcdc** [comment]
在高级设置中，将 `GPT4-Turbo` 关闭即可，猜测可能由于 `GPT4-Turbo` 不稳定，目前还处于灰度测试阶段
<img width="1081" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/af987f45-24e8-484e-9c43-1ca9efc476c8">
图中为关闭后的结果
