### ISSUE TITLE
[Feature] 🌈 连续的语音对话

### ISSUE THREAD

**Issue by dcityteg** [Harry-zklcdc/go-proxy-bingai#288]
### Describe the problem related to the feature request

每次想要语音对话都要点一下那个图标，点了之后**只能用一次**。
不知项目能否跟进。

### Describe the solution you'd like

 可以在**设置**里加一个**持续对话**的选项，打开之后使用语音对话就不会在**使用完一次之后**关闭

**Comment by shenmidigua** [comment]
官方已更新此功能

**Comment by Harry-zklcdc** [comment]
尝试最新版本是否可以正常连续对话
