### ISSUE TITLE
[Bug] 🐛 API搜索情况下输出不全

### ISSUE THREAD

**Issue by dcityteg** [Harry-zklcdc/go-proxy-bingai#289]
### Describe the bug

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/132677224/f1136524-ba46-4e6c-b76b-d77445a46640)
如图，在使用搜索时，完成搜索后第一个字符会无法输出。
如图，Bing chat的B没有输出。

### Steps to reproduce

在使用API的情况下，问出一些需要搜索的问题，在搜索完成后，第一个字符会不输出。

### Expected behavior

能够正确输出第一个字符

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/132677224/65fc7c25-d7e4-4707-8a02-cda0cd2d5b83)

### Versions

- OS: 
- Browser & Version:

**Comment by Harry-zklcdc** [comment]
已知问题，尝试修复

**Comment by Harry-zklcdc** [comment]
已修复: 6787897b1e7d99710c88b17985c82c1a63156e46
