### ISSUE TITLE
我部署的CF服务器貌似没办法国内直连

### ISSUE THREAD

**Issue by landones** [Harry-zklcdc/go-proxy-bingai#29]
RT，完全复制开发者大大的代码，并修改了相关的cookie，但如果不翻墙就无法在国内直连，会直接红色显示，无论是自己部署的站还是别的大佬部署的站貌似都一样，快被逼疯了。

**Comment by Harry-zklcdc** [comment]
可能你的所在地那边有 `sni 白名单`，这个不做解决，（解决了容易去踩缝纫机）
