### ISSUE TITLE
[Bug] 🐛 Errors in Cloudflare works

### ISSUE THREAD

**Issue by ddaaww** [Harry-zklcdc/go-proxy-bingai#290]
### Describe the bug

There are a lot of errors in bjs.js

### Steps to reproduce

When deploying in Cloudflare, there are a lot of errors in the code of bjs.js.

### Expected behavior

The code can be smoothly compiled.

### Screenshots

<img width="471" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/37658163/9a13b7df-940c-4628-aa97-d8dce70dd5fc">

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by LWF666** [comment]
+1

**Comment by Harry-zklcdc** [comment]
报错正常，保存即可，无需理会
