### ISSUE TITLE
[Bug] 🐛 弹出两次信息来源

### ISSUE THREAD

**Issue by dcityteg** [Harry-zklcdc/go-proxy-bingai#291]
### Describe the bug

会显示两次”了解详细信息“，也就是bing搜集到的信息来源

### Steps to reproduce

在无痕模式触发搜索，比如：告诉我关于核污水的相关信息，在最下面会显示两次了解详细信息
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/132677224/6acd7d13-5088-4768-9327-c68f9cd162e0)

### Expected behavior

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/132677224/26ab8a81-f643-4333-b470-334321670a51)
希望只有一个了解详细信息

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/132677224/04c8df5d-d8aa-4cf0-b38f-d69f2e7b5674)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/132677224/c1357240-e7b7-4a8c-9d2a-946c04e0fcc2)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/132677224/c68a91a3-3695-472b-b565-338f2cd8596a)

### Versions

- OS: Windows 11
- Browser & Version: Microsoft Edge
- GoProxiBing Version: 最新

**Comment by Harry-zklcdc** [comment]
第一次提问会这样，似乎是「巨硬」的问题，之后在提问就不会了
