### ISSUE TITLE
[Help] 🤔 美国vps部署一直正在尝试重新连接

### ISSUE THREAD

**Issue by fangyuan99** [Harry-zklcdc/go-proxy-bingai#292]
### Describe the bug

站点和cookie都配置了，但还是一直显示正在尝试重新连接
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/62874116/bac9fc50-e1c2-49aa-b4e5-e06ec208fb83)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/62874116/284556d0-9974-43b9-914d-872e15bf2840)

### Steps to reproduce

美国的vps,正常用docker-compose部署

### Expected behavior

正常使用

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by fangyuan99** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/62874116/9c068641-0c52-4033-bfdd-f7a1dd519d6e)
我应该是按照教程配置好了的

**Comment by Harry-zklcdc** [comment]
bt自带反代配置不支持websocket

**Comment by fangyuan99** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/62874116/5be2dada-b8f3-4cef-81fb-fbc1e9ab5464)
控制台输出和网络截图
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/62874116/fb741e4c-1922-4d39-b0cb-b75d52a7694c)

**Comment by Harry-zklcdc** [comment]
我之前有个nginx配置来着，你翻翻issue

**Comment by Harry-zklcdc** [comment]
这wiki我该改一下了🤣

**Comment by Harry-zklcdc** [comment]
https://github.com/adams549659584/go-proxy-bingai/issues/282#issuecomment-1605262801

nginx cache那部分注释掉试试

**Comment by fangyuan99** [comment]
有些部分一直报错，删掉后正常
```
server {
    listen 80;
    server_name yourdomain.com;

  location / {
		proxy_pass http://127.0.0.1:8080;
 		proxy_http_version        1.1;
 		proxy_cache_bypass     $http_upgrade;

 		# Proxy headers
 		proxy_set_header Upgrade                   $http_upgrade;
 		proxy_set_header Connection               $connection_upgrade;
 		proxy_set_header Host                          $host;
 		proxy_set_header X-Real-IP                  $remote_addr;
 		proxy_set_header X-Forwarded-For      $proxy_add_x_forwarded_for;
 		proxy_set_header X-Forwarded-Proto   $scheme;
 		proxy_set_header X-Forwarded-Host    $host;
 		proxy_set_header X-Forwarded-Port     $server_port;


 		proxy_ignore_headers Set-Cookie Cache-Control expires;
 		proxy_cache cache_one;
 		proxy_cache_key $host$uri$is_args$args;
 		proxy_cache_valid 200 304 301 302 1m;
	}
}
```

**Comment by Harry-zklcdc** [comment]
和cache相关的都可以删掉了

**Comment by fangyuan99** [comment]
有个叫[Cookie-Editor | Chrome扩展 - Crx搜搜](https://www.crxsoso.com/webstore/detail/hlkenndednhfkekhgcdicdfddnkalmdm)的插件可以一键导出cookie，就是不知道格式是否支持解析
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/62874116/42ab6a7e-baec-4581-8d32-c32115093ed8)

**Comment by Harry-zklcdc** [comment]
> 有个叫[Cookie-Editor | Chrome扩展 - Crx搜搜](https://www.crxsoso.com/webstore/detail/hlkenndednhfkekhgcdicdfddnkalmdm)的插件可以一键导出cookie，就是不知道格式是否支持解析 [image](https://private-user-images.githubusercontent.com/62874116/297665441-42ab6a7e-baec-4581-8d32-c32115093ed8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NjUxMjgsIm5iZiI6MTcwNTU2NDgyOCwicGF0aCI6Ii82Mjg3NDExNi8yOTc2NjU0NDEtNDJhYjZhN2UtYmFlYy00NTgxLThkMzItYzMyMTE1MDkzZWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA4MDAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlOWRlOWU3ZGE5NTliYTUxN2IxMDgzYzdiODRjODMzNTg3M2Y3Y2NhODMxMjkxY2I5ZTZhYTA4OTVkNjQ5MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yyX7xAtvnUcgY1DUhQjnKUnsbuf4Dxw-JzldGOlzUmA)

暂不支持
