### ISSUE TITLE
[Help] Cloudflare 生成/上传图片异常

### ISSUE THREAD

**Issue by CalCobalt** [Harry-zklcdc/go-proxy-bingai#294]
### Describe the help wanted

无法上传图片和生成图片

### Steps to behave

在Cloudflare部署的应用

在worker.js里已经填写了4个cookie。

### Expected behavior

正常使用

### Screenshots

![IMG_0035](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/96706505/204d435c-d5ae-449d-9304-280192898c66)

### Versions

- OS: Cloudflare
- Browser & Version: Safari
- GoProxiBing Version: 1.18.9

**Comment by Harry-zklcdc** [comment]
好的，尝试修复

**Comment by Harry-zklcdc** [comment]
已修复: 2a2aa6a61f22a5cd17ea004b617626dd21b52607
