### ISSUE TITLE
[Bug] 🐛 OpenAI格式api调用出现404报错

### ISSUE THREAD

**Issue by chaoyu1999** [Harry-zklcdc/go-proxy-bingai#297]
### Describe the bug

openai 格式api调用出现404报错

### Steps to reproduce

使用一键部署，部署到hf上之后调用接口会报错。
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/46945475/d0745975-5e8d-46ce-a588-3c4d94199c4a)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/46945475/ceedf5fe-a6d2-4fde-8dbd-09f761ad472a)

### Expected behavior

没有回复

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/46945475/c819a8cd-7c02-43f6-b808-071dfaacaa22)

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by Harry-zklcdc** [comment]
看 [wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/BingAPI#%E8%81%8A%E5%A4%A9)

你的API地址输错了，hf部署的话，要是 `/api/v1/chat/completions`

**Comment by chaoyu1999** [comment]
> 看 [wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/BingAPI#%E8%81%8A%E5%A4%A9)
> 
> 你的API地址输错了，hf部署的话，要是 `/api/v1/chat/completions`

换了api地址，现在报错405了：
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/46945475/188cd670-d609-489e-99d4-53d7db05439a)

**Comment by Harry-zklcdc** [comment]
> 换了api地址，现在报错405了： [image](https://private-user-images.githubusercontent.com/46945475/297963906-188cd670-d609-489e-99d4-53d7db05439a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDMwMzYsIm5iZiI6MTcwNTY0MjczNiwicGF0aCI6Ii80Njk0NTQ3NS8yOTc5NjM5MDYtMTg4Y2Q2NzAtZDYwOS00ODllLTk5ZDQtNTNkN2RiMDU0MzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA1Mzg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3MTE0MDk2MzE1YTQ5Mjk0YWI5YTI0YmM4ZGI5ZGI2NDQ4YWZhNmQ5ZDI2ODk3M2EwZDBkOGZkMWMyNjhmZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EV0kn2o4-o7ZW-fU2LFLscP6tpIZ8mmkS87pqXtUx38)

你的调用方法是不是不对，要用Post方法哇

调用示例
```bash
curl https://harry-zklcdc-go-proxy-bingai.hf.space/api/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer sk-bing" \
  -d '{
    "model": "Creative-g4t",
    "messages": [
      {
        "role": "user",
        "content": "鲁迅和周树人是什么关系"
      }
    ]
  }'
```

**Comment by chaoyu1999** [comment]
> > 换了api地址，现在报错405了： [image](https://private-user-images.githubusercontent.com/46945475/297963906-188cd670-d609-489e-99d4-53d7db05439a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDMwMzYsIm5iZiI6MTcwNTY0MjczNiwicGF0aCI6Ii80Njk0NTQ3NS8yOTc5NjM5MDYtMTg4Y2Q2NzAtZDYwOS00ODllLTk5ZDQtNTNkN2RiMDU0MzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA1Mzg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3MTE0MDk2MzE1YTQ5Mjk0YWI5YTI0YmM4ZGI5ZGI2NDQ4YWZhNmQ5ZDI2ODk3M2EwZDBkOGZkMWMyNjhmZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EV0kn2o4-o7ZW-fU2LFLscP6tpIZ8mmkS87pqXtUx38)
> 
> 你的调用方法是不是不对，要用Post方法哇
> 
> 调用示例
> 
> ```shell
> curl -X POST https://harry-zklcdc-go-proxy-bingai.hf.space/api/v1/chat/completions \
>   -H "Content-Type: application/json" \
>   -H "Authorization: Bearer sk-bing" \
>   -d '{
>     "model": "Creative-g4t",
>     "messages": [
>       {
>         "role": "user",
>         "content": "鲁迅和周树人是什么关系"
>       }
>     ]
>   }'
> ```

好了调试通了。
**出错原因：直接在前端请求了接口，前端可能有验证机制报错。从后端请求可以正常获取结果。**
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/46945475/078917a6-5901-447f-b813-0cb459446f13)
