### ISSUE TITLE
[Help] 🤔 cloudflare部署完成聊天报错

### ISSUE THREAD

**Issue by ws910616** [Harry-zklcdc/go-proxy-bingai#298]
### Describe the help wanted

Error 1101 Ray ID: 847c70110c375df6 • 2024-01-19 04:47:06 UTC
Worker threw exception
What happened?
You've requested a page on a website (bing.wscdd.net) that is on the [Cloudflare](https://www.cloudflare.com/5xx-error-landing/) network. An unknown error occurred while rendering the page.

What can I do?
If you are the owner of this website:
you should [login to Cloudflare](https://www.cloudflare.com/login?utm_source=error_100x) and check the error logs for bing.wscdd.net.

Cloudflare Ray ID: 847c70110c375df6
Your IP: Click to reveal
Performance & security by [Cloudflare](https://www.cloudflare.com/5xx-error-landing)

![QQ截图20240119125324](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/105333186/2bf358f8-3d4e-435a-a33c-0902d2cffaa1)

### Steps to behave

请问是我部署的问题吗？还是啥问题

### Expected behavior

能够帮忙看看是什么情况

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by Harry-zklcdc** [comment]
没填 `PASS_SERVER`，详细操作请看 [wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/Cloudflare-Worker-%E9%83%A8%E7%BD%B2)

或者 [视频](https://b23.tv/qH8l01c)
