### ISSUE TITLE
[Help] 🤔 调用绘图接口后返回结果有问题

### ISSUE THREAD

**Issue by chaoyu1999** [Harry-zklcdc/go-proxy-bingai#299]
### Describe the help wanted

我在hf上一键部署了项目，且设置了`Go_Proxy_BingAI_USER_TOKEN_1`值为我本地bing 的`_U`值。现在我用post请求绘图api接口，给我返回的结果有问题。
返回的结果里，前两个不知道是什么图片的base64编码，后面的结果虽然有图片链接，但是不是我提词里要画的东西，而是我本地的bing前几天绘图的历史记录。

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/46945475/d44bd21a-6d60-4014-8462-8c1ecf559ea2)

### Steps to behave

hf部署设置好环境变量了。

### Expected behavior

返回正确的图

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by Harry-zklcdc** [comment]
奇了怪了，我研究一下，我这边测试是没有问题的

**Comment by chaoyu1999** [comment]
> 奇了怪了，我研究一下，我这边测试是没有问题的

老哥可否给个测试链接我也看看

**Comment by chaoyu1999** [comment]
> 奇了怪了，我研究一下，我这边测试是没有问题的

今早测试了一下，又好了！但是前两个返回的东西还有，历史记录也有。
紫色框为不知道是啥的base64编码，红色为绘制的图，蓝色为历史记录。
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/46945475/7fb35151-de14-490b-93f2-5aa9bba8220d)

**Comment by Harry-zklcdc** [comment]
估计bing换接口了，我到时候更新一下

**Comment by Harry-zklcdc** [comment]
我这边单元测试结果是正常的
<img width="1053" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/1667da11-fbec-4630-91b2-f45dba3c259b">

**Comment by chaoyu1999** [comment]
> 我这边单元测试结果是正常的 <img alt="image" width="1053" src="https://private-user-images.githubusercontent.com/21104213/298385198-1667da11-fbec-4630-91b2-f45dba3c259b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NDM5MzEsIm5iZiI6MTcwNTg0MzYzMSwicGF0aCI6Ii8yMTEwNDIxMy8yOTgzODUxOTgtMTY2N2RhMTEtZmJlYy00NjMwLTkxYjItZjQ1ZGJhM2MyNTliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDEzMjcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NGU4OTA2NjFiZTU0ZTRlNzUxNWExY2VjZTJhMzExYzBjOTAzZGM5OTg0MTgwMDMzYzc0YWMzMTI3N2M3ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-QoA3XxxtFl-9YX34fiMsGADUQPJNk8D5f-t8dkaAbI">

okk 我在看看怎么回事。

**Comment by Harry-zklcdc** [comment]
奇了怪了，难道还有地域差别？

**Comment by chaoyu1999** [comment]
> 奇了怪了，难道还有地域差别？

我是hf上部署的
