### ISSUE TITLE
怎么给go-proxy-bingai部署CA证书啊？我用的是docker部署，🆘！

### ISSUE THREAD

**Issue by Xqh-Cxy** [Harry-zklcdc/go-proxy-bingai#30]

**Comment by ccodingfundddd** [comment]
caddy

**Comment by Harry-zklcdc** [comment]
反向代理

**Comment by Xqh-Cxy** [comment]
> 反向代理

怎么弄？能具体点吗

**Comment by Harry-zklcdc** [comment]
为什么不问问神奇的NewBing呢😊

**Comment by ilolita945** [comment]
> > 为什么不问问神奇的NewBing呢😊
> 
> 没部署好怎么问呢……

我也是用docker部署，https用我用的nginx web反代

**Comment by Xqh-Cxy** [comment]
> caddy

能分享一下怎么弄吗

**Comment by Harry-zklcdc** [comment]
https://github.com/adams549659584/go-proxy-bingai/issues/282#issuecomment-1605262801

**Comment by skyfly2000** [comment]
最简单办法就是宝塔反代
