### ISSUE TITLE
[Feature] 🌈 添加手机版侧边栏

### ISSUE THREAD

**Issue by Whitekabi** [Harry-zklcdc/go-proxy-bingai#300]
### Describe the help wanted

我刚刚用电脑测试了一下，电脑有历史记录，用手机访问了一下，没有历史记录怎么办？是还没出吗？

就连设置里的历史记录开了都没有怎么回事？电脑就行

### Steps to behave

电脑登录了账号，手机也是（我用电脑把Token，KievRPSSecAuth和_RwBf，发到手机上复制就可以登录了）登录了还是没有
在网页上到处找了，都还是没有

### Expected behavior

手机如果没出这个功能的话，建议出一下

### Screenshots

![5A8BE94714236554F05DF78AA46EF19D](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/132870128/da201a37-a469-4609-b275-f59cae1b7468)

### Versions

版本号
v1.18.10

**Comment by Harry-zklcdc** [comment]
手机版暂不支持，后面会想办法加上

**Comment by Whitekabi** [comment]
> 手机版暂不支持，后面会想办法加上

好的好的，谢谢解释

**Comment by sunzongjian** [comment]
你好，请问z这种错误怎么解决，详情如下图所示
<img width="1089" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/24264891/49b0367d-6c5f-4e8b-8e90-2334ce786d2c">
<img width="482" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/24264891/34bcc5b5-4039-439c-82bf-c66b91de5720">

**Comment by Harry-zklcdc** [comment]
已提交代码, Commit: 83b12202e2082a105186c2f3e9514a129ed13997
