### ISSUE TITLE
[Help] 🤔 How can I add Bing models to my chatgptnextweb app ?

### ISSUE THREAD

**Issue by FlyingHermes** [Harry-zklcdc/go-proxy-bingai#301]
### Describe the help wanted

https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/BingAPI >> I found the website in the documentation. 

### Steps to behave

https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/BingAPI >> I found the website in the documentation. 

### Expected behavior

I already have my vercel.app application running chatgpt-next-web and I want to add Bing models to my application, how can I do this ? 

### Screenshots

![изображение](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/79836672/f23c76bf-b9c2-4126-a43d-b572d3058ccf)

![изображение](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/79836672/255e2ec5-b681-4b17-af7b-7860dd3efb4e)

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by Harry-zklcdc** [comment]
First, you should set the API Endpoint. Second, set the environment `CUSTOM_MODELS`, just like [this](https://huggingface.co/spaces/Harry-zklcdc/chatgpt-next-web/blob/f33847a1260978b1c9a36729472892c21f457b0b/Dockerfile#L3).

And there is a [example site](https://huggingface.co/spaces/Harry-zklcdc/chatgpt-next-web) which deploy on Huggingface

**Comment by Harry-zklcdc** [comment]
> [IMG_20240122_161535.jpg](https://private-user-images.githubusercontent.com/64531014/298509225-717d672c-1c2c-4f24-8d9a-7cbdf0d3372e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTE5NjIsIm5iZiI6MTcwNTkxMTY2MiwicGF0aCI6Ii82NDUzMTAxNC8yOTg1MDkyMjUtNzE3ZDY3MmMtMWMyYy00ZjI0LThkOWEtN2NiZGYwZDMzNzJlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA4MjEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlMGY4NDJkMGZkMDM4ODU3MzRiZGJhZDNkYzYxOWNmNjdmM2Y3ZWI1NTFjYTQzNzkxMmRlNjZlODA0MmZjZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Jw0S6NXfEM5PCaSjYqmJ38YtpV1i7wsaepSjMOBLDmE) [IMG_20240122_161929.jpg](https://private-user-images.githubusercontent.com/64531014/298510275-8d621694-2699-4737-be46-d80b405168af.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTE5NjIsIm5iZiI6MTcwNTkxMTY2MiwicGF0aCI6Ii82NDUzMTAxNC8yOTg1MTAyNzUtOGQ2MjE2OTQtMjY5OS00NzM3LWJlNDYtZDgwYjQwNTE2OGFmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA4MjEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5YzZhYTY3ZTcxOTY5YjdmY2VmMDg1NDg5OWYwODg5MzFjMWI3NDY5NzRiYTVhZDgwOTMyODI1ODBiMjQyMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OX-eM1w5QYjCT1BjETG7Le6Yss9xV4XErYEJtkVZnhE)
> 
> 为啥每次会话的第一个回答都会报错@Harry-zklcdc PC端也是

设置里面关闭系统提示词注入
<img width="1409" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/eabbcf9a-1afe-48a3-8603-e3fe4550fda7">

**Comment by Harry-zklcdc** [comment]
> 应该是ChatGPTNextWeb bug [ChatGPTNextWeb/ChatGPT-Next-Web#3684](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/3684) 这个pull提交了 按理来说应该是只有gpt-模型才会注入系统提示词

这个去 NextWeb 那边询问，和我项目无关

**Comment by Harry-zklcdc** [comment]
> > First, you should set the API Endpoint. Second, set the environment `CUSTOM_MODELS`, just like [this](https://huggingface.co/spaces/Harry-zklcdc/chatgpt-next-web/blob/f33847a1260978b1c9a36729472892c21f457b0b/Dockerfile#L3).
> > And there is a [example site](https://huggingface.co/spaces/Harry-zklcdc/chatgpt-next-web) which deploy on Huggingface
> 
> 演示站点貌似挂了 而且我搭的站点也提示**unexpected end of JSON input**
> 
> [SAVE_20240124_201440.jpg](https://private-user-images.githubusercontent.com/64531014/299309465-0ae91809-7b65-45e8-a089-2b8f1262a169.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMDQ3NjYsIm5iZiI6MTcwNjEwNDQ2NiwicGF0aCI6Ii82NDUzMTAxNC8yOTkzMDk0NjUtMGFlOTE4MDktN2I2NS00NWU4LWEwODktMmI4ZjEyNjJhMTY5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDEzNTQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMTczZWQyNGYxODExZjk4ODNhYjZkNjkzMmJiYTgyOWZhZTA2NWM0NDEzMjI3MmQ4NWI0ODkxNjdjMDM1OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ktraBJ9f75n5Rz9VATHGVmyxCErcfc3NvLxGWem0auA)

<img width="1083" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/16173557-9395-47e7-8c7b-ff70560767a8">
我这边显示要人机验证，这个 API 自动过人机验证的还没完全解决

**Comment by Harry-zklcdc** [comment]
> 演示站貌似又挂了
> 
> ```json
> {
>   "error": true,
>   "message": "empty response"
> }
> ```

没办法，流量太大了，IP 容易就黑了

**Comment by Harry-zklcdc** [comment]
> 演示站貌似又挂了
> 
> ```json
> {
>   "error": true,
>   "message": "empty response"
> }
> ```

修复了这个问题（应该👉🏻👈🏻）
