### ISSUE TITLE
[Bug] 🐛 Designer深色模式显示错误

### ISSUE THREAD

**Issue by gdfhlfkg** [Harry-zklcdc/go-proxy-bingai#302]
### Describe the help wanted

![屏幕截图 2024-01-21 184042](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/104117637/81a97323-c9b1-498a-8823-0c598430185b)

### Steps to behave

在深色模式下点击Designer，发现其在空气下发出耀眼的白光且伴随用户尖锐的爆鸣声

### Expected behavior

字体颜色、背景恢复正常，修复奇怪的推荐选项

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version: 
- Cloudflare

**Comment by Harry-zklcdc** [comment]
图片请检查网络是否正常，至于暗黑模式，Copilot 官方还未适配
