### ISSUE TITLE
[Feature] 🌈 支持关闭 手机版搜索插件

### ISSUE THREAD

**Issue by d4renk** [Harry-zklcdc/go-proxy-bingai#303]
### Describe the problem related to the feature request

开启搜索插件后newbing回答速度大幅度减慢 且回答质量也大幅度降低 希望支持关闭手机版搜索插件

### Describe the solution you'd like

用[Kiwi浏览器](https://play.google.com/store/apps/details?id=com.kiwibrowser.browser)切换到电脑版访问站点，关闭搜索插件，再切回手机版，就可以关掉插件。但其他浏览器即使用电脑版访问，还是显示手机版。

**Comment by Harry-zklcdc** [comment]
和 #300 重复, 关闭一个

**Comment by Harry-zklcdc** [comment]
已提交代码, Commit: 83b12202e2082a105186c2f3e9514a129ed13997
