### ISSUE TITLE
是失效了吗？昨晚还能用来的，今天中午用不了了。

### ISSUE THREAD

**Issue by XCQ0607** [Harry-zklcdc/go-proxy-bingai#306]
1.演示站点人机验证报错：{“code”：500，“message”：“invalid character '\u003c' looking for beginning of value”，“data”：null}
2.huggingface部署的space自动被删除了
3.使用cloudflare部署的bingai中PASSBY_SERVER变量更改为部署在codesandbox的验证服务同样会报错：{“code”：405，“message”：“Method Not Allowed”，“data”：null}

官方修改人机验证规则了还是咋的了？

**Comment by ryanzhaorx** [comment]
1.人机验证服务器挂了(频道里说了)
2.HF的空间是被官方删了(我也是其中之一)
3.可能需要自己在网页里设置

**Comment by Harry-zklcdc** [comment]
演示站已恢复
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/f9768e17-f3f6-45e9-87aa-0c52da4ce142)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/2bb2f9bb-3d3a-4437-8914-185ec7333c5f)

**Comment by ws910616** [comment]
用不了在hugging face部署的验证服务器被删除了，无法验证通过
