### ISSUE TITLE
[Help] 🤔 codesandbox怎么更新啊

### ISSUE THREAD

**Issue by ryanzhaorx** [Harry-zklcdc/go-proxy-bingai#307]
### Describe the help wanted

codesandbox如何更新版本

### Steps to behave

None

### Expected behavior

更新版本

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by Harry-zklcdc** [comment]
shift + ctrl/cmd + p后，输入 rebuild，有一个without cache

**Comment by ryanzhaorx** [comment]
> shift + ctrl/cmd + p后，输入 rebuild，有一个without cache

<img width="642" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/103013573/6279ba41-4f6c-48e6-a451-4a37a2ac7e8b">
是第二个吗

**Comment by Harry-zklcdc** [comment]
对
