### ISSUE TITLE
[Feature] 🌈 Copilot新UI

### ISSUE THREAD

**Issue by dcityteg** [Harry-zklcdc/go-proxy-bingai#308]
### Describe the problem related to the feature request

能否改成官网的Copilot的新UI？就是现UI顶部能否改成这样：
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/132677224/c406f467-819d-4864-b768-b947ebb29590)

官网截图：
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/132677224/362a561c-9076-4a68-8394-63e8835ed6c7)

不知项目能否跟进。

### Describe the solution you'd like

原来是这样（现在UI）：
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/132677224/03526f69-d976-471a-8140-15ecab5c7eed)
希望能改成官网的Copilot新UI：
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/132677224/635ff3fb-df2e-42bf-973f-5386d711e802)

**Comment by Harry-zklcdc** [comment]
不改，和copilot做区分（虽然功能会跟进）

为了项目能长久，不改，原因在QQ频道我说过了
