### ISSUE TITLE
[Help] 🤔 deploy on hf spaces 无法通过人机验证

### ISSUE THREAD

**Issue by d4renk** [Harry-zklcdc/go-proxy-bingai#311]
### Describe the help wanted

构建的空间无法通过人机验证  handless true 和false 都试了
但使用[演示站](https://harry-zklcdc-go-proxy-bingai.hf.space)可以得到正常响应
hf 日志一直提示
`2024-01-24 10:00:15,017 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140457089546704 for <Subprocess at 140457089535568 with name go-proxy-bingai in state RUNNING> (stderr)> (<class 'OSError'>:[Errno 29] Illegal seek [/usr/lib/python3/dist-packages/supervisor/supervisord.py|runforever|220] [/usr/lib/python3/dist-packages/supervisor/dispatchers.py|handle_read_event|270] [/usr/lib/python3/dist-packages/supervisor/dispatchers.py|record_output|204] [/usr/lib/python3/dist-packages/supervisor/dispatchers.py|_log|173] [/usr/lib/python3/dist-packages/supervisor/loggers.py|info|327] [/usr/lib/python3/dist-packages/supervisor/loggers.py|log|345] [/usr/lib/python3/dist-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3/dist-packages/supervisor/loggers.py|doRollover|264])`

### Steps to behave

`2024-01-24 09:54:39,293 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140457089546272 for <Subprocess at 140457089535376 with name go-bingai-pass in state RUNNING> (stderr)> (<class 'OSError'>:[Errno 29] Illegal seek [/usr/lib/python3/dist-packages/supervisor/supervisord.py|runforever|220] [/usr/lib/python3/dist-packages/supervisor/dispatchers.py|handle_read_event|270] [/usr/lib/python3/dist-packages/supervisor/dispatchers.py|record_output|204] [/usr/lib/python3/dist-packages/supervisor/dispatchers.py|_log|173] [/usr/lib/python3/dist-packages/supervisor/loggers.py|info|327] [/usr/lib/python3/dist-packages/supervisor/loggers.py|log|345] [/usr/lib/python3/dist-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3/dist-packages/supervisor/loggers.py|doRollover|264])`
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/64531014/29610397-3996-493f-a9b6-3128cf1bd1d3)

### Expected behavior

得到new bing回复

### Versions

- OS: Windows 10 
- Browser & Version: Chrome 120 
- GoProxiBing Version: v1.19.1

**Comment by Harry-zklcdc** [comment]
你的 HEADLESS 是大写还是小写？这个日志无意义，我看不出任何东西

**Comment by Harry-zklcdc** [comment]
我这边配置了自动刷新，并没有遇到这种情况

**Comment by Harry-zklcdc** [comment]
配置了 Token？

**Comment by Harry-zklcdc** [comment]
你发哪了？

**Comment by Harry-zklcdc** [comment]
我这没收到
