### ISSUE TITLE
[Bug]使用Cloudflare的works直接部署bing项目，人机验证框弹出报错信息

### ISSUE THREAD

**Issue by zyrubber** [Harry-zklcdc/go-proxy-bingai#312]
### Describe the bug

项目使用bjs.js 和work.js部署，添加域名。网页能正常打开，但是输入对话后，弹出校验框报错。部署使用的人机验证地址是作者部署在Hugging Face的项目。也尝试了使用项目中的专门的人机验证，在Hugging Face上部署。同样有错误。网页显示反复跳出人机验证，无法通过。Hugging Face上log弹出错误信息

### Steps to reproduce

Error 1101 Ray ID:        • 2024-01-25 06:27:36 UTC
Worker threw exception
What happened?
You've requested a page on a website (      ) that is on the Cloudflare network. An unknown error occurred while rendering the page.

What can I do?
If you are the owner of this website:
you should login to Cloudflare and check the error logs for bing.neu-tech.eu.org.

Cloudflare Ray ID:        
Your IP: Click to reveal
Performance & security by Cloudflare

### Expected behavior

请对人机验证的部分给出更详尽的部署说明。谢谢

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by Harry-zklcdc** [comment]
教程在写了，别急，等我这几天解决一下循环验证的问题

**Comment by dcityteg** [comment]
同问

**Comment by Harry-zklcdc** [comment]
请检查部署操作是否有问题，[Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/Cloudflare-Worker-%E9%83%A8%E7%BD%B2)
