### ISSUE TITLE
[Bug] 🐛 {"code":500,"message": "Post \"http://localhost:8080\": dial tcp [::1]:8080: connect: connection refused", "data":null}

### ISSUE THREAD

**Issue by chokiproai** [Harry-zklcdc/go-proxy-bingai#313]
### Describe the bug

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/128912789/d3980867-e0a6-49fe-82b7-eb74c99b2ff1)

### Steps to reproduce

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/128912789/80ca2462-5545-40ef-a17a-1b5397ea9d20)

### Expected behavior

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/128912789/4d538a61-2c87-4686-94da-42c46979859f)

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/128912789/4bca46c3-2814-4838-af13-fa03eb5b62ab)

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by Harry-zklcdc** [comment]
无效信息，无法定位问题，如不提供以下信息，该 issue 将在一天后关闭
1. 本体在哪个平台搭建的？
2. 人机验证服务器在哪个平台搭建的？
3. 如何搭建？（贴出搭建教程或者视频地址，或者详细说明）
4. 遇到了什么问题？（截图加说明）

**Comment by chokiproai** [comment]
huggingface

**Comment by chokiproai** [comment]
it is Duplicate this Space from you

**Comment by Harry-zklcdc** [comment]
please try `Factory rebuild`

**Comment by chokiproai** [comment]
it still doesn't work

**Comment by chokiproai** [comment]
It's the same with your space

**Comment by chokiproai** [comment]
it cannot be verified

**Comment by chokiproai** [comment]
If no error is displayed it will get stuck in the verification step
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/128912789/1d4de34a-5f4b-41a2-9f67-0cf6c25214ee)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/128912789/fa5ca993-b6dc-4cce-820b-849a6959b627)

**Comment by chokiproai** [comment]
the problem may lie at https://github.com/Harry-zklcdc/go-bingai-pass

**Comment by Harry-zklcdc** [comment]
It is interesting. My HF Web Site is no problem to pass CF Verifying. 🤔

**Comment by chokiproai** [comment]
it leads to https://huggingface.co/spaces/Harry-zklcdc/chatgpt-next-web which also doesn't work

**Comment by chokiproai** [comment]
it can verify when not using Embed Link, but there is a new problem that https://huggingface.co/spaces/Harry-zklcdc/chatgpt-next-web cannot be used

**Comment by Harry-zklcdc** [comment]
Use the latest version to have a try? I think maybe fix.
