### ISSUE TITLE
[Help] 🤔 自动验证还能使用吗

### ISSUE THREAD

**Issue by bincooo** [Harry-zklcdc/go-proxy-bingai#315]
### Describe the help wanted

RT

### Steps to behave

//

### Expected behavior

//

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version: 

### Additional context

//

**Comment by Harry-zklcdc** [comment]
哪个自动验证？

**Comment by bincooo** [comment]
应该是这个？
https://github.com/Harry-zklcdc/go-bingai-pass

**Comment by Harry-zklcdc** [comment]
等教程，在写了，别急（急的话你来帮我写）

**Comment by Harry-zklcdc** [comment]
教程写完了 https://github.com/Harry-zklcdc/go-proxy-bingai/wiki
