### ISSUE TITLE
[Feature] 🌈 类搜索引擎的提问

### ISSUE THREAD

**Issue by dcityteg** [Harry-zklcdc/go-proxy-bingai#316]
### Describe the problem related to the feature request

在地址栏加入search?q=(这是一个问题)
来实现类似搜索引擎的快速提问。
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/132677224/b80ba464-824e-4e9c-9821-fe5f2f7002a4)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/132677224/1f3adaf4-5674-48d4-addd-bfdbccf86033)

但是在项目中无法直接使用这个，所以能否通过在URL的末尾加上?q=xxx来实现这个功能？比如：
https://xxx.com/web/search?q=xxx&?showconv=1#/

### Describe the solution you'd like

 -

**Comment by dcityteg** [comment]
https://xxx.com/web/search?q=xxx&?showconv=1#/
这链接格式好像不对，不过也不管了

**Comment by Harry-zklcdc** [comment]
不打算支持，（个人很不喜欢这个功能）
