### ISSUE TITLE
[Feature] 🌈 Copilot换新的聊天界面了

### ISSUE THREAD

**Issue by ningguoxu** [Harry-zklcdc/go-proxy-bingai#317]
### Describe the problem related to the feature request

Copilot换新的聊天界面了

### Describe the solution you'd like

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/87106666/dff8d092-0afe-409a-9ce5-18ef5f6b628b)

**Comment by jsdianman** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/143573972/48462d66-d493-425f-bec2-088667b98633)

**Comment by Harry-zklcdc** [comment]
https://github.com/Harry-zklcdc/go-proxy-bingai/issues/308#issuecomment-1905322075

**Comment by Harry-zklcdc** [comment]
我这还是旧版

**Comment by dcityteg** [comment]
我的昨天是新的，今天变成旧的了（

**Comment by Harry-zklcdc** [comment]
已提交代码, Commit: 94614406b316fd06121e4a4e62844898f3c1c68e
