### ISSUE TITLE
[Bug] 🐛 API调用提示要验证，网页端不会

### ISSUE THREAD

**Issue by dcityteg** [Harry-zklcdc/go-proxy-bingai#319]
### Describe the bug

在调用API来使用的时候，有时候会提示User needs to solve CAPTCHA to continue.
但是，如果在调用的网页使用，就不会要验证

### Steps to reproduce

在第三方聊天项目调用一个正常的项目的API，有几率触发。

### Expected behavior

自动验证能够正常执行

### Versions

- OS: Windows11
- Browser & Version: Edge
- GoProxiBing Version: >最新

**Comment by Harry-zklcdc** [comment]
在研究了，别急

**Comment by Harry-zklcdc** [comment]
已提交代码, Commit: aa72a2e329718b2a971f79a54b802bf91f9ff1c8

**Comment by dopamines-001** [comment]
still exists on api based on CF page deploy

**Comment by jhale1206636** [comment]
still exists on api based on CF page deploy
