### ISSUE TITLE
能否添加暗黑模式

### ISSUE THREAD

**Issue by wurenzhiwen666** [Harry-zklcdc/go-proxy-bingai#32]

**Comment by Harry-zklcdc** [comment]
add ToDo List

**Comment by Harry-zklcdc** [comment]
已添加
Commit: 76b6fd73b80daa0d796ef1e28d4dd0dfd6433ca9
Release: https://github.com/Harry-zklcdc/go-proxy-bingai/releases/tag/v1.10.2
