### ISSUE TITLE
[Help] 🤔 Copilot如何画图

### ISSUE THREAD

**Issue by dcityteg** [Harry-zklcdc/go-proxy-bingai#320]
### Describe the help wanted

在windows11的Copilot里怎么绘图？调用指令之后没有展示，但是在go-proxy-bingai里面有。

### Steps to behave

/

### Expected behavior

/

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by Harry-zklcdc** [comment]
不是这个项目解决的问题

> PS: 为什么不问问 BingAI 呢？

**Comment by dcityteg** [comment]
是按照WIKI配置的
