### ISSUE TITLE
[Feature] 🌈 Supports more OPENAI models like GPT-4-turbo and adds https://.../v1

### ISSUE THREAD

**Issue by chokiproai** [Harry-zklcdc/go-proxy-bingai#324]
### Describe the problem related to the feature request

- Supports call OPENAI models like GPT-4-turbo and adds https://.../v1. Similar to OPENAI models
- So that projects similar to this project can call the API
> https://github.com/Chanzhaoyu/chatgpt-web

### Describe the solution you'd like

- Supports call OPENAI models like GPT-4-turbo and adds https://.../v1. Similar to OPENAI models
- So that projects similar to this project can call the API
> https://github.com/Chanzhaoyu/chatgpt-web

### Additional context

https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo
https://github.com/weaigc/bingo

**Comment by Harry-zklcdc** [comment]
Please Read [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/BingAPI), please

**Comment by chokiproai** [comment]
Thank you. i have read the wiki but i don't know where to add the model

**Comment by chokiproai** [comment]
Thank you

**Comment by chokiproai** [comment]
How to add:
https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/BingAPI#%E8%BF%94%E5%9B%9E%E7%A4%BA%E4%BE%8B

**Comment by Harry-zklcdc** [comment]
eh？I need more detail.

**Comment by chokiproai** [comment]
How to add model

**Comment by chokiproai** [comment]
which file to add?

**Comment by chokiproai** [comment]
I want to add another model name

**Comment by Harry-zklcdc** [comment]
on the API response？

**Comment by chokiproai** [comment]
yes

**Comment by chokiproai** [comment]
I want to add model names of openai

**Comment by chokiproai** [comment]
How can I add models so that they display in /v1/models

**Comment by Harry-zklcdc** [comment]
I think you can use this project to manage you API Endpoint
https://github.com/songquanpeng/one-api

**Comment by chokiproai** [comment]
I know that

**Comment by Harry-zklcdc** [comment]
https://github.com/Harry-zklcdc/go-proxy-bingai/blob/master/api/v1/models.go
https://github.com/Harry-zklcdc/go-proxy-bingai/blob/master/api/v1/model.go
https://github.com/Harry-zklcdc/bing-lib/blob/main/chat.go#L15

**Comment by chokiproai** [comment]
How to run it?

> https://github.com/Harry-zklcdc/go-proxy-bingai/blob/master/api/v1/models.go https://github.com/Harry-zklcdc/go-proxy-bingai/blob/master/api/v1/model.go https://github.com/Harry-zklcdc/bing-lib/blob/main/chat.go#L15

**Comment by Harry-zklcdc** [comment]
You should learn how to run Golang & Vue3 projects. I won't waste time on such meaningless issues
