### ISSUE TITLE
[Bug] 🐛 没魔法的情况下，designer里的三张图片不显示。 有时填了_u值后，会出现反复验证的情况。

### ISSUE THREAD

**Issue by GforPG** [Harry-zklcdc/go-proxy-bingai#325]
### Describe the bug

没魔法的情况下，designer里的三张图片不显示。 有时填了_u值后，会出现反复验证的情况。

### Steps to reproduce

试试

### Expected behavior

修复

### Screenshots

![截图20240130202252](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/138672705/08e3ff4d-a59b-4ddf-b402-bbdae255e372)

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by Harry-zklcdc** [comment]
循环人机验证请看 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/FAQ#q-%E5%BE%AA%E7%8E%AF%E4%B8%80%E7%9B%B4%E4%BA%BA%E6%9C%BA%E9%AA%8C%E8%AF%81)

这个图片我到时候做个反代

**Comment by Harry-zklcdc** [comment]
Designer 的问题已修复, Commit: 67f60369bf8f8672c966a3f23d9db541900e3825

**Comment by GforPG** [comment]
大佬，Designer的图片问题好像还没好，旧浏览器加载过图片的可以显示（像是缓存里的），但新浏览器显示不出来

**Comment by Harry-zklcdc** [comment]
你是不是套了CF，套了CF的话去缓存设置里面把缓存清了，旧浏览器也清了缓存试试
