### ISSUE TITLE
[Help] 🤔 codesandbox无法部署

### ISSUE THREAD

**Issue by wurenzhiwen** [Harry-zklcdc/go-proxy-bingai#329]
### Describe the help wanted

提示失效
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/118254009/b4328245-686c-4e15-8086-6dbb8186342e)

### Steps to behave

无

### Expected behavior

成功部署

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by ryanzhaorx** [comment]
这好像跟你的额度有关，等Harry来看一下吧

**Comment by Harry-zklcdc** [comment]
我的免费额度用完了，我这几天重新搞一下吧

**Comment by Harry-zklcdc** [comment]
已修复
