### ISSUE TITLE
[Bug] 🐛 在1.19.7（Hugging Face部署）版本中人机验证时有时无无法正常回复消息

### ISSUE THREAD

**Issue by Super12138** [Harry-zklcdc/go-proxy-bingai#332]
### Describe the bug

详见视频

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/70494801/d9b5d024-cec8-4517-bd23-29ab618ff56b)

https://github.com/Harry-zklcdc/go-proxy-bingai/assets/70494801/469a28e3-2e0e-42e8-8cc7-dc7d09613b3c

### Steps to reproduce

1. 打开部署好的网页
2. 随便选择一个模式
3. 输入任意内容并回车

### Expected behavior

正常的与我对话，不要像视频里一样弹出又消失再弹出人机验证的框框

### Versions

- OS: Windows 11（在Android手机上也发现了这个问题，Android 10）
- Browser & Version: 121.0.6167.140
- GoProxiBing Version: 1.19.7

**Comment by Harry-zklcdc** [comment]
能找到触发条件吗？我这复现不出来

方便F12 调试看一下Network 抓包和 Console 输出吗？

**Comment by Harry-zklcdc** [comment]
没有提供更多信息, 关闭此 issue，如有问题重新打开
