### ISSUE TITLE
[Bug] 🐛 Error of not displaying images when viewing details

### ISSUE THREAD

**Issue by chokiproai** [Harry-zklcdc/go-proxy-bingai#334]
### Describe the bug

Error of not displaying images when viewing details

### Steps to reproduce

.

### Expected behavior

https://github.com/Harry-zklcdc/go-proxy-bingai/commit/67f60369bf8f8672c966a3f23d9db541900e3825

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/128912789/7e409ec5-d529-4864-8c05-076d576fc9dd)

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version: 

### Additional context

https://harry-zklcdc-go-proxy-bingai.hf.space

**Comment by Harry-zklcdc** [comment]
<img width="818" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/c0b7d77d-ae8f-4a9a-8114-054ae4f4bf7a">

More Detail Need

**Comment by chokiproai** [comment]
error appears when using copilot to draw

**Comment by chokiproai** [comment]
maybe it just happens with my account

**Comment by chokiproai** [comment]
When creating an image, sometimes an option will appear when clicking on the image ![image](https://private-user-images.githubusercontent.com/128912789/302018963-7e409ec5-d529-4864-8c05-076d576fc9dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NTAyMDAsIm5iZiI6MTcwNjk0OTkwMCwicGF0aCI6Ii8xMjg5MTI3ODkvMzAyMDE4OTYzLTdlNDA5ZWM1LWQ1MjktNDg2NC04YzA1LTA3NmQ1NzZmYzlkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QwODQ1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjI1NDE0NDQxYjI2MjljZjgzMzc2NGY4OWIyMTBkODY2MWU2OGQ5NzQ0MTVjZmNhODk3ZDhlYzMxMDg5OTBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.odwpoWtqLy1r8w2Ken0SwQTP23z8v0TlwR1GLh5Qu3A)

**Comment by chokiproai** [comment]
I think it used "designer.microsoft.com" to create the image

**Comment by Harry-zklcdc** [comment]
Check your code. These don't happend on my code version.

**Comment by chokiproai** [comment]
https://github.com/Harry-zklcdc/go-proxy-bingai/assets/128912789/78f34351-ed88-464a-b89b-cdb3f04c5f31

**Comment by chokiproai** [comment]
> Untitled.project.mp4

maybe it only works with my account

**Comment by Harry-zklcdc** [comment]
fix, Commit: 65a322598e027adc0b646018a244877bab4b2b93
