### ISSUE TITLE
Okay I keep name of the original authors now unblock me please and i fork the repo according to your instructions

### ISSUE THREAD

**Issue by rkihacker** [Harry-zklcdc/go-proxy-bingai#336]
Okay I keep name of the original authors now unblock me please and i fork the repo according to your instructions

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/148688885/732100b6-c4fd-4994-b408-00271ef4a84e)

**Comment by Niansuh** [comment]
Sir

**Comment by Niansuh** [comment]
Now can i tranlsate this into English

**Comment by Harry-zklcdc** [comment]
> Now can i tranlsate this into English

Yes. But You should keep my COMMIT HISTORY. And DON'T REMOVE ORIGIN AUTHOR INFO according to the MIT agreement.

> **PS: Your other repositories also violation of open source agreement.**

**Comment by Niansuh** [comment]
Okay can i add one more author of my profile including you and adam

**Comment by Harry-zklcdc** [comment]
In my opinion, I think you should keep my COMMIT history that is regarded as follow open source agreement.
