### ISSUE TITLE
[Help] 🤔 always loading with IvfoLO3XuUzsCyfv53CD-ckZU3s.br.js error

### ISSUE THREAD

**Issue by pavlelee** [Harry-zklcdc/go-proxy-bingai#337]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

help debug reason with IvfoLO3XuUzsCyfv53CD-ckZU3s.br.js EOF

### Steps to behave

deploy https bingai with docker

### Expected behavior

open normal bingai

### Screenshots

<img width="1726" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/5382358/3ea89a0f-69a0-474c-b31c-a745c53983eb">

### Deploy

Docker

### OS & Version

Linux VM-0-10-centos 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 22 13:25:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Browser & Version

Chrome 121.0.6167.85

### GoProxiBingAI Version

v1.20.0

**Comment by Harry-zklcdc** [comment]
Check your server network that could get https://www.bing.com/rp/IvfoLO3XuUzsCyfv53CD-ckZU3s.br.js

And if not, you can change `UI Version` to `v2` on Advanced Settings.

**Comment by Harry-zklcdc** [comment]
If you have any probeln, reopen issue. Clonse now.
