### ISSUE TITLE
[Bug] 🐛 worker部署，升级到1.20.x后，一直“很抱歉，似乎出现错误。 让我们重新开始吧。”

### ISSUE THREAD

**Issue by GforPG** [Harry-zklcdc/go-proxy-bingai#342]
### Confirmations

- [X] #343

### Describe the bug

worker部署，旧版很流畅，升级到1.20.x后，一直“很抱歉，似乎出现错误。 让我们重新开始吧。”而且UI刷新的时候不停新旧交替，一键重置也一样。中间的大图显示不出来。

### Steps to reproduce

worker部署，升级到1.20.x后，一直“很抱歉，似乎出现错误。 让我们重新开始吧。”而且UI刷新的时候不停新旧交替，一键重置也一样。中间的大图显示不出来。

### Expected behavior

修复

### Deploy

Cloudflare Worker

### OS & Version

windows11,10

### Browser & Version

chrome 121.0.6167.140

### GoProxiBingAI Version

v1.20.x

**Comment by liliwen365** [comment]
现在墙内，墙外都访问不了，现在正在尝试连接
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/76478019/2c702f24-febc-422d-8d65-9fe5ce18ad78)

**Comment by Harry-zklcdc** [comment]
检查你自己的网络问题，演示站是没有问题的

<img width="1042" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/6c12088b-5f32-466a-90db-ad5380ecb419">

**Comment by Harry-zklcdc** [comment]
UI 刷新一直切换、中间的图标显示不出来，是因为 v3 界面还在灰度测试中，只有有权限的 `MUID` Cookie 才能正常显示，可以多次一键重置，来获取有权限的 `MUID` Cookie，或者在高级设置中把界面换到v2

**Comment by zhanghxiao** [comment]
> UI 刷新一直切换、中间的图标显示不出来，是因为 v3 界面还在灰度测试中，只有有权限的 `MUID` Cookie 才能正常显示，可以多次一键重置，来获取有权限的 `MUID` Cookie，或者在高级设置中把界面换到v2

huggingface是不是开始不支持部署最新版的了，我看现在好像是直接连号一起封

**Comment by Harry-zklcdc** [comment]
> huggingface是不是开始不支持部署最新版的了，我看现在好像是直接连号一起封

对，我还在尝试有没有办法绕过他们的检测

> PS: 我又被删号了

**Comment by GforPG** [comment]
> 演示站会这样不？

[bingai.zklcdc.xyz](https://bingai.zklcdc.xyz/)这个不会

**Comment by Harry-zklcdc** [comment]
你再试试吧，刚才我刷新了缓存了，可能是缓存问题导致的

**Comment by GforPG** [comment]
> > 演示站会这样不？
> 
> [bingai.zklcdc.xyz](https://bingai.zklcdc.xyz/)这个不会

https://bingai-cfwk.zklcdc.xyz/这个会！

**Comment by Harry-zklcdc** [comment]
> https://bingai-cfwk.zklcdc.xyz

你把你电脑上的缓存清一清，实在不行「一键重置」

**Comment by GforPG** [comment]
> > https://bingai-cfwk.zklcdc.xyz
> 
> 你把你电脑上的缓存清一清，实在不行「一键重置」

弱弱问一句，演示丫的人机验证服务器是用https://zklcdc-pass.hf.space吗？

**Comment by Harry-zklcdc** [comment]
不是

**Comment by Harry-zklcdc** [comment]
bypass.zklcdc.xyz

**Comment by GforPG** [comment]
> bypass.zklcdc.xyz

哈，我估计问题就在这里了

**Comment by Harry-zklcdc** [comment]
不是，我自己用的好好的，三个演示站全是这个集中验证点

**Comment by GforPG** [comment]
> 不是，我自己用的好好的，三个演示站全是这个集中验证点

我是说，我用了[https://zklcdc-pass.hf.space]这个，所以才不行；现在改成bypass.zklcdc.xyz，就可以了

**Comment by Harry-zklcdc** [comment]
昨天抱脸的部署方式全被封杀了

**Comment by GforPG** [comment]
> 昨天抱脸的部署方式全被封杀了

我才知道
