### ISSUE TITLE
How to get api key and base url🤔 

### ISSUE THREAD

**Issue by Niansuh** [Harry-zklcdc/go-proxy-bingai#345]
How to get api key and base url🤔 

https://bingapi.zklcdc.xyz/

**Comment by Harry-zklcdc** [comment]
Read Wiki, Wiki say everything. 

I won't waste time on meaningless issues like this. Next time I ask questions that have been written in the wiki, I will either **close or delete** them directly

**Comment by Niansuh** [comment]
wait how to get api for chatgpt-next-web please please
