### ISSUE TITLE
[Help] 🤔 codesandbox部署无法使用

### ISSUE THREAD

**Issue by zhengqwe** [Harry-zklcdc/go-proxy-bingai#347]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

按照Wiki操作，点击「Preview: 8080」后只显示`{"result":{},"error":{}}`

### Steps to behave

按照Wiki操作，到点击「Preview: 8080」这一步

### Expected behavior

正常使用

### Deploy

CodeSandbox

### OS & Version

Windows 10

### Browser & Version

Edge 121.0.0.0

### GoProxiBingAI Version

v1.20.3

**Comment by Harry-zklcdc** [comment]
应该preview 7860，我改了配置，但是教程还没更新，之后我改一下

**Comment by Harry-zklcdc** [comment]
链接地址出来，在浏览器输入，别用自带的那个webview用

**Comment by Harry-zklcdc** [comment]
> 还是用不了，一堆502错误（rebuild过了），难道这种部署方式也寄了？ [image](https://private-user-images.githubusercontent.com/103168200/304302003-8d79543f-9e71-4a7d-834d-33bc73266fcf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MDg5MzAsIm5iZiI6MTcwNzgwODYzMCwicGF0aCI6Ii8xMDMxNjgyMDAvMzA0MzAyMDAzLThkNzk1NDNmLTllNzEtNGE3ZC04MzRkLTMzYmM3MzI2NmZjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QwNzE3MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjgyNmViNzc4ODIyMjFhNGM2ZmI5OWQ1NmY3ZDIwNzU5OGZhN2Q2NjYxYjEyMDRhYmU5Y2IzODdmZWExNjczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xx-pdyxONNR4lztN2emZwHsAYmCWD7AQt8OM3g-Zk1E)

并没有，你看我演示站不还在嘛？试试群里那个方法咯

**Comment by Harry-zklcdc** [comment]
CodeSandbox 教程已更新，请重新部署试试看

**Comment by Harry-zklcdc** [comment]
你去频道或者 tg 问问吧，交流容易一些

**Comment by Harry-zklcdc** [comment]
https://github.com/Harry-zklcdc/go-proxy-bingai/issues/348#issuecomment-1943298828
