### ISSUE TITLE
[Help] 🤔 codesandbox doesn't work

### ISSUE THREAD

**Issue by chokiproai** [Harry-zklcdc/go-proxy-bingai#348]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

`https://tkgrg2-8080.csb.app`
error;  正在尝试重新连接...
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/128912789/aad79be7-bd58-40c2-87fa-f5fc3cd874b7)

### Steps to behave

`https://tkgrg2-8080.csb.app`
error;  正在尝试重新连接...
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/128912789/aad79be7-bd58-40c2-87fa-f5fc3cd874b7)

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/128912789/aad79be7-bd58-40c2-87fa-f5fc3cd874b7)

### Deploy

CodeSandbox

### OS & Version

Windows 11

### Browser & Version

Chrome latest version

### GoProxiBingAI Version

v1.20.3

##### Still works with Cloudflare Zero Trust Tunnel
- `https://bingai-csb.zklcdc.xyz`
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/128912789/58c0e076-8a59-44be-b617-a21caab48e58)

**Comment by Harry-zklcdc** [comment]
Try `Settings` -> `Push-Button Reset`(设置 -> 一键重置), just because the suffix of domain `csb.app` will push some cookies to make 502 happend. So try use Cloudflare Zero Trust Tunnel direction proxy like #338

**Comment by chokiproai** [comment]
it has no effect

**Comment by chokiproai** [comment]
Is there any way without using Cloudflare Zero Trust Tunnel?

**Comment by chokiproai** [comment]
You can use Cloudflare Worker... to change the domain name

**Comment by chokiproai** [comment]
for no domain name, payment card

**Comment by Harry-zklcdc** [comment]
> for no domain name, payment card

Use paypel.

**Comment by chokiproai** [comment]
> Cloudflare Worker

Thanks and I'm using it, is there any way to use Cloudflare Worker etc

**Comment by chokiproai** [comment]
> > for no domain name, payment card
> 
> Use paypel.

Thanks and I'm using it, is there any way to use Cloudflare Worker etc

**Comment by Harry-zklcdc** [comment]
> Thanks and I'm using it, is there any way to use Cloudflare Worker etc

No, it still push some cookies.
