### ISSUE TITLE
我的cloudF服务器貌似没法直连，是我哪里搞错了吗？

### ISSUE THREAD

**Issue by landones** [Harry-zklcdc/go-proxy-bingai#35]
我在完整复制了作者的worker代码过后，需要使用魔法才能看到服务器部署成功的页面，而且在自己部署的项目内也需要魔法才能看到延迟，否则就是红色错误和无法访问部署页面。

**Comment by Harry-zklcdc** [comment]
那就是被墙了，或者就是被 sni阻断 了，目前无解
