### ISSUE TITLE
[Help] 🤔 我在部署时填入了教程中的示例地址，但使用时卡在自动通过人机验证

### ISSUE THREAD

**Issue by CreeperAWA** [Harry-zklcdc/go-proxy-bingai#350]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

我在使用Cloudflare Worker 部署时填入了教程中的示例地址(https://bypass.zklcdc.xyz)，使用时卡在自动通过人机验证，在示例站点(https://bingai.zklcdc.xyz/)使用时也出现了这个情况，无法对话

### Steps to behave

我确定我严格按照教程完成了Cloudflare Worker 部署，填写了wiki中的人机验证服务地址，但我没有自定义域名
我访问了Worker控制台提供的链接
填入了我的cookie
向Copilot说：“你好” 但卡在自动通过人机验证

### Expected behavior

我想要正常使用自动通过人机验证/手动通过

### Screenshots

我在向Copilot说“你好”后陷入了这个状态
<img width="923" alt="PixPin_2024-02-16_15-34-06" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/134939494/a8910c6e-066a-4e87-a49e-204ed8d9edcc">
我查看了Worker控制台，没有看到任何错误，浏览器控制台有ERR_NAME_NOT_RESOLVED

### Deploy

Cloudflare Worker

### OS & Version

Windows 11 专业工作站版 23H2

### Browser & Version

Google Chrome 121.0.6167.161（正式版本） （64 位）

### GoProxiBingAI Version

v2.0.1

**Comment by Harry-zklcdc** [comment]
检查你的DNS，ERR_NAME_NOT_RESOLVED说明你的DNS出问题了

**Comment by mountainguan** [comment]
遇到的一样的情况，前面测试还好好的，后面忽然不行了，cloudflare worker搭建和vercel搭建都忽然不行。
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/2704026/910d8e42-2c34-4efc-8e3d-63563b6a6c09)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/2704026/57b5c106-dc6d-4055-a778-a53fad18873a)

**Comment by CreeperAWA** [comment]
> 检查你的 DNS，ERR_NAME_NOT_RESOLVED 说明你的 DNS 出问题了

我之前使用了Simple DNSCrypt，关闭以后连自动通过人机验证中都没有了，提示ERR_NAME_NOT_RESOLVED和ERR_CONNECTION_RESET，过了一会界面提示 正在尝试重新连接

**Comment by Harry-zklcdc** [comment]
你在哪个地区？BYPASS_SERVER在哪填的？

**Comment by mountainguan** [comment]
> 检查你的DNS，ERR_NAME_NOT_RESOLVED说明你的DNS出问题了
cf worker的演示站点也不行，但是vercel那边的演示站点却可以，我的物理地址是广东的
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/2704026/4d8c5dc7-098d-4bda-9dc3-97a513cfdc43)

**Comment by Harry-zklcdc** [comment]
> 遇到的一样的情况，前面测试还好好的，后面忽然不行了，cloudflare worker搭建和vercel搭建都忽然不行。 

我现在没法触发人机验证，没法复现，重置了很多次都没触发😂

**Comment by Harry-zklcdc** [comment]
目前已知浙江和福建实行域名白名单制度，直接 SNI 拦截

**Comment by CreeperAWA** [comment]
> 目前已知浙江和福建实行域名白名单制度，直接 SNI 拦截

我是武汉联通的，现在访问演示站点(https://bingai.zklcdc.xyz/)也是一样的状况，连自动通过中的提示都没有

**Comment by CreeperAWA** [comment]
> 检查你的 DNS，ERR_NAME_NOT_RESOLVED 说明你的 DNS 出问题了

我如果用浏览器直接访问https://bypass.zklcdc.xyz/会立即返回{"code":405,"message":"Method Not Allowed","data":null}

**Comment by Harry-zklcdc** [comment]
我找到 bug 在哪了，已修复，Cloudflare Worker 代码要换成最新的

**Comment by CreeperAWA** [comment]
> 我找到 bug 在哪了，已修复，Cloudflare Worker 代码要换成最新的

感谢

**Comment by Harry-zklcdc** [comment]
如果没有问题就关闭此issue

**Comment by CreeperAWA** [comment]
> 如果没有问题就关闭此 issue

我重新弄了一遍还是有问题啊(

**Comment by CreeperAWA** [comment]
> 如果没有问题就关闭此 issue

仓库还是17小时前更新啊

**Comment by Harry-zklcdc** [comment]
仓库代码没问题，bypass的代码问题

**Comment by Harry-zklcdc** [comment]
你看看演示站有没有问题，演示站没问题就说明代码是正常的

**Comment by CreeperAWA** [comment]
> 你看看演示站有没有问题，演示站没问题就说明代码是正常的

不响应，自动过验证的提示都没有
<img width="923" alt="PixPin_2024-02-16_19-54-24" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/134939494/a051206a-d231-4703-a908-54a2abaf61d0">

**Comment by Harry-zklcdc** [comment]
> 不响应，自动过验证的提示都没有 
重新进入，有CF墙

**Comment by CreeperAWA** [comment]
> > 不响应，自动过验证的提示都没有
> > 重新进入，有 CF 墙

换了台电脑
<img width="887" alt="PixPin_2024-02-16_20-12-26" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/134939494/c93d3c5e-2c3b-441c-8e3c-89b2e8e080e0">

**Comment by Harry-zklcdc** [comment]
> 换了台电脑 

不是这个演示站，用 bingai-cfwk.zklcdc.xyz 那个

**Comment by CreeperAWA** [comment]
> > 换了台电脑
> 
> 不是这个演示站，用 bingai-cfwk.zklcdc.xyz 那个

还是不行
<img width="887" alt="PixPin_2024-02-16_20-12-26" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/134939494/0f5fcd85-f55c-472a-9b85-868e32397c74">

**Comment by CreeperAWA** [comment]
> > 换了台电脑
> 
> 不是这个演示站，用 bingai-cfwk.zklcdc.xyz 那个

还是不行
<img width="923" alt="PixPin_2024-02-16_20-23-08" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/134939494/3a90bb62-0a07-4b22-9360-c0f4101eca66">

**Comment by Harry-zklcdc** [comment]
> 还是不行 

403是没过CF墙

**Comment by CreeperAWA** [comment]
用了魔法还是不行
<img width="923" alt="PixPin_2024-02-16_20-28-55" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/134939494/d115b1f9-0811-4657-b4a5-78134c3fbf3b">

**Comment by Harry-zklcdc** [comment]
![Screenshot_2024-02-16-20-31-54-144_com kiwibrowser browser-edit](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/b57e55a8-211e-4069-938f-81503201751a)

我这没问题，你那一键重置试试吧，就是没过CF墙

**Comment by CreeperAWA** [comment]
> ![Screenshot_2024-02-16-20-31-54-144_com kiwibrowser browser-edit](https://private-user-images.githubusercontent.com/21104213/305414779-b57e55a8-211e-4069-938f-81503201751a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwODc3NjMsIm5iZiI6MTcwODA4NzQ2MywicGF0aCI6Ii8yMTEwNDIxMy8zMDU0MTQ3NzktYjU3ZTU1YTgtMjExZS00MDY5LTkzOGYtODE1MDMyMDE3NTFhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDEyNDQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlNTJlYmE5OWIzYWYzN2EyMTVjODMxMjZlM2JhYTYyOGExYjUwNmNjZmM5NjE2Y2Y5MjI1ZGZlZjc3Yzc2ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C4CZ-iwYSRvep7XTK0n5caDnPtpFxcs1JWXhKzdGT88)
> 
> 我这没问题，你那一键重置试试吧，就是没过 CF 墙

一键重置+魔法也不行，我明天再试试吧

**Comment by chokiproai** [comment]
Strangely, it works on the mobile version, but on pc it crashes:
- PC
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/128912789/1aaf5674-d537-40d1-b613-92090c76e0c1)
- Mobile
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/128912789/745aef32-c0c6-44bc-9404-b2494e0d781f)

**Comment by CreeperAWA** [comment]
> ![Screenshot_2024-02-16-20-31-54-144_com kiwibrowser browser-edit](https://private-user-images.githubusercontent.com/21104213/305414779-b57e55a8-211e-4069-938f-81503201751a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwOTM0NzcsIm5iZiI6MTcwODA5MzE3NywicGF0aCI6Ii8yMTEwNDIxMy8zMDU0MTQ3NzktYjU3ZTU1YTgtMjExZS00MDY5LTkzOGYtODE1MDMyMDE3NTFhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDE0MTkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyODc2NjlhZDdjMmEyYjIzNmEzY2FjMTQ5MzA0MTJlMTQ3Y2RiMTNlZjE0YjI1NDlhYmFlMTczMTY4ZjIzMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IHd4DphtURNeCa8Q8uIaaJ-MwOszONYu-r3Z9p1fchE)
> 
> 我这没问题，你那一键重置试试吧，就是没过 CF 墙

解决了，谢谢

**Comment by CreeperAWA** [comment]
> ![Screenshot_2024-02-16-20-31-54-144_com kiwibrowser browser-edit](https://private-user-images.githubusercontent.com/21104213/305414779-b57e55a8-211e-4069-938f-81503201751a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwOTUyMzQsIm5iZiI6MTcwODA5NDkzNCwicGF0aCI6Ii8yMTEwNDIxMy8zMDU0MTQ3NzktYjU3ZTU1YTgtMjExZS00MDY5LTkzOGYtODE1MDMyMDE3NTFhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDE0NDg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyMDBhMjczMDdjOTAzNGY5N2E2MTkzYmU2MDllMjljZTA4NTA3YWMxMDQwMjJjZWVjN2FkZWY1MDEzNDczYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9dljtYUwZuSk5-tvFfeeCEDDUF_ngEk4e1BwrpunKsY)
> 
> 我这没问题，你那一键重置试试吧，就是没过 CF 墙

啊，不对，是解决了一半

**Comment by CreeperAWA** [comment]
> bingai-cfwk.zklcdc.xyz

现在我自己的站点和演示站点都出了这个问题，选择聊天服务器时用Cloudflare Worker回不停验证(显示了一下消失，然后又出现)，这样有了几次以后我想复现又不行了，变成要同意协议，点继续又一直验证的了(如GIF所示)
![PixPin_2024-02-16_23-08-28](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/134939494/28cbe067-065f-4209-8aa4-bc2d0831d62c)

**Comment by CreeperAWA** [comment]
> > bingai-cfwk.zklcdc.xyz
> 
> 现在我自己的站点和演示站点都出了这个问题，选择聊天服务器时用 Cloudflare Worker 回不停验证 (显示了一下消失，然后又出现)，这样有了几次以后我想复现又不行了，变成要同意协议，点继续又一直验证的了 (如 GIF 所示) ![PixPin_2024-02-16_23-08-28](https://private-user-images.githubusercontent.com/134939494/305456342-28cbe067-065f-4209-8aa4-bc2d0831d62c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwOTY1NTIsIm5iZiI6MTcwODA5NjI1MiwicGF0aCI6Ii8xMzQ5Mzk0OTQvMzA1NDU2MzQyLTI4Y2JlMDY3LTA2NWYtNDIwOS04YWE0LWJjMmQwODMxZDYyYy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNlQxNTEwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZGE0NzliNTQzMDgwYzhkY2MxODk1Njk5YjA3ODEyNzQwYjdhYzc1Y2QwODVjYjE3OTNhNGMzMDlhODUxNTc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tKM7sl4Asrxp6fGSZ32-ZTLI4DqrZHy-0UEAVSBm6G4) [ ![PixPin_2024-02-16_23-08-28](https://private-user-images.githubusercontent.com/134939494/305456342-28cbe067-065f-4209-8aa4-bc2d0831d62c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwOTY1NTIsIm5iZiI6MTcwODA5NjI1MiwicGF0aCI6Ii8xMzQ5Mzk0OTQvMzA1NDU2MzQyLTI4Y2JlMDY3LTA2NWYtNDIwOS04YWE0LWJjMmQwODMxZDYyYy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNlQxNTEwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZGE0NzliNTQzMDgwYzhkY2MxODk1Njk5YjA3ODEyNzQwYjdhYzc1Y2QwODVjYjE3OTNhNGMzMDlhODUxNTc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tKM7sl4Asrxp6fGSZ32-ZTLI4DqrZHy-0UEAVSBm6G4) ](https://private-user-images.githubusercontent.com/134939494/305456342-28cbe067-065f-4209-8aa4-bc2d0831d62c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwOTY1NTIsIm5iZiI6MTcwODA5NjI1MiwicGF0aCI6Ii8xMzQ5Mzk0OTQvMzA1NDU2MzQyLTI4Y2JlMDY3LTA2NWYtNDIwOS04YWE0LWJjMmQwODMxZDYyYy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNlQxNTEwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZGE0NzliNTQzMDgwYzhkY2MxODk1Njk5YjA3ODEyNzQwYjdhYzc1Y2QwODVjYjE3OTNhNGMzMDlhODUxNTc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tKM7sl4Asrxp6fGSZ32-ZTLI4DqrZHy-0UEAVSBm6G4) [ ](https://private-user-images.githubusercontent.com/134939494/305456342-28cbe067-065f-4209-8aa4-bc2d0831d62c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwOTY1NTIsIm5iZiI6MTcwODA5NjI1MiwicGF0aCI6Ii8xMzQ5Mzk0OTQvMzA1NDU2MzQyLTI4Y2JlMDY3LTA2NWYtNDIwOS04YWE0LWJjMmQwODMxZDYyYy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNlQxNTEwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZGE0NzliNTQzMDgwYzhkY2MxODk1Njk5YjA3ODEyNzQwYjdhYzc1Y2QwODVjYjE3OTNhNGMzMDlhODUxNTc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tKM7sl4Asrxp6fGSZ32-ZTLI4DqrZHy-0UEAVSBm6G4)

因为我只在CloudFlare部署了，所以只能用CloudFlare，不能用本站

**Comment by Harry-zklcdc** [comment]
选本站呢？谁说不能了？演示站就是纯 cfwk 部署的

**Comment by CreeperAWA** [comment]
> 选本站呢？谁说不能了？演示站就是纯 cfwk 部署的

在测试站选本站可以正常使用，我自己部署的只有CFWK可选 我之前看的一个教程说不能，而且我本站是不可用

**Comment by CreeperAWA** [comment]
> 你挂个🪜试试，有可能被Websocket拦截了，估计广东也要开始实行白名单了

我用手机访问演示站是CFWK也可以的，自己部署的打不开，我没有域名

**Comment by Harry-zklcdc** [comment]
Worker。dev 这个后缀的域名早就被墙了

**Comment by CreeperAWA** [comment]
> Worker。dev 这个后缀的域名早就被墙了

也就是说必须买域名？

**Comment by jsdianman** [comment]
是

**Comment by CreeperAWA** [comment]
> Windows 11 专业工作站版 23H2

我现在用了仓库里最新的worker.js和bjs.js再对话会提示“您似乎是盗版软件的受害者” 详见[issues#353](https://github.com/Harry-zklcdc/go-proxy-bingai/issues/353)

**Comment by Harry-zklcdc** [comment]
有问题，进频道或者Tg说，先关闭此issue
