### ISSUE TITLE
[Help] 🤔 请问cloudflare的Tunnels隧道连接不稳定，有撒解决方法没呢？

### ISSUE THREAD

**Issue by wangzhilin777** [Harry-zklcdc/go-proxy-bingai#352]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

Tunnels一会healty一会down的，隔几分钟就连不上，然后过一会又好，如此循环。有点难顶😂

### Steps to behave

1

### Expected behavior

1

### Deploy

CodeSandbox

### OS & Version

codedandbox

### Browser & Version

codedandbox

### GoProxiBingAI Version

codedandbox

### Additional context

1

**Comment by Harry-zklcdc** [comment]
自己加上 ngrok 或者n2n等其他方式的内网穿透

**Comment by wangzhilin777** [comment]
> 自己加上 ngrok 或者n2n等其他方式的内网穿透

我是在codesandbox自定义域名的时候遇到的，请问这个可以弄这两种方式吗？

**Comment by Harry-zklcdc** [comment]
可以

> PS: CSB 要保活

**Comment by wangzhilin777** [comment]
> 可以
> 
> > PS: CSB 要保活，不然就会一会断一会连

好像是没保活的原因，等我试试，谢谢解答。

**Comment by wangzhilin777** [comment]
> 可以
> 
> > PS: CSB 要保活，不然就会一会断一会连

你好，请问怎么保活呢？百度了半天没找到😂

**Comment by jsdianman** [comment]
> > 可以
> 
> > 
> 
> > > PS: CSB 要保活，不然就会一会断一会连
> 
> 
> 
> 你好，请问怎么保活呢？百度了半天没找到😂

应该用replit的方法就可以了吧

**Comment by wangzhilin777** [comment]
> > > 可以
> > 
> > 
> > > 
> > 
> > 
> > > > PS: CSB 要保活，不然就会一会断一会连
> > 
> > 
> > 你好，请问怎么保活呢？百度了半天没找到😂
> 
> 应该用replit的方法就可以了吧

我试了用uptimerobot来保活，原地址和自定义域名都加上了，还是没法保活，不知道是不是cf自带cdn的原因，我ping了一下两个地址都是cf地址。

**Comment by MkStoler** [comment]
> 可以
> 
> > PS: CSB 要保活，不然就会一会断一会连

@Harry-zklcdc 抱歉at您一句（如果打扰到了我十分抱歉！），但是我找了半天issues和百度也没找到保活方法呢😅
能讲解一下吗

**Comment by Harry-zklcdc** [comment]
我自己用的是Cloudflare worker定时任务，去发送请求

**Comment by MkStoler** [comment]
啊谢谢
我让Copilot帮忙写一个脚本就行了

> 我自己用的是Cloudflare worker定时任务，去发送请求

**Comment by wangzhilin777** [comment]
> 啊谢谢 我让Copilot帮忙写一个脚本就行了
> 
> > 我自己用的是Cloudflare worker定时任务，去发送请求

脚本能分享一下吗？谢谢！

**Comment by MkStoler** [comment]
> > 啊谢谢 我让Copilot帮忙写一个脚本就行了
> > > 我自己用的是Cloudflare worker定时任务，去发送请求
> 
> 脚本能分享一下吗？谢谢！

不知能不能用：
```javascript
// 定义要请求的域名
const domain = "example.com";

// 定义一个定时器，每隔一分钟执行一次
const timer = setInterval(() => {
  // 创建一个fetch请求
  const request = new Request(`https://${domain}`, {
    method: "GET",
    headers: {
      "User-Agent": "Cloudflare Workers"
    }
  });

  // 发送请求并获取响应
  fetch(request)
    .then(response => {
      // 如果响应状态码为200，表示请求成功
      if (response.status === 200) {
        // 读取响应的文本内容
        response.text().then(text => {
          // 打印页面信息
          console.log(`Page information from ${domain}:`);
          console.log(text);
        });
      } else {
        // 如果响应状态码不为200，表示请求失败
        console.error(`Request to ${domain} failed with status ${response.status}`);
      }
    })
    .catch(error => {
      // 如果发生错误，打印错误信息
      console.error(`Request to ${domain} failed with error ${error}`);
    });
}, 60000); // 一分钟的毫秒数

// 定义一个事件监听器，当收到请求时返回一个空响应
addEventListener("fetch", event => {
  event.respondWith(new Response());
});

```

**Comment by MkStoler** [comment]
> > > 啊谢谢 我让Copilot帮忙写一个脚本就行了
> > > > 我自己用的是Cloudflare worker定时任务，去发送请求
> > 
> > 
> > 脚本能分享一下吗？谢谢！
> 
> 不知能不能用：
> 
> ```js
> // 定义要请求的域名
> const domain = "example.com";
> 
> // 定义一个定时器，每隔一分钟执行一次
> const timer = setInterval(() => {
>   // 创建一个fetch请求
>   const request = new Request(`https://${domain}`, {
>     method: "GET",
>     headers: {
>       "User-Agent": "Cloudflare Workers"
>     }
>   });
> 
>   // 发送请求并获取响应
>   fetch(request)
>     .then(response => {
>       // 如果响应状态码为200，表示请求成功
>       if (response.status === 200) {
>         // 读取响应的文本内容
>         response.text().then(text => {
>           // 打印页面信息
>           console.log(`Page information from ${domain}:`);
>           console.log(text);
>         });
>       } else {
>         // 如果响应状态码不为200，表示请求失败
>         console.error(`Request to ${domain} failed with status ${response.status}`);
>       }
>     })
>     .catch(error => {
>       // 如果发生错误，打印错误信息
>       console.error(`Request to ${domain} failed with error ${error}`);
>     });
> }, 60000); // 一分钟的毫秒数
> 
> // 定义一个事件监听器，当收到请求时返回一个空响应
> addEventListener("fetch", event => {
>   event.respondWith(new Response());
> });
> ```

不行，不中用，我在修了

**Comment by MkStoler** [comment]
试一试新的（不行就换csb自带的域名）：
```javascript
// 定义要请求的域名
const domain = "example.com";

// 定义一个函数，用于向指定域名发送请求并获取页面信息
async function getPageInfo() {
  // 创建一个fetch请求
  const request = new Request(`https://${domain}`, {
    method: "GET",
    headers: {
      "User-Agent": "Cloudflare Workers"
    }
  });

  try {
    // 发送请求并获取响应
    const response = await fetch(request);
    // 如果响应状态码为200，表示请求成功
    if (response.status === 200) {
      // 读取响应的文本内容
      const text = await response.text();
      // 打印页面信息
      console.log(`Page information from ${domain}:`);
      console.log(text);
    } else {
      // 如果响应状态码不为200，表示请求失败
      console.error(`Request to ${domain} failed with status ${response.status}`);
    }
  } catch (error) {
    // 如果发生错误，打印错误信息
    console.error(`Request to ${domain} failed with error ${error}`);
  }
}

// 定义一个事件监听器，当收到请求时执行定时器
addEventListener("fetch", event => {
  // 定义一个定时器，每隔一分钟执行一次
  const timer = setInterval(getPageInfo, 60000); // 一分钟的毫秒数
  // 返回一个空响应
  event.respondWith(new Response());
});

```

**Comment by Harry-zklcdc** [comment]
```javascript
const CSB_SERVER = '';

export default {
  async scheduled(event, env, ctx) {
    let newReq = new Request(CSB_SERVER, {
      method: 'GET',
    })
    await fetch(newReq)
    console.log('CodeSandbox Request')
  },
};
```

然后配置 cron
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/979119a6-ff2d-4f08-8845-d4431e7a4ae3)

**Comment by wangzhilin777** [comment]
> ```js
> const CSB_SERVER = '';
> 
> export default {
>   async scheduled(event, env, ctx) {
>     let newReq = new Request(CSB_SERVER, {
>       method: 'GET',
>     })
>     await fetch(newReq)
>     console.log('CodeSandbox Request')
>   },
> };
> ```
> 
> 然后配置 cron ![image](https://private-user-images.githubusercontent.com/21104213/305691292-979119a6-ff2d-4f08-8845-d4431e7a4ae3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNDQ3NTMsIm5iZiI6MTcwODI0NDQ1MywicGF0aCI6Ii8yMTEwNDIxMy8zMDU2OTEyOTItOTc5MTE5YTYtZmYyZC00ZjA4LTg4NDUtZDQ0MzFlN2E0YWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA4MjA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNzU5ZjIyMTAzMDE0ZTQ1MGYxNjBlYjNlMWI1ZTIwMTEzZmUwMTJiNWNmNDc1MTkzZGI4MmU4MDI1ZjY3Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KJiNGL5OcGINxpLmsrgHMwrm3URIrb-WfxvH5q4mP9A)



> ```js
> const CSB_SERVER = '';
> 
> export default {
>   async scheduled(event, env, ctx) {
>     let newReq = new Request(CSB_SERVER, {
>       method: 'GET',
>     })
>     await fetch(newReq)
>     console.log('CodeSandbox Request')
>   },
> };
> ```
> 
> 然后配置 cron ![image](https://private-user-images.githubusercontent.com/21104213/305691292-979119a6-ff2d-4f08-8845-d4431e7a4ae3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNDQ3NzksIm5iZiI6MTcwODI0NDQ3OSwicGF0aCI6Ii8yMTEwNDIxMy8zMDU2OTEyOTItOTc5MTE5YTYtZmYyZC00ZjA4LTg4NDUtZDQ0MzFlN2E0YWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA4MjExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZjIxMTZmNmVlYjEzMTk1OTU1YmQ2ZWY1OTlkODk2NmQyZDI5MTk3NGM2MGJiODQ1NWI3YjQxN2E1YzAyOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y_BbkMLnI6oOkSiOujg4f6izjjlhdgwYXVRGbzihUmw)

好的，谢谢，已经弄好了

**Comment by gclm** [comment]
> ```js
> const CSB_SERVER = '';
> 
> export default {
>   async scheduled(event, env, ctx) {
>     let newReq = new Request(CSB_SERVER, {
>       method: 'GET',
>     })
>     await fetch(newReq)
>     console.log('CodeSandbox Request')
>   },
> };
> ```
> 
> 然后配置 cron ![image](https://private-user-images.githubusercontent.com/21104213/305691292-979119a6-ff2d-4f08-8845-d4431e7a4ae3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTE3MTksIm5iZiI6MTcwODMxMTQxOSwicGF0aCI6Ii8yMTEwNDIxMy8zMDU2OTEyOTItOTc5MTE5YTYtZmYyZC00ZjA4LTg4NDUtZDQ0MzFlN2E0YWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAyNTY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5YmQ2NDU0N2NlZGMyMzgwMDA0ZGE4Y2JlNjA1YWFlNzFlOTVhOGZmYWE2ZjZjMzE0NDU5YTEyZjY4ZGIwNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.akrru-vhyr5ghkwZ6FNyknj6jr_bEBwxU7WRpPW6vlw)

这个CSB_SERVER 配置的是那个？能提供一下示例吗？

**Comment by wangzhilin777** [comment]
> > ```js
> > const CSB_SERVER = '';
> > 
> > export default {
> >   async scheduled(event, env, ctx) {
> >     let newReq = new Request(CSB_SERVER, {
> >       method: 'GET',
> >     })
> >     await fetch(newReq)
> >     console.log('CodeSandbox Request')
> >   },
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后配置 cron ![image](https://private-user-images.githubusercontent.com/21104213/305691292-979119a6-ff2d-4f08-8845-d4431e7a4ae3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTE3MTksIm5iZiI6MTcwODMxMTQxOSwicGF0aCI6Ii8yMTEwNDIxMy8zMDU2OTEyOTItOTc5MTE5YTYtZmYyZC00ZjA4LTg4NDUtZDQ0MzFlN2E0YWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAyNTY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5YmQ2NDU0N2NlZGMyMzgwMDA0ZGE4Y2JlNjA1YWFlNzFlOTVhOGZmYWE2ZjZjMzE0NDU5YTEyZjY4ZGIwNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.akrru-vhyr5ghkwZ6FNyknj6jr_bEBwxU7WRpPW6vlw)
> 
> 这个CSB_SERVER 配置的是那个？能提供一下示例吗？

csb给你的8080端口的网址就行

**Comment by ychappyboy** [comment]
> > > ```js
> > > const CSB_SERVER = '';
> > > 
> > > export default {
> > >   async scheduled(event, env, ctx) {
> > >     let newReq = new Request(CSB_SERVER, {
> > >       method: 'GET',
> > >     })
> > >     await fetch(newReq)
> > >     console.log('CodeSandbox Request')
> > >   },
> > > };
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 然后配置 cron ![image](https://private-user-images.githubusercontent.com/21104213/305691292-979119a6-ff2d-4f08-8845-d4431e7a4ae3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTE3MTksIm5iZiI6MTcwODMxMTQxOSwicGF0aCI6Ii8yMTEwNDIxMy8zMDU2OTEyOTItOTc5MTE5YTYtZmYyZC00ZjA4LTg4NDUtZDQ0MzFlN2E0YWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAyNTY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5YmQ2NDU0N2NlZGMyMzgwMDA0ZGE4Y2JlNjA1YWFlNzFlOTVhOGZmYWE2ZjZjMzE0NDU5YTEyZjY4ZGIwNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.akrru-vhyr5ghkwZ6FNyknj6jr_bEBwxU7WRpPW6vlw)
> > 
> > 
> > 这个CSB_SERVER 配置的是那个？能提供一下示例吗？
> 
> csb给你的8080端口的网址就行

你好，按照这个设置了，怎么还是无法保活呢

**Comment by jjyung168** [comment]
> > > ```js
> > > const CSB_SERVER = '';
> > > 
> > > export default {
> > >   async scheduled(event, env, ctx) {
> > >     let newReq = new Request(CSB_SERVER, {
> > >       method: 'GET',
> > >     })
> > >     await fetch(newReq)
> > >     console.log('CodeSandbox Request')
> > >   },
> > > };
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 然后配置 cron ![image](https://private-user-images.githubusercontent.com/21104213/305691292-979119a6-ff2d-4f08-8845-d4431e7a4ae3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTE3MTksIm5iZiI6MTcwODMxMTQxOSwicGF0aCI6Ii8yMTEwNDIxMy8zMDU2OTEyOTItOTc5MTE5YTYtZmYyZC00ZjA4LTg4NDUtZDQ0MzFlN2E0YWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAyNTY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5YmQ2NDU0N2NlZGMyMzgwMDA0ZGE4Y2JlNjA1YWFlNzFlOTVhOGZmYWE2ZjZjMzE0NDU5YTEyZjY4ZGIwNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.akrru-vhyr5ghkwZ6FNyknj6jr_bEBwxU7WRpPW6vlw)
> > 
> > 
> > 这个CSB_SERVER 配置的是那个？能提供一下示例吗？
> 
> csb给你的8080端口的网址就行

请问我设置了CSB的8080端口网址 然后CORN也设置了10分钟 还是失败了 你是怎么设置的
