### ISSUE TITLE
[Bug] 🐛 使用CF部署，对话时会提示“您似乎是盗版软件的受害者”

### ISSUE THREAD

**Issue by CreeperAWA** [Harry-zklcdc/go-proxy-bingai#353]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the bug

使用CF部署，代码照着仓库抄的，只加了自动验证服务器，在发送对话后过自动验证时会提示“您似乎是盗版软件的受害者”

### Steps to reproduce

使用CF部署最新的worker.js和bjs.js
与Copilot对话时会提示“您似乎是盗版软件的受害者”

### Expected behavior

不显示该提示

### Screenshots

<img width="1260" alt="PixPin_2024-02-17_08-15-32" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/134939494/192d6da9-cd2d-490d-9b64-514932da64fa">

### Deploy

Cloudflare Worker

### UserId

有两个 gwz82k%7C2%7Cfjc%7C0%7C1507 和 snzrcb%7C2%7Cfi6%7C1%7C1236

### OS & Version

Windows 11 专业工作站版 23H2

### Browser & Version

Google Chrome 121.0.6167.161（正式版本） （64 位）

### GoProxiBingAI Version

v2.0.1

**Comment by Propny** [comment]
我也遇到这种情况🤣

**Comment by ryanzhaorx** [comment]
你们手太快了，还没更新完你们就同步了，当然会显示了，可以先用API...

**Comment by CreeperAWA** [comment]
> 你们手太快了，还没更新完你们就同步了，当然会显示了，可以先用 API...

哈哈

**Comment by wangzhilin777** [comment]
> 你们手太快了，还没更新完你们就同步了，当然会显示了，可以先用API...

什么意思呢，没太明白😂

**Comment by wangzhilin777** [comment]
我是，点击设置-》自动人机验证-》启动，就可以了。而且要使用自定义域名才行。

**Comment by CreeperAWA** [comment]
> 我是，点击设置 -》自动人机验证 -》启动，就可以了。而且要使用自定义域名才行。 ![screenshot-1708165152247](https://private-user-images.githubusercontent.com/75417416/305636371-69b0bced-bf96-4550-a77e-50c7491d808d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNjc5NTMsIm5iZiI6MTcwODE2NzY1MywicGF0aCI6Ii83NTQxNzQxNi8zMDU2MzYzNzEtNjliMGJjZWQtYmY5Ni00NTUwLWE3N2UtNTBjNzQ5MWQ4MDhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDExMDA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmNmRjZDYwNWViNDRkNzc1NTdjYTE4NGNiMTJmM2FkZDM0MDQzNjgyODgxODFhZjQ5OTdhNTAwNDdiOGY4NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gd1_TI9ggIKRYEPmgJlyXDhRu_Z36GmjtisjvEvY8Do)

不用域名是不是验证过不去啊，我不想搞域名(原因：没钱)

**Comment by wangzhilin777** [comment]
> > 我是，点击设置 -》自动人机验证 -》启动，就可以了。而且要使用自定义域名才行。 ![screenshot-1708165152247](https://private-user-images.githubusercontent.com/75417416/305636371-69b0bced-bf96-4550-a77e-50c7491d808d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNjc5NTMsIm5iZiI6MTcwODE2NzY1MywicGF0aCI6Ii83NTQxNzQxNi8zMDU2MzYzNzEtNjliMGJjZWQtYmY5Ni00NTUwLWE3N2UtNTBjNzQ5MWQ4MDhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDExMDA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmNmRjZDYwNWViNDRkNzc1NTdjYTE4NGNiMTJmM2FkZDM0MDQzNjgyODgxODFhZjQ5OTdhNTAwNDdiOGY4NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gd1_TI9ggIKRYEPmgJlyXDhRu_Z36GmjtisjvEvY8Do)
> 
> 不用域名是不是验证过不去啊，我不想搞域名(原因：没钱)

我试了不行，我买的域名5块一年

**Comment by CreeperAWA** [comment]
> > > 我是，点击设置 -》自动人机验证 -》启动，就可以了。而且要使用自定义域名才行。 ![screenshot-1708165152247](https://private-user-images.githubusercontent.com/75417416/305636371-69b0bced-bf96-4550-a77e-50c7491d808d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNjc5NTMsIm5iZiI6MTcwODE2NzY1MywicGF0aCI6Ii83NTQxNzQxNi8zMDU2MzYzNzEtNjliMGJjZWQtYmY5Ni00NTUwLWE3N2UtNTBjNzQ5MWQ4MDhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDExMDA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmNmRjZDYwNWViNDRkNzc1NTdjYTE4NGNiMTJmM2FkZDM0MDQzNjgyODgxODFhZjQ5OTdhNTAwNDdiOGY4NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gd1_TI9ggIKRYEPmgJlyXDhRu_Z36GmjtisjvEvY8Do)
> > 
> > 
> > 不用域名是不是验证过不去啊，我不想搞域名 (原因：没钱)
> 
> 我试了不行，我买的域名 5 块一年

我的意思是人机验证过不去是不是必须要域名或者魔法(

**Comment by wangzhilin777** [comment]
> > > > 我是，点击设置 -》自动人机验证 -》启动，就可以了。而且要使用自定义域名才行。 ![screenshot-1708165152247](https://private-user-images.githubusercontent.com/75417416/305636371-69b0bced-bf96-4550-a77e-50c7491d808d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNjc5NTMsIm5iZiI6MTcwODE2NzY1MywicGF0aCI6Ii83NTQxNzQxNi8zMDU2MzYzNzEtNjliMGJjZWQtYmY5Ni00NTUwLWE3N2UtNTBjNzQ5MWQ4MDhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDExMDA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmNmRjZDYwNWViNDRkNzc1NTdjYTE4NGNiMTJmM2FkZDM0MDQzNjgyODgxODFhZjQ5OTdhNTAwNDdiOGY4NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gd1_TI9ggIKRYEPmgJlyXDhRu_Z36GmjtisjvEvY8Do)
> > > 
> > > 
> > > 不用域名是不是验证过不去啊，我不想搞域名 (原因：没钱)
> > 
> > 
> > 我试了不行，我买的域名 5 块一年
> 
> 我的意思是人机验证过不去是不是必须要域名或者魔法(

我自己测试是。

**Comment by SokWith** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/30f6b350-6502-4e25-8916-b9d5637cd5ad)
只要使用了cf部署的pass服务器，就跳出来。

FROM zklcdc/go-proxy-bingai:latest

ENV BYPASS_SERVER="https://cct.nbing.eu.org"               //cf 部署
#ENV BYPASS_SERVER="https://bingcct.onrender.com"   //render部署

ENV PORT 7860
EXPOSE 7860

**Comment by Harry-zklcdc** [comment]
得再加一个转发 把 request.search 转发过去

**Comment by SokWith** [comment]
> 得再加一个转发 把 request.search 转发过去

没明白。
这个https://cct.nbing.eu.org只是简单利用了request:

**Comment by Harry-zklcdc** [comment]
完整代码发出来

**Comment by SokWith** [comment]
> 完整代码发出来，用markdown的代码块

`//本项目获取bing cct

//const BING_PROXY = 'https://rendcreate.onrender.com'; 
const BING_PROXY = 'https://sokwith-nbing.hf.space'; 
//const BING_PROXY = 'https://dswnb-proxycfweb.hf.space'; 
//const BING_PROXY = 'https://sokwith-proxybing.hf.space'; 
//const BING_PROXY = 'https://www.bing.com'; 
 
function generateUUID() {
  let dt = new Date().getTime();
  const uuid = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
    const r = (dt + Math.random() * 16) % 16 | 0;
    dt = Math.floor(dt / 16);
    return (c === 'x' ? r : (r & 0x3 | 0x8)).toString(16);
  });
  return uuid;
}


async function getfreeCookies(request) {
  const uuid = generateUUID();
  const oldUA = request.headers.get('user-agent') || '';
  let freeisMobile = oldUA.includes('Mobile') || oldUA.includes('Android');
  const newcctHeaders = new Headers();
  if (freeisMobile = true) {
      newcctHeaders.set(
        'user-agent',
        'Mozilla/5.0 (iPhone; CPU iPhone OS 15_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.7 Mobile/15E148 Safari/605.1.15 BingSapphire/1.0.410427012'
      );
    } else {
      newcctHeaders.set('user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.35');
    }
    const  challtargetUrl = new URL(BING_PROXY + '/turing/captcha/challenge?q=&iframeid=local-gen-' + uuid);
    const newcctReq = new Request(challtargetUrl, {
   //   method: request.method,
      method: 'GET',
      headers: newcctHeaders,  
   //   body: request.body,
    });

    const cctcookie = await getCookies(newcctReq);
    //const responseBody = await cctcookie.text(); // 获取响应体的文本内容
    //const result = JSON.parse(responseBody); // 解析 JSON 数据
    //const freecctcookie = result.result.cookies;

  const newcctRes = new Response(cctcookie.body, cctcookie);
 //const newcctRes = new Response(responseBody);
  newcctRes.headers.set('Access-Control-Allow-Origin', request.headers.get('Origin'));
  newcctRes.headers.set('Access-Control-Allow-Methods', 'GET,HEAD,POST,OPTIONS');
  newcctRes.headers.set('Access-Control-Allow-Credentials', 'true');
  newcctRes.headers.set('Access-Control-Allow-Headers', '*');
//  newcctRes.headers.set('FreeCookie', freecctcookie); 
  return  newcctRes;

}

// 编写一个 cf workers 的函数，访问指定的网址，从返回的相应头中获取全部 set-cookie，取出主键值，用分号“;"连接起来，赋值给 strValues
async function getCookies(request) {
  try {
    let response = await fetch(request);
    let cookies = response.headers.get('set-cookie');
    let strValues = '';

    if (cookies) {
      const pairs = cookies.split(','); // 使用逗号分隔
      const values = pairs.map(pair => {
        const firstSemicolonIndex = pair.indexOf(';'); // 找到第一个分号的位置
        const keyValue = firstSemicolonIndex !== -1 ? pair.slice(0, firstSemicolonIndex) : pair; // 提取第一个分号前的数据
        const [key, value] = keyValue.split('='); // 拆分键值对
      //  return keyValue.trim(); // 去除首尾空格
        if (key && value) {
          return `${key}=${value.trim()}`; // 去除首尾空格
        }
        return ''; // 无效的 cookie
      });
   strValues = values.filter(cookie => cookie !== '').join('; '); // 去除无效的 cookie
    }
    const result = { result: { cookies: strValues } };
    const jsonResult = JSON.stringify(result);

    return new Response(jsonResult, {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
   });
  } catch (error) {
    console.error(error);
   return new Response('', { status: 500 });
  }
}
 



export default {
  /**
   * fetch
   * @param {Request} request
   * @param {*} env
   * @param {*} ctx
   * @returns
   */
  async fetch (request, env, ctx) {
    
    return await getfreeCookies(request);
    
  },
};

`

**Comment by SokWith** [comment]
请勿扩散，请勿向MS/CF提交BUG，谢谢大家。

**Comment by Harry-zklcdc** [comment]
应该不算bug，你去频道私我把，我告诉你怎么改

**Comment by SokWith** [comment]
> 应该不算bug，你去频道私我把，我告诉你怎么改

没有qq，没进频道。
如果方便的话，发邮件给我：me@sokwith.eu.org

**Comment by Harry-zklcdc** [comment]
QQ、tg、Discord 都可以

**Comment by chaoyu1999** [comment]
> 请勿扩散，请勿向MS/CF提交BUG，谢谢大家。

请问是有简单的方法可以过CF验证吗？

**Comment by SokWith** [comment]
> > 请勿扩散，请勿向MS/CF提交BUG，谢谢大家。
> 
> 请问是有简单的方法可以过CF验证吗？

不是的。似乎只是获取cct的速度要快一些。

**Comment by SokWith** [comment]
为了加快速度，硬编码改了一下：
`
export default {
  /**
   * fetch
   * @param {Request} request
   * @param {*} env
   * @param {*} ctx
   * @returns
   */
  async fetch (request, env, ctx) {

    const currentUrl = new URL(request.url);
    const keytoken = {
    T:'SjQH0q3MzCEXay9WfVPAdkL518iZcghu4Uteprwl7bxTvG6RsK2oYIFONDBmnJ',
    TP:[21,58,22,34,0,51,58,37,20,54,16,41,29,16,14,33,24,46,7,60,5,16,54,27,28,44,1,26,57,21,46,49,19,45,16,14,3,26]
  };
    const jsonResult = JSON.stringify(keytoken);
   
    if (currentUrl.pathname.startsWith('/gettoken')) {
    return new Response(jsonResult, {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
   });
    }
    
    return await getfreeCookies(request);
    
  },
};
`
