### ISSUE TITLE
[Help] 🤔 Docker部署，用脚本登录之后画图无法显示

### ISSUE THREAD

**Issue by ixxmu** [Harry-zklcdc/go-proxy-bingai#354]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

vps上Docker部署，用脚本登录之后图像无法显示，需要跳转到图像生成器页面才能看见，用的最新版本

### Steps to behave

vps上Docker部署，用脚本登录之后图像无法显示，需要跳转到图像生成器页面才能看见，用的最新版本

### Expected behavior

可以在主页中默认显示图片，不跳转

### Deploy

Docker

### OS & Version

Ubuntu 22.04

### Browser & Version

Chrome

### GoProxiBingAI Version

v2.0.3

**Comment by Harry-zklcdc** [comment]
详细描述，否则关闭

**Comment by ixxmu** [comment]
应该是caddy配置不当引起的，用了大佬的nginx配置替换了，关闭issue！

感谢大佬的项目，飒 的很啊
