### ISSUE TITLE
[Feature] 🌈 CF部署添加BingAPI支持

### ISSUE THREAD

**Issue by dcityteg** [Harry-zklcdc/go-proxy-bingai#356]
### Describe the problem related to the feature request

目前Cloudflare部署无法使用BingAPI，
不知道是不是CF的原因。如果可以的话，能否在CF添加BingAPI的支持？因为目前其他方法都不太好用。
谢谢！

### Describe the solution you'd like

/

### Describe alternatives you've considered

/

### Additional context

/

**Comment by Harry-zklcdc** [comment]
![Screenshot_2024-02-23-17-56-26-011_com kiwibrowser browser-edit](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/8c7d3d46-971b-42fd-aec6-3255d430dc45)

暂不支持，还在解决

**Comment by dcityteg** [comment]
好的，谢谢
那后续会支持吗？

**Comment by Harry-zklcdc** [comment]
短期内估计不会，等啥时候 Cloudflare worker支持 wasm 发送 http 请求的时候我再试试吧，~~懒，实在不想再用 js 写一遍 API~~

**Comment by Harry-zklcdc** [comment]
同时添加了 CFWK 的一键部署

**Comment by mountainguan** [comment]
> 同时添加了 CFWK 的一键部署，教程明天更

大佬辛苦了，非常期待

**Comment by Harry-zklcdc** [comment]
教程写完了
