### ISSUE TITLE
[Feature] 🌈 希望能尽快实现API的图片识别功能

### ISSUE THREAD

**Issue by ryanzhaorx** [Harry-zklcdc/go-proxy-bingai#357]
### Describe the problem related to the feature request

希望能尽快实现API的图片识别功能

### Describe the solution you'd like

希望能尽快实现API的图片识别功能

**Comment by Harry-zklcdc** [comment]
计划中

**Comment by Harry-zklcdc** [comment]
<img width="482" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/07e8f0b6-9631-4d39-9f89-f59f212bfdb9">
这让我很不想更这个功能
