### ISSUE TITLE
[Feature] 🌈 请问是否可以提供 arm 的 docker 版本？

### ISSUE THREAD

**Issue by Kaol-Fu** [Harry-zklcdc/go-proxy-bingai#359]
### Describe the problem related to the feature request

当前docker版本 arm 缺失，请问是否可以提供 arm 的 docker 版本？

### Describe the solution you'd like

希望提供 arm 版本的 docker img。

**Comment by Harry-zklcdc** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/0e0e67a9-7540-4243-8b8e-07847f050f8e)
