### ISSUE TITLE
我用replit免费部署了一个，但是为什么聊天服务器不可用？

### ISSUE THREAD

**Issue by Xqh-Cxy** [Harry-zklcdc/go-proxy-bingai#36]
> [复刻URL](https://replit.com/@xinyan37/go-proxy-bingai?v=1)
![](http://d.kjzly.cn/a3hf08)

**Comment by Xqh-Cxy** [comment]
> [复刻URL](https://replit.com/@xinyan37/go-proxy-bingai?v=1)
![](http://d.kjzly.cn/a3hf08)

**Comment by Harry-zklcdc** [comment]
不知道

**Comment by Harry-zklcdc** [comment]
replit的IP被封，然后还不支持websocket
