### ISSUE TITLE
[Bug] 🐛 cf部署的点不开引用网页

### ISSUE THREAD

**Issue by ikunfans** [Harry-zklcdc/go-proxy-bingai#360]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

就是回答下面引用网页，打开还是cf的网站，提示 Web server is returning an unknown error，是要在cf里设置什么吗 ···

### Steps to behave

rt

### Expected behavior

rt

### Deploy

Cloudflare Worker

### OS & Version

win11

### Browser & Version

edge 

### GoProxiBingAI Version

2.0.10

**Comment by Harry-zklcdc** [comment]
已修复
