### ISSUE TITLE
[Feature] 🌈 提供go-bingai-pass的 ARM docker 版本

### ISSUE THREAD

**Issue by Kaol-Fu** [Harry-zklcdc/go-proxy-bingai#361]
### Describe the problem related to the feature request

之前已经添加了go-proxy-bingai的 ARM docker 版本，但是还缺少go-bingai-pass的 ARM docker 版本

### Describe the solution you'd like

添加go-bingai-pass的 ARM docker 版本

**Comment by Harry-zklcdc** [comment]
pass 不支持 arm 的 docker，因为 arm 的浏览器只有 chromium，但是在同一台机器上，整合进 docker 镜像中就会出现人机不通过的情况，单独运行可以使用，具体原因未知
