### ISSUE TITLE
[Bug] 🐛 EDGE浏览器生成图片无法下载

### ISSUE THREAD

**Issue by GforPG** [Harry-zklcdc/go-proxy-bingai#362]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the bug

如题

### Steps to reproduce

只填了_u值，然后画图，结果如下题

### Expected behavior

我也不知道

### Screenshots

![未标题-1](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/138672705/7f6fa524-1416-4bd2-9d94-3a5742b13a7e)
![未标题-2](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/138672705/cb0d63e7-a512-4b71-b75c-5139dd00d0b6)

### Deploy

Cloudflare Worker

### OS & Version

windows11

### Browser & Version

edge

### GoProxiBingAI Version

117.0.2045.60

**Comment by Harry-zklcdc** [comment]
演示站没有这个问题，请更新 Cloudflare Worker 的代码

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/939e21c4-27fd-4b6b-bf44-6cd41c9dd9a7)
