### ISSUE TITLE
[Bug] 🐛 bing-pass启动后，浏览器服务不运行

### ISSUE THREAD

**Issue by NikoCat233** [Harry-zklcdc/go-proxy-bingai#365]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the bug

通过docker compose 和 自行部署启动的docker容器里都不会启动edge进程
日志请见
https://github.com/Harry-zklcdc/go-bingai-pass/issues/5

### Steps to reproduce

本机出现问题

### Expected behavior

应该自动补全并启动edge进程

### Deploy

Docker

### OS & Version

ubuntu 20.04

### Browser & Version

后端问题

### GoProxiBingAI Version

docker版本

**Comment by Harry-zklcdc** [comment]
贴出配置（包括 `docker-compose.yml` 和 环境变量配置）

**Comment by NikoCat233** [comment]
version: '3'

services:
  go-proxy-bingai:
    image: zklcdc/go-proxy-bingai
    container_name: go-proxy-bingai  
    restart: always
    ports:
      - 8080:8080
    environment:
      - BYPASS_SERVER=http://xxxx:7860
      # - BING_BASE_URL=https://www.bing.com
      # - SYDNEY_BASE_URL=https://sydney.bing.com
      # - HTTP_PROXY=http://172.17.0.1:18080
      # - HTTPS_PROXY=http://172.17.0.1:18080
      # - Go_Proxy_BingAI_USER_TOKEN_1=xxx
      # - Go_Proxy_BingAI_USER_TOKEN_2=xxx
      # - USER_KievRPSSecAuth=xxx
      # - USER_RwBf=xxx
      # - USER_MUID=xxx
      # - APIKEY=sk-xxx


  go-bingai-pass:
    image: zklcdc/go-bingai-pass
    container_name: go-bingai-pass
    restart: always
    environment:
      # - PROXY_SERVER=http://172.17.0.1:18080
      - PASS_TIMEOUT=3
      - HEADLESS=false
    ports:
      - 7860:7860

**Comment by NikoCat233** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/139348239/5a410ddf-b245-4fd7-a16a-6e6b043f07a7)

**Comment by Harry-zklcdc** [comment]
```yaml
go-proxy-bingai:
  environment:
    - BYPASS_SERVER=http://172.17.0.1:7860
```
这玩意别改

**Comment by Harry-zklcdc** [comment]
长时间无回复，如有问题重新开启此 issue

**Comment by NikoCat233** [comment]
被你关闭的issue无法重新开启

**Comment by NikoCat233** [comment]
我的问题是bing-pass容器内不自动补全edge运行环境和不运行edge
您的建议显然无法解决这个问题


> ```yaml
> go-proxy-bingai:
>   environment:
>     - BYPASS_SERVER=http://172.17.0.1:7860
> ```
> 
> 这玩意别改

**Comment by Harry-zklcdc** [comment]
问题是 zklcdc/go-bingai-pass 这个镜像已经包含了 edge 浏览器了，而且你的日志里面也没有对应的人机验证请求，只能说明要不配置有问题，要不哪里搞错了

**Comment by NikoCat233** [comment]
edge启动时好像应该会有一个相应的日志
我的容器内没有这个日志，容器内活动进程没有edge
直接访问接口返回如下结果
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/139348239/6863c1fb-dc44-47b0-b75e-0fadf93129f6)

**Comment by NikoCat233** [comment]
我记得我第一次部署docker的时候是有一个 edge start的日志条目，但是我之后重启布置就没有这么个条目了

**Comment by Harry-zklcdc** [comment]
> edge启动时好像应该会有一个相应的日志 我的容器内没有这个日志，容器内活动进程没有edge 直接访问接口返回如下结果

直接访问不是请求人机验证，人机验证的请求方法是 POST 不是 GET，你的日志里面全是 GET，所以显然没有人机验证的请求

**Comment by NikoCat233** [comment]
请等我尝试一下分开部署proxy 和 pass
本人docker环境网关ip每部署一次都不一样，使用172.16.0.1指定不到网关
host-gateway解析居然也是172.16.0.1

**Comment by Harry-zklcdc** [comment]
那你用

```yaml
go-proxy-bingai:
  environment:
    - BYPASS_SERVER=http://go-bingai-pass:7860
```

试试

> 如果没设置  `HTTP_PROXY` 和 `HTTPS_PROXY` 的话

**Comment by Harry-zklcdc** [comment]
尝试使用此镜像 `zklcdc/go-proxy-bingai:latest-with-pass`

https://github.com/Harry-zklcdc/go-proxy-bingai/issues/369#issuecomment-1991142831
