### ISSUE TITLE
[Help] 🤔 请问新的cfwk的Go_Proxy_BingAI_USER_TOKEN变量，可以用多个cookie吗？

### ISSUE THREAD

**Issue by GforPG** [Harry-zklcdc/go-proxy-bingai#368]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

如题

### Steps to behave

如题

### Expected behavior

此变量希望可以用多个cookie，用“,”分开，现在一个账号每天画图的“提升”很少啊。

### Deploy

Cloudflare Worker

### OS & Version

windows11

### Browser & Version

chrome 121.0.6167.140

### GoProxiBingAI Version

v2.0.15

**Comment by Harry-zklcdc** [comment]
安排
