### ISSUE TITLE
[Help] 🤔 CF使用BingAPI返回Failed to fetch

### ISSUE THREAD

**Issue by dcityteg** [Harry-zklcdc/go-proxy-bingai#370]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### 在按照WIKI在CF部署了这个项目后，
# 可以正常对话（在bing-cf.xodi.top
但是，调用的时候就提示Failed to fetch（在nextchat
API设置正确，
调用地址为bing-cf.xodi.top/api/v1
不知刀是什么问题？

### Steps to behave

按照wiki教程部署

### Expected behavior

能够正常返回结果

### Deploy

Cloudflare Worker

### OS & Version

Windows11

### Browser & Version

Chrome

### GoProxiBingAI Version

最新

**Comment by Harry-zklcdc** [comment]
BASE_URL 填 `https://bing-cf.xodi.top/api`

**Comment by dcityteg** [comment]
还是不行

**Comment by Harry-zklcdc** [comment]
进用户交流群吧，你这啥也没有，我压根看不出什么问题

**Comment by SokWith** [comment]
> 调用地址为bing-cf.xodi.top/api/v1

next的调用地址似乎只需要host部分吧？ https://bing-cf.xodi.top
