### ISSUE TITLE
[Help] 🤔 很抱歉，你已达到可在 24 小时内发送到必应的邮件限制。请稍后回来查看!

### ISSUE THREAD

**Issue by XingYaoA** [Harry-zklcdc/go-proxy-bingai#372]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the bug

询问任意问题后，提示很抱歉，你已达到可在 24 小时内发送到必应的邮件限制。请稍后回来查看!

### Steps to reproduce

询问任意问题

### Expected behavior

回答问题

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/102949335/a83ce35a-c5db-4f10-bb65-e7490bbb27c2)

### Deploy

Cloudflare Worker

### UserId

1r3ntye%7C2%7Cfjx%7C0%7C1529

### OS & Version

Windows 11

### Browser & Version

Microsoft Edge 122.0.2365.80

### GoProxiBingAI Version

v2.0.15

**Comment by wurenzhiwen** [comment]
账号之前使用过bingai吗

**Comment by XingYaoA** [comment]
@wurenzhiwen 没有使用过

**Comment by Harry-zklcdc** [comment]
没有使用过的话，需要先在官网使用一次，之后才可以正常对话
