### ISSUE TITLE
[Feature] 🌈 历史记录问题能不能有什么办法解决，如保存在本地浏览器缓存中

### ISSUE THREAD

**Issue by GforPG** [Harry-zklcdc/go-proxy-bingai#373]
### Describe the problem related to the feature request

感觉啥都好，就差个历史记录了。

### Describe the solution you'd like

如保存在本地浏览器缓存中

**Comment by gitMFQ** [comment]
可以用api暂时代替

**Comment by baminkon** [comment]
> 可以用api暂时代替

是这么想，正在尝试，但API用起来，没直接用方便、直观和美观

**Comment by GforPG** [comment]
> 可以用api暂时代替

API试过，没有直接用起来爽，选模型太杂乱的感觉，还是期待一下这个功能

**Comment by Harry-zklcdc** [comment]
不做，和官方保持同步，如果实在要保存聊天记录，请使用「账号登录」功能
