### ISSUE TITLE
[Feature] 🌈 CF 部署支持配置访问密码

### ISSUE THREAD

**Issue by GforPG** [Harry-zklcdc/go-proxy-bingai#375]
### Describe the problem related to the feature request

防止流出，内置cookie被滥用

### Describe the solution you'd like

增加访问密码功能

**Comment by GforPG** [comment]
> 安全相关 授权密码 可选, 简单授权认证密码
> 
> Go_Proxy_BingAI_AUTH_KEY=xxx

没留意到这个变量，多谢大佬！

**Comment by GforPG** [comment]
> 安全相关 授权密码 可选, 简单授权认证密码
> 
> Go_Proxy_BingAI_AUTH_KEY=xxx

CK部署的不行耶

**Comment by Harry-zklcdc** [comment]
CF部署不支持，影响执行效率，所以暂未支持

**Comment by GforPG** [comment]
> CF部署不支持，影响执行效率，所以暂未支持

期待ing

**Comment by GforPG** [comment]
请问，目前支持Go_Proxy_BingAI_AUTH_KEY这个变量的，是哪种部署办法？

**Comment by Harry-zklcdc** [comment]
除了 cf

**Comment by Harry-zklcdc** [comment]
在不影响执行效率的情况下简单支持了一下，Commit: acdffd6ab15720dd223ee89e6dd12c3327d74ca0, ~~基本上防君子不防小人~~，后续想办法增强一下
