### ISSUE TITLE
[Feature] 🌈 好像支持文件上传功能了

### ISSUE THREAD

**Issue by ryanzhaorx** [Harry-zklcdc/go-proxy-bingai#376]
### Describe the problem related to the feature request

<img width="1419" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/103013573/4a417004-ceab-4ec3-87e1-350ddef42634">
好像支持文件上传了

### Describe the solution you'd like

能否添加文件上传

**Comment by ryanzhaorx** [comment]
![a6aa23a3357170a34503e0201a617fb9_720](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/103013573/5a474f83-6ba8-4d46-8992-c4695eb8f4f6)
![c5bc1d2af5b4597122fa7a589e846326_720](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/103013573/1f6794b8-6656-4926-bc91-1af261209117)

**Comment by Harry-zklcdc** [comment]
#270 在这追踪进度
