### ISSUE TITLE
[Bug] 🐛 在vercel后端变量设置多用户cookie不成功

### ISSUE THREAD

**Issue by GforPG** [Harry-zklcdc/go-proxy-bingai#377]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the bug

在cf中变量设置多cookie成功，在vercel后端变量设置多cookie不成功（同时前端填多COOKIE也不成功，前端填单COOKIE成功）

### Steps to reproduce

如上描述

### Expected behavior

修复

### Deploy

Vercel

### OS & Version

windows11

### Browser & Version

chrome 121.0.6167.140

### GoProxiBingAI Version

v2.1.1

**Comment by Harry-zklcdc** [comment]
Vercel 的话比较繁琐，需要填多个环境变量

```bash
Go_Proxy_BingAI_USER_TOKEN=token_1,token2,token3
Go_Proxy_BingAI_USER_TOKEN_1=token_1
Go_Proxy_BingAI_USER_TOKEN_2=token_2
Go_Proxy_BingAI_USER_TOKEN_3=token_3
```

**Comment by Harry-zklcdc** [comment]
而且现在支持前端直接账号登录了，内置 Cookie 实在没什么必要了

**Comment by GforPG** [comment]
哦，这样，我以为可以逗号隔开呢，明白了，好的，都试玩玩，账号也试试

**Comment by GforPG** [comment]
登录一个账号一天只有15个提升，多COOKIE就不用账号换来换去啊，大佬

**Comment by GforPG** [comment]
所以这个功能不要删除啊
