### ISSUE TITLE
[Help] 🤔 二进制运行参数配置

### ISSUE THREAD

**Issue by NikoCat233** [Harry-zklcdc/go-proxy-bingai#378]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

文档中没有提及二进制程序参数的配置
请问如果配置二进制直接运行的参数

### Steps to behave

无需

### Expected behavior

无需

### Deploy

Others

### OS & Version

无需

### Browser & Version

无需

### GoProxiBingAI Version

无需

**Comment by Harry-zklcdc** [comment]
参考 [Wiki - 环境变量(https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F)

**Comment by Harry-zklcdc** [comment]
已在 Wiki 中添加对应提示，感谢~
