### ISSUE TITLE
[Help] 🤔 vercel 部署之后，调用api，返回500

### ISSUE THREAD

**Issue by SummerSec** [Harry-zklcdc/go-proxy-bingai#379]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

vercel 部署之后，添加环境变量SYDNEY_BASE_URL不生效

### Steps to behave

<img width="917" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/47944478/210aaeb9-1b7d-486a-a176-2db591141adc">
没有发现添加SYDNEY_BASE_URL 的动作

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/47944478/f7b722c9-0e15-488a-940e-49598e1e55ef)

### Expected behavior

如何做？

### Deploy

Vercel

### OS & Version

mac

### Browser & Version

chrome

### GoProxiBingAI Version

最新版

**Comment by SummerSec** [comment]
没有发现默认设置自定义的聊天服务器

**Comment by SummerSec** [comment]
> https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/Vercel-%E9%83%A8%E7%BD%B2
> 
> 应该是没有按照wiki说明部署。
> 
> 其实由于vercel不支持wss，所以，其上部署的sydney路由
> ` {
>       "src": "/sydney/.*",
>       "dest": "/api/sydney.go"
>     },`
> 并不会生效。
> 只能在域名服务器上添加路由。其实质略等于另外一个CF部署。

第一个域名解决了，另一个api调用是什么情况呀?请问大佬

**Comment by Harry-zklcdc** [comment]
所以你是想要请求哪一个的 API，cfwk 还是 vercel 的，要请求哪一个就去看对应的部署文档，确保按照文档完成部署

**Comment by SummerSec** [comment]
> 所以你是想要请求哪一个的 API，cfwk 还是 vercel 的，要请求哪一个就去看对应的部署文档，确保按照文档完成部署

cfwk和vercel的API都出现了这个调用返回500的问题，目前聊天服务器的问题都已经解决了。网页端都能正常使用了，API也配置了默认key

**Comment by Harry-zklcdc** [comment]
请给出对应请求的日志

**Comment by SummerSec** [comment]
> 请给出对应请求的日志

请问设置环境变量debug之后在哪能看日志呀

**Comment by SummerSec** [comment]
调用路径``/v1/chat/completions``和``/api/v1/chat/completions``是一样的问题，请求包如下：
```http
POST /v1/chat/completions HTTP/1.1
Host: bing.xxxx
User-Agent: curl/7.79.1
Accept: */*
Content-Type: application/json
Authorization: Bearer sk-sxxx
Content-Length: 146

{
    "id": "chatcmpl-NewBing",
    "object": "chat.completion.chunk",
    "created": 1705389778,
    "model": "Creative-g4t",
    "system_fingerprint": "ZB1yCBf7GngW",
    "choices": [
        {
            "index": 0,
            "delta": {},
            "message": {
                "role": "assistant",
                "content": "你好！这里是必应。我可以帮助你找到信息、回答问题、创造内容，还有更多。请问有什么我可以帮助你的吗？ 😊"
            },
            "finish_reason": "stop"
        }
    ]
}
```
<img width="1393" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/47944478/bae1a30e-1843-455e-944c-cb7a4de9c025">
 
<img width="1384" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/47944478/a90116bb-a876-45c7-bf30-4a3310fff9a2">

**Comment by Harry-zklcdc** [comment]
这报错咋这么奇怪，我代码里面没有单独的s变量哇，同步代码试试

**Comment by SummerSec** [comment]
> 这报错咋这么奇怪，我代码里面没有单独的s变量哇，同步代码试试
更新到最新版本，还是一样

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/47944478/fdd2e633-6d12-4119-929a-82471928a149)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/47944478/53d7a7ea-db89-4c05-917a-7daef47a7ffe)

**Comment by Harry-zklcdc** [comment]
Cloudflare
<img width="537" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/fff68e5e-8609-4035-b028-129e017cd1d2">

Vercel
<img width="536" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/f772d957-9168-4bf6-b9e2-acbf3fe65998">

我这都是正常的

**Comment by SummerSec** [comment]
> Cloudflare 云焰 <img alt="image" width="537" src="https://private-user-images.githubusercontent.com/21104213/314408289-fff68e5e-8609-4035-b028-129e017cd1d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MjIyNTMsIm5iZiI6MTcxMDkyMTk1MywicGF0aCI6Ii8yMTEwNDIxMy8zMTQ0MDgyODktZmZmNjhlNWUtODYwOS00MDM1LWIwMjgtMTI5ZTAxN2NkMWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDA4MDU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0NzlkNzUwYTVhNjgwMjFhNzA4ZmNjMjkxNGU3MDQ0MGQ3YWE2OTUyYzhmNzIxZjM5NjNkNTMzODhhNGY5ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pIhi_uQsr7twnZAwVMDM8snUh8SZ9eShOVVhJiy58A0">
> 
> Vercel 韦尔塞尔 <img alt="image" width="536" src="https://private-user-images.githubusercontent.com/21104213/314408575-f772d957-9168-4bf6-b9e2-acbf3fe65998.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MjIyNTMsIm5iZiI6MTcxMDkyMTk1MywicGF0aCI6Ii8yMTEwNDIxMy8zMTQ0MDg1NzUtZjc3MmQ5NTctOTE2OC00YmY2LWI5ZTItYWNiZjNmZTY1OTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDA4MDU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2ZmFjZGQ4ZjM2MDUxNzU2ZmM5ZTZlOTUwYjk1ZjgxMTNkNWM3Y2VjMTQwZDVlNzJhMzIwODQ2NTQzZDcyMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SeSeA3m1WyKx_o935wm9HQuNmmXClnOi3aKb20oFxoM">
> 
> 我这都是正常的
知道是什么问题了，是我请求包错了
