### ISSUE TITLE
添加 聊天记录 开关

### ISSUE THREAD

**Issue by luckyEason** [Harry-zklcdc/go-proxy-bingai#38]
聊天记录在iPad上会显示不完整，网站如果公开也会暴露用户隐私，有没有什么办法让聊天记录不显示

**Comment by Harry-zklcdc** [comment]
> 聊天记录在iPad上会显示不完整，网站如果公开也会暴露用户隐私，有没有什么办法让聊天记录不显示

聊天记录只会保留在对应的用户的账号上，除非 你是共享`_U`cookie

**Comment by luckyEason** [comment]
> > 聊天记录在iPad上会显示不完整，网站如果公开也会暴露用户隐私，有没有什么办法让聊天记录不显示
> 
> 
> 
> 聊天记录只会保留在对应的用户的账号上，除非 你是共享`_U`cookie

我是共享的

**Comment by Harry-zklcdc** [comment]
> 我是共享的

共享Cookie自然就会这样，你再怎么改都是掩耳盗铃罢，
实在要修改，改这个：[frontend/public/js/bing/chat/config.js](https://github.com/Harry-zklcdc/go-proxy-bingai/blob/master/frontend/public/js/bing/chat/config.js)

**Comment by luckyEason** [comment]
> 
> 
> > 我是共享的
> 
> 
> 
> 共享Cookie自然就会这样，你再怎么改都是掩耳盗铃罢，
> 
> 实在要修改，改这个：[frontend/public/js/bing/chat/config.js](https://github.com/Harry-zklcdc/go-proxy-bingai/blob/master/frontend/public/js/bing/chat/config.js)

改什么内容求解答

**Comment by Harry-zklcdc** [comment]
> 改什么内容求解答

自己找一下，试一下内容，我记得有注释，没有注释就自己试试

**Comment by luckyEason** [comment]
> 

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/109937362/ac43f911-e865-4f9a-addf-0aa88bb82400)
这样吗？

**Comment by Harry-zklcdc** [comment]
> ![image](https://user-images.githubusercontent.com/109937362/256807404-ac43f911-e865-4f9a-addf-0aa88bb82400.png) 这样吗？

你都试试吧，我也不太确定

**Comment by Harry-zklcdc** [comment]
之后我做个设置页面吧

**Comment by luckyEason** [comment]
ヾ(≧∇≦谢谢≧∇≦)ノ

**Comment by Harry-zklcdc** [comment]
已提交代码，commit: bae010e5bdbd1b9b2f8ebb4f7e96bbc62b1ab14e
