### ISSUE TITLE
[Bug] 🐛 Cloudflare部署无法使用登录功能

### ISSUE THREAD

**Issue by liliwen365** [Harry-zklcdc/go-proxy-bingai#381]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/76478019/b60526fd-cbcc-40e4-8984-eabcbf2a2dd4)
你好，我自建的CloudFlare站，用账户密码登录时显示登录失败，如上图，请问是什么原因，我应该如何处理，感谢！

### Steps to behave

账户密码登录时报错：登录失败，请重试！

### Expected behavior

我应该如何处理，希望得到指导，感谢！

### Deploy

Cloudflare Worker

### OS & Version

windows11

### Browser & Version

Chrome

### GoProxiBingAI Version

v2.2.0

**Comment by Harry-zklcdc** [comment]
https://account.live.com/activity

点一下同意，第一次密码登录会被拦截

**Comment by Harry-zklcdc** [comment]
无回复消息，关闭此issu

**Comment by liliwen365** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/76478019/9f961350-060a-4a3a-8b64-f643b77b27bd)
点击了你的连接，输入我的微软账户和密码，就出现如上图；没有显示需要同意的地方；
然后我去登录我自建的项目网页，还是显示失败；但是我可以用我的账户登录你的公开的这个https://bingai.zklcdc.xyz/web/index.html#/演示站，另一个演示站：https://bingai-cfwk.zklcdc.xyz/web/#/，CF的这个你的这个也登录不了；是不是我搭建的项目在CF上，所有也登录不了？
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/76478019/48fb990f-60b5-4464-9c1d-c8ae8fa7c107)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/76478019/42b07234-2c8c-4a47-83a0-cb5ba191518f)
感谢你的回答~~~~

**Comment by liliwen365** [comment]
我刚才测试了几个你的演示站，还有我自己建的vercel上的站，都可以账户密码登录；唯独Cloudflare Worker的不行，你公开的演示站也不行；应该是这个Cloudflare Worker平台相关的问题；

**Comment by Harry-zklcdc** [comment]
我尝试复现一下

**Comment by Harry-zklcdc** [comment]
会有这种提示，你的邮箱也会有提醒
<img width="1103" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/f0898083-256c-4d97-81df-00575d17fe7d">

我这边测试是正常可以登录的
<img width="967" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/cb44a06d-b02f-438e-9508-1827d1cc0b1b">

**Comment by Harry-zklcdc** [comment]
无回复消息，关闭此issue

**Comment by Diaoest-Mian** [comment]
你好，我也遇到了一样的问题，尝试了几个公开的演示站，部署在cf workers的只有`https://bing.dongsiqie.me/`可以登录成功，其他都是登录失败，且在微软账号活动记录页面没有记录。然后又尝试了pages部署，一样提示登录失败。
目前部署版本是2.3.0, 尝试一键重置再登录也一样。

**Comment by Harry-zklcdc** [comment]
> 你好，我也遇到了一样的问题，尝试了几个公开的演示站，部署在cf workers的只有`https://bing.dongsiqie.me/`可以登录成功，其他都是登录失败，且在微软账号活动记录页面没有记录。然后又尝试了pages部署，一样提示登录失败。
> 目前部署版本是2.3.0, 尝试一键重置再登录也一样。

进频道私我账密，我需要账密用来 debug，我自己的账号一直可以用
