### ISSUE TITLE
[Bug] 🐛 图片生成API请求出错

### ISSUE THREAD

**Issue by chaoyu1999** [Harry-zklcdc/go-proxy-bingai#382]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the bug

vercel部署，图片生成API请求出错。
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/46945475/4ef91634-3b04-46ab-acc6-192c7d1772ab)

### Steps to reproduce

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/46945475/129ca1bc-57f9-4fb1-a361-de9743fafecb)

### Expected behavior

返回Json图片url

### Deploy

Vercel

### OS & Version

win 10

### Browser & Version

edge 电脑版

### GoProxiBingAI Version

最新版

**Comment by Harry-zklcdc** [comment]
不是bug，是超时了，Vercel有限制25秒得要有返回内容，换CF吧
