### ISSUE TITLE
使用api进行部署nextchat报错"empty response from server"[Help] 🤔 

### ISSUE THREAD

**Issue by chengtx809** [Harry-zklcdc/go-proxy-bingai#383]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

本体部署在cf上，可以直接访问网页进行聊天
但是在使用api接入nextchat后报错
{
  "error": true,
  "message": "empty response from server"
}

### Steps to behave

go-proxy-bingai部署在 https://chat.chengtx.xyz ，可以正常聊天

nextchat的环境变量：
OPENAI_API_KEY环境变量正常设置，与cf设置的一样，没有问题
BASE_URL设置为https://chat.chengtx.xyz/v1/chat/completions

开始聊天后就会出现如下图所示的问题
还望大佬解答

### Expected behavior

正常聊天

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/103792951/3cbb5021-a99f-4080-a1b7-8b3010d015f4)

### Deploy

Cloudflare Worker

### OS & Version

windows 10

### Browser & Version

Microsoft Edge 版本 122.0.2365.92 (正式版本) (64 位)

### GoProxiBingAI Version

最新

**Comment by chengtx809** [comment]
补一下：
在nextchat使用自定义接口，完全一样的地址又可以正常聊天，不知道为什么
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/103792951/9e0697fd-0b43-49ea-8ba7-f21ee77e8d37)

**Comment by Harry-zklcdc** [comment]
baseURL 设置错误

应该为
```bash
BASE_URL=https://chat.chengtx.xyz
```

**Comment by chengtx809** [comment]
> baseURL 设置错误
> 
> 应该为
> 
> ```shell
> BASE_URL=https://chat.chengtx.xyz
> ```

还是无法使用，大佬可以尝试下复现看看？
apikey我暂时设置成了sk-123456

**Comment by Harry-zklcdc** [comment]
我有空试一下

**Comment by chengtx809** [comment]
> 我有空试一下

好的，我感觉和[#3427](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/3427)提到的这个issue有关？

**Comment by Harry-zklcdc** [comment]
我这边正常

<img width="489" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/56928162-55f0-4f03-847f-b6792abf3880">
<img width="992" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/57f40f08-89bc-4e81-8afd-f4538f36dd63">

**Comment by chengtx809** [comment]
> 我这边正常
> 
> <img alt="image" width="489" src="https://private-user-images.githubusercontent.com/21104213/317212753-56928162-55f0-4f03-847f-b6792abf3880.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MzQzOTUsIm5iZiI6MTcxMTUzNDA5NSwicGF0aCI6Ii8yMTEwNDIxMy8zMTcyMTI3NTMtNTY5MjgxNjItNTVmMC00ZjAzLTg0N2YtYjY3OTJhYmYzODgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDEwMDgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmNjQ4NGI3YjZlYzdmNDU2YmIwZTIzZDY4YTVmN2FiYWJmMTQ3YjcxZWNlNjliM2ViNzY1ZjgwNDg3NmEyNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FZQm-0WDAfIDLFnnmCwxHs5kx2Cq-zJBFZa0EU3MSTY"> <img alt="image" width="992" src="https://private-user-images.githubusercontent.com/21104213/317212690-57f40f08-89bc-4e81-8afd-f4538f36dd63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MzQzOTUsIm5iZiI6MTcxMTUzNDA5NSwicGF0aCI6Ii8yMTEwNDIxMy8zMTcyMTI2OTAtNTdmNDBmMDgtODliYy00ZTgxLThhZmQtZjQ1MzhmMzZkZDYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDEwMDgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5MTEwNDEyNTQ3YzMwOGJiMzEyYjZjZTVhOGZlNWRiOTgwNjJkYWM4OGMyZDU0YWI1ZWM3NGFjYzA0OWRmZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r_fbl8btqAYnpApTgoy5mGvftOpOX_Q1Mk-SrKqpr1Q">

奇了怪了，我部署在vercel上就有问题

**Comment by chengtx809** [comment]
在cf上部署后正常，应该是vercel的问题，与本项目无关
