### ISSUE TITLE
[Feature] 🌈 能不能加入一个环境变量来选择默认UI版本

### ISSUE THREAD

**Issue by chengtx809** [Harry-zklcdc/go-proxy-bingai#385]
### Describe the problem related to the feature request

个人不太喜欢V3版本的UI，觉得V2好点
希望可以加入一个环境变量来指定默认UI版本

### Describe the solution you'd like

环境变量

**Comment by Harry-zklcdc** [comment]
不做，请使用设置-高级设置自行指定，或自行修改前端源代码
