### ISSUE TITLE
[Feature] 🌈 模型请求

### ISSUE THREAD

**Issue by i2qaq** [Harry-zklcdc/go-proxy-bingai#387]
### Describe the problem related to the feature request

发现模型列表里少了几个模型

### Describe the solution you'd like

大佬，请问可以添加三种模式下的g4t-18k-offline
和g4t-18k-offline-vision模型吗？
（各种特性buff叠满的模型（bushi）

**Comment by ryanzhaorx** [comment]
我记得之前他在QQ频道里说过18K不能关闭搜索，会出现错误

**Comment by Harry-zklcdc** [comment]
楼上正解

而且经过测试，不含-18k的模型似乎可以正常有32k的上下文

**Comment by ryanzhaorx** [comment]
> 楼上正解
> 
> 而且经过测试，不含-18k的模型似乎可以正常有32k的上下文

也就是这18K还是累赘？

**Comment by i2qaq** [comment]
原来如此，谢谢大佬们解答

**Comment by Harry-zklcdc** [comment]
> 也就是这18K还是累赘？

也不是，就是 18K 的参数我是从 Notebook 模式提取出来的，Notebook 模式有的特性，这个模型都有
