### ISSUE TITLE
[Help] 🤔 登录后智力变低

### ISSUE THREAD

**Issue by RayGicEFL** [Harry-zklcdc/go-proxy-bingai#388]
登录前
<img width="833" alt="PixPin_2024-03-31_09-10-40" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/96906415/d2bac5ca-67fb-4ab6-a683-fc1b0e84b95f">

<img width="839" alt="1" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/96906415/33ac0c14-4024-45bc-ba9e-533d6061e473">

登录后
<img width="820" alt="PixPin_2024-03-31_09-13-04" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/96906415/4ced0bcb-a0f7-442a-84ba-bb32331628e6">

<img width="826" alt="2" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/96906415/ca4546ac-7239-4852-9ad4-515caeb951c5">

**Comment by ningguoxu** [comment]
换成精确模式试试

**Comment by Harry-zklcdc** [comment]
有空我试试啥情况

**Comment by RayGicEFL** [comment]
切精确模式后好了。。好奇这是什么原理，总不能登录和非登录用户的temperature不一样吧

**Comment by RayGicEFL** [comment]
直接官网 bing 不登录也是傻的，只有 go-proxy-bingai 不登录智商高一点。。
<img width="1120" alt="无标题" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/96906415/c0841079-b077-4173-bd22-55d2b73a102a">
用别的逻辑问题试了一下，也是这个结论。

**Comment by Harry-zklcdc** [comment]
GPB我调过参数，可能登录账号会把参数覆盖了，我看看能不能调一下

**Comment by RayGicEFL** [comment]
哪个commit？指个路呗

**Comment by Harry-zklcdc** [comment]
> 哪个commit？指个路呗

https://github.com/Harry-zklcdc/go-proxy-bingai/blob/206d9e82b36a8ad1a545f7db56f56828e345213d/frontend/src/views/chat/components/Chat/Chat.vue#L246-L285

**Comment by Harry-zklcdc** [comment]
我这登录前后都是正常的，请尝试更新到最新版本

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/c264c05b-9999-4ef7-973f-37ddebe022b6)

**Comment by Harry-zklcdc** [comment]
> 猜测可能和点击了「新话题」或者选择了「对话风格」，导致注入的参数失效

不过我这边试了一下，点击「新话题」或选择「对话风格」的时候，并不会导致 智力下降 的情况

**Comment by RayGicEFL** [comment]
破案了，登录之后必须把GPT-4 Turbo的开关关掉，再打开，就有效果了，看看是不是代码逻辑有点问题？

**Comment by Harry-zklcdc** [comment]
> 破案了，登录之后必须把GPT-4 Turbo的开关关掉，再打开，就有效果了，看看是不是代码逻辑有点问题？

我这边开不开都一样，都能正常回答出问题

**Comment by RayGicEFL** [comment]
那奇怪了，也许高峰期微软ban了部分用户的GPT-4权限？我看Copilot Pro的宣传就说“在高峰期能够使用GPT-4或GPT-4-Turbo”。没事了

**Comment by sdferttt** [comment]
same as me
