### ISSUE TITLE
[Help] 🤔 BYPASS_SERVER  怎么部署,有教程吗

### ISSUE THREAD

**Issue by yuzhegan** [Harry-zklcdc/go-proxy-bingai#389]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

BYPASS_SERVER  怎么部署,有教程吗

### Steps to behave

BYPASS_SERVER  怎么部署,有教程吗

### Expected behavior

BYPASS_SERVER  怎么部署,有教程吗

### Screenshots

BYPASS_SERVER  怎么部署,有教程吗

### Deploy

Cloudflare Worker

### OS & Version

win11

### Browser & Version

chorme

### GoProxiBingAI Version

v.19

**Comment by Harry-zklcdc** [comment]
请不要提无意义的问题，看文档能解决大部分的问题

Azure、CodeSandbox、Docker 部署均有说明
