### ISSUE TITLE
无效域。如果此问题仍然存在，请与站点管理员联系。

### ISSUE THREAD

**Issue by jivaklong** [Harry-zklcdc/go-proxy-bingai#39]
你们的还可以正常使用吗? 现在选择Cloudflare | https://sydney.vcanbb.chat 聊天时提示 无效域。如果此问题仍然存在，请与站点管理员联系。
或是科学上网选择https://sydney.bing.com   也是回复没反应

**Comment by qinguoluo** [comment]
1.9.3版本还是没有解决这个问题。

**Comment by Harry-zklcdc** [comment]
你是一点不看啊，https://github.com/adams549659584/go-proxy-bingai/issues/378#issue-1823522916

**Comment by qinguoluo** [comment]
> 你是一点不看啊，[adams549659584#378 (comment)](https://github.com/adams549659584/go-proxy-bingai/issues/378#issue-1823522916)

抱歉，我是真没注意到。
