### ISSUE TITLE
[Help] 🤔 vercel部署失败，import按教程走的。

### ISSUE THREAD

**Issue by jokson** [Harry-zklcdc/go-proxy-bingai#390]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

在vercel初始部署阶段

### Steps to behave

fork到自己仓库后在vercel里import添加环境变量后部署发生错误。
<html>
<body>

Error: The following Serverless Functions contain an invalid "runtime":
--
11:19:00.693 | - api/Opaluqu (provided.al2)
11:19:00.693 | - api/bypass (provided.al2)
11:19:00.693 | - api/challenge (provided.al2)
11:19:00.693 | - api/designer (provided.al2)
11:19:00.693 | - api/edgesvc (provided.al2)
11:19:00.693 | - api/index (provided.al2)
11:19:00.693 | - api/login (provided.al2)
11:19:00.693 | - api/sydney (provided.al2)
11:19:00.693 | - api/sys-config (provided.al2)
11:19:00.693 | - api/verify (provided.al2)
11:19:00.693 | - api/web (provided.al2). Learn More: https://vercel.com/guides/serverless-function-contains-invalid-runtime-error

</body>
</html>

### Expected behavior

求帮忙看看。

### Deploy

Vercel

### OS & Version

win10

### Browser & Version

edge

### GoProxiBingAI Version

v2.11

**Comment by Harry-zklcdc** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/8166b8ec-a076-4dea-9f76-be839bc2784e)

这边设置 Node 版本为 18.x

> PS: 之前的版本默认为 18.x ，现在默认20.x了，会导致报错

**Comment by jokson** [comment]
> https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/Vercel-%E9%83%A8%E7%BD%B2#%EF%B8%8F-%E6%B3%A8%E6%84%8F

感谢，已解决。
