### ISSUE TITLE
[Bug] 🐛 codesandbox无法部署

### ISSUE THREAD

**Issue by wurenzhiwen** [Harry-zklcdc/go-proxy-bingai#394]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

如何正确在csb上部署此项目

### Steps to behave

按照wiki上的教程

### Expected behavior

正常部署

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/118254009/b9b33862-a300-4ee9-afd7-41d103350719)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/118254009/d77bcde4-40b9-45d8-a654-4304b06fcc53)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/118254009/edbf870d-5a7a-4373-967a-9b85d4cf0850)

### Deploy

CodeSandbox

### OS & Version

win11

### Browser & Version

Microsoft Edge 版本 123.0.2420.65 (正式版本) (64 位)

### GoProxiBingAI Version

2.3.0

**Comment by Harry-zklcdc** [comment]
CodeSandbox部署，似乎出问题了，我这边也是一直没法用，有空我看看吧

**Comment by AlterGu** [comment]
你好，我单独部署验证服务的时候也是如下报错: `Dev server was stopped. Do you want to close it?`
是跟据wiki中的教程一步步走的。

**Comment by Harry-zklcdc** [comment]
已修复
