### ISSUE TITLE
[Help] 🤔 关于画图后，单张图片再创作

### ISSUE THREAD

**Issue by GforPG** [Harry-zklcdc/go-proxy-bingai#395]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

大佬，之前画图的时候，点进去单张图片，还可以再创作，比较更改尺寸，加滤镜啥的，现在怎么没有了

### Steps to behave

。。。

### Expected behavior

恢复单张图片再创作

### Screenshots

![309489235-7f6fa524-1416-4bd2-9d94-3a5742b13a7e](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/138672705/f2e4ad59-7e7c-43ee-ad82-36b2f8b50914)

### Deploy

Cloudflare Worker

### OS & Version

windows11

### Browser & Version

chrome 121.0.6167.140

### GoProxiBingAI Version

v2.3.0

**Comment by Harry-zklcdc** [comment]
演示站有没有这个问题

**Comment by GforPG** [comment]
> 演示站有没有这个问题

演示站可以单图再创作啊，就跟上面发那张图一样！官网试了都不行，官网点单图就进图像创建器网页了。咋回事。现在CF部署的，有时和演示站一样，有时和官网一样。

**Comment by GforPG** [comment]
我去多测试了几次，感觉和个人账号有关

**Comment by Harry-zklcdc** [comment]
清除一下 CF 的缓存

**Comment by GforPG** [comment]
好像好了，谢谢！

**Comment by Harry-zklcdc** [comment]
没问题就先关闭此 Issue 吧，有问题再打开
