### ISSUE TITLE
[Bug] 🐛 docker部署失败

### ISSUE THREAD

**Issue by kkkunny** [Harry-zklcdc/go-proxy-bingai#396]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

docker部署失败

### Steps to behave

按照官网教程进行docker部署
首先教程滞后，docker-compose.yml已经不再包含go-bingai-pass服务
转而尝试部署docker-compose-with-pass.yml文件，遇到第一个错误
```bash
service "go-proxy-bingai" depends on undefined service "go-bingai-pass": invalid compose project
```
删除docker-compose-with-pass.yml中的go-bingai-pass依赖后继续尝试部署
docker容器创建成功，但是容器内报错
```text
Error: Format string '/app/cloudflared tunnel --no-autoupdate run --token %(ENV_CF_ZERO_TRUST_TOKEN)s' for 'program:cloudflared.command' contains names ('ENV_CF_ZERO_TRUST_TOKEN') which cannot be expanded. Available names: ENV_BROWSER_BINARY, ENV_BYPASS_SERVER, ENV_DISPLAY, ENV_DISPLAY_NUM, ENV_GBP_USER, ENV_GBP_USER_ID, ENV_Go_Proxy_BingAI_BLANK_API_KEY, ENV_HEADLESS, ENV_HOME, ENV_HOSTNAME, ENV_LC_CTYPE, ENV_LOG_LEVEL, ENV_PATH, ENV_PORT, ENV_PWD, ENV_SCREEN_DEPTH, ENV_SCREEN_DPI, ENV_SCREEN_HEIGHT, ENV_SCREEN_WIDTH, ENV_SE_START_XVFB, ENV_XDG_CACHE_HOME, ENV_XDG_CONFIG_HOME, group_name, here, host_node_name, numprocs, process_num, program_name in section 'program:cloudflared' (file: '/etc/supervisor/conf.d/supervisor.conf')
```

### Expected behavior

通过docker-compose-with-pass.yml正确部署

### Deploy

Docker

### OS & Version

Ubuntu 22.04.4 LTS

### Browser & Version

Edge

### GoProxiBingAI Version

v0.0.0

**Comment by Harry-zklcdc** [comment]
已修复，请尝试 dev 分支
