### ISSUE TITLE
[Help] 🤔 如何在部署时修改高级选项中的默认提示词

### ISSUE THREAD

**Issue by liliwen365** [Harry-zklcdc/go-proxy-bingai#398]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

你好，感谢你项目提供的帮助，我有一个需求：
我想在部署时，修改高级选项中的默认提示词，如下图：请问我在vercel部署时如何修改这个提示词，非常感谢！
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/76478019/b3a843e1-944f-41f6-831d-1a99767b169a)

### Steps to behave

无

### Expected behavior

无

### Deploy

Vercel

### OS & Version

windows11

### Browser & Version

Chrome

### GoProxiBingAI Version

v2.3

**Comment by Harry-zklcdc** [comment]
自行修改这行代码：https://github.com/Harry-zklcdc/go-proxy-bingai/blob/871af103fec68a00c09c66d61618c6a94354d13d/frontend/src/stores/modules/user/index.ts#L31

然后`npm run build` 重新构建前端，`git push`到你的项目中
