### ISSUE TITLE
[Help] 🤔 

### ISSUE THREAD

**Issue by 1215548** [Harry-zklcdc/go-proxy-bingai#399]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

提示
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/14362835/2fae32f6-3dce-4b83-be20-064f17600b28)

### Steps to behave

按正常登入操作，账号登入成功，但提示如图

### Expected behavior

-

### Screenshots

-

### Deploy

Cloudflare Worker

### OS & Version

win11

### Browser & Version

edge

### GoProxiBingAI Version

-

**Comment by Harry-zklcdc** [comment]
可能是CF出bug了，过段时间看看吧

**Comment by Harry-zklcdc** [comment]
没有提交反馈，关闭此issue

**Comment by Harry-zklcdc** [comment]
重新登录账号试试，非本项目解决的问题
