### ISSUE TITLE
[Help] 🤔 使用docker搭建，打开页面一直是加载的状态，API测试可以用

### ISSUE THREAD

**Issue by LoveU3th** [Harry-zklcdc/go-proxy-bingai#400]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

使用docker搭建，打开页面一直是加载的状态，API测试可以用
![截图魔板-04_17_08_44](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/50294305/da0a4b19-929f-4be1-b063-3250785e9ee6)

### Steps to behave

go-proxy-bingai:
    image: zklcdc/go-proxy-bingai
    container_name: go-proxy-bingai
    restart: always
    ports:
      - 8183:8080
    environment:
      - BYPASS_SERVER=https://bypass.zklcdc.xyz
      #https://zklcdc-pass.hf.space

      # - BING_BASE_URL=https://www.bing.com
      # - SYDNEY_BASE_URL=https://sydney.bing.com
      # - HTTP_PROXY=http://172.17.0.1:18080
      # - HTTPS_PROXY=http://172.17.0.1:18080
      # - Go_Proxy_BingAI_USER_TOKEN_1=xxx
      # - Go_Proxy_BingAI_USER_TOKEN_2=xxx
      # - USER_KievRPSSecAuth=xxx
      # - USER_RwBf=xxx
      # - USER_MUID=xxx
      # - APIKEY=sk-xxx

### Expected behavior

更换了最新的chrome浏览器也无法打开，期望能正常打开网页界面

### Deploy

Docker

### OS & Version

Ubuntu 18.04

### Browser & Version

Cent Browser 版本 5.0.1002.354（正式版本） （64 位） (Portable) (Chromium 102.0.5005.167)

### GoProxiBingAI Version

zklcdc/go-proxy-bingai:latest

**Comment by Harry-zklcdc** [comment]
https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/Docker-%E9%83%A8%E7%BD%B2#5-%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86

#261 #210 https://github.com/Harry-zklcdc/go-proxy-bingai/issues/76#issuecomment-1663302300

**Comment by LoveU3th** [comment]
原来必须要443，挂了个cf tunnel可以啦，谢谢
