### ISSUE TITLE
[Feature] 🌈 支持 Copilot Pro 代理

### ISSUE THREAD

**Issue by shuoli-flash** [Harry-zklcdc/go-proxy-bingai#401]
### Describe the problem related to the feature request

我已经购买了Copilot Pro，我发现没有相关Copilot Pro的代理。

### Describe the solution you'd like

是否可以支持代理Copilot Pro?

**Comment by Harry-zklcdc** [comment]
需要提供账号，我方便做兼容

~~我自己买了GPT Plus~~

**Comment by Harry-zklcdc** [comment]
试了一下，CopilotPro 的效果甚至不如我调整之后的版本🤣，只有输出速度的差别

后面单独做一个默认关闭的按钮吧

**Comment by Harry-zklcdc** [comment]
已支持, Commit: 13dccf6a7ff24758a06f5dfce305e7c84dbf39b8
