### ISSUE TITLE
[Bug] 🐛 API回复随机出现叠字

### ISSUE THREAD

**Issue by chunzha1** [Harry-zklcdc/go-proxy-bingai#402]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the bug

利用CF部署的服务，在nextchat/lobechat等调用时，发现随机出现叠字现象：
你你好！有什什么什么我什么我可以什么我可以帮什么我可以帮助什么我可以帮助你什么我可以帮助你的什么我可以帮助你的吗什么我可以帮助你的吗？😊

### Steps to reproduce

随机出现

### Expected behavior

确认原因

### Deploy

Cloudflare Worker

### OS & Version

\

### Browser & Version

\

### GoProxiBingAI Version

\

**Comment by Harry-zklcdc** [comment]
能否提供稳定复现方式？

请去掉system消息后尝试

**Comment by chunzha1** [comment]
> 能否提供稳定复现方式？
> 
> 请去掉system消息后尝试
使用lobechat，默认模式不包含system
![LobeChat_随便聊聊_2024-04-18](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/125763492/a9e68ad4-d912-484c-a10f-f912749c5248)

**Comment by Harry-zklcdc** [comment]
![LobeChat_随便聊聊_2024-04-18](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/e161d6a4-ec1a-4a4e-98d7-7481fdc822d6)

我这没有复现出来

**Comment by chunzha1** [comment]
> ![LobeChat_随便聊聊_2024-04-18](https://private-user-images.githubusercontent.com/21104213/323539194-e161d6a4-ec1a-4a4e-98d7-7481fdc822d6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MzE1NTgsIm5iZiI6MTcxMzQzMTI1OCwicGF0aCI6Ii8yMTEwNDIxMy8zMjM1MzkxOTQtZTE2MWQ2YTQtZWMxYS00YTRlLTk4ZDctNzQ4MWZkYzgyMmQ2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA5MDczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YzU0NWM1ZTlhN2Q5MzQzOTMwMTc1NjllODA3MWQ5Y2M1YzQzMDM5MDAxNWZlYjZjODQzYjgwMmJjY2IzODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EepDzFkfNY2OrwiXJQmIyhpwrtR4ouCVEBBdmCcpS04)
> 
> 我这没有复现出来

模型选择有影响吗？我没有自己建bing-类的模型；另外是否可能跟Cloudflare worker部署方式相关？

**Comment by chunzha1** [comment]
这个并非100%复现，另外一个问题是吐字很慢，没有像web那样流畅

**Comment by Harry-zklcdc** [comment]
![LobeChat_随便聊聊_2024-04-18](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/8cbbaf53-9917-48b1-a3a3-a5df5add4ffc)

我这没法复现，可能是CF部署的原因

请尝试 [BingAPI演示站](https://bingapi.zklcdc.xyz/)

**Comment by chunzha1** [comment]
我也复现不出来了，似乎是一段时间没使用之后，第一次容易出现；我晚点再尝试下

**Comment by yushangxiao** [comment]
同cf部署，也有这种情况，而且也有只回复一个data片段且不存在content字段的情况

**Comment by Harry-zklcdc** [comment]
试一下 vercel 部署有没有这种情况

**Comment by yushangxiao** [comment]
> 试一下 vercel 部署有没有这种情况
用vercel会好很多
没有再出现只回复一个数据片段且不存在content字段的情况
但是依然会出现叠字，但是出现叠字的频率低了非常非常多，实验很多次才会出现一次
![Clip_2024-04-19_00-21-17](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/104288245/a97bae7c-47d7-421a-a328-a1e89af24f09)

**Comment by Harry-zklcdc** [comment]
~~Vercel 和 CF的实现是同源的~~

**Comment by yushangxiao** [comment]
> ~~Vercel 和 CF的实现是同源的~~

额，说实话，没搞明白为什么兜这么一圈子用 vercel 部署

可能的原因：
1.时间，cf 部署测试时 是下午-傍晚，欧美时差原因，用户少微软放的算力少，导致回复反应慢…
2.运行速度，使用 vercel 运行速度会快（未知）…确实响应快很多

**Comment by Harry-zklcdc** [comment]
我的意思是 Vercel 的 BingAPI 的实现代码和 CF 是一样的，并不是说Vercel 部署需要 CF 的那个`触发域`🤣🤣🤣

**Comment by yushangxiao** [comment]
> 我的意思是 Vercel 的 BingAPI 的实现代码和 CF 是一样的，并不是说Vercel 部署需要 CF 的那个`触发域`🤣🤣🤣

那这样的话， 一直不明白的是， vercel 部署前先部署 cf worker 和设置 cf worker 的目的是什么🤨

**Comment by Harry-zklcdc** [comment]
> 那这样的话， 一直不明白的是， vercel 部署前先部署 cf worker 和中间设置 cf worker 的目的是什么🤨

因为Vercel不能传输websocket到客户端，但是可以发起websocket连接到服务器

**Comment by yushangxiao** [comment]
> 
> > 那这样的话， 一直不明白的是， vercel 部署前先部署 cf worker 和中间设置 cf worker 的目的是什么🤨
> 
> 因为Vercel不能传输websocket到客户端，但是可以发起websocket连接到服务器
> 

原来如此，感谢解答(^🙏^)

**Comment by chunzha1** [comment]
![LobeChat_随便聊聊_2024-04-19](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/125763492/7b00bade-552e-411c-81e5-3adb4f083b20)
刚又试了几次，多次生成中出现了叠字以及无content、报504；
很抱歉，服务器没有等到上游服务器的回应，请稍后再试
Show Details
json
{
  "message": "很抱歉，服务器没有等到上游服务器的回应，请稍后再试",
  "type": 504
}
（吐字实在是好慢）
看两位上面的讨论，vercel部署似乎也避免不了？

**Comment by yushangxiao** [comment]
> ![LobeChat_随便聊聊_2024-04-19](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/125763492/7b00bade-552e-411c-81e5-3adb4f083b20)
> 刚又试了几次，多次生成中出现了叠字以及无content、报504；
> 很抱歉，服务器没有等到上游服务器的回应，请稍后再试
> Show Details
> json
> {
>   "message": "很抱歉，服务器没有等到上游服务器的回应，请稍后再试",
>   "type": 504
> }
> （吐字实在是好慢）
> 看两位上面的讨论，vercel部署似乎也避免不了？

vercel 部署， 现在又试了试，这些错误也都发生了，这么说确实与部署环境影响不大…

昨晚 夜间的响应很快很好虽然有叠字但频率很低，没有报错和无 content 的问题。

但这些现在又出现了，现在响应慢一些且频繁出问题。

这么说难道真的是时间的问题🤨
微软在使用流量低的时候，算力倾斜小，检查更严格？

**Comment by chunzha1** [comment]
但是用web的版本好像没有这个问题，吐字速度也快不少，不知道两者有什么差异？

**Comment by chaoyu1999** [comment]
感觉和网络稳定性有关系，我之前在微软官方Coplit和cbs、cf上部署的都会有叠字的现象，换到AZ之后就没有了。我猜测和网络环境有关，网络不稳定可能会导致丢包，然后服务器重发数据，但前面的数据包实际没丢，然后就叠字了。

**Comment by Harry-zklcdc** [comment]
看一下 [BingAPI演示站](https://BingAPI.zklcdc.xyz) 有没有这个问题

> 吐字速度

请确保web端和API选择的模型是同一个。平衡模式的输出速度是远大于创造和精准模式。

基于你选择的模型 `gpt-4-turbo-preview`，请调整 temperature 调整实际调用的模式，请参考 [Wiki - BingAPI - 模型列表](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/BingAPI#%E6%A8%A1%E5%9E%8B%E5%88%97%E8%A1%A8)

**Comment by chunzha1** [comment]
API画图还有个奇怪的问题，突然一直报{"error":"Generate Image Error"}%   然而网页版却可以正常画图，看cflog报的500，但是一curl就报错了，看起来不像超时

**Comment by yushangxiao** [comment]
> 感觉和网络稳定性有关系，我之前在微软官方Coplit和cbs、cf上部署的都会有叠字的现象，换到AZ之后就没有了。我猜测和网络环境有关，网络不稳定可能会导致丢包，然后服务器重发数据，但前面的数据包实际没丢，然后就叠字了。

Azure好啊，我也去部署在azure上了，确实挺丝滑的，舒服了

**Comment by dong152389** [comment]
这个问题我之前在vercel和cf上部署的时候 都遇到过，后来换了一个国外的服务器就不会出现这个问题了。
> 反正到现在是没遇到过

**Comment by Harry-zklcdc** [comment]
但是很奇怪的是，我明明已经对网络重新发包的情况，写了判断，不会发送重复的文字

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/255e46b4-cba2-4490-9bef-856696d69f2b)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/1a32fbcd-eb7d-4187-bee8-3011fcefab00)

**Comment by Harry-zklcdc** [comment]
目前还有没有这个情况？如有重新开启 issue

**Comment by chengtx809** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/103792951/b27dd525-03e6-4d91-a8c6-ba8c2bd60455)
大佬你的演示站也偶发性出现叠词了，我自己部署的也是 @Harry-zklcdc

**Comment by chengtx809** [comment]
> 现在发现先使用cfpg部署的本项目，再把[chatgptProxyAPI](https://github.com/x-dr/chatgptProxyAPI) 这个项目在自己的cf上部署一遍，反代本项目部署出来的page链接，得到的api就很稳定，用了一周，各个网络环境都试过了没有出现叠词

@Harry-zklcdc 大佬可以看看顺着这个思路能不能优化下本项目🙏
