### ISSUE TITLE
很抱歉，你已达到可在 24 小时内发送到必应的邮件限制。请稍后回来查看![Help] 🤔 

### ISSUE THREAD

**Issue by longstorying** [Harry-zklcdc/go-proxy-bingai#403]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

用油猴脚本登陆的。聊天的时候返回：很抱歉，你已达到可在 24 小时内发送到必应的邮件限制。请稍后回来查看!

### Steps to behave

按照wiki操作用cookie登陆

### Expected behavior

能正常聊天和画图

### Deploy

Cloudflare Worker

### OS & Version

win11

### Browser & Version

Chrome 124.0.6367.60

### GoProxiBingAI Version

最新版

**Comment by Harry-zklcdc** [comment]
更换账号

**Comment by longstorying** [comment]
> 更换账号
> 
> [Wiki - FAQ](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/FAQ#q-%E5%BE%88%E6%8A%B1%E6%AD%89%E4%BD%A0%E5%B7%B2%E8%BE%BE%E5%88%B0%E5%8F%AF%E5%9C%A8-24-%E5%B0%8F%E6%97%B6%E5%86%85%E5%8F%91%E9%80%81%E5%88%B0%E5%BF%85%E5%BA%94%E7%9A%84%E9%82%AE%E4%BB%B6%E9%99%90%E5%88%B6%E8%AF%B7%E7%A8%8D%E5%90%8E%E5%9B%9E%E6%9D%A5%E6%9F%A5%E7%9C%8B)

好的，我试试。
