### ISSUE TITLE
[Bug] 🐛 夜间模式时，使用/触发的提示词列表看不清

### ISSUE THREAD

**Issue by OuroborosCaster** [Harry-zklcdc/go-proxy-bingai#404]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the bug

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/49244214/bf3bddd2-e060-48cc-a894-23285e074acf)

### Steps to reproduce

在主题模式设置为深色时，在输入框处输入 / 

### Expected behavior

希望能优化显示

### Deploy

Docker

### UserId

m8dfra%7C2%7Cfl6%7C0%7C1558

### OS & Version

Win10

### Browser & Version

Chrome 124.0.6367.61

### GoProxiBingAI Version

v2.3.1

**Comment by Harry-zklcdc** [comment]
已修复, Commit: cfd8d3b1bf6f40523c8b56072e3f1c29ace1752f
