### ISSUE TITLE
[Feature] 🌈 请问能否增加一曾转换层，适配多条messages的情况

### ISSUE THREAD

**Issue by git-syl** [Harry-zklcdc/go-proxy-bingai#405]
### Describe the problem related to the feature request

当api模式下，请求携带多个上下文的时候bing只会获取第一个。
这个条消息，期望bing回复她的名字，实际bing回答的是Thanks you, i am a helpful assistant xxxx
```
{
    "model": "gpt-4-turbo-preview",
    "temperature": 1.25,
    "messages": [
        {
            "role": "system",
            "content": "You are a helpful assistant."
        },
        {
            "role": "user",
            "content": "你的名字,好吗？"
        }
    ]
}
```

请问作者后续是否考虑添加一个转换层，可以把多个上下文拼接起来一起发送呢？以解决上下文丢失的问题。感谢。

### Describe the solution you'd like

考虑添加一个转换层，可以把多个上下文拼接起来一起发送。

或者仅获取最后一条"role": "user"的消息，但是这样会丢失上下文。

**Comment by Harry-zklcdc** [comment]
现在已经是拼接的情况了

**Comment by git-syl** [comment]
> 现在已经是拼接的情况了
> 
> https://github.com/Harry-zklcdc/bing-lib/blob/e3351f6bbd4db0e6937ee2ab242224916780be3d/chat.go#L182-L275

我是今天早上一键部署测试的，没有出效果。
感谢，我再试试看。
