### ISSUE TITLE
[Bug] 🐛 bing不说中文了

### ISSUE THREAD

**Issue by hjx2289206** [Harry-zklcdc/go-proxy-bingai#408]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the bug

在演示站中，似乎只有Vercel演示站的bing说中文，其他演示站都不说中文了，电脑手机都一样

### Steps to reproduce

直接用演示站发信息

### Expected behavior

查看这个问题，是否可以修复

### Screenshots

![Screenshot_20240507_225757_com lemurbrowser exts](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/134860604/c7ff46c7-3ac6-4fd2-a95a-1f42f4f4f221)

### Deploy

Others

### OS & Version

Windows10、鸿蒙

### Browser & Version

edge、狐猴

### GoProxiBingAI Version

v2.3.1

**Comment by yurhett** [comment]
经过确认，发现是接口已更新。更新的地方还挺多的，特别是地址/语言提示，这也解释了为什么语言出问题的原因。大佬最近有空修复吗？ @Harry-zklcdc

**Comment by chengtx809** [comment]
我也是遇到了一样的情况欸，加油大佬

**Comment by Harry-zklcdc** [comment]
已经在研究了，目前测试下来，BingAPI没影响，web端影响较大

**Comment by Harry-zklcdc** [comment]
已修复, Commit: 9992862a0c58476fc6cc900177f5b03bde95eebb
