### ISSUE TITLE
[Bug] 🐛 登录账号后，聊天记录不能保存

### ISSUE THREAD

**Issue by atomlong** [Harry-zklcdc/go-proxy-bingai#410]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the bug

电脑端不能记住聊天记录。但手机端可以。

### Steps to reproduce

电脑端：
开启历史记录；
新打开聊天；
右侧显示聊天标题；
5分钟后右侧聊天记录消失；
刷新后也看不到聊天记录；
手机端：
验证手机端可以记住聊天记录。

### Expected behavior

电脑端记住聊天记录。

### Screenshots

开始的时候可以显示聊天记录
![2024-05-09_112336](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/3690342/bcb4af77-10dd-4373-b02d-5a7de3a18518)
稍等一会，聊天记录消失
![2024-05-09_112354](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/3690342/162e172d-a46a-4851-94c2-f15c9775b93b)
刷新后聊天记录不见
![2024-05-09_112433](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/3690342/6d7af3de-4d53-4ea2-8140-422e564479fd)

试过Microsoft Edge和Google chrome浏览器都不行。

### Deploy

Docker

### OS & Version

Windows 11

### Browser & Version

Microsoft Edge 商业版 版本 124.0.2478.80 (正式版本) (64 位)

### GoProxiBingAI Version

2.4.0

**Comment by Harry-zklcdc** [comment]
登录账号了？没有登录账号的话聊天记录是不保存的

**Comment by atomlong** [comment]
> 登录账号了？没有登录账号的话聊天记录是不保
已经登录账号了

**Comment by Harry-zklcdc** [comment]
看了一下代码，该传的参数都传了

**Comment by atomlong** [comment]
刚刚又试了一下。
打开梯子，账号登录方式选“一键登录”，这种登录方式是可以保存聊天记录的；
如果是“账号登录”方式则不行。
这两种不同的登录方式所获取的Cookie应该是不一样的。

**Comment by Harry-zklcdc** [comment]
OK，了解了

**Comment by Harry-zklcdc** [comment]
已修复, Commit: 250f571261e2e909546c48cf9578ed88ba9bf62e
