### ISSUE TITLE
[Bug] 🐛 cf+vercel在更有创造力模式下仍无法使用中文对话

### ISSUE THREAD

**Issue by chengtx809** [Harry-zklcdc/go-proxy-bingai#411]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the bug

cf+vercel在更有创造力模式下仍无法使用中文对话
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/103792951/9471865d-154f-4717-b007-4f276a42b22b)

### Steps to reproduce

直接聊天

### Expected behavior

使用中文对话

### Deploy

Vercel

### OS & Version

windows 10

### Browser & Version

Microsoft Edge

### GoProxiBingAI Version

v2.4.0

**Comment by chengtx809** [comment]
好像现在还不是很稳定，有时中文有时英文
使用演示站也这样
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/103792951/c6ee6b6c-7a48-44b9-ba95-d666611e6f22)

**Comment by chengtx809** [comment]
现在变成第一句英文，接下来中文了

**Comment by chengtx809** [comment]
> 现在变成第一句英文，接下来中文了

刚才手滑关了issues，补张图
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/103792951/89185f40-a4f7-4282-bcde-da6612e49309)

**Comment by Harry-zklcdc** [comment]
尝试一键重置

<img width="967" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/96577fda-7d21-48d8-8c43-e2ef6a3dbb26">

**Comment by Harry-zklcdc** [comment]
如有问题请在原 Issue 下继续回复，请勿开新 Issue
