### ISSUE TITLE
[Help] 🤔 请问下cloudflare works部署，出现Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

### ISSUE THREAD

**Issue by wangzhilin777** [Harry-zklcdc/go-proxy-bingai#412]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

出现Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.提示，
我看部署文件里面是18.7呢。请教。

### Steps to behave

.

### Expected behavior

.

### Deploy

Cloudflare Worker

### OS & Version

win10

### Browser & Version

edge

### GoProxiBingAI Version

v2.4.1

### Additional context

求教

**Comment by Harry-zklcdc** [comment]
截图，在哪出现的？

**Comment by Harry-zklcdc** [comment]
无回复，关闭Issue
