### ISSUE TITLE
[Bug] 🐛 cf部署循环人机验证

### ISSUE THREAD

**Issue by chengtx809** [Harry-zklcdc/go-proxy-bingai#413]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the bug

cf部署循环人机验证，page和worker都会
演示站也出现这个问题

### Steps to reproduce

正常聊天

### Expected behavior

通过人机验证

### Deploy

Cloudflare Worker

### OS & Version

windows 10

### Browser & Version

Microsoft Edge

### GoProxiBingAI Version

v2.4.1

**Comment by SokWith** [comment]
建议暂时使用我的cct服务器应急：

https://cct.nbing.eu.org/ cf workers部署     or
https://cctb.pages.dev/ cf pages 部署

**Comment by chengtx809** [comment]
> 建议暂时使用我的cct服务器应急：
> 
> https://cct.nbing.eu.org/ cf workers部署 or https://cctb.pages.dev/ cf pages 部署
> 
> 目前看上去cct cookie 对出口ip有要求，似乎是在同一网络获得的cct才有效，从其他网络获得的cct无效。 ![image](https://private-user-images.githubusercontent.com/129967025/330349892-17261b44-485a-484d-ad6c-8e1d07da5202.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODI0MDAsIm5iZiI6MTcxNTY4MjEwMCwicGF0aCI6Ii8xMjk5NjcwMjUvMzMwMzQ5ODkyLTE3MjYxYjQ0LTQ4NWEtNDg0ZC1hZDZjLThlMWQwN2RhNTIwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQxMDIxNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMWM2N2YzNWM3ZjBiMWIyMWUzOGE2NzQ4NDhjMDlhN2U4ODAyOGVjNzQwNDJkNmMzZTEyNmNhMTQ3YTY0NmQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LEBGlonFFymCAIX8KGUeaSNuumdOiCu0ZanEyU2D4oc)

好的，谢谢🙏

**Comment by chengtx809** [comment]
> 建议暂时使用我的cct服务器应急：
> 
> https://cct.nbing.eu.org/ cf workers部署 or https://cctb.pages.dev/ cf pages 部署
> 
> 目前看上去cct cookie 对出口ip有要求，似乎是在同一网络获得的cct才有效，从其他网络获得的cct无效。 ![image](https://private-user-images.githubusercontent.com/129967025/330349892-17261b44-485a-484d-ad6c-8e1d07da5202.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODI0NDgsIm5iZiI6MTcxNTY4MjE0OCwicGF0aCI6Ii8xMjk5NjcwMjUvMzMwMzQ5ODkyLTE3MjYxYjQ0LTQ4NWEtNDg0ZC1hZDZjLThlMWQwN2RhNTIwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQxMDIyMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGRkM2JjMTlkMzhiZThlYTliNmZhM2Q1YmFjNDExNzFiODNjZGIwZTI2OGUxMmZkYWZkOTRjZjQ1MDYyMTAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BBv8I-sGl46hsNAjCdyB4LI93l5OvsAm7i1tfrwY97k)

哇大佬你这个人机验证过得好快，能不能讲下是怎么实现的
（膜拜

**Comment by Harry-zklcdc** [comment]
> 目前看上去cct cookie 对出口ip有要求，似乎是在同一网络获得的cct才有效，从其他网络获得的cct无效。 

并没有，感觉还是和 IP 干净度有关，我自己的账号，在docker演示站上，一直可以通过人机验证，然而docker演示站在米国，验证服务器在泡菜国，说明还是和IP干净度有关系

**Comment by Harry-zklcdc** [comment]
而且还有一点，我的人机验证服务我做了缓存，~~有可能你拿到的cct是已经过期的，或者可能是每天聊天技术被用完了~~

**Comment by SokWith** [comment]
> > 目前看上去cct cookie 对出口ip有要求，似乎是在同一网络获得的cct才有效，从其他网络获得的cct无效
> 
> 并没有，感觉还是和 IP 干净度有关，我自己的账号，在docker演示站上，一直可以通过人机验证，然而docker演示站在米国，验证服务器在泡菜国，说明还是和IP干净度有关系

我的cct服务器是通过套娃获得的，多次测试表明：
1、如果最后一步与bing的连接是在hf上，则获得的cct对hf有效，对cf无效；
2、如果进一步套娃，让最后一步与bing的连接在cf上，则获得的cct对hf，cf都有效（目前取得的cct就是这样的）

目前演示站点上的验证，AZ不需要，docker和hf、CSB能够过，与cf相关的worker、pages、vc以及gitch都会无限循环，效果与我第1种获得的cct相似。

**Comment by Harry-zklcdc** [comment]
所以我感觉还是干净度，演示站的HF是`BYPASS_SERVER`填的也是`bypass.b1ng.chat`，glich和CF无关，只是用了CF的Tunnel

CF我自己试了一下，CFPG没有问题，CFWK一直循环
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/6318920d-d4ad-4b21-99d6-801612b3416d)

而且我试过同一个cct在CFPG和CFWK的情况下，CFPG正常，CFWK循环验证


而且`bypass.b1ng.chat`后端的服务器遍布全球，什么服务商都有，所以比较杂，可能有些能过，有些过不了，具体我没有细究

**Comment by chengtx809** [comment]
> 所以我感觉还是干净度，演示站的HF是`BYPASS_SERVER`填的也是`bypass.b1ng.chat`，glich和CF无关，只是用了CF的Tunnel
> 
> CF我自己试了一下，CFPG没有问题，CFWK一直循环 ![image](https://private-user-images.githubusercontent.com/21104213/330409458-6318920d-d4ad-4b21-99d6-801612b3416d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2OTM5MDMsIm5iZiI6MTcxNTY5MzYwMywicGF0aCI6Ii8yMTEwNDIxMy8zMzA0MDk0NTgtNjMxODkyMGQtZDRhZC00YjIxLTk5ZDYtODAxNjEyYjM0MTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDEzMzMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiZGU5YzQ5MTY3ZWY5MDgyMjc4YTc1NTJmZTlkNDNiNzcxNzE2OWEzMzYyOTQwNTY0N2MxN2I4NzQxMGY1NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rdopSAplmb2RSnJo3wWaidrS_FaJaOF4jfhU_XqTr8s)
> 
> 而且我试过同一个cct在CFPG和CFWK的情况下，CFPG正常，CFWK循环验证
> 
> 而且`bypass.b1ng.chat`后端的服务器遍布全球，什么服务商都有，所以比较杂，可能有些能过，有些过不了，具体我没有细究

大佬，worker和page在处理消息这块有何异同？感觉用下来确实是page比worker稳些

**Comment by chengtx809** [comment]
> > > 目前看上去cct cookie 对出口ip有要求，似乎是在同一网络获得的cct才有效，从其他网络获得的cct无效
> > 
> > 
> > 并没有，感觉还是和 IP 干净度有关，我自己的账号，在docker演示站上，一直可以通过人机验证，然而docker演示站在米国，验证服务器在泡菜国，说明还是和IP干净度有关系
> 
> 我的cct服务器是通过套娃获得的，多次测试表明： 1、如果最后一步与bing的连接是在hf上，则获得的cct对hf有效，对cf无效； 2、如果进一步套娃，让最后一步与bing的连接在cf上，则获得的cct对hf，cf都有效（目前取得的cct就是这样的）
> 
> 目前演示站点上的验证，AZ不需要，docker和hf、CSB能够过，与cf相关的worker、pages、vc以及gitch都会无限循环，效果与我第1种获得的cct相似。

大佬cct服务器有开源吗，能不能指下路，想自己部署🙏

**Comment by Harry-zklcdc** [comment]
隔壁：https://github.com/Harry-zklcdc/go-bingai-pass
而且 Readme 里面也写了哇

**Comment by SokWith** [comment]
> > > > 目前看上去cct cookie 对出口ip有要求，似乎是在同一网络获得的cct才有效，从其他网络获得的cct无效
> > > 
> > > 
> > > 并没有，感觉还是和 IP 干净度有关，我自己的账号，在docker演示站上，一直可以通过人机验证，然而docker演示站在米国，验证服务器在泡菜国，说明还是和IP干净度有关系
> > 
> > 
> > 我的cct服务器是通过套娃获得的，多次测试表明： 1、如果最后一步与bing的连接是在hf上，则获得的cct对hf有效，对cf无效； 2、如果进一步套娃，让最后一步与bing的连接在cf上，则获得的cct对hf，cf都有效（目前取得的cct就是这样的）
> > 目前演示站点上的验证，AZ不需要，docker和hf、CSB能够过，与cf相关的worker、pages、vc以及gitch都会无限循环，效果与我第1种获得的cct相似。
> 
> 大佬cct服务器有开源吗，能不能指下路，想自己部署🙏

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/28cae0cd-3547-45aa-916f-812254e4a420)
之前仓库开放过，目前关闭了（毕竟也算是大厂的一个bug）。
但是站点上有fork，所以有心者就费心一点点啦。

**Comment by chengtx809** [comment]
好的谢谢

**Comment by chengtx809** [comment]
更换人机验证服务器后问题已解决，感谢大佬们
