### ISSUE TITLE
[Bug] 🐛 v2.4.1登录账号仍然无法保存聊天记录

### ISSUE THREAD

**Issue by atomlong** [Harry-zklcdc/go-proxy-bingai#414]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the bug

登录账号，无法保存聊天记录

### Steps to reproduce

打开https://dc.b1ng.chat/；
登录账号(账号登录方式)；
输入聊天内容；
右侧聊天标题过一会将会消失。

### Expected behavior

登录账号，可以保存聊天记录。

### Deploy

Docker

### OS & Version

Windows 11

### Browser & Version

EDGE 版本 124.0.2478.97 (正式版本) (64 位)

### GoProxiBingAI Version

2.4.1

**Comment by Harry-zklcdc** [comment]
看来是又更新了参数了

**Comment by Harry-zklcdc** [comment]
已修复, Commit: 77a0a3b9107eb8e4ef95116aec9cc0611f3488cf
