### ISSUE TITLE
[Bug] 🐛 vercel 部署失败

### ISSUE THREAD

**Issue by wkk-dev** [Harry-zklcdc/go-proxy-bingai#417]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the bug

无限循环下载 go
Unknown Go version in /vercel/path0/go.mod

### Steps to reproduce

<html>
<body>

Warning: Unknown Go version in /vercel/path0/go.mod
--
09:07:02.802 | Downloading go: https://dl.google.com/go/go1.21.1.linux-amd64.tar.gz
09:07:11.742 | go: finding module for package github.com/vercel/go-bridge/go/bridge
09:07:11.789 | go: found github.com/vercel/go-bridge/go/bridge in github.com/vercel/go-bridge v0.0.0-20221108222652-296f4c6bdb6d
09:07:11.796 | go: finding module for package github.com/aws/aws-lambda-go/lambda
09:07:11.797 | go: finding module for package github.com/aws/aws-lambda-go/events
09:07:11.805 | go: found github.com/aws/aws-lambda-go/events in github.com/aws/aws-lambda-go v1.47.0
09:07:11.805 | go: found github.com/aws/aws-lambda-go/lambda in github.com/aws/aws-lambda-go v1.47.0
09:07:12.331 | Warning: Unknown Go version in /vercel/path0/go.mod
09:07:12.355 | Downloading go: https://dl.google.com/go/go1.21.1.linux-amd64.tar.gz
09:07:20.865 | go: finding module for package github.com/vercel/go-bridge/go/bridge
09:07:20.914 | go: found github.com/vercel/go-bridge/go/bridge in github.com/vercel/go-bridge v0.0.0-20221108222652-296f4c6bdb6d
09:07:20.923 | go: finding module for package github.com/aws/aws-lambda-go/lambda
09:07:20.925 | go: finding module for package github.com/aws/aws-lambda-go/events
09:07:20.930 | go: found github.com/aws/aws-lambda-go/events in github.com/aws/aws-lambda-go v1.47.0
09:07:20.931 | go: found github.com/aws/aws-lambda-go/lambda in github.com/aws/aws-lambda-go v1.47.0
09:07:21.480 | Build Completed in /vercel/output [2m]
09:07:21.594 | Deploying outputs...
09:07:21.601 | Error: The following Serverless Functions contain an invalid "runtime":
09:07:21.601 | - api/bypass (provided.al2)
09:07:21.601 | - api/challenge (provided.al2)
09:07:21.601 | - api/designer (provided.al2)
09:07:21.602 | - api/edgesvc (provided.al2)
09:07:21.602 | - api/index (provided.al2)
09:07:21.602 | - api/login (provided.al2)
09:07:21.602 | - api/sys-config (provided.al2)
09:07:21.602 | - api/th (provided.al2)
09:07:21.602 | - api/verify (provided.al2)
09:07:21.603 | - api/web (provided.al2). Learn More: https://vercel.com/guides/serverless-function-contains-invalid-runtime-error

</body>
</html>

### Expected behavior

无限循环下载 go
Unknown Go version in /vercel/path0/go.mod

### Screenshots

![vercel_17-5-2024_988_vercel com](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/159266689/836dd494-3109-4b7a-9fba-6e243ce69e39)

### Deploy

Vercel

### OS & Version

Windows_11 X86

### Browser & Version

Edge 124.0.2478.105 64bit

### GoProxiBingAI Version

2.0

**Comment by wkk-dev** [comment]
@Harry-zklcdc

**Comment by xiao-gy** [comment]
@wkk-dev  有尝试过教程里面更改node版本为18.x的步骤吗？没有的话可以试试

**Comment by wkk-dev** [comment]
不行啊
![Snipaste_2024-05-17_10-37-50](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/159266689/e3fba121-ee4d-4414-9f68-dcd2890ed18c)
look
https://vercel-go-proxy-bingai-4mq9w33hr-wkk-dev1s-projects.vercel.app

**Comment by wkk-dev** [comment]
oh 好了
@xiao-gy

**Comment by wkk-dev** [comment]
awa
忘记关这个issue了
