### ISSUE TITLE
[Bug] 🐛 获取邮箱验证码失败

### ISSUE THREAD

**Issue by atomlong** [Harry-zklcdc/go-proxy-bingai#418]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the bug

登录方式为"邮箱验证码登录"总是失败。

### Steps to reproduce

账号登录方式；
输入微软账户；
点击"获取邮箱验证码"；
提示"获取邮箱验证码失败，请重试"；
多次重试仍失败。

### Expected behavior

获取邮箱验证码成功。

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/3690342/092d1b20-3e4c-4a31-bb26-6d7dfe9015ed)

### Deploy

Docker

### OS & Version

Windows 11

### Browser & Version

Microsoft Edge 商业版 版本 124.0.2478.109 (正式版本) (64 位)

### GoProxiBingAI Version

v2.4.3

**Comment by xiao-gy** [comment]
@atomlong 请阅读wiki中关于邮箱登陆的条目，将收取邮箱验证码的相关设置打开

**Comment by atomlong** [comment]
> @atomlong 请阅读wiki中关于邮箱登陆的条目，将收取邮箱验证码的相关设置打开

开启了，似乎也不行。
账号这一栏输入的是备用邮箱吗？

**Comment by Harry-zklcdc** [comment]
请提供详细日志
