### ISSUE TITLE
任意提问一次, 有返回结果, 并且显示验证通过

### ISSUE THREAD

**Issue by bullkq** [Harry-zklcdc/go-proxy-bingai#42]
选择对应的服务IP
在 go-proxy-bingai 的站点上任意提问, 会提示不可用，请联系管理员
在电脑上, 用对应账号登录 'new.bing.com', 任意提问一次, 有返回结果, 并且显示验证通过
此时就可以在 go-proxy-bingai 的站点上正常提问了

1请问我的登录账号是否必须是newbing已经排队通过审核的ID。还是普通outlook账号就可以？
2是否每次登录都需要查询一次cookie 和KievRPSSecAuth的值分别进行录入和修改？我是电脑盲。求大神耐心解答。
3我试了您的方法，部署在vercel，然后在worker里那个js文件也改了，并且关联到我的CF管理的域名上，提示成功部署worker站点，我在自定义里加入worker链接。还是显示请联系管理员。
4另外，我现在无论是否翻墙，哪怕ip在国外，都无法进入www.newbing.com的美国站点，永远都是返回到cn.newbing.com,是不是就没办法申请排队了？
5我以前没用过github，这个界面没有上传图片的功能吗

我的站点信息如下：
Bing 官方	https://sydney.bing.com	不可用
Cloudflare	https://sydney.vcanbb.chat	901 ms
本站	https://bing.wbyai.top	不可用
自定义 https://wbyaitop.drwangyue.workers.dev/ 667 ms

**Comment by bullkq** [comment]
请问我从亚马逊中国官网申请一个海外的EC2 windows免费项目可以部署这个项目吗

**Comment by Sisyphean-a** [comment]
1. 现在只要是微软账户就可以进，同时bing就算审核应该也是秒过
2. 登录一次就行，把你的u_cookie复制到”设置用户就可以“
3. 请求联系管理员的话，如果你不会整，就直接删除用户就好了，重置你的bing，不要登录，也可以正常使用
4. 翻墙的问题，这里应该帮不了你，如果你用的是cfw，可以帮你看看配置，例如分组之后是否bing走的那个代理组是否是美国的，如果不是自己添加规则，这些可以上网查
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/59257340/1865bb8b-a306-4c00-b2ae-e00941a28387)
5. 图片直接粘贴上来就可以了，会自动转换成markdown语法，发出去后就会显示

**Comment by bullkq** [comment]
ubuntu@ip-172-31-38-68:~/go-proxy-bingai$ docker run -e USER_KievRPSSecAuth=FABKB......................Bof3hV1neJxAcytZASsR0u -v $PWD/go-proxy-bingai:/app/go-proxy-bingai -d -p 8080:8080 --name go-proxy-bingai --restart=always adams549659584/go-proxy-bingai
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create?name=go-proxy-bingai": dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.

我申请了一个亚马逊云，装了个ubantu系统，在命令行下面装了docker，建了一个go-proxy-bingai目录，把最新版的文件传输到了这个目录下面，然后修改这个命令行内的xxx值，运行说permission denied。这个怎么弄，我完全是it老白，对各种linux命令，docker命令完全没概念。哪位高手方便出个视频放油管里啊，拜托了。


我用的是cloudflare 的 zero trust翻墙的。

**Comment by myflavor** [comment]
> ubuntu@ip-172-31-38-68:~/go-proxy-bingai$ docker run -e USER_KievRPSSecAuth=FABKB......................Bof3hV1neJxAcytZASsR0u -v $PWD/go-proxy-bingai:/app/go-proxy-bingai -d -p 8080:8080 --name go-proxy-bingai --restart=always adams549659584/go-proxy-bingai docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create?name=go-proxy-bingai": dial unix /var/run/docker.sock: connect: permission denied. See 'docker run --help'.
> 
> 我申请了一个亚马逊云，装了个ubantu系统，在命令行下面装了docker，建了一个go-proxy-bingai目录，把最新版的文件传输到了这个目录下面，然后修改这个命令行内的xxx值，运行说permission denied。这个怎么弄，我完全是it老白，对各种linux命令，docker命令完全没概念。哪位高手方便出个视频放油管里啊，拜托了。
> 
> 我用的是cloudflare 的 zero trust翻墙的。cfw是啥

Ubuntu默认账号不是root，sudo bash一下

**Comment by bullkq** [comment]
root@ip-172-31-38-68:/home/ubuntu/go-proxy-bingai# docker ps -a
CONTAINER ID   IMAGE                            COMMAND                  CREATED          STATUS    PORTS                                       NAMES
7ea566fb594c   adams549659584/go-proxy-bingai   "/app/go-proxy-bingai"   20 minutes ago   Created   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   go-proxy-bingai
root@ip-172-31-38-68:/home/ubuntu/go-proxy-bingai# 

似乎我已经部署完容器了？接下去该怎么办，把ip地址和cloudflare 的DNS绑定吗？如何操作

**Comment by Harry-zklcdc** [comment]
我这没太懂，你把图复制了直接粘贴就可以有图了

**Comment by bullkq** [comment]
Length: 3129162 (3.0M) [application/octet-stream]
Saving to: ‘go-proxy-bingai-linux-amd64.tar.gz’

go-proxy-bingai-linux-amd64 100%[==========================================>]   2.98M  --.-KB/s    in 0.04s   

2023-07-29 08:56:23 (66.8 MB/s) - ‘go-proxy-bingai-linux-amd64.tar.gz’ saved [3129162/3129162]

root@ip-172-31-15-165:/home/ubuntu/go-proxy-bingai# vim docker-compose.yml
root@ip-172-31-15-165:/home/ubuntu/go-proxy-bingai# docker-compose up -d
**services.go-proxy-bingai must be a mapping**
root@ip-172-31-15-165:/home/ubuntu/go-proxy-bingai#

宝塔客户端的字特别小，没有办法调整吗。
我在ubuntu目录下建了go-proxy-bingai，把那个gz压缩文件放入目录但没有解压缩，并编辑了那个带xxx的yml文件。运行docker-compose up -d，显示services.go-proxy-bingai must be a mapping

此后我又解压缩了那个gz文件，继续docker-compose 还是显示services.go-proxy-bingai must be a mapping
哪里出问题了。

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/118818378/089d3df3-ed86-4fa3-9400-1ae3c9e53b74)

**Comment by bullkq** [comment]
新建的目录go-proxy-bingai应该放在home/ubuntu下面还是根目录下？还有那个反向代理的nginx。

我安装宝塔后说是也一起安装了这个image，但是我没看到这个目录，也没找到这个文件。

另外到底是该把前一个老版本1.8.7的版本文件拉过来，还是拉新版本的1.9.3，命令上如何改？被两边弄晕了

**Comment by dw3143** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/88608061/47eb8756-421e-4b58-bfac-bd7b0949cb44)
微软的日本的一个云服务器
第三个不能用，这是被ban了吗，还是没设置好

**Comment by Apretend** [comment]
请问一下，我部署了程序，目前第二个的Cloudflare https://sydney.vcanbb.chat/ 是不可用，然后我又做了个自己的服务，这个服务显示可用，结果在聊天框输入东西发送后，bing并没有任何的反应是为什么呢，并且我可以一直发送，并没有出现停止响应的按钮
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/45417872/9d1daa1d-b21c-4208-b7f9-cda34cd2e893)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/45417872/51a03cb2-46ca-488c-956f-69fa30639f16)

**Comment by Harry-zklcdc** [comment]
> 请问一下，我部署了程序，目前第二个的Cloudflare https://sydney.vcanbb.chat/ 是不可用，然后我又做了个自己的服务，这个服务显示可用，结果在聊天框输入东西发送后，bing并没有任何的反应是为什么呢，并且我可以一直发送，并没有出现停止响应的按钮 [image](https://user-images.githubusercontent.com/45417872/257139336-9d1daa1d-b21c-4208-b7f9-cda34cd2e893.png) [image](https://user-images.githubusercontent.com/45417872/257139390-51a03cb2-46ca-488c-956f-69fa30639f16.png)

你那个服务我这边可以用，用什么部署的

**Comment by bullkq** [comment]
新问题，过了几个小时再来，提示当日提问达到最大次数
刷新网页，显示要求重新连接
![6](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/118818378/6db86fc6-3464-4291-a988-e6383357b3a5)
