### ISSUE TITLE
[Help] 🤔 BingAPI调用出现英文需要验证码提示。`User needs to solve CAPTCHA to continue.`

### ISSUE THREAD

**Issue by Dx-hualuo** [Harry-zklcdc/go-proxy-bingai#420]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

询问在哪里可以完成验证验证码

### Steps to behave

使用`ChatNextWeb`调用BingAPI时返回`User needs to solve CAPTCHA to continue.`

### Expected behavior

可以使用类似`OpenAI`的方式调用此项目

### Screenshots

外网可访问图片：![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/54300227/e24c7413-3037-450f-ba04-ea0fc3f8f1d9)
国内可访问图片：![image-jqnr.png](https://home.mikufans.club:9000/mikufans-blog/image-jqnr.png)

### Deploy

Binary

### OS & Version

Windows 11 专业版 22H2 22621.3527，Windows Feature Experience Pack 1000.22700.1003.0

### Browser & Version

Microsoft Edge 版本 124.0.2478.67 (正式版本) (64 位)

### GoProxiBingAI Version

v2.4.3【release】go-proxy-bingai-linux-amd64.tar.gz

**Comment by Harry-zklcdc** [comment]
配置人机验证服务器了没？

**Comment by Dx-hualuo** [comment]
如果服务器在国外需要配置人机验证服务器吗

**Comment by ryanzhaorx** [comment]
> 如果服务器在国外需要配置人机验证服务器吗

当然需要啊

**Comment by Dx-hualuo** [comment]
谢谢帮助，已部署`go-bingai-pass`解决

**Comment by Dx-hualuo** [comment]
谢谢帮助，已部署`go-bingai-pass`解决
