### ISSUE TITLE
[Help] 🤔 在 TX 云服务器上使用 Docker 部署显示你似乎已注销

### ISSUE THREAD

**Issue by xiaoheiCat** [Harry-zklcdc/go-proxy-bingai#422]
### Confirmations

- [x] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

按照相关教程部署后在聊天时提示「很抱歉，你似乎已注销。请重新登录。」
使用右上角设置菜单登录账号或填入 Bing 的 Cookie 后也依旧如此。

### Steps to behave

1. 根据 Wiki 页面使用 Docker 完成 go-proxy-bingai 的部署，并开放 8080 端口。
2. 使用 Docker 继续部署 Nginx，并根据 Wiki 页面反向代理教程完成反向代理配置。已上传当前域名证书并配置正确。其中，反向代理目标指向 Docker 宿主机 (172.17.0.1) 的 8080 端口。开放 443 端口用于外部访问。
3. 使用 https通过外网 访问 Nginx 页面。

### Expected behavior

能正常使用 Bing AI 聊天。

### Screenshots

![屏幕截图 2024-05-25 112115](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/104667776/12b94e3b-d48f-4c98-a26b-e431e53b1f4f)

### Deploy

Docker

### OS & Version

Windows 10 22H2 19045.2006

### Browser & Version

Microsoft Edge 125.0.2535.51

### GoProxiBingAI Version

v2.4.3

### Additional context

尝试过 Docker 镜像的 nightly 版本与将反向代理目标设置为容器内部 IP 都未解决问题。
帮帮孩子吧  求求啦~
谢谢你~~

**Comment by Harry-zklcdc** [comment]
请提供你的 docker-compose.yml或者 docker 启动命令

**Comment by xiaoheiCat** [comment]
> 请提供你的 docker-compose.yml或者 docker 启动命令

docker run -d --name go-proxy-bingai -p 8808:8080 -e BYPASS_SERVER=https://bypass.b1ng.chat -e Go_Proxy_BingAI_AUTH_KEY=123456 -e APIKEY=sk-123456 zklcdc/go-proxy-bingai

**Comment by Harry-zklcdc** [comment]
你的代理呢？TX 服务器是哪个区的

**Comment by xiaoheiCat** [comment]
> 你的代理呢？TX 服务器是哪个区的

没有使用代理，服务器在硅谷区

**Comment by Harry-zklcdc** [comment]
看着是没问题的

**Comment by xiaoheiCat** [comment]
> 看着是没问题的

有没有一种可能是服务器 IP 被微软屏蔽了

**Comment by xiaoheiCat** [comment]
> > 看着是没问题的
> 
> 有没有一种可能是服务器 IP 被微软屏蔽了

破案了——和我猜想的一样，是 IP 被 ban 了，架上代理即可解决，感谢大佬帮助排查，感激不尽~
