### ISSUE TITLE
[Help] 🤔 有没有方法不让api输出消息来源

### ISSUE THREAD

**Issue by chengtx809** [Harry-zklcdc/go-proxy-bingai#426]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

api接入到lobechat，nextchat等平台时消息会输出引用来源
如[^1^]，
但是实测下来发现大多平台无法正确渲染其脚注，
或者使用场景并不需要
能不能直接关闭api输出消息来源的功能

### Steps to behave

使用lobechat调用api

### Expected behavior

不输出脚注

### Deploy

Vercel

### OS & Version

win10

### Browser & Version

edge

### GoProxiBingAI Version

最新

**Comment by chengtx809** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/103792951/07f3c732-6f44-4369-8b85-ac60de51a1b2)
补张图

**Comment by chengtx809** [comment]
这段时间的测试发现vercel部署lobechat再调本项目api就一切正常，其他平台部署的就会重复输出：（

**Comment by chengtx809** [comment]
> ~我当初还特别为这个功能做了适配~

蛤？那大佬这个功能要怎么用，谢谢！

**Comment by chengtx809** [comment]
大佬，我在你的bingapi演示站使用发现可以正常渲染脚注，我自己fork了一份你的仓库部署出来发现不行。能不能帮忙看看是什么问题，谢谢
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/103792951/dfcd656b-bba2-48c8-81c2-4fac27bedf36)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/103792951/55bb8679-855f-434d-830e-a7598e1d1caf)

**Comment by Harry-zklcdc** [comment]
有概率输出不出来

**Comment by chengtx809** [comment]
佬，能不能指下commit，我看看能不能自己改改，现在我的使用场景不太需要脚注这个功能（哭

**Comment by chengtx809** [comment]
找到了脚注是在[v1.19.8](https://github.com/Harry-zklcdc/go-proxy-bingai/releases/tag/v1.19.8)加入的，但是commit是https://github.com/Harry-zklcdc/go-proxy-bingai/commit/240a3b3207750331a40b7d298523add9ce7b83e3，貌似是个人机验证服务器bug修复的，并不是脚注相关的

**Comment by Harry-zklcdc** [comment]
https://github.com/Harry-zklcdc/bing-lib/blob/491ac86e880c911b50b8e853279f7c48026760c6/chat.go#L734-L745

**Comment by chengtx809** [comment]
跪求佬出个控制需不需要脚注的设置项，现在反而用不上脚注，哭死
