### ISSUE TITLE
[Help] 🤔 Zeabur部署后一直提示“正在尝试重新连接”，后台反复生成新的apikey

### ISSUE THREAD

**Issue by Geek66666** [Harry-zklcdc/go-proxy-bingai#430]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

昨天部署成功了，API也可以正常使用，今天早上就出现了这个情况

### Steps to behave

rt

### Expected behavior

求助

### Screenshots

这是zeabur后台的runtime log
2024/06/06 03:40:48 - ERROR - 代理异常 ：%!(EXTRA *net.OpError=read tcp 172.31.29.255:40392->204.79.197.200:443: read: connection reset by peer)
还有这个
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/61675035/ac927b39-fec7-4692-bd1e-2c94c21960b9)

### Deploy

Others

### OS & Version

Windows 10

### Browser & Version

Edge 119.0.0.0

### GoProxiBingAI Version

v1.22.1

**Comment by Geek66666** [comment]
还有这个
2024/06/06 03:50:51 - ERROR - 代理异常 ：%!(EXTRA *errors.errorString=context canceled)

**Comment by SokWith** [comment]
可能是巨硬今天又开始封 create 的 ip 了，HF上的一些部署出现create 400 ；由于发生在人机验证之前，唯有更换ip来规避。
对部署而言，可以使用环境变量 BING_BASE_URL 指向其他可用的部署地址来规避；之前的经验，AZ和CF的网络几乎不会出 create 400错误，所以尽可能的使用这两个网络来搭建www.bing.com的反代服务器充当 BING_BASE_URL
对API是否有效？ @Harry-zklcdc

**Comment by Harry-zklcdc** [comment]
> 对API是否有效？ @Harry-zklcdc

有效

**Comment by Harry-zklcdc** [comment]
Zeabur 似乎封禁了这个项目
