### ISSUE TITLE
[Help] 🤔 关于人机验证的问题

### ISSUE THREAD

**Issue by DreamofInfinity1** [Harry-zklcdc/go-proxy-bingai#431]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

在cloud flare搭建[人机验证]后，正常使用一段时间后，出现一直人机验证的状态，然后去官网访问了一下，才恢复正常，这是正常现象吗？

### Steps to behave

在cloudflare搭建完works page，绑定了自己的域名，将其作为环境变量添加进了bing的部署。 

### Expected behavior

求助，回答关于一些人机验证的问题。

### Deploy

Cloudflare Worker

### OS & Version

windows11

### Browser & Version

Chrome.125.0.6422.142

### GoProxiBingAI Version

 v2.4.3

**Comment by DreamofInfinity1** [comment]
人机验证添加之后，可正常使用，过了两三天，就会出现反复弹出人机验证，然后得打开copilot官方，弹出人机验证，验证后部署的网站才能重新使用。看wiki的文档，[人机验证]不是解决这个问题的吗？

**Comment by SokWith** [comment]
你用我的验证服务器试试，之前是有解决这个问题的。  https://cct.nbing.eu.org
许久没有使用内置账号的方式了，内置账号即使一时能够过验证，原来最多也就2周的有效期，然后就得更改内置的数据了，太麻烦了。
现在主要采用推送cookie的方式，将cookie推送到存储服务器上，再在部署应用里面拉取下来使用。存储cookie的服务器部署代码仓库在这儿：
https://github.com/SokWith/setpushcookie
有node.js，go和cf worker.js的几种部署方式，配合 https://github.com/iszhouhua/cookie-push 推送cookie的插件使用，方便自动更新cookie到存储服务器上。

**Comment by Harry-zklcdc** [comment]
> 我未采取一键登陆的形式，而是将用户cookie以环境变量的形式存在代码中部署的。

我不建议在变量中填写用户Cookie，除了用来做画图API，其他的没啥用处

而且会导致过人机验证的时候缺少对应的数据包，导致没法通过

**Comment by DreamofInfinity1** [comment]
感谢🙇‍

**Comment by DreamofInfinity1** [comment]
/(ㄒoㄒ)/~~
不好意思，打扰一下。我将所有关于cookie的变量删除了，然后网站无法访问了，之后重新部署，显示workers.api.error.deployment_not_found (Code: 100146)
![屏幕截图 2024-06-06 181711](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129919780/a22d3bf2-50f2-41ef-a2aa-6f0a27be37da)

**Comment by CreeperAWA** [comment]
> /(ㄒoㄒ)/~~ 不好意思，打扰一下。我将所有关于cookie的变量删除了，然后网站无法访问了，之后重新部署，显示workers.api.error.deployment_not_found (Code: 100146) ![屏幕截图 2024-06-06 181711](https://private-user-images.githubusercontent.com/129919780/337223848-a22d3bf2-50f2-41ef-a2aa-6f0a27be37da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NTIzOTYsIm5iZiI6MTcyMzY1MjA5NiwicGF0aCI6Ii8xMjk5MTk3ODAvMzM3MjIzODQ4LWEyMmQzYmYyLTUwZjItNDFlZi1hMmFhLTZmMGEyN2JlMzdkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQxNjE0NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjRmMjBlOTc0Y2I4ZWMxZjg1YjE4MTI4MmFlMjgzNGUyMTdmYzBmZDFiMmY3Zjc2N2M4MGY3ZjRmY2M3NDI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Pqn25KUhApgUI6ZlY12G8OPuaFDWgCEmVp7yn_jyaXU)

这是没有部署成功吧，报错的意思是找不到worker
