### ISSUE TITLE
[Help] 🤔 关于环境变量cookie的一些疑问

### ISSUE THREAD

**Issue by chengtx809** [Harry-zklcdc/go-proxy-bingai#432]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

大佬，请教下如果我想要多cookie填入环境变量做画图api，
是只需要设置多个Go_Proxy_BingAI_USER_TOKEN吗？
那么剩下的三个值要怎么填写，wiki我读过后还不是很理解，谢谢！
另外，能否支持填写完整cookie到环境变量？

### Steps to behave

填入cookie

### Expected behavior

正常聊天

### Deploy

HuggingFace

### OS & Version

win10

### Browser & Version

edge

### GoProxiBingAI Version

最新

**Comment by chengtx809** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/103792951/02bb64dc-7106-4289-b190-ede129c7ea80)
我填写完后打开网页，右侧闪了一下聊天记录又不见了，然后发现没登陆上
但是闪出来的聊天记录又是我账号里的
部署方式为cf page

**Comment by Harry-zklcdc** [comment]
对，环境变量登录账号的话前端会屏蔽聊天记录，这个我特别设计的

**Comment by chengtx809** [comment]
好的谢谢
