### ISSUE TITLE
[Bug] 🐛 一键登录打开登录页面显示 error 1103

### ISSUE THREAD

**Issue by leioukupo** [Harry-zklcdc/go-proxy-bingai#434]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the bug

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/60430874/aa04aa6f-e276-4d09-b635-33a6409e8305)
使用账号登录一键登录，error 1103

### Steps to reproduce

登录
一键登录
出现error 1103

### Expected behavior

无法自动获取cookie

### Deploy

Cloudflare Worker

### OS & Version

win10

### Browser & Version

edge  125.0.2535.92 

### GoProxiBingAI Version

最新

**Comment by Harry-zklcdc** [comment]
![a11fac5f75bcdc095f14e6395f45ecc2](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/2bb21dc7-27d1-4e88-8c30-5ed6fa273963)

演示站没有问题，请提供详细操作或者相关日志

**Comment by coolair01** [comment]
一键登录一直提示：获取 Cookie 时间过长, 请检查油猴插件及脚本是否安装正确
