### ISSUE TITLE
如何解决522错误

### ISSUE THREAD

**Issue by Miolaloro** [Harry-zklcdc/go-proxy-bingai#435]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

使用自定义域名访问，报错522，求助如何解决！

### Steps to behave

1.本体是在 Cloudflare Workers 搭建的
2.人机验证服务器：https://bypass.b1ng.chat
3.搭建教程：https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/Cloudflare-Worker-%E9%83%A8%E7%BD%B2
4.域名是在cloudflare买的.com的二级域名

### Expected behavior

正常访问

### Screenshots

<img width="829" alt="PixPin_2024-06-11_09-29-22" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/104066375/2f76bd88-9a0f-49f7-b7fd-c27573da8c05">

### Deploy

Cloudflare Worker

### OS & Version

Windows11

### Browser & Version

edge 125.0.2535.92

### GoProxiBingAI Version

2.4.3

**Comment by 751317151** [comment]
我也遇到了同样的问题

**Comment by Harry-zklcdc** [comment]
我感觉可能是Cloudflare的bug

**Comment by 751317151** [comment]
> > 我刚刚新建了一个默认的输出 helloworld的worker，可以在网页上访问，然后把教程的js代码复制到helloworld的worker里，helloworld的页面可以正常显示教程的项目了，然后一开始新建的教程项目竟然也能正常访问了，不知道什么原理
> 
> 为什么我按你这个来，直接把教材的js代码复制到新worker里面会出现这个报错，是少了什么模块吗？ Uncaught Error: No such module "bingapi.js". imported from "worker.js" (Code: 10021)
新worker里还要新建个bingapi.js文件，教程项目里有这个文件

**Comment by 751317151** [comment]
> > 我刚刚新建了一个默认的输出 helloworld的worker，可以在网页上访问，然后把教程的js代码复制到helloworld的worker里，helloworld的页面可以正常显示教程的项目了，然后一开始新建的教程项目竟然也能正常访问了，不知道什么原理
> 
> 为什么我按你这个来，直接把教材的js代码复制到新worker里面会出现这个报错，是少了什么模块吗？ Uncaught Error: No such module "bingapi.js". imported from "worker.js" (Code: 10021)

新worker里还要新建个bingapi.js文件，教程项目里有这个文件

**Comment by LQZ100** [comment]
> > > 我刚刚新建了一个默认的输出 helloworld的worker，可以在网页上访问，然后把教程的js代码复制到helloworld的worker里，helloworld的页面可以正常显示教程的项目了，然后一开始新建的教程项目竟然也能正常访问了，不知道什么原理
> > 
> > 
> > 为什么我按你这个来，直接把教材的js代码复制到新worker里面会出现这个报错，是少了什么模块吗？ Uncaught Error: No such module "bingapi.js". imported from "worker.js" (Code: 10021)
> 
> 新worker里还要新建个bingapi.js文件，教程项目里有这个文件

没见到啊，教程里面的不是一键部署吗，你是指哪个教程呀，worker的那个教程吗

**Comment by 751317151** [comment]
> > > > 我刚刚新建了一个默认的输出 helloworld的worker，可以在网页上访问，然后把教程的js代码复制到helloworld的worker里，helloworld的页面可以正常显示教程的项目了，然后一开始新建的教程项目竟然也能正常访问了，不知道什么原理
> > > 
> > > 
> > > 为什么我按你这个来，直接把教材的js代码复制到新worker里面会出现这个报错，是少了什么模块吗？ Uncaught Error: No such module "bingapi.js". imported from "worker.js" (Code: 10021)
> > 
> > 
> > 新worker里还要新建个bingapi.js文件，教程项目里有这个文件
> 
> 没见到啊，教程里面的不是一键部署吗，你是指哪个教程呀，worker的那个教程吗

就是你一开始按教程搭建的cloudflare worker里，编辑代码，里面有这个文件，在worker项目里增加这个文件

**Comment by LQZ100** [comment]
> > > > > 我刚刚新建了一个默认的输出 helloworld的worker，可以在网页上访问，然后把教程的js代码复制到helloworld的worker里，helloworld的页面可以正常显示教程的项目了，然后一开始新建的教程项目竟然也能正常访问了，不知道什么原理
> > > > 
> > > > 
> > > > 为什么我按你这个来，直接把教材的js代码复制到新worker里面会出现这个报错，是少了什么模块吗？ Uncaught Error: No such module "bingapi.js". imported from "worker.js" (Code: 10021)
> > > 
> > > 
> > > 新worker里还要新建个bingapi.js文件，教程项目里有这个文件
> > 
> > 
> > 没见到啊，教程里面的不是一键部署吗，你是指哪个教程呀，worker的那个教程吗
> 
> 就是你一开始按教程搭建的cloudflare worker里，编辑代码，里面有这个文件，在worker项目里增加这个文件

好的，我明白了。我已经用pages搭建好了，worker我觉得应该是有bug的，不知道问题出在哪

**Comment by Harry-zklcdc** [comment]
worker 应该是被 cf 拦截了，不让部署，我后面看看怎么修

**Comment by LQZ100** [comment]
> worker 应该是被 cf 拦截了，不让部署，我后面看看怎么修

有可能，js文件应该是没问题的，用pages搭建就没出现522的问题

**Comment by 751317151** [comment]
> worker 应该是被 cf 拦截了，不让部署，我后面看看怎么修

我用原本的worker脚本，本站的聊天服务器不可用，我把脚本里baseUrl的`Harry-zklcdc` 改成我自己的github用户名就能用了，这也不知道为什么

**Comment by Harry-zklcdc** [comment]
#440

**Comment by Harry-zklcdc** [comment]
已修复
