### ISSUE TITLE
[Bug] 🐛 使用worker部署，授权码的功能有问题

### ISSUE THREAD

**Issue by jiojiojackson** [Harry-zklcdc/go-proxy-bingai#443]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the bug

使用worker部署，授权码的功能有问题，输入正确的授权码，也会报授权码错。确切关掉这个授权页面，就可以正常使用了。相当于授权这个功能无效.

### Steps to reproduce

使用worker部署

### Expected behavior

修复

### Deploy

Cloudflare Worker

### OS & Version

win11

### Browser & Version

chrome

### GoProxiBingAI Version

v2.4.3

**Comment by Harry-zklcdc** [comment]
有看看

**Comment by DreamofInfinity1** [comment]
我也遇到了 是dev的最新版本

**Comment by lm379** [comment]
我用pages部署，直接把那个提示叉掉就能用了，相当于这个功能是个摆设

**Comment by Harry-zklcdc** [comment]
> 我用pages部署，直接把那个提示叉掉就能用了，相当于这个功能是个摆设

直接关能关掉？

**Comment by lm379** [comment]
> > 我用pages部署，直接把那个提示叉掉就能用了，相当于这个功能是个摆设
> 
> 直接关能关掉？

对，是不是因为我在环境变量里添加了cookie？然后程序认为我已经登录了账号，就可以关掉提示了？

**Comment by DreamofInfinity1** [comment]
和那个没关系吧，我以前部署的时候就发现设置授权码后，到页面可以直接×掉授权码提示框可以直接使用

**Comment by Harry-zklcdc** [comment]
已修复
