### ISSUE TITLE
[Bug] 🐛 人机验证过不去

### ISSUE THREAD

**Issue by Wodksk** [Harry-zklcdc/go-proxy-bingai#444]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the bug

人机验证在多次重试后过不去

### Steps to reproduce

发送消息验证

### Expected behavior

修复

### Deploy

Cloudflare Worker

### OS & Version

win10

### Browser & Version

chrom

### GoProxiBingAI Version

2.4.3

**Comment by Harry-zklcdc** [comment]
循环验证的话，就一键重置
