### ISSUE TITLE
[Bug] 🐛  400 Bad Request：很抱歉，你似乎已注销。 请重新登录。

### ISSUE THREAD

**Issue by PIKACHUIM** [Harry-zklcdc/go-proxy-bingai#445]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the bug

使用二进制部署，提示：很抱歉，你似乎已注销。 请重新登录。

### Steps to reproduce

请求方法:
GET
状态代码:
400 Bad Request
远程地址:
*****************:443
引用站点策略:
origin-when-cross-origin
请求地址:
`https://*****************/fd/ls/l?IG=*****************&TYPE=Event.ClientInst&DATA=%5B%7B%22Namespace%22%3A%22Conversation%22%2C%22CustomData%22%3A%22%7B%5C%22errorMessage%5C%22%3A%5C%22CreateConversationUnauthorizedError%20User%20is%20unauthorized%20to%20access%20chat%5C%22%2C%5C%22errorDetails%5C%22%3A%5C%22CreateConversationUnauthorizedError%20-%20User%20is%20unauthorized%20to%20access%20chat%5C%22%2C%5C%22request%5C%22%3A%5C%22%7B%5C%5C%5C%22source%5C%5C%5C%22%3A%5C%5C%5C%22cib%5C%5C%5C%22%2C%5C%5C%5C%22optionsSets%5C%5C%5C%22%3A%5B%5C%5C%5C%22nlu_direct_response_filter%5C%5C%5C%22%2C%5C%5C%5C%22deepleo%5C%5C%5C%22%2C%5C%5C%5C%22disable_emoji_spoken_text%5C%5C%5C%22%2C%5C%5C%5C%22responsible_ai_policy_235%5C%5C%5C%22%2C%5C%5C%5C%22enablemm%5C%5C%5C%22%2C%5C%5C%5C%22dv3sugg%5C%5C%5C%22%2C%5C%5C%5C%22autosave%5C%5C%5C%22%2C%5C%5C%5C%22iyxapbing%5C%5C%5C%22%2C%5C%5C%5C%22iycapbing%5C%5C%5C%22%2C%5C%5C%5C%22enable_user_consent%5C%5C%5C%22%2C%5C%5C%5C%22fluxmemcst%5C%5C%5C%22%2C%5C%5C%5C%22galileo%5C%5C%5C%22%2C%5C%5C%5C%22saharagenconv5%5C%5C%5C%22%2C%5C%5C%5C%22bflxvoice%5C%5C%5C%22%2C%5C%5C%5C%22enstmdf%5C%5C%5C%22%2C%5C%5C%5C%22rcaldictans%5C%5C%5C%22%2C%5C%5C%5C%22gndlogcf%5C%5C%5C%22%2C%5C%5C%5C%22sapsgrd%5C%5C%5C%22%2C%5C%5C%5C%22localreducehho%5C%5C%5C%22%2C%5C%5C%5C%22paydetec%5C%5C%5C%22%2C%5C%5C%5C%22gptv1desc3%5C%5C%5C%22%2C%5C%5C%5C%22gptvmv3%5C%5C%5C%22%2C%5C%5C%5C%22gptvnocon%5C%5C%5C%22%2C%5C%5C%5C%22eredirecturl%5C%5C%5C%22%2C%5C%5C%5C%22ldsummary%5C%5C%5C%22%2C%5C%5C%5C%22ldqa%5C%5C%5C%22%2C%5C%5C%5C%22sdretrieval%5C%5C%5C%22%2C%5C%5C%5C%22dlgpt4t%5C%5C%5C%22%2C%5C%5C%5C%22dlbmtc%5C%5C%5C%22%2C%5C%5C%5C%22dlbpc4575%5C%5C%5C%22%2C%5C%5C%5C%22dlbrngnp%5C%5C%5C%22%2C%5C%5C%5C%22dlbtc%5C%5C%5C%22%2C%5C%5C%5C%22dlbuc07%5C%5C%5C%22%2C%5C%5C%5C%22dlbuf03%5C%5C%5C%22%5D%2C%5C%5C%5C%22allowedMessageTypes%5C%5C%5C%22%3A%5B%5C%5C%5C%22ActionRequest%5C%5C%5C%22%2C%5C%5C%5C%22Chat%5C%5C%5C%22%2C%5C%5C%5C%22ConfirmationCard%5C%5C%5C%22%2C%5C%5C%5C%22Context%5C%5C%5C%22%2C%5C%5C%5C%22InternalSearchQuery%5C%5C%5C%22%2C%5C%5C%5C%22InternalSearchResult%5C%5C%5C%22%2C%5C%5C%5C%22Disengaged%5C%5C%5C%22%2C%5C%5C%5C%22InternalLoaderMessage%5C%5C%5C%22%2C%5C%5C%5C%22Progress%5C%5C%5C%22%2C%5C%5C%5C%22RenderCardRequest%5C%5C%5C%22%2C%5C%5C%5C%22RenderContentRequest%5C%5C%5C%22%2C%5C%5C%5C%22AdsQuery%5C%5C%5C%22%2C%5C%5C%5C%22SemanticSerp%5C%5C%5C%22%2C%5C%5C%5C%22GenerateContentQuery%5C%5C%5C%22%2C%5C%5C%5C%22SearchQuery%5C%5C%5C%22%2C%5C%5C%5C%22GeneratedCode%5C%5C%5C%22%2C%5C%5C%5C%22InternalTasksMessage%5C%5C%5C%22%2C%5C%5C%5C%22Disclaimer%5C%5C%5C%22%5D%2C%5C%5C%5C%22sliceIds%5C%5C%5C%22%3A%5B%5C%5C%5C%22orcacrtrnewcf%5C%5C%5C%22%2C%5C%5C%5C%22codecrtv2cf%5C%5C%5C%22%2C%5C%5C%5C%22tcrtrv3%5C%5C%5C%22%2C%5C%5C%5C%22voicedup2%5C%5C%5C%22%2C%5C%5C%5C%22enziknavc%5C%5C%5C%22%2C%5C%5C%5C%22translnochr%5C%5C%5C%22%2C%5C%5C%5C%22dynhtrr%5C%5C%5C%22%2C%5C%5C%5C%22caccaconsccf%5C%5C%5C%22%2C%5C%5C%5C%22415dicts0%5C%5C%5C%22%2C%5C%5C%5C%220411dylbs0%5C%5C%5C%22%2C%5C%5C%5C%220306flows0%5C%5C%5C%22%2C%5C%5C%5C%22kcgmm2cf%5C%5C%5C%22%2C%5C%5C%5C%22sapsgrd%5C%5C%5C%22%2C%5C%5C%5C%220404redhoo%5C%5C%5C%22%2C%5C%5C%5C%22418paydetec%5C%5C%5C%22%2C%5C%5C%5C%220325phones0%5C%5C%5C%22%2C%5C%5C%5C%22reduceretrycf%5C%5C%5C%22%2C%5C%5C%5C%223daytone%5C%5C%5C%22%2C%5C%5C%5C%22exptone%5C%5C%5C%22%2C%5C%5C%5C%22sstoprevcf%5C%5C%5C%22%5D%2C%5C%5C%5C%22verbosity%5C%5C%5C%22%3A%5C%5C%5C%22verbose%5C%5C%5C%22%2C%5C%5C%5C%22scenario%5C%5C%5C%22%3A%5C%5C%5C%22SERP%5C%5C%5C%22%2C%5C%5C%5C%22plugins%5C%5C%5C%22%3A%5B%7B%5C%5C%5C%22id%5C%5C%5C%22%3A%5C%5C%5C%22c310c353-b9f0-4d76-ab0d-1dd5e979cf68%5C%5C%5C%22%2C%5C%5C%5C%22category%5C%5C%5C%22%3A1%7D%5D%2C%5C%5C%5C%22traceId%5C%5C%5C%22%3A%5C%5C%5C%22ed7887ea2b2949da919a081396989852%5C%5C%5C%22%2C%5C%5C%5C%22conversationHistoryOptionsSets%5C%5C%5C%22%3A%5B%5C%5C%5C%22autosave%5C%5C%5C%22%2C%5C%5C%5C%22savemem%5C%5C%5C%22%2C%5C%5C%5C%22uprofupd%5C%5C%5C%22%2C%5C%5C%5C%22uprofgen%5C%5C%5C%22%5D%2C%5C%5C%5C%22gptId%5C%5C%5C%22%3A%5C%5C%5C%22copilot%5C%5C%5C%22%2C%5C%5C%5C%22isStartOfSession%5C%5C%5C%22%3Atrue%2C%5C%5C%5C%22requestId%5C%5C%5C%22%3A%5C%5C%5C%22f67abdc1-9d7a-ad5d-54a1-d18ddb937c09%5C%5C%5C%22%2C%5C%5C%5C%22message%5C%5C%5C%22%3A%7B%5C%5C%5C%22locale%5C%5C%5C%22%3A%5C%5C%5C%22zh-CN%5C%5C%5C%22%2C%5C%5C%5C%22market%5C%5C%5C%22%3A%5C%5C%5C%22zh-CN%5C%5C%5C%22%2C%5C%5C%5C%22region%5C%5C%5C%22%3A%5C%5C%5C%22CN%5C%5C%5C%22%2C%5C%5C%5C%22location%5C%5C%5C%22%3A%5C%5C%5C%22lat%3A47.639557%3Blong%3A-122.128159%3Bre%3D1000m%3B%5C%5C%5C%22%2C%5C%5C%5C%22locationHints%5C%5C%5C%22%3A%5B%7B%5C%5C%5C%22country%5C%5C%5C%22%3A%5C%5C%5C%22United%20States%5C%5C%5C%22%2C%5C%5C%5C%22state%5C%5C%5C%22%3A%5C%5C%5C%22California%5C%5C%5C%22%2C%5C%5C%5C%22city%5C%5C%5C%22%3A%5C%5C%5C%22Los%20Angeles%5C%5C%5C%22%2C%5C%5C%5C%22zipcode%5C%5C%5C%22%3A%5C%5C%5C%2298161%5C%5C%5C%22%2C%5C%5C%5C%22timezoneoffset%5C%5C%5C%22%3A8%2C%5C%5C%5C%22dma%5C%5C%5C%22%3A819%2C%5C%5C%5C%22countryConfidence%5C%5C%5C%22%3A8%2C%5C%5C%5C%22cityConfidence%5C%5C%5C%22%3A5%2C%5C%5C%5C%22Center%5C%5C%5C%22%3A%7B%5C%5C%5C%22Latitude%5C%5C%5C%22%3A78.4156%2C%5C%5C%5C%22Longitude%5C%5C%5C%22%3A-101.4458%7D%2C%5C%5C%5C%22RegionType%5C%5C%5C%22%3A2%2C%5C%5C%5C%22SourceType%5C%5C%5C%22%3A1%7D%5D%2C%5C%5C%5C%22userIpAddress%5C%5C%5C%22%3A%5C%5C%5C%2213.78.237.126%5C%5C%5C%22%2C%5C%5C%5C%22timestamp%5C%5C%5C%22%3A%5C%5C%5C%222024-06-20T11%3A06%3A32%2B08%3A00%5C%5C%5C%22%2C%5C%5C%5C%22adaptiveCards%5C%5C%5C%22%3A%5B%5D%2C%5C%5C%5C%22author%5C%5C%5C%22%3A%5C%5C%5C%22user%5C%5C%5C%22%2C%5C%5C%5C%22inputMethod%5C%5C%5C%22%3A%5C%5C%5C%22Keyboard%5C%5C%5C%22%2C%5C%5C%5C%22text%5C%5C%5C%22%3A%5C%5C%5C%22%E5%88%86%E4%BA%AB%E4%B8%80%E4%BA%9B%E5%85%B3%E4%BA%8E%E6%B5%B7%E6%B4%8B%E6%BD%AE%E6%B1%90%E7%9A%84%E6%9C%89%E8%B6%A3%E4%BA%8B%E5%AE%9E%5C%5C%5C%22%2C%5C%5C%5C%22messageType%5C%5C%5C%22%3A%5C%5C%5C%22Chat%5C%5C%5C%22%2C%5C%5C%5C%22requestId%5C%5C%5C%22%3A%5C%5C%5C%22f67abdc1-9d7a-ad5d-54a1-d18ddb937c09%5C%5C%5C%22%2C%5C%5C%5C%22messageId%5C%5C%5C%22%3A%5C%5C%5C%22f67abdc1-9d7a-ad5d-54a1-d18ddb937c09%5C%5C%5C%22%7D%2C%5C%5C%5C%22tone%5C%5C%5C%22%3A%5C%5C%5C%22Balanced%5C%5C%5C%22%2C%5C%5C%5C%22extraExtensionParameters%5C%5C%5C%22%3A%7B%5C%5C%5C%22gpt-creator-persona%5C%5C%5C%22%3A%7B%5C%5C%5C%22personaId%5C%5C%5C%22%3A%5C%5C%5C%22copilot%5C%5C%5C%22%7D%7D%2C%5C%5C%5C%22spokenTextMode%5C%5C%5C%22%3A%5C%5C%5C%22None%5C%5C%5C%22%2C%5C%5C%5C%22conversationId%5C%5C%5C%22%3Anull%7D%5C%22%2C%5C%22requestId%5C%22%3A%5C%22f67abdc1-9d7a-ad5d-54a1-d18ddb937c09%5C%22%2C%5C%22traceId%5C%22%3A%5C%22ed7887ea2b2949da919a081396989852%5C%22%2C%5C%22convId%5C%22%3Anull%2C%5C%22optionSet%5C%22%3A%5C%22%5Bnlu_direct_response_filter%2Cdeepleo%2Cdisable_emoji_spoken_text%2Cresponsible_ai_policy_235%2Cenablemm%2Cdv3sugg%2Cautosave%2Ciyxapbing%2Ciycapbing%2Cenable_user_consent%2Cfluxmemcst%2Cgalileo%2Csaharagenconv5%2Cbflxvoice%2Censtmdf%2Crcaldictans%2Cgndlogcf%2Csapsgrd%2Clocalreducehho%2Cpaydetec%2Cgptv1desc3%2Cgptvmv3%2Cgptvnocon%2Ceredirecturl%2Cldsummary%2Cldqa%2Csdretrieval%2Cdlgpt4t%2Cdlbmtc%2Cdlbpc4575%2Cdlbrngnp%2Cdlbtc%2Cdlbuc07%2Cdlbuf03%5D%5C%22%2C%5C%22callStack%5C%22%3A%5C%22CreateConversationUnauthorizedError%3A%20User%20is%20unauthorized%20to%20access%20chat%5C%5Cn%20%20%20%20at%20getRetryModifiers%20(https%3A%2F%2Fbingai-sg1.opkg.cn%2Frp%2FV6IKxmcE5rJ2bGlG-v3sIvR-550.br.js%3A2%3A1711776)%5C%5Cn%20%20%20%20at%20Object.retryStrategy%20(https%3A%2F%2Fbingai-sg1.opkg.cn%2Frp%2FV6IKxmcE5rJ2bGlG-v3sIvR-550.br.js%3A2%3A1712339)%5C%5Cn%20%20%20%20at%20HttpRetryPolicy.sendRequest%20(https%3A%2F%2Fbingai-sg1.opkg.cn%2Frp%2FV6IKxmcE5rJ2bGlG-v3sIvR-550.br.js%3A2%3A1713835)%5C%5Cn%20%20%20%20at%20async%20Object.sendRequest%20(https%3A%2F%2Fbingai-sg1.opkg.cn%2Frp%2FV6IKxmcE5rJ2bGlG-v3sIvR-550.br.js%3A2%3A1691293)%5C%5Cn%20%20%20%20at%20async%20Object.sendRequest%20(https%3A%2F%2Fbingai-sg1.opkg.cn%2Frp%2FV6IKxmcE5rJ2bGlG-v3sIvR-550.br.js%3A2%3A1731409)%5C%5Cn%20%20%20%20at%20async%20BingAPI.sendOperationRequest%20(https%3A%2F%2Fbingai-sg1.opkg.cn%2Frp%2FV6IKxmcE5rJ2bGlG-v3sIvR-550.br.js%3A2%3A1742545)%5C%5Cn%20%20%20%20at%20async%20kg.callCreateConversationAsync%20(https%3A%2F%2Fbingai-sg1.opkg.cn%2Frp%2FV6IKxmcE5rJ2bGlG-v3sIvR-550.br.js%3A2%3A2724411)%5C%5Cn%20%20%20%20at%20async%20kg.tryUpdateTokenDetailAsync%20(https%3A%2F%2Fbingai-sg1.opkg.cn%2Frp%2FV6IKxmcE5rJ2bGlG-v3sIvR-550.br.js%3A2%3A2723006)%5C%5Cn%20%20%20%20at%20async%20kg.getEncryptedTokenAsync%20(https%3A%2F%2Fbingai-sg1.opkg.cn%2Frp%2FV6IKxmcE5rJ2bGlG-v3sIvR-550.br.js%3A2%3A2721604)%5C%5Cn%20%20%20%20at%20async%20qm.startConnectionAsync%20(https%3A%2F%2Fbingai-sg1.opkg.cn%2Frp%2FV6IKxmcE5rJ2bGlG-v3sIvR-550.br.js%3A2%3A2648786)%5C%22%2C%5C%22fullStack%5C%22%3A%5C%22CreateConversationUnauthorizedError%3A%20User%20is%20unauthorized%20to%20access%20chat%5C%5Cn%20%20%20%20at%20getRetryModifiers%20(https%3A%2F%2Fbingai-sg1.opkg.cn%2Frp%2FV6IKxmcE5rJ2bGlG-v3sIvR-550.br.js%3A2%3A1711776)%5C%5Cn%20%20%20%20at%20Object.retryStrategy%20(https%3A%2F%2Fbingai-sg1.opkg.cn%2Frp%2FV6IKxmcE5rJ2bGlG-v3sIvR-550.br.js%3A2%3A1712339)%5C%5Cn%20%20%20%20at%20HttpRetryPolicy.sendRequest%20(https%3A%2F%2Fbingai-sg1.opkg.cn%2Frp%2FV6IKxmcE5rJ2bGlG-v3sIvR-550.br.js%3A2%3A1713835)%5C%5Cn%20%20%20%20at%20async%20Object.sendRequest%20(https%3A%2F%2Fbingai-sg1.opkg.cn%2Frp%2FV6IKxmcE5rJ2bGlG-v3sIvR-550.br.js%3A2%3A1691293)%5C%5Cn%20%20%20%20at%20async%20Object.sendRequest%20(https%3A%2F%2Fbingai-sg1.opkg.cn%2Frp%2FV6IKxmcE5rJ2bGlG-v3sIvR-550.br.js%3A2%3A1731409)%5C%5Cn%20%20%20%20at%20async%20BingAPI.sendOperationRequest%20(https%3A%2F%2Fbingai-sg1.opkg.cn%2Frp%2FV6IKxmcE5rJ2bGlG-v3sIvR-550.br.js%3A2%3A1742545)%5C%5Cn%20%20%20%20at%20async%20kg.callCreateConversationAsync%20(https%3A%2F%2Fbingai-sg1.opkg.cn%2Frp%2FV6IKxmcE5rJ2bGlG-v3sIvR-550.br.js%3A2%3A2724411)%5C%5Cn%20%20%20%20at%20async%20kg.tryUpdateTokenDetailAsync%20(https%3A%2F%2Fbingai-sg1.opkg.cn%2Frp%2FV6IKxmcE5rJ2bGlG-v3sIvR-550.br.js%3A2%3A2723006)%5C%5Cn%20%20%20%20at%20async%20kg.getEncryptedTokenAsync%20(https%3A%2F%2Fbingai-sg1.opkg.cn%2Frp%2FV6IKxmcE5rJ2bGlG-v3sIvR-550.br.js%3A2%3A2721604)%5C%5Cn%20%20%20%20at%20async%20qm.startConnectionAsync%20(https%3A%2F%2Fbingai-sg1.opkg.cn%2Frp%2FV6IKxmcE5rJ2bGlG-v3sIvR-550.br.js%3A2%3A2648786)%5C%22%2C%5C%22messageObject%5C%22%3A%5C%22%7B%5C%5C%5C%22locale%5C%5C%5C%22%3A%5C%5C%5C%22zh-CN%5C%5C%5C%22%2C%5C%5C%5C%22market%5C%5C%5C%22%3A%5C%5C%5C%22zh-CN%5C%5C%5C%22%2C%5C%5C%5C%22region%5C%5C%5C%22%3A%5C%5C%5C%22CN%5C%5C%5C%22%2C%5C%5C%5C%22location%5C%5C%5C%22%3A%5C%5C%5C%22lat%3A47.639557%3Blong%3A-122.128159%3Bre%3D1000m%3B%5C%5C%5C%22%2C%5C%5C%5C%22locationHints%5C%5C%5C%22%3A%5B%7B%5C%5C%5C%22country%5C%5C%5C%22%3A%5C%5C%5C%22United%20States%5C%5C%5C%22%2C%5C%5C%5C%22state%5C%5C%5C%22%3A%5C%5C%5C%22California%5C%5C%5C%22%2C%5C%5C%5C%22city%5C%5C%5C%22%3A%5C%5C%5C%22Los%20Angeles%5C%5C%5C%22%2C%5C%5C%5C%22zipcode%5C%5C%5C%22%3A%5C%5C%5C%2298161%5C%5C%5C%22%2C%5C%5C%5C%22timezoneoffset%5C%5C%5C%22%3A8%2C%5C%5C%5C%22dma%5C%5C%5C%22%3A819%2C%5C%5C%5C%22countryConfidence%5C%5C%5C%22%3A8%2C%5C%5C%5C%22cityConfidence%5C%5C%5C%22%3A5%2C%5C%5C%5C%22Center%5C%5C%5C%22%3A%7B%5C%5C%5C%22Latitude%5C%5C%5C%22%3A78.4156%2C%5C%5C%5C%22Longitude%5C%5C%5C%22%3A-101.4458%7D%2C%5C%5C%5C%22RegionType%5C%5C%5C%22%3A2%2C%5C%5C%5C%22SourceType%5C%5C%5C%22%3A1%7D%5D%2C%5C%5C%5C%22userIpAddress%5C%5C%5C%22%3A%5C%5C%5C%2213.78.237.126%5C%5C%5C%22%2C%5C%5C%5C%22timestamp%5C%5C%5C%22%3A%5C%5C%5C%222024-06-20T11%3A06%3A32%2B08%3A00%5C%5C%5C%22%2C%5C%5C%5C%22adaptiveCards%5C%5C%5C%22%3A%5B%5D%2C%5C%5C%5C%22author%5C%5C%5C%22%3A%5C%5C%5C%22user%5C%5C%5C%22%2C%5C%5C%5C%22inputMethod%5C%5C%5C%22%3A%5C%5C%5C%22Keyboard%5C%5C%5C%22%2C%5C%5C%5C%22text%5C%5C%5C%22%3A%5C%5C%5C%22%E5%88%86%E4%BA%AB%E4%B8%80%E4%BA%9B%E5%85%B3%E4%BA%8E%E6%B5%B7%E6%B4%8B%E6%BD%AE%E6%B1%90%E7%9A%84%E6%9C%89%E8%B6%A3%E4%BA%8B%E5%AE%9E%5C%5C%5C%22%2C%5C%5C%5C%22messageType%5C%5C%5C%22%3A%5C%5C%5C%22Chat%5C%5C%5C%22%2C%5C%5C%5C%22requestId%5C%5C%5C%22%3A%5C%5C%5C%22f67abdc1-9d7a-ad5d-54a1-d18ddb937c09%5C%5C%5C%22%2C%5C%5C%5C%22messageId%5C%5C%5C%22%3A%5C%5C%5C%22f67abdc1-9d7a-ad5d-54a1-d18ddb937c09%5C%5C%5C%22%7D%5C%22%2C%5C%22requestbody%5C%22%3A%5C%22%5C%22%2C%5C%22retryCount%5C%22%3A%5C%220%5C%22%2C%5C%22maxRetryExceeded%5C%22%3A%5C%22%5C%22%7D%22%2C%22T%22%3A%22CI.Error%22%2C%22TS%22%3A1718852796213%2C%22Name%22%3A%22InternetErrorEvent%22%2C%22FID%22%3A%22Codex%22%7D%5D`

### Expected behavior

无

### Screenshots

Bad Request
Your browser sent a request that this server could not understand.
Reference #7.3fdb387d.1718853285.14847cdf

https://errors.edgesuite.net/7.3fdb387d.1718853285.14847cdf

### Deploy

Binary

### UserId

无

### OS & Version

Ubuntu 22.04

### Browser & Version

Microsoft Edge 版本 124.0.2478.105 (正式版本) (64 位)

### GoProxiBingAI Version

v2.4.3

**Comment by Harry-zklcdc** [comment]
在什么情况，什么状态，有这个报错

**Comment by PIKACHUIM** [comment]
感谢大佬回复，通过二进制部署的，随意输入内容，提示：`很抱歉，你似乎已注销。 请重新登录。`
F12打开`https://*********/fd/ls/l`发现是上面的这个问题：400 Bad Request

**Comment by PIKACHUIM** [comment]
# Bad Request
Your browser sent a request that this server could not understand.
Reference #7.3fdb387d.1718856755.165a6178

https://errors.edgesuite.net/7.3fdb387d.1718856755.165a6178

**Comment by PIKACHUIM** [comment]
如果点击登录的话：

**Comment by PIKACHUIM** [comment]
通过右上角设置可以正常登录，但是登录之后还是`很抱歉，你似乎已注销。 请重新登录。`

**Comment by Harry-zklcdc** [comment]
那个报错是正常的，官网也有这个报错

我感觉是你的服务器IP被巨硬ban了

**Comment by SokWith** [comment]
> 那个报错是正常的，官网也有这个报错
> 
> 我感觉是你的服务器IP被巨硬ban了

![hf-banip](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/f70acc3b-0de2-4069-b6e9-e383ce7d89e8)

## huggingface的网络环境，即使专门的去验证，过了也不生成cct,USRLOC一大串值：
![typecatchall](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/2205e59c-2876-45c7-86f5-c271b17a163c)
``
SRCHD=AF=NOFORM; SRCHUID=V=2&GUID=6F8E5CE7647B42F6A0AE5FD17898A43A&dmnchg=1; MUID=18D549D1A99466D12C4D5D75A8236769; MUIDB=18D549D1A99466D12C4D5D75A8236769; _EDGE_V=1; _EDGE_S=F=1&SID=054AA60E4C8562890C41B2AA4DCA6355; MUIDB=18D549D1A99466D12C4D5D75A8236769; _Rwho=u=d&ts=2024-06-20; SRCHUSR=DOB=20240620&T=1718845737000&TPC=1718845738000; _clck=h22fom%7C2%7Cfms%7C0%7C1632; USRLOC=HS=1&ELOC=LAT=30.269315719604492|LON=-97.74359893798828|N=Austin%2C%20Texas|ELT=1|; ipv6=hit=1718850612454; _clsk=1eo8838%7C1718847586574%7C5%7C1%7Ct.clarity.ms%2Fcollect; SRCHHPGUSR=SRCHLANG=en&PV=5.10.217&BRW=NOTP&BRH=S&CW=701&CH=393&SCW=1164&SCH=393&DPR=1.0&UTC=0&DM=0&CIBV=1.1776.0&WTS=63854442537&HV=1718847015&PRVCW=701&PRVCH=393&IG=F269B4049B514069891165985CDD8366&EXLTT=2; _RwBf=r=0&ilt=5&ihpd=0&ispd=2&rc=25&rb=0&gb=0&rg=200&pc=20&mtu=0&rbb=0&g=0&cid=&clo=0&v=5&l=2024-06-19T07:00:00.0000000Z&lft=0001-01-01T00:00:00.0000000&aof=0&ard=0001-01-01T00:00:00.0000000&rwdbt=0001-01-01T00:00:00.0000000&rwflt=0001-01-01T00:00:00.0000000&o=2&p=&c=&t=0&s=0001-01-01T00:00:00.0000000+00:00&ts=2024-06-20T01:39:47.0751227+00:00&rwred=0&wls=&wlb=&wle=&ccp=&cpt=&lka=0&lkt=0&aad=0&TH=; _SS=SID=09670785CAF36D7410801321CB446C7F&R=25&RB=0&GB=0&RG=200&RP=20; dsc=order=Video
``
