### ISSUE TITLE
[Bug] 🐛 couldflare 部署 

### ISSUE THREAD

**Issue by Yumega** [Harry-zklcdc/go-proxy-bingai#447]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the bug

Annotations
2 warnings

### Steps to reproduce

deploy
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

deploy
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

### Expected behavior

no warning 

### Deploy

Cloudflare Worker

### OS & Version

windows11

### Browser & Version

chrome121

### GoProxiBingAI Version

V3

**Comment by sdlkhfksl** [comment]
在 GitHub 仓库中添加 Secret
进入您的 GitHub 仓库。
导航到 Settings > Secrets > Actions。
点击 New repository secret。
将新建的 API Token 命名为 CLOUDFLARE_API_TOKEN，并将生成的令牌粘贴到输入框中。

**Comment by Harry-zklcdc** [comment]
请按照教程部署，如有问题重新开启
