### ISSUE TITLE
[Bug] 🐛 

### ISSUE THREAD

**Issue by bullkq** [Harry-zklcdc/go-proxy-bingai#45]
### Describe the bug

用最新的1.9.5安装包，copy到ubuntu22系统里，运行
chmod +x go-proxy-bingai
USER_KievRPSSecAuth=xxx ./go-proxy-bingai

访问
54.199.40.161:8080 一直在转蓝色圈圈

有啥问题吗
![5](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/118818378/eb6ceeed-b791-4143-915b-1c890dac6236)

### Steps to reproduce

-

### Expected behavior

-

### Versions

- OS: 
- Platform: 
- GoProxiBing version:

**Comment by high-player** [comment]
好像必须得有ssl证书的域名，不要用IP地址:端口访问，用域名去访问。但是我加载出来也没法用，不知道为啥。

**Comment by bullkq** [comment]
https://nb95.wbyai.top/ 这个显示的怎么不是部署的界面？我cf里设置了workers 不知道弄得对不对

我换回1.9.3 ubuntu换成20 也不行了，忘了昨天是怎么弄成的了。

**Comment by ilolita945** [comment]
> ### Describe the bug
> 用最新的1.9.5安装包，copy到ubuntu22系统里，运行 chmod +x go-proxy-bingai USER_KievRPSSecAuth=xxx ./go-proxy-bingai
> 
> 访问 54.199.40.161:8080 一直在转蓝色圈圈
> 
> 有啥问题吗 ![5](https://user-images.githubusercontent.com/118818378/257063586-eb6ceeed-b791-4143-915b-1c890dac6236.jpg)
> 
> ### Steps to reproduce
> 
> ### Expected behavior
> 
> ### Screenshots
> _No response_
> 
> ### Versions
> * OS:
> * Platform:
> * GoProxiBing version:
> 
> ### Additional context
> _No response_

必须要HTTPS
