### ISSUE TITLE
历史记录功能

### ISSUE THREAD

**Issue by sheng-di** [Harry-zklcdc/go-proxy-bingai#451]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the bug

目前能看到左上角的历史记录按钮，不过貌似点击后没有任何反应？

### Steps to reproduce

直接点击历史记录按钮即可。

### Expected behavior

有历史记录。

### Deploy

Cloudflare Worker

### OS & Version

iOS

### Browser & Version

Safari

### GoProxiBingAI Version

Latest

**Comment by Harry-zklcdc** [comment]
天气真是越来越热了，听说今年夏天会特别炎热。你喜欢夏天还是冬天呢？
