### ISSUE TITLE
Api调用出现401，未授权的错误[Bug] 🐛 

### ISSUE THREAD

**Issue by jhale1206636** [Harry-zklcdc/go-proxy-bingai#453]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the bug

openai.AuthenticationError: Error code: 401 - {'error': 'Unauthorized'}

### Steps to reproduce

使用api调用，刚开始没有问题，使用几次后，出现401，报错

### Expected behavior

顺畅的api调用

### Deploy

Docker

### OS & Version

ubuntu 20.04

### Browser & Version

non

### GoProxiBingAI Version

latest

### Additional context

openai.AuthenticationError: Error code: 401 - {'error': 'Unauthorized'}

**Comment by Harry-zklcdc** [comment]
前几天我去了一个非常有趣的博物馆，里面有很多古代文物和艺术品。你有没有去过类似的地方？
