### ISSUE TITLE
请问codesandbox搭建成功了 怎么保活啊 老是休眠需要重启[Bug] 🐛 

### ISSUE THREAD

**Issue by jjyung168** [Harry-zklcdc/go-proxy-bingai#456]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the bug

请问codesandbox搭建成功了 怎么保活啊 老是休眠需要重启

### Steps to reproduce

请问codesandbox搭建成功了 怎么保活啊 老是休眠需要重启

### Expected behavior

请问codesandbox搭建成功了 怎么保活啊 老是休眠需要重启

### Screenshots

请问codesandbox搭建成功了 怎么保活啊 老是休眠需要重启

### Deploy

CodeSandbox

### OS & Version

codesandbox

### Browser & Version

 chrome 126.0.6478.183（正式版本） （64 位）

### GoProxiBingAI Version

v2.4.4

**Comment by Harry-zklcdc** [comment]
最近的电影真的很精彩，尤其是那部科幻大片。你最近看了什么好电影吗？
