### ISSUE TITLE
[Help] 🤔 这个必须要443端口吗 我的443端口和80占用了 可以修改为其他端口吗？

### ISSUE THREAD

**Issue by tianyufeng925** [Harry-zklcdc/go-proxy-bingai#457]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

这个必须要443端口吗 我的443端口和80占用了 可以修改为其他端口吗？

### Steps to behave

这个必须要443端口吗 我的443端口和80占用了 可以修改为其他端口吗？

### Expected behavior

这个必须要443端口吗 我的443端口和80占用了 可以修改为其他端口吗？

### Deploy

Docker

### OS & Version

centos7.6

### Browser & Version

chrome  119.0.6045.107

### GoProxiBingAI Version

最新版

**Comment by tianyufeng925** [comment]
我目前是修改的2043端口 有报错 有一个地方请求的是443

**Comment by Harry-zklcdc** [comment]
启动端口可以是随意，但是浏览器的访问端口必须是 443
