### ISSUE TITLE
[Help] 🤔 使用分支go-proxy-bingai:latest-with-pass是否不需要手动指定pass的环境变量？

### ISSUE THREAD

**Issue by tempppabx1** [Harry-zklcdc/go-proxy-bingai#459]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

如果使用`latest-with-pass`分支进行docker部署，是否就不需要配置`BYPASS_SERVER`这个变量了，默认走的就是在本地运行的pass服务器？

### Steps to behave

使用仓库目录 `Harry-zklcdc/go-proxy-bingai/blob/master/docker/` 下的 [docker-compose-with-pass.yml](https://github.com/Harry-zklcdc/go-proxy-bingai/blob/master/docker/docker-compose-with-pass.yml)进行部署

### Expected behavior

请求走本地搭建的bypass服务器

### Deploy

Docker

### OS & Version

Ubuntu 22.04

### Browser & Version

Chrome 127

### GoProxiBingAI Version

v2.4.4

**Comment by Harry-zklcdc** [comment]
> 如果使用latest-with-pass分支进行docker部署，是否就不需要配置BYPASS_SERVER这个变量了，默认走的就是在本地运行的pass服务器？

是的，不需要

> 另一个问题是变量CF_ZERO_TRUST_TOKEN，我在项目里搜了一下，看起来跟docker部署的用户关系不大，但是如果这个变量为空docker启动就会报错，但是随便写一个值就正常了，这是一个bug吗

算，也不算，是为了搞 CF 的穿透留的环境变量，有空我给修一下吧
