### ISSUE TITLE
海外服务器，利用Docker部署、宝塔面板反代小白教程

### ISSUE THREAD

**Issue by skyfly2000** [Harry-zklcdc/go-proxy-bingai#46]
最新版本号:1.10.0，最新Fork仓库地址:https://github.com/Harry-zklcdc/go-proxy-bingai
请确保您的VPS没有被微软封禁。目前已知的被封禁的服务包括Railway、Vercel、Render以及腾讯云海外VPS，Cloudflare的聊天服务器也被封禁。
## 安装步骤
1. 在VPS上安装宝塔面板。
2. 根据宝塔的提示，安装相关插件和Nginx。
3. 在宝塔中安装Docker。
4. 在宝塔的"网站"，添加站点并添加已解析好的域名。
5. 在宝塔的"网站"，点击“刚添加的域名”，点击“SSL”，然后点击“Let's Encrypt”申请证书，选择“强制https”，“保存”。
6. 在宝塔的"网站"，点击“刚添加的域名”，点击“反向代理”，点击“添加反向代理”，“目标URL” 输入“http://127.0.0.1:8080 ”（或输入VPS地址:“http://xxx:8080”）。
7. 通过SSH连接到VPS。
8. 下载二进制文件（如果是arm架构，请自行替换最新版本所对应的文件地址）：
    ```
    wget https://github.com/Harry-zklcdc/go-proxy-bingai/releases/download/v1.10.0/go-proxy-bingai-linux-amd64.tar.gz
    ```

9. 解压二进制文件：
    ```
    tar -xzvf go-proxy-bingai-linux-amd64.tar.gz
    ```

10. 赋予go-proxy-bingai文件可执行权限：
    ```
    chmod +x go-proxy-bingai
    ```

11. 挂载二进制文件：
    ```
    docker run -e USER_KievRPSSecAuth=XXXXXXX -v $PWD/go-proxy-bingai:/app/go-proxy-bingai -d -p 8080:8080 --name go-proxy-bingai --restart=always adams549659584/go-proxy-bingai
    ```

OK,部署完成！
如果需要升级版本，只需在宝塔内的Docker中删除容器，然后重复SSH下载二进制文件、解压、挂载、赋予权限的步骤即可。

**Comment by ccodingfundddd** [comment]
能搞个国内服务器使用宝塔+Nginx+Warp的教程吗？

**Comment by skyfly2000** [comment]
> 能搞个国内服务器使用宝塔+Nginx+Warp的教程吗？

有人成功在国内部署的，Nginx配置需要加入……，你自己琢磨吧，比较复杂且很不稳定


server {
    listen 80;
    server_name xxx.xxx.xxx;

    location /sydney/ChatHub {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version                 1.1;
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";
        proxy_set_header Host              $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;
    }

    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host              $host;    
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;
    } 

}


server {
    listen              443 ssl;
    server_name         xxx.xxx.xxx;
    ssl_certificate     xxx/fullchain.pem;
    ssl_certificate_key xxx/privkey.pem;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;

    location /sydney/ChatHub {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version                 1.1;
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";
        proxy_set_header Host              $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;
    }

    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host              $host;    
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;
    } 

}

**Comment by skyfly2000** [comment]
> 能搞个国内服务器使用宝塔+Nginx+Warp的教程吗？

有人成功在国内部署的，Nginx配置需要加入……，你自己琢磨吧，比较复杂且很不稳定
server {
    listen 80;
    server_name xxx.xxx.xxx;

    location /sydney/ChatHub {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version                 1.1;
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";
        proxy_set_header Host              $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;
    }

    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host              $host;    
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;
    } 

}


server {
    listen              443 ssl;
    server_name         xxx.xxx.xxx;
    ssl_certificate     xxx/fullchain.pem;
    ssl_certificate_key xxx/privkey.pem;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;

    location /sydney/ChatHub {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version                 1.1;
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";
        proxy_set_header Host              $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;
    }

    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host              $host;    
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;
    } 

}

**Comment by skyfly2000** [comment]
有人成功在国内部署过，你自己琢磨吧，Nginx配置如下：

server {
    listen 80;
    server_name xxx.xxx.xxx;

    location /sydney/ChatHub {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version                 1.1;
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";
        proxy_set_header Host              $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;
    }

    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host              $host;    
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;
    } 

}


server {
    listen              443 ssl;
    server_name         xxx.xxx.xxx;
    ssl_certificate     xxx/fullchain.pem;
    ssl_certificate_key xxx/privkey.pem;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;

    location /sydney/ChatHub {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version                 1.1;
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";
        proxy_set_header Host              $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;
    }

    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host              $host;    
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;
    } 

}

**Comment by skyfly2000** [comment]
> 能搞个国内服务器使用宝塔+Nginx+Warp的教程吗？

你国内服务器全局和谐上网

**Comment by bullkq** [comment]
万分感谢，终于成了。哈哈 还是有几个问题
#根据提示宝塔内安装相关插件和Nginx 相关插件PHP FTP这些不是必须的把，只要Nginx就可以？

#挂载二进制文件
docker run -e 。。。。
这个貌似一定要sodu bash后才有效，否则报错

新版本看起来很好，我都不想在输入_u和 KievRPSSecAuth了， 平时用不到图像。

**Comment by skyfly2000** [comment]
> 万分感谢，终于成了。哈哈 还是有几个问题 #根据提示宝塔内安装相关插件和Nginx 相关插件PHP FTP这些不是必须的把，只要Nginx就可以？
> 
> #挂载二进制文件 docker run -e 。。。。 这个貌似一定要sodu bash后才有效，否则报错
> 
> 新版本看起来很好，我都不想在输入_u和 KievRPSSecAuth了， 平时用不到图像。

这个貌似用不到PHP和FTP……，宝塔可以部署很多项目，最大化利用VPS，安装起来也不浪费，占用空间很少……

**Comment by Harry-zklcdc** [comment]
可以麻烦重新按照markdown的格式排一下版嘛，然后我把这个issue置顶

**Comment by skyfly2000** [comment]
> 

修改过来是这种格式么？ @Harry-zklcdc

**Comment by Harry-zklcdc** [comment]
> 修改过来是这种格式么？ @Harry-zklcdc

可以的，然后Railway、Vercel、Render理论上还能用来部署，不过要配合cloudflare的worker才能使用本站的聊天服务器

**Comment by skyfly2000** [comment]
> 配合

貌似是一直显示网络被阻止……，你把cloudflare的worker修改后的代码发出来，我试试

**Comment by skyfly2000** [comment]
> > 修改过来是这种格式么？ @Harry-zklcdc
> 
> 可以的，然后Railway、Vercel、Render理论上还能用来部署，不过要配合cloudflare的worker才能使用本站的聊天服务器

貌似是一直显示网络被阻止……，和腾讯云海外vps一样，你把cloudflare的worker修改后的代码发出来，我试试，如果行的话，那么理论上被BAN的vps都是可以的哦

**Comment by Harry-zklcdc** [comment]
> 貌似是一直显示网络被阻止……，你把cloudflare的worker修改后的代码发出来，我试试

就是现在的 [cloudflare/worker.js](https://github.com/Harry-zklcdc/go-proxy-bingai/blob/master/cloudflare/worker.js)，其他的一模一样，但是得手动过验证，然后前端填写 `_U` 和 `KievRPSSecAuth`

Cloudflare worker 里面配置一下路由
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/ad317e19-2a97-43ce-abad-6054c5d1eff0)

然后代理

**Comment by Harry-zklcdc** [comment]
CF确定没法不登录使用，只能登录后才能使用，VPS部署是最稳妥的，配置了 `USER_KievRPSSecAuth` 环境变量后才可以直接不登录问答

**Comment by skyfly2000** [comment]
> CF确定没法不登录使用，只能登录后才能使用，VPS部署是最稳妥的，配置了 `USER_KievRPSSecAuth` 环境变量后才可以直接不登录问答

修改[worker.js](https://github.com/Harry-zklcdc/go-proxy-bingai/blob/master/cloudflare/worker.js)，填入KievRPSSecAuth，聊天服务器公开后有一定风险

**Comment by skyfly2000** [comment]
> > CF确定没法不登录使用，只能登录后才能使用，VPS部署是最稳妥的，配置了 `USER_KievRPSSecAuth` 环境变量后才可以直接不登录问答
> 
> 修改[worker.js](https://github.com/Harry-zklcdc/go-proxy-bingai/blob/master/cloudflare/worker.js)，填入KievRPSSecAuth，聊天服务器公开后有一定风险还是Docker比较稳妥，不行就加密码

**Comment by Harry-zklcdc** [comment]
> > CF确定没法不登录使用，只能登录后才能使用，VPS部署是最稳妥的，配置了 `USER_KievRPSSecAuth` 环境变量后才可以直接不登录问答
> 
> 修改[worker.js](https://github.com/Harry-zklcdc/go-proxy-bingai/blob/master/cloudflare/worker.js)，填入KievRPSSecAuth，聊天服务器公开后有一定风险

是这样的，所以那个提交我后面备注了建议自行部署，不公开使用

**Comment by skyfly2000** [comment]
> 0803最新版本号:1.11.2，最新Fork仓库地址:https://github.com/Harry-zklcdc/go-proxy-bingai。
>8 月 4 日Docker部署1.11.2，发现腾讯云解禁，可以正常使用，Google 还没来及测试；
> 
> ## Docker安装步骤
> 1. 在VPS上安装宝塔面板。
> 2. 根据宝塔的提示，安装相关插件和Nginx。
> 3. 在宝塔中安装Docker。
> 4. 在宝塔的"网站"，添加站点并添加已解析好的域名。
> 5. 在宝塔的"网站"，点击“刚添加的域名”，点击“SSL”，然后点击“Let's Encrypt”申请证书，选择“强制https”，“保存”。
> 6. 在宝塔的"网站"，点击“刚添加的域名”，点击“反向代理”，点击“添加反向代理”，“目标URL” 输入“http://127.0.0.1:8080 ”（或输入VPS地址:“[http://xxx:8080”）。](http://xxx:8080%E2%80%9D%EF%BC%89%E3%80%82)
> 7. 通过SSH连接到VPS。
> 8. 下载二进制文件（如果是arm架构，请自行替换最新版本所对应的文件地址）：
>    ```
>    wget https://github.com/Harry-zklcdc/go-proxy-bingai/releases/download/v1.11.2/go-proxy-bingai-linux-amd64.tar.gz
>    ```
> 9. 解压二进制文件：
>    ```
>    tar -xzvf go-proxy-bingai-linux-amd64.tar.gz
>    ```
> 10. 赋予go-proxy-bingai文件可执行权限：
>     ```
>     chmod +x go-proxy-bingai
>     ```
> 11. 挂载二进制文件：
>     ```
>     docker run -e USER_KievRPSSecAuth=XXXXXXX -v $PWD/go-proxy-bingai:/app/go-proxy-bingai -d -p 8080:8080 --name go-proxy-bingai --restart=always adams549659584/go-proxy-bingai
>     ```
> 
> OK,部署完成！ 如果需要升级版本，只需在宝塔内的Docker中删除容器，然后ssh删除原压缩文件 `rm -rf go-proxy-bingai-linux-amd64.tar.gz` 重复SSH“下载二进制文件”、“解压”、“挂载”、“赋予权限”的步骤即可。
> 
> 0802增加KievRPSSecAuth和_U的取得方法: 1、Egde浏览器安装插件Cookie Editor 2、架梯子开全局，Egde浏览器打开www.bing.com，如果出现“聊天”则继续，如果不出现则梯子地区不对，或没开全局 3、登录bing，随意聊天几句话 4、打开Cookie Editor，可以找到KievRPSSecAuth和_U。 重点是必须有登录过程，并成功建立“聊天”对话。

**Comment by DevDreamerx** [comment]
<img width="1146" alt="Screenshot 2023-08-05 at 1 07 25 AM" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/27147728/f7883d86-283e-46c2-8ff0-fee2d5b43ee4">
请问这是什么原因导致的

**Comment by skyfly2000** [comment]
> <img alt="Screenshot 2023-08-05 at 1 07 25 AM" width="1146" src="https://user-images.githubusercontent.com/27147728/258485963-f7883d86-283e-46c2-8ff0-fee2d5b43ee4.png"> 请问这是什么原因导致的

网络不稳定，vps到 new bing或者你的 pc到vps任何一个节点不稳定都会出现，建议选择线路好DNS干净的 vps，比如 Google 云
