### ISSUE TITLE
[Bug] 🐛 脚注格式不规范

### ISSUE THREAD

**Issue by chengtx809** [Harry-zklcdc/go-proxy-bingai#460]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the bug

目前api输出的脚注标记是[^1^]这样的格式，但在如nextchat等平台渲染错误
后来发现正确的格式应该是[^1]这样的，改正后显示正常，望大佬修复
参考资料链接 [Markdown 脚注](https://markdown.com.cn/extended-syntax/footnotes.html)

### Steps to reproduce

正常聊天

### Expected behavior

正常聊天

### Deploy

Cloudflare Worker

### OS & Version

win10

### Browser & Version

edge

### GoProxiBingAI Version

最新

**Comment by chengtx809** [comment]
@Harry-zklcdc 大佬有空可以看看吗，谢谢

**Comment by Harry-zklcdc** [comment]
![QQ_1723190766156](https://github.com/user-attachments/assets/10794572-dd7e-419a-a219-a0c17068ba56)

Bing 返回的脚注还是 `1^`，而不是 `1`，所以得用 `[^1^]`，而不是 `[^1]`
