### ISSUE TITLE
[Bug] 🐛 Unable to use API from binary/Cloudflare Pages/Cloudflare Workeer

### ISSUE THREAD

**Issue by Sakura-Byte** [Harry-zklcdc/go-proxy-bingai#464]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the bug

I used deploy methods like binary/Cloudflare pages/workers + cloudflare workers challenge solver.
None of these worked for me.
All I got was User needs to solve CAPTCHA to continue.

### Steps to reproduce

deploy go-proxy-bingai using binary/Cloudflare pages/workers + cloudflare workers challenge solver.
And use python's openai package.

### Expected behavior

Auto solve the challenge and output the desired result.

### Screenshots

![screenshot](https://github.com/user-attachments/assets/21a1b831-0bb5-4115-a8b6-f1400ed218ef)

### Deploy

Binary

### OS & Version

Windows 11

### Browser & Version

Browser worked normally.

### GoProxiBingAI Version

latest/2.4.4

**Comment by Harry-zklcdc** [comment]
What is the environment param `BYPASS_SERVER`?
