### ISSUE TITLE
[Help] 🤔 请教在OpenResty 1.25.3中反向代理的正确书写方式

### ISSUE THREAD

**Issue by pudding1111** [Harry-zklcdc/go-proxy-bingai#465]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

最近我是用的[宝塔面板国际版](https://github.com/aaPanel/aaPanel），经常会遇到python定时爆满问题，根据网上教程并没有[解决](https://blog.csdn.net/q506844270/article/details/131012533)，所以我更改成[mdserver-web](https://github.com/midoks/mdserver-web/tree/master)管理面板，这个面板使用[openresty](https://openresty.org/cn/)作为nignx管理工具，这个和宝塔反向代理有点点不同。

### Steps to behave

[根据版主提供的反向代理格式](https://github.com/Harry-zklcdc/go-proxy-```
`
bingai/wiki/%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86)
map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}
map $remote_addr $proxy_forwarded_elem {
    # IPv4 addresses can be sent as-is
    ~^[0-9.]+$        "for=$remote_addr";

    # IPv6 addresses need to be bracketed and quoted
    ~^[0-9A-Fa-f:.]+$ "for=\"[$remote_addr]\"";

    # Unix domain socket names cannot be represented in RFC 7239 syntax
    default           "for=unknown";
}
map $http_forwarded $proxy_add_forwarded {
    default "$proxy_forwarded_elem";
}
`
会提示
`OpenResty 配置测试不通过, 请重试: nginx: [emerg] unknown "proxy_add_forwarded" variable nginx: configuration file /www/server/openresty/nginx/conf/nginx.conf test failed`

更改成
```
location ^~ / {
    proxy_pass http://127.0.0.1:18085;    # 你部署的地址和端口
    proxy_http_version        1.1;

    # Proxy headers
    proxy_set_header Upgrade             $http_upgrade;
    proxy_set_header Connection          $connection_upgrade;
    proxy_set_header Host                $host;
    proxy_set_header X-Real-IP           $remote_addr;

    # 设置 X-Forwarded-For 头部
    proxy_set_header X-Forwarded-For     $proxy_add_x_forwarded_for;

    proxy_set_header X-Forwarded-Proto   $scheme;
    proxy_set_header X-Forwarded-Host    $host;
    proxy_set_header X-Forwarded-Port    $server_port;

    # Proxy timeouts
    proxy_connect_timeout    300s;
    proxy_send_timeout       300s;
    proxy_read_timeout       300s;
}
```
也会报错

### Expected behavior

请教版主遇到这样的情况该怎么填写正确的反向代理

### Deploy

Docker

### OS & Version

DEBAIN12

### Browser & Version

CHROME LATEST

### GoProxiBingAI Version

LATTEST

**Comment by Harry-zklcdc** [comment]
![QQ_1724219794577](https://github.com/user-attachments/assets/780126ad-c099-462c-9928-a2682282047e)

**Comment by pudding1111** [comment]
这样的搭建在经过重置系统后，解决了反向代理的一部分问题，后来我遇到了heed头过大的问题
`2024/08/19 19:23:41 [error] 582465#0: *10346 upstream sent too big header while reading response header from upstream, client: 192.9.134.93, server: bing.257053.xyz, request: "GET /turing/conversation/create?bundleVersion=1.1725.0 HTTP/2.0", upstream: "http://127.0.0.1:18085/turing/conversation/create?bundleVersion=1.1725.0", host: "bing.257053.xyz", referrer: "https://bing.257053.xyz/web/"`
我在nginx的配置文件中增加
`   large_client_header_buffers 4 16k; # 默认是 4 1k`
怎么说呢，添加这段代码后确实不在报错，但是出现了比较难受的问题，就是我在科学上网的环境中，bingai使用毫无问题，
![image](https://github.com/user-attachments/assets/015f01d1-1692-4971-9512-b72dc5b0c9db)
但是在国内环境中，却始终无法连接
![image](https://github.com/user-attachments/assets/0d96a887-e083-4905-99b8-e0051aa33fba)
这个vps刚买一个月，是正经使用的vps，ip干净，域名也是备案域名无dns污染，我查看了日志文件，无报错，并且都有访问记录。
实在是摸不着头脑

**Comment by Harry-zklcdc** [comment]
直接进相关讨论群找我吧，我有空给你看看，最近忙

**Comment by pudding1111** [comment]
好的，已经在tg上进行联系
