### ISSUE TITLE
[Help] 🤔 最新www.bing.com无法攻取KievRPSSecAuth cookie

### ISSUE THREAD

**Issue by haso2007** [Harry-zklcdc/go-proxy-bingai#468]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://git.11778899.xyz/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

根据一键登录的说明，需要获取名为KievRPSSecAuth 的cookie,但是实测无法找到这个cookie.各位大佬可以分享一下解决方法吗？
另外，完整cookie 在网络中查找create也找不到的，有没其它代替的方法。

### Steps to behave

按教程操作

### Expected behavior

找到KievRPSSecAuth 

### Deploy

Cloudflare Worker

### OS & Version

Microsoft Windows 10 企业版10.0.19045 N/A Build 19045

### Browser & Version

Microsoft Edge Version 128.0.2739.67 (Official build) (64-bit)

### GoProxiBingAI Version

2.4.4

**Comment by SokWith** [comment]
https://github.com/Harry-zklcdc/go-proxy-bingai/issues/431#issuecomment-2151574200

有帐号需求的我推荐使用推送，1次部署，随处引用

**Comment by haso2007** [comment]
实测无需要使用[KievRPSSecAuth cookie]也可使用。
