### ISSUE TITLE
[Help] 🤔 glitch 里的变量 CF_ZERO_TRUST_TOKEN 对应的端口和路径如何设置？

### ISSUE THREAD

**Issue by fscarmen** [Harry-zklcdc/go-proxy-bingai#469]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

建了 cloudflare tunnel ，请问详细如何设置？

### Steps to behave

如上

### Expected behavior

如上

### Deploy

Others

### OS & Version

Debian 11

### Browser & Version

1

### GoProxiBingAI Version

1

**Comment by Harry-zklcdc** [comment]
不需要，直接CNAME 解析就行

**Comment by fscarmen** [comment]
cname glitch给出来的地址吗？因为我运行的时候一直卡着

<img width="1094" alt="image" src="https://github.com/user-attachments/assets/b5d5aa97-7f83-4bf6-8e0a-32e2acb5560e">

**Comment by Harry-zklcdc** [comment]
啊不对，我下午说错了，需要 CFZT 来穿透一下。

> `CF_ZERO_TRUST_TOKEN `

参考 #338

> CF 隧道配置

![QQ_1727005930946](https://github.com/user-attachments/assets/4118e519-ab97-49a2-9807-dc75a26e910c)

**Comment by fscarmen** [comment]
可以了，谢谢
