### ISSUE TITLE
[Bug] 🐛 历史记录显示不能滚动

### ISSUE THREAD

**Issue by YuenSzeHong** [Harry-zklcdc/go-proxy-bingai#47]
### Describe the bug

历史记录显示不能滚动

### Steps to reproduce

查看历史记录（如果记录多的就没办法滚动

### Expected behavior

可以滚动查看早一点的历史记录

### Screenshots

go-proxy
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/40477634/f7dc439f-5420-49a9-9580-01ac7754e2b1)
原版
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/40477634/4eba7c0a-3eb7-46d3-9fae-8964976014b2)

### Versions

- OS: 
- Platform: MS edge dev
- GoProxiBing version:1.9.5

**Comment by YuenSzeHong** [comment]
感觉应该是css问题

**Comment by Harry-zklcdc** [comment]
好的，待修复

**Comment by YuenSzeHong** [comment]
1.11.5 版本再次出现这个问题
