### ISSUE TITLE
[Help] 🤔一直卡在“ 自动通过人机验证中 请耐心等待...”

### ISSUE THREAD

**Issue by gudaoxongdi** [Harry-zklcdc/go-proxy-bingai#470]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

服务器选择“Cloudflare Worker”没有问题，选择本站时，一直卡在“ 自动通过人机验证中 请耐心等待...”。已经在cf变量里把BYPASS_SERVER 设置成了https://bypass.b1ng.chat，
之前是另外的一个地址。请问要怎么解决。

### Steps to behave

如上

### Expected behavior

如上

### Deploy

Cloudflare Worker

### OS & Version

win11

### Browser & Version

chrome

### GoProxiBingAI Version

v2.4.4

**Comment by fscarmen** [comment]
应该是不能用了，看看作者后续有没有维护了。

**Comment by Harry-zklcdc** [comment]
等我后期有空了再维护一下，最近实在太忙，顾不上这个项目了

**Comment by Harry-zklcdc** [comment]
已修复

![QQ_1726995188711](https://github.com/user-attachments/assets/f06266c6-4995-4b3d-802a-b53f2bc3e25b)
