### ISSUE TITLE
[Bug] 🐛 老问题，不说中文

### ISSUE THREAD

**Issue by hjx2289206** [Harry-zklcdc/go-proxy-bingai#472]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the bug

老问题了

### Steps to reproduce

老问题了

### Expected behavior

修复

### Deploy

Others

### OS & Version

Windows11

### Browser & Version

edge

### GoProxiBingAI Version

2.4.4

**Comment by icychick-liu** [comment]
同样问题
![image](https://github.com/user-attachments/assets/57dea4c6-50d0-431d-b3f9-b158614e352a)

**Comment by Harry-zklcdc** [comment]
#473

**Comment by SokWith** [comment]
https://github.com/Harry-zklcdc/go-proxy-bingai/issues/473#issuecomment-2429177725
