### ISSUE TITLE
[Bug] 🐛 示例站点宕机

### ISSUE THREAD

**Issue by huajideshutiao** [Harry-zklcdc/go-proxy-bingai#474]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the bug

![Screenshot_2024-10-12-01-22-12-848_mark via](https://github.com/user-attachments/assets/3abbc9eb-4db2-419b-b2ef-809d50832f34)

### Steps to reproduce

无

### Expected behavior

正常工作

### Deploy

Others

### OS & Version

安卓14

### Browser & Version

webview 118.0.5993.80

### GoProxiBingAI Version

所有演示站

**Comment by Harry-zklcdc** [comment]
#473
