### ISSUE TITLE
[Bug] 🐛 部署后无法运行,有4个.js文件404 Not Found

### ISSUE THREAD

**Issue by shoot82003** [Harry-zklcdc/go-proxy-bingai#475]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the bug

![Uploading QQ截图20241014111226.png…]()

### Steps to reproduce

1.清除浏览器记录
2.[Cloudfalre Worker 部署](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/Cloudflare-Worker-%E9%83%A8%E7%BD%B2)
---失败
3.[Vercel 部署](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/Vercel-%E9%83%A8%E7%BD%B2)
---补充Vercel,仍失败

### Expected behavior

出现(百度统计?)hm.js?6002068077c49f5ff6fa1c10d4ae55dc
nAb2_uMWSHAhScje1ODrwe4cVoA.br.js
rp/nAb2_uMWSHAhScje1ODrwe4cVoA.br.js
三个链接失效

### Deploy

Vercel

### OS & Version

Windows 11

### Browser & Version

Chrome/128.0.0.0

### GoProxiBingAI Version

v2.4.4

**Comment by SokWith** [comment]
https://github.com/Harry-zklcdc/go-proxy-bingai/issues/473#issuecomment-2409894813
