### ISSUE TITLE
[Help] 🤔 一重置就打不开

### ISSUE THREAD

**Issue by Zhudi-778899** [Harry-zklcdc/go-proxy-bingai#477]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

本来好好的，一点一键重置就打不开了，一直在三个圆圈加载，请问怎么办，在线等

### Steps to behave

本来好好的，一点一键重置就打不开了，一直在三个圆圈加载，请问怎么办，在线等，是使用cloudflare pages部署的

### Expected behavior

能否给我一个解决办法

### Deploy

Cloudflare Worker

### OS & Version

Windows 10

### Browser & Version

Chrome 130.0.6723.92

### GoProxiBingAI Version

v2.4.4

### Additional context

不是Workers，是Pages

**Comment by Zhudi-778899** [comment]
有没有好心人看看为什么啊

**Comment by midway2333** [comment]
你仔细看看上一条issues，情况已经有说明了

**Comment by Zhudi-778899** [comment]
> 你仔细看看上一条issues，情况已经有说明了

可我是pages部署，workers部署无法添加路由，https://mycfoo-bingai.hf.space/web/index.html#/，请问这个人的站点是如何搭建的

**Comment by SokWith** [comment]
> > 你仔细看看上一条issues，情况已经有说明了
> 
> 可我是pages部署，workers部署无法添加路由，[https://mycfoo-bingai.hf.space/web/index.html#/，请问这个人的站点是如何搭建的](https://mycfoo-bingai.hf.space/web/index.html#/%EF%BC%8C%E8%AF%B7%E9%97%AE%E8%BF%99%E4%B8%AA%E4%BA%BA%E7%9A%84%E7%AB%99%E7%82%B9%E6%98%AF%E5%A6%82%E4%BD%95%E6%90%AD%E5%BB%BA%E7%9A%84)

在huggingface上是一直可以搭建的，尽可能使用自己创建的docker来加载，避免多人引用被系统扫描到了。huggingface对前期几种代理特征（在docker里面内置浏览器、VNC、CF TURNNEL...任意一种就）进行了封杀，所以不建议你们直接加载我的docker文件。

对于原代码追加核心api，需要增加这个路由：
https://github.com/SokWith/go-bingai/blob/master/api/rp.go

**Comment by Zhudi-778899** [comment]
> > > 你仔细看看上一条issues，情况已经有说明了
> > 
> > 
> > 可我是pages部署，workers部署无法添加路由，[https://mycfoo-bingai.hf.space/web/index.html#/，请问这个人的站点是如何搭建的](https://mycfoo-bingai.hf.space/web/index.html#/%EF%BC%8C%E8%AF%B7%E9%97%AE%E8%BF%99%E4%B8%AA%E4%BA%BA%E7%9A%84%E7%AB%99%E7%82%B9%E6%98%AF%E5%A6%82%E4%BD%95%E6%90%AD%E5%BB%BA%E7%9A%84)
> 
> 在huggingface上是一直可以搭建的，尽可能使用自己创建的docker来加载，避免多人引用被系统扫描到了。huggingface对前期几种代理特征（在docker里面内置浏览器、VNC、CF TURNNEL...任意一种就）进行了封杀，所以不建议你们直接加载我的docker文件。
> 
> 对于原代码追加核心api，需要增加这个路由： https://github.com/SokWith/go-bingai/blob/master/api/rp.go

我是小白，能不能告诉我怎么添加路由

**Comment by SokWith** [comment]
> > > > 你仔细看看上一条issues，情况已经有说明了
> > > 
> > > 
> > > 可我是pages部署，workers部署无法添加路由，[https://mycfoo-bingai.hf.space/web/index.html#/，请问这个人的站点是如何搭建的](https://mycfoo-bingai.hf.space/web/index.html#/%EF%BC%8C%E8%AF%B7%E9%97%AE%E8%BF%99%E4%B8%AA%E4%BA%BA%E7%9A%84%E7%AB%99%E7%82%B9%E6%98%AF%E5%A6%82%E4%BD%95%E6%90%AD%E5%BB%BA%E7%9A%84)
> > 
> > 
> > 在huggingface上是一直可以搭建的，尽可能使用自己创建的docker来加载，避免多人引用被系统扫描到了。huggingface对前期几种代理特征（在docker里面内置浏览器、VNC、CF TURNNEL...任意一种就）进行了封杀，所以不建议你们直接加载我的docker文件。
> > 对于原代码追加核心api，需要增加这个路由： https://github.com/SokWith/go-bingai/blob/master/api/rp.go
> 
> 我是小白，能不能告诉我怎么添加路由

如果只是自己用用，不建议再折腾newbing了，官网都已经下架了。目前能用也仅是官方的应用还没有完全切替保留的后门，应该要不了多久就会完全关闭了。

如果有心学习，可以借鉴作者的代码，去代理copilot也许更好一些。
copliot目前只有一个关卡，就是对所有可疑的连接都要求cf的人机验证，这个一旦被要求，目前是无解的。但是，如果是使用不受限制的ip去访问，则根本就不需要任何验证，直接就快速连接了。由此特性，推测只需要在外网普通的主机（各大云商应该是没戏了）上建立反代就可以了。有外网普通主机资源的可以去验证一下。

**Comment by Harry-zklcdc** [comment]
#473

**Comment by lizeyou0203** [comment]
> #473

这个我也看了,但是我是新安装的,第一回使用.就是想问下还有没有办法能正常用起来.
看这个情况,就只能等大佬们继续适配新的了.
感谢回答.
