### ISSUE TITLE
[Help] 🤔 无法加载聊天，一直是点点点

### ISSUE THREAD

**Issue by zhangqiang-routon** [Harry-zklcdc/go-proxy-bingai#479]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the help wanted

使用cloudflare部署，clouddns的域名，已托管到cloudflare；部署完成后，可以访问，但是聊天窗口一直三个点的加载中，无法进入聊天。

### Steps to behave

一键部署到cloudflare，并设置了环境变量BYPASS_SERVER为https://bypass.b1ng.chat。
添加了域名解析。
手机流量测试亦然。

### Expected behavior

可以正常使用

### Deploy

Cloudflare Worker

### OS & Version

win10 19043.1237

### Browser & Version

edage 131.0.2903.70 (正式版本) (64 位)

### GoProxiBingAI Version

v2.4.4

**Comment by SokWith** [comment]
https://github.com/Harry-zklcdc/go-proxy-bingai/issues/473#issuecomment-2409894813
