### ISSUE TITLE
[Fix] 🐛 "clearCache" take effect on KievRPSSecAuth 修复"一键重置"未清除KievRPSSecAuth值的问题

### ISSUE THREAD

**Issue by IT-HaoGe** [Harry-zklcdc/go-proxy-bingai#48]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/130531658/be843893-62df-44c5-b4d6-2813854dfdd9)

感谢作者维护，一个小疏漏可以顺便改一下，"一键重置"未清除KievRPSSecAuth值的问题

[commit/修改的地方](https://github.com/Harry-zklcdc/go-proxy-bingai/commit/02f69f7a663159d2976435d5028c700fe329f89c)

` cookies.set(userKievRPSSecAuthCookieName, '', -1);
    };`

**Comment by Harry-zklcdc** [comment]
可以提交一下PR，感谢😊
