### ISSUE TITLE
[Bug] 🐛 点击查看所有最近聊天会出现画面急速抖动

### ISSUE THREAD

**Issue by yihaoshiyan** [Harry-zklcdc/go-proxy-bingai#50]
### Describe the bug

如题，点击后画面开始抽搐

### Steps to reproduce

设置用户后，点击查看最近聊天记录

### Expected behavior

希望能修复

### Versions

- OS: 
- Platform: 
- GoProxiBing version:

**Comment by Harry-zklcdc** [comment]
我这边没有这种情况，请附上浏览器等信息

**Comment by yihaoshiyan** [comment]
> 我这边没有这种情况，请附上浏览器等信息

换了台电脑，好了，可能是特殊情况🙇‍，感谢大佬
