### ISSUE TITLE
[Bug] 🐛 撰写文章为暗黑模式

### ISSUE THREAD

**Issue by wurenzhiwen666** [Harry-zklcdc/go-proxy-bingai#51]
### Describe the bug

撰写文章为暗黑模式

### Steps to reproduce

打开bingai撰写

### Expected behavior

改为白色日间模式

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by Harry-zklcdc** [comment]
Fixing

**Comment by Harry-zklcdc** [comment]
已添加
Commit: 45e794e8572e5cec32e0fe5687b303b34e652c2b
Release: https://github.com/Harry-zklcdc/go-proxy-bingai/releases/tag/v1.10.2
