### ISSUE TITLE
过一段时间就会出现：很抱歉，似乎出现错误。 让我们重新开始吧。

### ISSUE THREAD

**Issue by bullkq** [Harry-zklcdc/go-proxy-bingai#52]
有些时候重新刷新newbing 发现cookie_u刷新了，重新填入设置，刷新bingAI页面可以有效，但最近这次很久了都连不上。
我申请的亚马逊免费云ubuntu 20.4版本，位置在东京。域名用cloudflare绑定的。

有什么问题吗

我的手机wifi状态下也是这些问题，但是关闭wifi移动4g连接又马上就能用了，很怪

开了cloudflare的zero trust代理，服务选项选的是本站：
Bing 官方 | https://sydney.bing.com | 不可用 | 检测选择
Cloudflare | https://sydney.vcanbb.chat | 2018 ms | 检测选择
本站 | https://nbx.wbyai.top | 1553 ms | 检测当前
自定义 | 自定义聊天服务器链接

不用代理显示如下：
Bing 官方 | https://sydney.bing.com | 不可用 | 检测选择
-- | -- | -- | --
Cloudflare | https://sydney.vcanbb.chat | 1430 ms | 检测选择
本站 | https://nbx.wbyai.top | 604 ms | 检测当前

![6](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/118818378/a5eb6aa5-6f96-4d80-8731-cdf42630d483)

刚刚刷新了几下显示 本站 不可用，再刷新以后就彻底连不上了
![7](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/118818378/aa09bc55-986c-4f82-b87d-461f6f955692)

**Comment by bullkq** [comment]
![8](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/118818378/8639b306-afd3-42ec-83ae-f3326c3a061f)
重新部署了一遍，还是提示有问题，但是手机用移动4g可以使用，wifi不行

**Comment by lw1290537863** [comment]
你们是怎么搭建成功的，为什么我总是失败

**Comment by bullkq** [comment]
> 你们是怎么搭建成功的，为什么我总是失败

按照置顶那个部署提示，用宝塔面板，亚马逊免费vps，我折腾了快三天才搞定，完全是it老白，主要是太需要用这个newbing了，给儿子学英语用的，指定词库范围内造句，特别给力

**Comment by Harry-zklcdc** [comment]
你的站点没有问题，如有问题尝试清除所有数据

按 F12 然后
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/e12450cd-b102-43fa-840c-603e11165b66)

**Comment by luckyEason** [comment]
zero trust官方客户端貌似现在用不了bing
