### ISSUE TITLE
[Bug] 🐛 

### ISSUE THREAD

**Issue by ningguoxu** [Harry-zklcdc/go-proxy-bingai#53]
### Describe the bug

聊天记录不能点击，不能查看聊天记录

### Steps to reproduce

用Vercel部署后

### Expected behavior

聊天记录可以查看

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by Harry-zklcdc** [comment]
我这没有这种问题，请提供浏览器等信息

**Comment by ningguoxu** [comment]
哦，好了，换成Chrome浏览器就可以了
