### ISSUE TITLE
最近这个项目一直出现问题，推荐另外一个项目。

### ISSUE THREAD

**Issue by Xqh-Cxy** [Harry-zklcdc/go-proxy-bingai#55]
免费可用链接：https://bing.github1s.tk/
GitHub：https://github.com/weaigc/bingo/

**Comment by luckyEason** [comment]
试过了，个人认为UI比较差，并且功能暂时少，bug还多

**Comment by Xqh-Cxy** [comment]
> 试过了，个人认为UI比较差，并且功能暂时少，bug还多

起码能用

**Comment by luckyEason** [comment]
手机上有bug，会报错，而且go-proxy-bingai没有问题，只要用vps配置好聊天服务器，就不会有问题

**Comment by Harry-zklcdc** [comment]
我已经尽我所能去修不能用的问题了，本质上都是一样，
我做的就是想要能用**更少的配置**去使用，就目前来说，仅需填两个Cookie，而且这两个Cookie都是在不需要魔法的情况下就可以获得，我整这个就是为了折腾
