### ISSUE TITLE
[Bug] 🐛 电脑端无法正常使用

### ISSUE THREAD

**Issue by liubanlaobanzhang** [Harry-zklcdc/go-proxy-bingai#56]
### 电脑端持续报错：Sorry, looks like your network settings are preventing access to this feature.

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/83630926/f688c247-2ef8-4186-bafe-791c473f529d)
1.两条要填的 Cookie 全部已经填上，平板端可以正常使用，但是电脑端依然报错……
<br><br>
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/83630926/76d173e1-e43f-43cf-b067-c5daccd36582)
2.但如果我在F12里面调为手机模式，也可以正常用了……
<br><br>
![9cf101b68ad5fc6a3c297005e1555ac](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/83630926/ae372f53-f20f-4f0b-b0ee-3403bdb0cdd9)
3.如果我在平板端开电脑模式，也不能正常用了
<br><br>

> PS：因为没钱买域名，所以用的 `Zeabur` 部署……和这个会有关系吗？（Zeabur 只支持 Dockfile 部署）

## Steps to reproduce

使用电脑端访问在 `Zeabur` 部署的 go-proxy-bingai 项目

## Expected behavior

电脑端正常使用

## Versions

电脑端：
- OS: Windows 11 Insider Preview Build 23506
- Browser & Version: Edge 116.0.1938.36 (正式版本) beta (64 位) 
- GoProxiBing Version: 1.10.2

平板端：
- 设备: DBY-W09 (HUAWEI MatePad 11 2021)
- OS: HarmonyOS 3.0.0.301
- Browser & Version: 华为浏览器 14.0.0.322
- GoProxiBing Version: 1.10.2

**Comment by ccodingfundddd** [comment]
腾讯有10块钱的域名，https://www.dynadot.com/  这个网站可以免费申请1年域名。

**Comment by Harry-zklcdc** [comment]
需要更多信息，我这边全部正常

把你的电脑浏览器、手机浏览器、平板浏览器版本都提供一下

**Comment by liubanlaobanzhang** [comment]
没提到手机啊（
电脑是 Edge 116.0.1938.36 (正式版本) beta (64 位)
平板是 华为浏览器 14.0.0.322

**Comment by liubanlaobanzhang** [comment]
在原作者那里找到一个issue:
adams549659584/go-proxy-bingai#362

**Comment by liubanlaobanzhang** [comment]
我的 `Zeabur` 链接在https://laobanzhang-bing.zeabur.app

**Comment by Harry-zklcdc** [comment]
> 我的 `Zeabur` 链接在https://laobanzhang-bing.zeabur.app

怀疑被封IP了

**Comment by Harry-zklcdc** [comment]
> 呃啊？不好意思没太听懂 是我被封了还是 Zeabur 被封了 问题是同一设备（无论是电脑还是平板） 用电脑UA就用不了 用手机UA就用得了🤔

Zeabur 被封了，改UA也没用，我这两个都连不上

**Comment by liubanlaobanzhang** [comment]
好吧 我再找找别的部署平台 谢谢大佬啦
