### ISSUE TITLE
[Bug] 🐛 KievRPSSecAuth参数找不到

### ISSUE THREAD

**Issue by Xqh-Cxy** [Harry-zklcdc/go-proxy-bingai#57]
### Describe the bug

KievRPSSecAuth参数在cookie中找不到

### Steps to reproduce

设置>KievRPSSecAuth

### Expected behavior

能够找到该参数

### Versions

- OS: iPadOS17 Beta 2
- Browser & Version: Safari Latest
- GoProxiBing Version: Latest

### Additional context

使用的是作者提供的链接

**Comment by Stonewalling** [comment]
> ### Describe the bug
> KievRPSSecAuth参数在cookie中找不到
> 
> ### Steps to reproduce
> 设置>KievRPSSecAuth
> 
> ### Expected behavior
> 能够找到该参数
> 
> ### Screenshots
> _No response_
> 
> ### Versions
> * OS: iPadOS17 Beta 2
> * Browser & Version: Safari Latest
> * GoProxiBing Version: Latest
> 
> ### Additional context
> 使用的是作者提供的链接

你筛选下，这个字段是有的

**Comment by Harry-zklcdc** [comment]
退出，重新登陆就有了
