### ISSUE TITLE
必应更新UI了

### ISSUE THREAD

**Issue by ccodingfundddd** [Harry-zklcdc/go-proxy-bingai#59]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/139052477/e8da5d0d-efc7-4826-8135-0d270b724363)

**Comment by Harry-zklcdc** [comment]
是的，但是似乎又撤回了，我现在回到旧的UI了

**Comment by ccodingfundddd** [comment]
赞赞赞赞赞赞赞赞赞赞赞

**Comment by Xqh-Cxy** [comment]
> 已完成，明天上传代码 ![image](https://usercontent.githubfast.com/user-images/21104213/257543882-36abda1e-ae89-43d2-868c-8e391b6c09fa.png)

这是你的电脑还是服务器

**Comment by Harry-zklcdc** [comment]
已更新
Commit: fb5f6a3ad72c6fd8c9fe5b1b1b5ef56b81383cdf
Release: https://github.com/Harry-zklcdc/go-proxy-bingai/releases/tag/v.1.11.0
