### ISSUE TITLE
增加docker部署的方式

### ISSUE THREAD

**Issue by tutianyu101** [Harry-zklcdc/go-proxy-bingai#6]
docker run -d -p 8080:8080 --name go-proxy-bingai --restart=unless-stopped Harry-zklcdc/go-proxy-bingai
找不到目标镜像。。

**Comment by tutianyu101** [comment]
@Harry-zklcdc

**Comment by tutianyu101** [comment]
docker对我这种小白太友好了。。求大佬加上

**Comment by Harry-zklcdc** [comment]
明天加上部署方式，挂载一下二进制文件就行

**Comment by Nothingness-Void** [comment]
> docker对我这种小白太友好了。。求大佬加上
我自己打包了一份镜像传dockerhub了

这是我自己用的docker-compose文件给你参考一下https://github.com/adams549659584/go-proxy-bingai/issues/361#issuecomment-1642403899

**Comment by Harry-zklcdc** [comment]
已更新 `docker-compose.yml` 的部署方式 [docker/docker-compose.yml](https://github.com/Harry-zklcdc/go-proxy-bingai/blob/master/docker/docker-compose.yml)

或直接执行下面的命令
~~~bash
# 注意编译好的二进制文件 (linux-amd64) 需要在当前执行命令的文件夹中，并赋予可执行权限 (`chmod +x go-proxy-bingai`)

# 运行容器 监听8080 端口
docker run -v $PWD/go-proxy-bingai:/app/go-proxy-bingai -d -p 8080:8080 --name go-proxy-bingai --restart=always adams549659584/go-proxy-bingai

# 配置 socks 环境变量
docker run -e Go_Proxy_BingAI_SOCKS_URL=192.168.0.88:1070 -e Go_Proxy_BingAI_SOCKS_USER=xxx -e Go_Proxy_BingAI_SOCKS_PWD=xxx -d -v $PWD/go-proxy-bingai:/app/go-proxy-bingai -p 8080:8080 --name go-proxy-bingai --restart=always adams549659584/go-proxy-bingai
~~~

**Comment by Nothingness-Void** [comment]
> > > docker对我这种小白太友好了。。求大佬加上
> > > 我自己打包了一份镜像传dockerhub了
> > 
> > 
> > 这是我自己用的docker-compose文件给你参考一下[adams549659584#361 (comment)](https://github.com/adams549659584/go-proxy-bingai/issues/361#issuecomment-1642403899) 不过镜像是昨天没有语音版本的
> 
> 完蛋看不懂。。。我需要镜像市场的那种。。

这是docker-compose啊。。是直接用的docker hub的镜像啊

**Comment by skyfly2000** [comment]
> 已更新 `docker-compose.yml` 的部署方式 [docker/docker-compose.yml](https://github.com/Harry-zklcdc/go-proxy-bingai/blob/master/docker/docker-compose.yml)
> 
> 或直接执行下面的命令
> 
> ```shell
> # 注意编译好的二进制文件 (linux-amd64) 需要在当前执行命令的文件夹中，并赋予可执行权限 (`chmod +x go-proxy-bingai`)
> 
> # 运行容器 监听8080 端口
> docker run -v $PWD/go-proxy-bingai:/app/go-proxy-bingai -d -p 8080:8080 --name go-proxy-bingai --restart=always adams549659584/go-proxy-bingai
> 
> # 配置 socks 环境变量
> docker run -e Go_Proxy_BingAI_SOCKS_URL=192.168.0.88:1070 -e Go_Proxy_BingAI_SOCKS_USER=xxx -e Go_Proxy_BingAI_SOCKS_PWD=xxx -d -v $PWD/go-proxy-bingai:/app/go-proxy-bingai -p 8080:8080 --name go-proxy-bingai --restart=always adams549659584/go-proxy-bingai
> ```

输出：docker run -v $PWD/go-proxy-bingai:/app/go-proxy-bingai -d -p 8080:8080 --name go-proxy-bingai --restart=always adams549659584/go-proxy-bingai
bd0df19dfaf171939fc5beda11801a4c45ab8522d0d5491e93f7b2482f2649b5
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/root/go-proxy-bingai" to rootfs at "/app/go-proxy-bingai": mount /root/go-proxy-bingai:/app/go-proxy-bingai (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
小白，请大佬帮助

**Comment by Harry-zklcdc** [comment]
> 输出：docker run -v $PWD/go-proxy-bingai:/app/go-proxy-bingai -d -p 8080:8080 --name go-proxy-bingai --restart=always adams549659584/go-proxy-bingai bd0df19dfaf171939fc5beda11801a4c45ab8522d0d5491e93f7b2482f2649b5 docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/root/go-proxy-bingai" to rootfs at "/app/go-proxy-bingai": mount /root/go-proxy-bingai:/app/go-proxy-bingai (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type. 小白，请大佬帮助

你的二进制文件没放倒那个文件夹

> 注意编译好的二进制文件 (linux-amd64) 需要在当前执行命令的文件夹中，并赋予可执行权限 (`chmod +x go-proxy-bingai`)

**Comment by skyfly2000** [comment]
部署笔记，适合和我一样啥也不懂的新手小白
#查看当前正在运行的容器（老版本）
docker ps -a
#命令停止要删除的容器
docker stop XXX
#删除容器
docker container rm  XXX
#赋予文件夹权限可读写可执行
chmod +x go-proxy-bingai
#创建可读写可执行文件夹（首次）
mkdir -m 777 go-proxy-bingai
#进入文件夹
cd go-proxy-bingai
#下载已增加图像识别二进制压缩文件
wget https://github.com/Harry-zklcdc/go-proxy-bingai/releases/download/v1.9.1/go-proxy-bingai-linux-amd64.tar.gz
#解压二进制文件
tar -xzvf go-proxy-bingai-linux-amd64.tar.gz
#确保docker正常，docker挂载二进制文件
docker run -v $PWD/go-proxy-bingai:/app/go-proxy-bingai -d -p 8080:8080 --name go-proxy-bingai --restart=always adams549659584/go-proxy-bingai

**Comment by bullkq** [comment]
> ```shell
> # 注意编译好的二进制文件 (linux-amd64) 需要在当前执行命令的文件夹中，并赋予可执行权限 (`chmod +x go-proxy-bingai`)
> 
> # 运行容器
> ```

这个 - USER_KievRPSSecAuth=xxx xxx需要替换为我们查到的值吗

**Comment by bullkq** [comment]
> 已更新 `docker-compose.yml` 的部署方式 [docker/docker-compose.yml](https://github.com/Harry-zklcdc/go-proxy-bingai/blob/master/docker/docker-compose.yml)
> 
> 或直接执行下面的命令
> 
> ```shell
> # 注意编译好的二进制文件 (linux-amd64) 需要在当前执行命令的文件夹中，并赋予可执行权限 (`chmod +x go-proxy-bingai`)
> 
> # 运行容器 监听8080 端口
> docker run -v $PWD/go-proxy-bingai:/app/go-proxy-bingai -d -p 8080:8080 --name go-proxy-bingai --restart=always adams549659584/go-proxy-bingai
> 
> # 配置 socks 环境变量
> docker run -e Go_Proxy_BingAI_SOCKS_URL=192.1


> 已更新 `docker-compose.yml` 的部署方式 [docker/docker-compose.yml](https://github.com/Harry-zklcdc/go-proxy-bingai/blob/master/docker/docker-compose.yml)
> 
> 或直接执行下面的命令
> 
> ```shell
> # 注意编译好的二进制文件 (linux-amd64) 需要在当前执行命令的文件夹中，并赋予可执行权限 (`chmod +x go-proxy-bingai`)
> 
> # 运行容器 监听8080 端口
> docker run -v $PWD/go-proxy-bingai:/app/go-proxy-bingai -d -p 8080:8080 --name go-proxy-bingai --restart=always adams549659584/go-proxy-bingai
> 
> # 配置 socks 环境变量
> docker run -e Go_Proxy_BingAI_SOCKS_URL=**_192.168.0.88:1070_** -e Go_Proxy_BingAI_SOCKS_USER=**_xxx_** -e Go_Proxy_BingAI_SOCKS_PWD=**_xxx_** -d -v $PWD/go-proxy-bingai:/app/go-proxy-bingai -p 8080:8080 --name go-proxy-bingai --restart=always **_adams549659584_**/go-proxy-bingai
> ```

68.0.88:1070 -e Go_Proxy_BingAI_SOCKS_USER=xxx -e Go_Proxy_BingAI_SOCKS_PWD=xxx -d -v $PWD/go-proxy-bingai:/app/go-proxy-bingai -p 8080:8080 --name go-proxy-bingai --restart=always adams549659584/go-proxy-bingai
> ```

请问这里的这几个参数需要修改吗？docker run -e Go_Proxy_BingAI_SOCKS_URL=**_192.168.0.88:1070_** -e Go_Proxy_BingAI_SOCKS_USER=**_xxx_** -e Go_Proxy_BingAI_SOCKS_PWD=**_xxx_** -d -v $PWD/go-proxy-bingai:/app/go-proxy-bingai -p 8080:8080 --name go-proxy-bingai --restart=always **_adams549659584_**/go-proxy-bingai

**Comment by high-player** [comment]
> 部署笔记，适合和我一样啥也不懂的新手小白 #查看当前正在运行的容器（老版本） docker ps -a #命令停止要删除的容器 docker stop XXX #删除容器 docker container rm XXX #赋予文件夹权限可读写可执行 chmod +x go-proxy-bingai #创建可读写可执行文件夹（首次） mkdir -m 777 go-proxy-bingai #进入文件夹 cd go-proxy-bingai #下载已增加图像识别二进制压缩文件 wget https://github.com/Harry-zklcdc/go-proxy-bingai/releases/download/v1.9.1/go-proxy-bingai-linux-amd64.tar.gz #解压二进制文件 tar -xzvf go-proxy-bingai-linux-amd64.tar.gz #确保docker正常，docker挂载二进制文件 docker run -v $PWD/go-proxy-bingai:/app/go-proxy-bingai -d -p 8080:8080 --name go-proxy-bingai --restart=always adams549659584/go-proxy-bingai

我也是小白，为啥我按照你的详细步骤部署完了还是1.8.7版本呀

**Comment by Nothingness-Void** [comment]
> > 部署笔记，适合和我一样啥也不懂的新手小白 #查看当前正在运行的容器（老版本） docker ps -a #命令停止要删除的容器 docker stop XXX #删除容器 docker container rm XXX #赋予文件夹权限可读写可执行 chmod +x go-proxy-bingai #创建可读写可执行文件夹（首次） mkdir -m 777 go-proxy-bingai #进入文件夹 cd go-proxy-bingai #下载已增加图像识别二进制压缩文件 wget https://github.com/Harry-zklcdc/go-proxy-bingai/releases/download/v1.9.1/go-proxy-bingai-linux-amd64.tar.gz #解压二进制文件 tar -xzvf go-proxy-bingai-linux-amd64.tar.gz #确保docker正常，docker挂载二进制文件 docker run -v $PWD/go-proxy-bingai:/app/go-proxy-bingai -d -p 8080:8080 --name go-proxy-bingai --restart=always adams549659584/go-proxy-bingai
> 
> 我也是小白，为啥我按照你的详细步骤部署完了还是1.8.7版本呀

你下的是大佬新发的二进制文件吗

**Comment by skyfly2000** [comment]
> > 部署笔记，适合和我一样啥也不懂的新手小白 #查看当前正在运行的容器（老版本） docker ps -a #命令停止要删除的容器 docker stop XXX #删除容器 docker container rm XXX #赋予文件夹权限可读写可执行 chmod +x go-proxy-bingai #创建可读写可执行文件夹（首次） mkdir -m 777 go-proxy-bingai #进入文件夹 cd go-proxy-bingai #下载已增加图像识别二进制压缩文件 wget https://github.com/Harry-zklcdc/go-proxy-bingai/releases/download/v1.9.1/go-proxy-bingai-linux-amd64.tar.gz #解压二进制文件 tar -xzvf go-proxy-bingai-linux-amd64.tar.gz #确保docker正常，docker挂载二进制文件 docker run -v $PWD/go-proxy-bingai:/app/go-proxy-bingai -d -p 8080:8080 --name go-proxy-bingai --restart=always adams549659584/go-proxy-bingai
> 
> 我也是小白，为啥我按照你的详细步骤部署完了还是1.8.7版本呀

你没下载Fork的二进制文件……
最新的版本 1.95，Fork地:https://github.com/Harry-zklcdc/go-proxy-bingai

**Comment by skyfly2000** [comment]
> > 部署笔记，适合和我一样啥也不懂的新手小白 #查看当前正在运行的容器（老版本） docker ps -a #命令停止要删除的容器 docker stop XXX #删除容器 docker container rm XXX #赋予文件夹权限可读写可执行 chmod +x go-proxy-bingai #创建可读写可执行文件夹（首次） mkdir -m 777 go-proxy-bingai #进入文件夹 cd go-proxy-bingai #下载已增加图像识别二进制压缩文件 wget https://github.com/Harry-zklcdc/go-proxy-bingai/releases/download/v1.9.1/go-proxy-bingai-linux-amd64.tar.gz #解压二进制文件 tar -xzvf go-proxy-bingai-linux-amd64.tar.gz #确保docker正常，docker挂载二进制文件 docker run -v $PWD/go-proxy-bingai:/app/go-proxy-bingai -d -p 8080:8080 --name go-proxy-bingai --restart=always adams549659584/go-proxy-bingai
> 
> 我也是小白，为啥我按照你的详细步骤部署完了还是1.8.7版本呀

2023.7.31海外服务器，利用Docker部署、宝塔面板反代小白教程
#最新版本1.95，最新Fork仓库地址:https://github.com/Harry-zklcdc/go-proxy-bingai
#确保VPS没有被微软Ban，目前数据所知，Railway、Vercel、Render和腾讯云海外VPS都已经被封禁，Cloudflare的聊天服务器也被ban
#vps安装宝塔面板
#根据提示宝塔内安装相关插件和Nginx
#宝塔安装Docker
#宝塔 网站 添加站点 添加解析好的域名
#宝塔 网站 SSL 点击Let's Encrypt申请证书 选择强制https 
#宝塔 网站 反向代理(vps地址:http://xxx:8080/)
#ssh连接vps
#下载1.95版二进制文件（替换最新文件地址）
wget https://github.com/Harry-zklcdc/go-proxy-bingai/releases/download/v1.9.5/go-proxy-bingai-linux-amd64.tar.gz
#解压二进制文件
tar -xzvf go-proxy-bingai-linux-amd64.tar.gz
#挂载二进制文件
docker run -e USER_KievRPSSecAuth=XXXXXXX -v $PWD/go-proxy-bingai:/app/go-proxy-bingai -d -p 8080:8080 --name go-proxy-bingai --restart=always adams549659584/go-proxy-bingai
#赋予go-proxy-bingai文件夹权限555
chmod +x go-proxy-bingai
OK，部署完毕
升级版本只需要宝塔内Docker删除容器，重复ssh下载二进制文件、解压、挂载、赋予权限即可

**Comment by high-player** [comment]
> > > 部署笔记，适合和我一样啥也不懂的新手小白 #查看当前正在运行的容器（老版本） docker ps -a #命令停止要删除的容器 docker stop XXX #删除容器 docker container rm XXX #赋予文件夹权限可读写可执行 chmod +x go-proxy-bingai #创建可读写可执行文件夹（首次） mkdir -m 777 go-proxy-bingai #进入文件夹 cd go-proxy-bingai #下载已增加图像识别二进制压缩文件 wget https://github.com/Harry-zklcdc/go-proxy-bingai/releases/download/v1.9.1/go-proxy-bingai-linux-amd64.tar.gz #解压二进制文件 tar -xzvf go-proxy-bingai-linux-amd64.tar.gz #确保docker正常，docker挂载二进制文件 docker run -v $PWD/go-proxy-bingai:/app/go-proxy-bingai -d -p 8080:8080 --name go-proxy-bingai --restart=always adams549659584/go-proxy-bingai
> > 
> > 
> > 我也是小白，为啥我按照你的详细步骤部署完了还是1.8.7版本呀
> 
> 你下的是大佬新发的二进制文件吗

下载了，没有注意$PWD，导致没有挂上，现在已解决。

**Comment by high-player** [comment]
> > > 部署笔记，适合和我一样啥也不懂的新手小白 #查看当前正在运行的容器（老版本） docker ps -a #命令停止要删除的容器 docker stop XXX #删除容器 docker container rm XXX #赋予文件夹权限可读写可执行 chmod +x go-proxy-bingai #创建可读写可执行文件夹（首次） mkdir -m 777 go-proxy-bingai #进入文件夹 cd go-proxy-bingai #下载已增加图像识别二进制压缩文件 wget https://github.com/Harry-zklcdc/go-proxy-bingai/releases/download/v1.9.1/go-proxy-bingai-linux-amd64.tar.gz #解压二进制文件 tar -xzvf go-proxy-bingai-linux-amd64.tar.gz #确保docker正常，docker挂载二进制文件 docker run -v $PWD/go-proxy-bingai:/app/go-proxy-bingai -d -p 8080:8080 --name go-proxy-bingai --restart=always adams549659584/go-proxy-bingai
> > 
> > 
> > 我也是小白，为啥我按照你的详细步骤部署完了还是1.8.7版本呀
> 
> 你没下载Fork的二进制文件…… 最新的版本 1.95，Fork地:https://github.com/Harry-zklcdc/go-proxy-bingai

下载了，没有注意$PWD，导致没有挂上，现在重新部署了一遍已经OK，但是目测我这个bandwagon的vps也被ban了。
