### ISSUE TITLE
okteto cloud的IP也被ban了吗？

### ISSUE THREAD

**Issue by Xqh-Cxy** [Harry-zklcdc/go-proxy-bingai#62]
我写的Dockerfile和docker-compose.yml：https://github.com/chixinyan/go-proxy-bingai-okteto.git

**Comment by Xqh-Cxy** [comment]
> _No description provided._

我的docker配置：https://github.com/chixinyan/go-proxy-bingai-okteto

**Comment by Xqh-Cxy** [comment]
> 我写的Dockerfile和docker-compose.yml：https://githubfast.com/chixinyan/go-proxy-bingai-okteto.git

具体截图：
![](https://s1.ax1x.com/2023/08/01/pPCJbkR.png)
<br>
![](https://s1.ax1x.com/2023/08/01/pPCJqt1.png)

**Comment by Harry-zklcdc** [comment]
看起来是的
