### ISSUE TITLE
[Bug] 🐛 一直提示“正在尝试重新连接...”

### ISSUE THREAD

**Issue by OptiJava** [Harry-zklcdc/go-proxy-bingai#63]
### Describe the bug

作者的网站`https://go-proxy-bingai.xiao-gy.tk`最近一直提示“正在尝试重新连接...”，`Token`和`KievRPSSecAuth`都填了，服务选择Cloudflare或本站都不行，开梯子也不行

### Steps to reproduce

进入`https://go-proxy-bingai.xiao-gy.tk`，填好`Token`和`KievRPSSecAuth`，然后发消息，就会提示“正在尝试重新连接...”，一键重置也不行

### Expected behavior

正常返回消息

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/106148777/f8940b13-075c-4358-afaa-45a559ca2be4)

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/106148777/021a4bfe-1592-4591-b5b4-7171a788d4da)

### Versions

- OS: Linux Kubuntu 23.04
- Browser & Version: Microsoft Edge 115.0.1901.188 (正式版本) (64 位) (for linux)
- GoProxiBing Version: v1.10.2

### Additional context

.

**Comment by Harry-zklcdc** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/81accb44-c297-4c5f-b19e-c6d7b8a4ad91)

**Comment by OptiJava** [comment]
可能是我的问题吧，我开着fastgithub进网站它提示正在尝试重新连接，关掉fastgithub没有任何代理他又提示无效域了
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/106148777/4ad712be-abd1-40ef-9901-b7325a10000b)
开着梯子也是qwq
开了梯子的话官方是正常的，只弹了一个cf人机验证

**Comment by OptiJava** [comment]
> ![image](https://user-images.githubusercontent.com/21104213/257518670-81accb44-c297-4c5f-b19e-c6d7b8a4ad91.png)

今天对话正常了，谢谢
