### ISSUE TITLE
[Bug] 我用中文问问题，它用英文回答我

### ISSUE THREAD

**Issue by sugar1688** [Harry-zklcdc/go-proxy-bingai#64]
### Describe the bug

![IMG_20230801_234933](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/134984318/64693966-9aa3-4291-8b9e-1bfa54629ad7)
![IMG_20230801_235540](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/134984318/7768dc69-7140-479d-a1f6-d9a60e95d132)

我用中文问问题，它用英文回答我 这是怎么回事呢?

### Steps to reproduce

不会用中文回答，是哪里错了

### Expected behavior

不会用中文回答，是哪里错了

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by Harry-zklcdc** [comment]
不知道，这个和我没关系😂

**Comment by YuenSzeHong** [comment]
> 不知道，这个和我没关系😂

感觉和那个turing的404有关
