### ISSUE TITLE
必须要用 VPN 吗？

### ISSUE THREAD

**Issue by Aoan2011** [Harry-zklcdc/go-proxy-bingai#66]
我看每次都提示无效域，是每过一段时间都要打开一次 VPN 吗？用的是作者的演示站点

**Comment by Harry-zklcdc** [comment]
非必须，演示站必须填那三个Cookie

**Comment by qinguoluo** [comment]
如果要使用VPN，再部署这个就没有意义了，直接登官方的网页不好吗？

**Comment by Aoan2011** [comment]
而且那个聊天输入框好像有点偏左了。mac 13 英寸

**Comment by Harry-zklcdc** [comment]
> 而且那个聊天输入框好像有点偏左了。mac 13 英寸

故意的，遵循原版
