### ISSUE TITLE
最新更新的v1.11.0中新增的_RwBf Cookie要在哪里填写？还是说无需人为操作、更新存储库即可？

### ISSUE THREAD

**Issue by FangZirui-E5** [Harry-zklcdc/go-proxy-bingai#67]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129593198/699f4a65-0642-4f64-a1ae-42e87fbd697b)

**Comment by ningguoxu** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/87106666/1e646a83-c406-4ada-a192-5291cddcda03)
部署后在设置里填

**Comment by Harry-zklcdc** [comment]
或者添加`USER_RwBf`环境变量

**Comment by FangZirui-E5** [comment]
我想了解一下这个cookie添加进来的作用是什么（不是很懂）
