### ISSUE TITLE
[Bug] 🐛 无法新开一个新主题

### ISSUE THREAD

**Issue by 111234567890** [Harry-zklcdc/go-proxy-bingai#68]
### Describe the bug

点新主题，回复的时候会提示：很抱歉，似乎发生错误

### Steps to reproduce

第一次打开网页，直接在问题框回复可以获得回应，但是如果我先点一下新主题，再发送回复就会提示：很抱歉，似乎发生错误

### Expected behavior

新主题可以点击么

### Versions

版本用的是最新的1.11.0

**Comment by Harry-zklcdc** [comment]
演示站呢？我这边没有这样的问题

**Comment by ilolita945** [comment]
> 演示站呢？我这边没有这样的问题

确实有这问题，非443端口，每次点击新主题不会创建一个新的会话ID

**Comment by Harry-zklcdc** [comment]
> 确实有这问题，非443端口，每次点击新主题不会生成一个新的会话ID，只能刷新浏览器页面

演示站也会吗？非443我没法解决，受限于 go-proxy-bingai 的实现方式，要解决只能另起炉灶了

**Comment by ilolita945** [comment]
> > 确实有这问题，非443端口，每次点击新主题不会生成一个新的会话ID，只能刷新浏览器页面
> 
> 演示站也会吗？非443我没法解决，受限于 go-proxy-bingai 的实现方式，要解决只能另起炉灶了

演示站也会   有时候不能生成新的会话

**Comment by Harry-zklcdc** [comment]
目前我还没遇到过，我这两天搞个在azure的演示站吧（轻虐，谢谢）

**Comment by ilolita945** [comment]
> 
![QQ截图20230802174741](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/49525838/cbc0b13d-43db-4982-afa4-7d5ed0f5c50b)
更新了最新版，控制台已经有新的会话ID了，但是红框这里的话 点击会报错，提问功能正常

**Comment by Harry-zklcdc** [comment]
> [QQ截图20230802174741](https://user-images.githubusercontent.com/49525838/257773793-cbc0b13d-43db-4982-afa4-7d5ed0f5c50b.png)
> 
> [QQ截图20230802174929](https://user-images.githubusercontent.com/49525838/257774366-fc5f6de0-ea01-4d10-95e5-e38e484b6430.png) [QQ截图20230802174915](https://user-images.githubusercontent.com/49525838/257774378-b3971be6-6b94-4adc-b760-1221c5f06f4b.png)
> 
> 更新了最新版，控制台已经有新的会话ID了，但是红框这里的话 点击会报错，提问功能正常

我这没这问题，可以点击，是演示站嘛？登录账号试试
提供一下浏览器信息

**Comment by ilolita945** [comment]
> > [QQ截图20230802174741](https://user-images.githubusercontent.com/49525838/257773793-cbc0b13d-43db-4982-afa4-7d5ed0f5c50b.png)
> > [QQ截图20230802174929](https://user-images.githubusercontent.com/49525838/257774366-fc5f6de0-ea01-4d10-95e5-e38e484b6430.png) [QQ截图20230802174915](https://user-images.githubusercontent.com/49525838/257774378-b3971be6-6b94-4adc-b760-1221c5f06f4b.png)
> > 更新了最新版，控制台已经有新的会话ID了，但是红框这里的话 点击会报错，提问功能正常
> 
> 我这没这问题，可以点击，是演示站嘛？登录账号试试 提供一下浏览器信息

不是演示站，我自己搭的，浏览器edge最新版

**Comment by ilolita945** [comment]
> > [QQ截图20230802174741](https://user-images.githubusercontent.com/49525838/257773793-cbc0b13d-43db-4982-afa4-7d5ed0f5c50b.png)
> > [QQ截图20230802174929](https://user-images.githubusercontent.com/49525838/257774366-fc5f6de0-ea01-4d10-95e5-e38e484b6430.png) [QQ截图20230802174915](https://user-images.githubusercontent.com/49525838/257774378-b3971be6-6b94-4adc-b760-1221c5f06f4b.png)
> > 更新了最新版，控制台已经有新的会话ID了，但是红框这里的话 点击会报错，提问功能正常
> 
> 我这没这问题，可以点击，是演示站嘛？登录账号试试 提供一下浏览器信息
![QQ截图20230802180055](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/49525838/50407835-e86e-4210-917d-82046a3dce5f)
上一个版本的话，这个位置点击功能正常

**Comment by Harry-zklcdc** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/6cf6e784-8127-4649-94c6-3aa9058083a4)

演示站没有问题，请检查自己的设置，或者你私发我 `zklcdc@qq.com` 你的网站我看看问题

**Comment by ilolita945** [comment]
> ![image](https://user-images.githubusercontent.com/21104213/257778295-6cf6e784-8127-4649-94c6-3aa9058083a4.png)
> 
> 演示站没有问题，请检查自己的设置，或者你私发我 `zklcdc@qq.com` 你的网站我看看问题

演示站没问题，大佬   已经QQ邮箱发你地址了

**Comment by ilolita945** [comment]
> ![image](https://user-images.githubusercontent.com/21104213/257778295-6cf6e784-8127-4649-94c6-3aa9058083a4.png)
> 
> 演示站没有问题，请检查自己的设置，或者你私发我 `zklcdc@qq.com` 你的网站我看看问题

我看了下演示站，首次使用会自动创建会话，但是我这边的话首次使用会提示创建会话失败，需要重置刷新才能有新的会话ID，我也不知道哪里配置有误  还望指点

**Comment by standee2023** [comment]
我用演示站，也填了相关的cookies,为什么还是提示“无效域。如果此问题仍然存在，请与站点管理员联系。”

**Comment by 111234567890** [comment]
我用演示站也会提示“无效域。如果此问题仍然存在，请与站点管理员联系。”，我自己搭建的站用的也是443.很正常的用A机器使用宝塔反代http+wss  B机器起的docker服务。新主题会创建不了，最近的活动那里也没法正常读取到。wss我只反代了/sydney/ChatHub这个地址

**Comment by 111234567890** [comment]
最近的活动那里也没法获取到最近的会话列表

**Comment by Harry-zklcdc** [comment]
尝试 Cloudflare Worker 部署一下？ 教程在这 #71

**Comment by Harry-zklcdc** [comment]
> 我用演示站也会提示“无效域。如果此问题仍然存在，请与站点管理员联系。”，我自己搭建的站用的也是443.很正常的用A机器使用宝塔反代http+wss B机器起的docker服务。新主题会创建不了，最近的活动那里也没法正常读取到。wss我只反代了/sydney/ChatHub这个地址

原因很多，包括但不限于

- 账号风险高；
- 服务器 IP 段风险高；

**Comment by Harry-zklcdc** [comment]
> 我用演示站，也填了相关的cookies,为什么还是提示“无效域。如果此问题仍然存在，请与站点管理员联系。”

现在还会嘛？得先在NewBing上正常提问一次

**Comment by standee2023** [comment]
已成功了，感谢。
另我怎么才能保持和你的库同步更新呢？你的版本好像又升级了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月3日(星期四) 下午4:42
收件人: ***@***.***&gt;; 
抄送: ***@***.******@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Harry-zklcdc/go-proxy-bingai] [Bug] 🐛 无法新开一个新主题 (Issue #68)





  
我用演示站，也填了相关的cookies,为什么还是提示“无效域。如果此问题仍然存在，请与站点管理员联系。”
  
现在还会嘛？得先在NewBing上正常提问一次

**Comment by SokWith** [comment]
> 已成功了，感谢。 另我怎么才能保持和你的库同步更新呢？你的版本好像又升级了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年8月3日(星期四) 下午4:42 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; ***@***.***&gt;; 主题: Re: [Harry-zklcdc/go-proxy-bingai] [Bug] 🐛 无法新开一个新主题 (Issue #68) 我用演示站，也填了相关的cookies,为什么还是提示“无效域。如果此问题仍然存在，请与站点管理员联系。” 现在还会嘛？得先在NewBing上正常提问一次 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

悄悄的告诉你，直接复制cf服务器配置，这样前端页面就完全使用的作者的了。作者的web目录更新了，你的cf服务器也就自动更新了。
为什么要自建cf服务器而不直接使用作者的？
1是cf workes的日访问量有限，就用自己的限额就好了。
2是使用自己的cookie植入，方便1键重置。
3是自己使用用量小不容易触发验证机制。
