### ISSUE TITLE
[Help] 🤔 最新版的镜像地址是什么？

### ISSUE THREAD

**Issue by 78design** [Harry-zklcdc/go-proxy-bingai#69]
### Describe the help wanted

最新版的镜像地址是什么？

### Steps to behave

最新版的镜像地址是什么？

### Expected behavior

最新版的镜像地址是什么？

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by Harry-zklcdc** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/b3d9face-9cad-4427-9d3f-3bfcfa862f70)
