### ISSUE TITLE
[Bug] 🐛 点击删除聊天记录，刷新页面后，聊天记录还在

### ISSUE THREAD

**Issue by s181462537** [Harry-zklcdc/go-proxy-bingai#70]
### Describe the bug

 点击删除聊天记录，刷新页面后，聊天记录还在

### Steps to reproduce

点击聊天记录右侧删除按键后，刷新页面

### Expected behavior

修复bug

### Versions

1.11.0

**Comment by Harry-zklcdc** [comment]
这个不是Bug，是代理的问题，代理的时间就就会这样
