### ISSUE TITLE
[Feature] 🌈 无后端, 完全 Cloudflare Worker 部署

### ISSUE THREAD

**Issue by Harry-zklcdc** [Harry-zklcdc/go-proxy-bingai#71]
经过一天研究，实现了完全 `Cloudflare Worker` 部署

Commit: 57d105d4ae60fc0af9a33e4e1314a491994c7af2

## 部署方式

核心代码 [worker.js](https://github.com/Harry-zklcdc/go-proxy-bingai/blob/master/cloudflare/worker.js)

具体部署 Cloudflare Workers 教程自行查询，大概如下

1. [注册 Cloudflare 账号](https://dash.cloudflare.com/sign-up)；
2. 创建 Worker 服务；
3. 复制 [worker.js](https://github.com/Harry-zklcdc/go-proxy-bingai/blob/master/cloudflare/worker.js) 全部代码，粘贴至创建的服务中；
4. 修改最上面的两个Cookie变量；
5. 保存并部署；
6. 触发器 中自定义访问域名。

## 已知问题

- 无法获取历史聊天记录

**Comment by Harry-zklcdc** [comment]
测试地址：[https://bingai-cfwk.xiao-gy.tk/web/#/](https://bingai-cfwk.xiao-gy.tk/web/#/)

注意：已删除共享Cookie代码，需要自行填入对应Cookie方可体验

**Comment by standee2023** [comment]
太棒了，等待更新

**Comment by s181462537** [comment]
已尝试，这个部署厉害！建议能不能再加点代码，_u值也写进去啊，想给身边人用，写进去就可以不用在外面输入_u值了

**Comment by Harry-zklcdc** [comment]
> 已尝试，这个部署厉害！建议能不能再加点代码，_u值也写进去啊，想给身边人用，写进去就可以不用在外面输入_u值了

改点代码就行了，仿照 `_RwBf` 的那个Cookie的写法就行

https://github.com/Harry-zklcdc/go-proxy-bingai/blob/57d105d4ae60fc0af9a33e4e1314a491994c7af2/cloudflare/worker.js#L3

https://github.com/Harry-zklcdc/go-proxy-bingai/blob/57d105d4ae60fc0af9a33e4e1314a491994c7af2/cloudflare/worker.js#L150-L152

**Comment by s181462537** [comment]
改了代码，果然就可以了，真棒！

**Comment by SokWith** [comment]
我觉得思路还可以继续打开，NewBingGoGo的插件版采用的是整个cookie拷贝进cf服务器的路子，只有不触发服务器ip锁(PS，悄悄的说一下，把转发ip地址池缩小到微软云IDC范围内，能大幅度规避ip锁)，基本上就可以保证cookie策略随微软的变化自动变化。
（可惜他放暑假后就没有跟随官方的api进行同步更新了。也幸好官方的核心api没有什么大变化，还能一直使用。）

**Comment by Harry-zklcdc** [comment]
> 我觉得思路还可以继续打开，NewBingGoGo的插件版采用的是整个cookie拷贝进cf服务器的路子，只有不触发服务器ip锁(PS，悄悄的说一下，把转发ip地址池缩小到微软云IDC范围内，能大幅度规避ip锁)，基本上就可以保证cookie策略随微软的变化自动变化。 （可惜他放暑假后就没有跟随官方的api进行同步更新了。也幸好官方的核心api没有什么大变化，还能一直使用。）

插件版在做了，为了实现edge侧边栏可以搜索页面的，不过估计要下个礼拜了，这个礼拜有其他的事情，手上还有一个大模型的项目在开发

**Comment by Xqh-Cxy** [comment]
> 经过一天研究，实现了完全 `Cloudflare Worker` 部署
> 
> Commit: [57d105d](https://githubfast.com/Harry-zklcdc/go-proxy-bingai/commit/57d105d4ae60fc0af9a33e4e1314a491994c7af2)
> 
> ## 部署方式
> 核心代码 [worker.js](https://githubfast.com/Harry-zklcdc/go-proxy-bingai/blob/master/cloudflare/worker.js)
> 
> 具体部署 Cloudflare Workers 教程自行查询，大概如下
> 
> 1. [注册 Cloudflare 账号](https://dash.cloudflare.com/sign-up)；
> 2. 创建 Worker 服务；
> 3. 复制 [worker.js](https://githubfast.com/Harry-zklcdc/go-proxy-bingai/blob/master/cloudflare/worker.js) 全部代码，粘贴至创建的服务中；
> 4. 修改最上面的两个Cookie变量；
> 5. 保存并部署；
> 6. 触发器 中自定义访问域名。
> 
> ## 已知问题
> * 无法获取历史聊天记录

什么原理啊，不是被ban IP了吗？

**Comment by SokWith** [comment]
> > 经过一天研究，实现了完全 `Cloudflare Worker` 部署
> > Commit: [57d105d](https://githubfast.com/Harry-zklcdc/go-proxy-bingai/commit/57d105d4ae60fc0af9a33e4e1314a491994c7af2)
> > ## 部署方式
> > 核心代码 [worker.js](https://githubfast.com/Harry-zklcdc/go-proxy-bingai/blob/master/cloudflare/worker.js)
> > 具体部署 Cloudflare Workers 教程自行查询，大概如下
> > 
> > 1. [注册 Cloudflare 账号](https://dash.cloudflare.com/sign-up)；
> > 2. 创建 Worker 服务；
> > 3. 复制 [worker.js](https://githubfast.com/Harry-zklcdc/go-proxy-bingai/blob/master/cloudflare/worker.js) 全部代码，粘贴至创建的服务中；
> > 4. 修改最上面的两个Cookie变量；
> > 5. 保存并部署；
> > 6. 触发器 中自定义访问域名。
> > 
> > ## 已知问题
> > 
> > * 无法获取历史聊天记录
> 
> 什么原理啊，不是被ban IP了吗？

测试服务器的ip是不是被ban了有个简单的方法，就是使用NewBingGoGo的插件版，魔法链接填服务器的网址，采用魔法聊天。确保你的ID没锁的情况下，显示服务器异常，则为ip锁了。
用cf的好处是，锁了ip不可怕，只要重置，一般几次后就可以后台自动更换了另一个ip。cf的地址池足够大，总会没有被锁的。

**Comment by SokWith** [comment]
按此方法新建的一个站点，跟踪一下存活情况：

https://cfwk.nbing.eu.org/

作者的测试站点是被多人访问，还是比较容易ip锁的，今晚已经被锁了1次了。

**Comment by SokWith** [comment]
> 按此方法新建的一个站点，跟踪一下存活情况：
> 
> https://cfwk.nbing.eu.org/
> 
> 作者的测试站点是被多人访问，还是比较容易ip锁的，今晚已经被锁了1次了。

我两个用cf做后端,前端分别在vercel和replit上的站点：
https://vercel.nbing.eu.org
https://replit.nbing.eu.org
今天一直正常。
但用这个纯cf的站点目前确实一直出现重新开始吧，但作为NewBingGoGo插件的魔法接入点又是可用的。觉得问题还是出在header的处理上。

**Comment by Harry-zklcdc** [comment]
> > 按此方法新建的一个站点，跟踪一下存活情况：

> 我两个用cf做后端,前端分别在vercel和replit上的站点： https://vercel.nbing.eu.org https://replit.nbing.eu.org 今天一直正常。 但用这个纯cf的站点目前确实一直出现重新开始吧，但作为NewBingGoGo插件的魔法接入点又是可用的。觉得问题还是出在header的处理上。

我明天在研究一下

**Comment by SokWith** [comment]
> > > 按此方法新建的一个站点，跟踪一下存活情况：
> 
> > 我两个用cf做后端,前端分别在vercel和replit上的站点： https://vercel.nbing.eu.org https://replit.nbing.eu.org 今天一直正常。 但用这个纯cf的站点目前确实一直出现重新开始吧，但作为NewBingGoGo插件的魔法接入点又是可用的。觉得问题还是出在header的处理上。
> 
> 我明天在研究一下

谢谢。我不会编码，帮不上什么忙，你辛苦了。

**Comment by Harry-zklcdc** [comment]
> 谢谢。我不会编码，帮不上什么忙，你辛苦了。

还是Cookie的问题，NewbingGoGo我研究了一下，他是直接拿的完整Cookie，所以没有那么容易触发验证，但是这样不安全
我这边有能让人机验证通过的方法，不过会卡在一直验证那边，在想办法解决

**Comment by jyuxkw** [comment]
部署完后，聊天出现：正在尝试连接，请稍候。  请问这个是什么问题？怎么解决

**Comment by Harry-zklcdc** [comment]
> 还是Cookie的问题，NewbingGoGo我研究了一下，他是直接拿的完整Cookie，所以没有那么容易触发验证，但是这样不安全 我这边有能让人机验证通过的方法，不过会卡在一直验证那边，在想办法解决

有个验证之后才有的Cookie，不过有效期就一天，我看看能不能直接在界面上能解决验证

**Comment by willggy** [comment]
CF把代码复制过去出现这种错误，绑定了域名
很抱歉，似乎出现错误。 让我们重新开始吧。

**Comment by SokWith** [comment]
> > > 按此方法新建的一个站点，跟踪一下存活情况：
> 
> > 我两个用cf做后端,前端分别在vercel和replit上的站点： https://vercel.nbing.eu.org https://replit.nbing.eu.org 今天一直正常。 但用这个纯cf的站点目前确实一直出现重新开始吧，但作为NewBingGoGo插件的魔法接入点又是可用的。觉得问题还是出在header的处理上。
> 
> 我明天在研究一下

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/64a55e67-9792-47c0-9100-964510dd06fe)
我似乎发现了我的replit可用而cfwk站点不可用的原因了。
网站1次打开时，在GET /turing/conversaton/create时是用的本机域名，而发起聊天时，却会再次GET这个会话，使用的是个体下来的官方的核心api，但是这个核心api的js文件里面，是写死了GET路径为www.bing.com
解决的办法可以是替换官方核心API，这也是NewBingGoGo因为是重写的核心api，所以一直可用的原因之一吧

**Comment by Harry-zklcdc** [comment]
> [image](https://user-images.githubusercontent.com/129967025/258298284-64a55e67-9792-47c0-9100-964510dd06fe.png) 我似乎发现了我的replit可用而cfwk站点不可用的原因了。 网站1次打开时，在GET /turing/conversaton/create时是用的本机域名，而发起聊天时，却会再次GET这个会话，使用的是个体下来的官方的核心api，但是这个核心api的js文件里面，是写死了GET路径为www.bing.com 解决的办法可以是替换官方核心API，这也是NewBingGoGo因为是重写的核心api，所以一直可用的原因之一吧

并不是，这个项目也有对应的模块
https://github.com/Harry-zklcdc/go-proxy-bingai/blob/298bfd0b2310ae40aa19475ea30bc903b937fdf6/common/proxy.go#L294-L317

**主要问题还是在Cookie上**

NewBingGoGo是直接获取你电脑上的所有Cookie给Bing发过去请求创建对话
对应 `/turning/conversation/create` 这个接口，然后会返回对应的 `ConversationID` 和 `ConversationSign`

我抓了官方的数据包，在对话的时候的没有发送Cookie的，那就可以判断Bing是通过 `ConversationID` 来确定是否需要人机验证

所以我现在的思路是直接触发验证的时候，直接过验证，但是目前不知道问题出在哪，一直验证通过，但是会重复验证

**Comment by SokWith** [comment]
仅针对这个cf纯web版，与部署版2次get的方式是不同的。
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/1e26d13e-f49a-48ac-b44e-48ccfb7ec999)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/27a0caab-a4a4-43b2-9097-78424faf86f3)

**Comment by Harry-zklcdc** [comment]
> 仅针对这个cf纯web版，与部署版2次get的方式是不同的。 [image](https://user-images.githubusercontent.com/129967025/258340841-1e26d13e-f49a-48ac-b44e-48ccfb7ec999.png) [image](https://user-images.githubusercontent.com/129967025/258340971-27a0caab-a4a4-43b2-9097-78424faf86f3.png)
> 
> 2次get是由上面那个核心js直接发起的，所以失败了

嗯？你看看演示站？演示站没这个问题吧

**Comment by SokWith** [comment]
> > 仅针对这个cf纯web版，与部署版2次get的方式是不同的。 [image](https://user-images.githubusercontent.com/129967025/258340841-1e26d13e-f49a-48ac-b44e-48ccfb7ec999.png) [image](https://user-images.githubusercontent.com/129967025/258340971-27a0caab-a4a4-43b2-9097-78424faf86f3.png)
> > 2次get是由上面那个核心js直接发起的，所以失败了
> 
> 嗯？你看看演示站？演示站没这个问题吧

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129967025/590fc48d-5c95-4634-a88d-6667aed9a279)
一样的baiox表现

**Comment by Harry-zklcdc** [comment]
> [image](https://user-images.githubusercontent.com/129967025/258360614-590fc48d-5c95-4634-a88d-6667aed9a279.png) 一样的baiox表现

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/a726a724-e2f7-4ae9-bb05-c7ffe07252a0)

emm

**Comment by ohmyivan** [comment]
不能用，输入了那两个变量然后部署的，都是正在尝试连接，请稍候··

**Comment by Harry-zklcdc** [comment]
> 不能用，输入了那两个变量然后部署的，都是正在尝试连接，请稍候··

这个部署方式Bug还很多呢，只是一个新特性

**Comment by SokWith** [comment]
> > > > 按此方法新建的一个站点，跟踪一下存活情况：
> > 
> > 
> > > 我两个用cf做后端,前端分别在vercel和replit上的站点： https://vercel.nbing.eu.org https://replit.nbing.eu.org 今天一直正常。 但用这个纯cf的站点目前确实一直出现重新开始吧，但作为NewBingGoGo插件的魔法接入点又是可用的。觉得问题还是出在header的处理上。
> > 
> > 
> > 我明天在研究一下
> 
> ![image](https://user-images.githubusercontent.com/129967025/258298284-64a55e67-9792-47c0-9100-964510dd06fe.png) 我似乎发现了我的replit可用而cfwk站点不可用的原因了。 网站1次打开时，在GET /turing/conversaton/create时是用的本机域名，而发起聊天时，却会再次GET这个会话，使用的是个体下来的官方的核心api，但是这个核心api的js文件里面，是写死了GET路径为www.bing.com 解决的办法可以是替换官方核心API，这也是NewBingGoGo因为是重写的核心api，所以一直可用的原因之一吧

按此思路救回了我的纯cf服务器 https://cfwk.nbing.eu.org，内置ID，开箱即用。

我另外两个测试站点 ：
https://vercel.nbing.eu.org/
https://replit.nbing.eu.org/
今天表现也很稳定。
只是，感谢各位参与测试的朋友，接下来一周我要离开一会儿，由于内置ID一般要每天科学验证1次，都没条件验证了，可能会停摆一阵了。

**Comment by cakexxx** [comment]
> > > > > 按此方法新建的一个站点，跟踪一下存活情况：
> > > 
> > > 
> > > > 我两个用cf做后端,前端分别在vercel和replit上的站点： https://vercel.nbing.eu.org https://replit.nbing.eu.org 今天一直正常。 但用这个纯cf的站点目前确实一直出现重新开始吧，但作为NewBingGoGo插件的魔法接入点又是可用的。觉得问题还是出在header的处理上。
> > > 
> > > 
> > > 我明天在研究一下
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/129967025/258298284-64a55e67-9792-47c0-9100-964510dd06fe.png) 我似乎发现了我的replit可用而cfwk站点不可用的原因了。 网站1次打开时，在GET /turing/conversaton/create时是用的本机域名，而发起聊天时，却会再次GET这个会话，使用的是个体下来的官方的核心api，但是这个核心api的js文件里面，是写死了GET路径为www.bing.com 解决的办法可以是替换官方核心API，这也是NewBingGoGo因为是重写的核心api，所以一直可用的原因之一吧
> 
> 按此思路救回了我的纯cf服务器 https://cfwk.nbing.eu.org 内置ID，开箱即用。
> 
> 我另外两个测试站点 ： https://vercel.nbing.eu.org/ https://replit.nbing.eu.org/ 今天表现也很稳定。 只是，感谢各位参与测试的朋友，接下来一周我要离开一会儿，由于内置ID一般要每天科学验证1次，都没条件验证了，可能会停摆一阵了。



> > 不能用，输入了那两个变量然后部署的，都是正在尝试连接，请稍候··
> 
> 这个部署方式Bug还很多呢，只是一个新特性

怎么验证的呀，我总是不行，要么显示这个
<img width="392" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/49086951/d0a0f7cf-da7b-4e44-9520-3090b4c66c0c">
要么显示这个
<img width="436" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/49086951/11ab0669-3514-4f22-9db9-6360d413285f">

**Comment by SokWith** [comment]
> > > > > > 按此方法新建的一个站点，跟踪一下存活情况：
> > > > 
> > > > 
> > > > > 我两个用cf做后端，前端分别在vercel和replit上的站点： https://vercel.nbing.eu.org https://replit.nbing.eu.org 今天一直正常。但用这个纯cf的站点目前确实一直出现重新开始吧，但作为NewBingGoGo插件的魔法接入点又是可用的。觉得问题还是出在header的处理上。
> > > > 
> > > > 
> > > > 我明天在研究一下
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/129967025/258298284-64a55e67-9792-47c0-9100-964510dd06fe.png)我似乎发现了我的replit可用而cfwk站点不可用的原因了。网站1次打开时，在GET /turing/conversaton/create时是用的本机域名，而发起聊天时，却会再次GET这个会话，使用的是个体下来的官方的核心api，但是这个核心api的js文件里面，是写死了GET路径为 www.bing.com 解决的办法可以是替换官方核心API，这也是NewBingGoGo因为是重写的核心api，所以一直可用的原因之一吧
> > 
> > 
> > 按此思路救回了我的纯cf服务器 https://cfwk.nbing.eu.org 内置ID，开箱即用。
> > 我另外两个测试站点 ： [https://vercel.nbing.eu.org/ https://replit.nbing.eu.org/](https://vercel.nbing.eu.org/)  今天表现也很稳定。只是，感谢各位参与测试的朋友，接下来一周我要离开一会儿，由于内置ID一般要每天科学验证1次，都没条件验证了，可能会停摆一阵了。
> 
> > > 不能用，输入了那两个变量然后部署的，都是正在尝试连接，请稍候··
> > 
> > 
> > 这个部署方式Bug还很多呢，只是一个新特性
> 
> 怎么验证的呀，我总是不行，要么显示这个 要么显示这个 <img alt="image" width="392" src="https://user-images.githubusercontent.com/49086951/258568123-d0a0f7cf-da7b-4e44-9520-3090b4c66c0c.png"> <img alt="image" width="436" src="https://user-images.githubusercontent.com/49086951/258568135-11ab0669-3514-4f22-9db9-6360d413285f.png">

vercel   replit   cfwk.nbing.eu.org  已更新内置ID，可以继续使用了。

**Comment by xuehaosheng** [comment]
修改最上面的两个Cookie变量
请问这个具体是怎么操作

**Comment by YuenSzeHong** [comment]
话说我NAS部署docker无法存取历史记录正常吗？

**Comment by SokWith** [comment]
加上随机cookie后，可以实现无ID(K\U\R值)聊天。

 const randcookie = randomString(99);
    if (!cookie.includes('_U=')) {
      cookies += '; _U=' + randcookie;
    }


function randomChar() {
  var chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  var index = Math.floor(Math.random() * chars.length);
  return chars[index];
}

function randomString(n) {
  var str = "";
  for (var i = 0; i < n; i++) {
    str += randomChar();
  }
  return str;
}

随机字符串函数是bingAI给我的。

测试站点： https://cfree.nbing.eu.org

已知问题，每次重置或者刷新页面后，不能直接聊天，需要先点击首页上的推荐聊天项目，得到输出后可以刷新新主题后就正常了。

**Comment by Harry-zklcdc** [comment]
> 加上随机cookie后，可以实现无ID(K\U\R值)聊天。
> 
> const randcookie = randomString(99); if (!cookie.includes('_U=')) { cookies += '; _U=' + randcookie; }
> 
> function randomChar() { var chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"; var index = Math.floor(Math.random() * chars.length); return chars[index]; }
> 
> function randomString(n) { var str = ""; for (var i = 0; i < n; i++) { str += randomChar(); } return str; }
> 
> 随机字符串函数是bingAI给我的。
> 
> 测试站点： https://cfree.nbing.eu.org
> 
> 已知问题，每次重置或者刷新页面后，不能直接聊天，需要先点击首页上的推荐聊天项目，得到输出后可以刷新新主题后就正常了。 [image](https://user-images.githubusercontent.com/129967025/261350601-d7e149d7-c3b4-4b15-b526-d5e9286ab41f.png)

我测试一下

**Comment by SokWith** [comment]
> > 加上随机cookie后，可以实现无ID(K\U\R值)聊天。
> > const randcookie = randomString(99); if (!cookie.includes('_U=')) { cookies += '; _U=' + randcookie; }
> > function randomChar() { var chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"; var index = Math.floor(Math.random() * chars.length); return chars[index]; }
> > function randomString(n) { var str = ""; for (var i = 0; i < n; i++) { str += randomChar(); } return str; }
> > 随机字符串函数是bingAI给我的。
> > 测试站点： https://cfree.nbing.eu.org
> > 已知问题，每次重置或者刷新页面后，不能直接聊天，需要先点击首页上的推荐聊天项目，得到输出后可以刷新新主题后就正常了。 [image](https://user-images.githubusercontent.com/129967025/261350601-d7e149d7-c3b4-4b15-b526-d5e9286ab41f.png)
> 
> 我测试一下

这个微软的漏洞居然没有存活过24小时，今天上午两个无cookie测试站点 hfwk cfree都一直无效域了，也就是假cookie拿到的create无效了。

**Comment by Harry-zklcdc** [comment]
> 这个微软的漏洞居然没有存活过24小时，今天上午两个无cookie测试站点 hfwk cfree都一直无效域了，也就是假cookie拿到的create无效了。

你去看看那个Github Action 部署的项目吧，目前来说 Github Action + Cloudflare Tunnel 是最优解，不过就是存活时间的问题了。只有6搁小时，还有就是容易被封号

**Comment by YuenSzeHong** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/40477634/2fee6fdc-d3eb-407a-93d2-e941bcca5821)
worker部署，转圈圈

**Comment by SokWith** [comment]
> > [image](https://user-images.githubusercontent.com/129967025/258298284-64a55e67-9792-47c0-9100-964510dd06fe.png) 我似乎发现了我的replit可用而cfwk站点不可用的原因了。 网站1次打开时，在GET /turing/conversaton/create时是用的本机域名，而发起聊天时，却会再次GET这个会话，使用的是个体下来的官方的核心api，但是这个核心api的js文件里面，是写死了GET路径为www.bing.com 解决的办法可以是替换官方核心API，这也是NewBingGoGo因为是重写的核心api，所以一直可用的原因之一吧
> 
> 并不是，这个项目也有对应的模块
> 
> https://github.com/Harry-zklcdc/go-proxy-bingai/blob/298bfd0b2310ae40aa19475ea30bc903b937fdf6/common/proxy.go#L294-L317
> 
> **主要问题还是在Cookie还有IP上**
> 
> NewBingGoGo是直接获取你电脑上的所有Cookie给Bing发过去请求创建对话 对应 `/turning/conversation/create` 这个接口，然后会返回对应的 `ConversationID` 和 `ConversationSign`
> 
> 我抓了官方的数据包，在对话的时候的没有发送Cookie的，那就可以判断Bing是通过 `ConversationID` 来确定是否需要人机验证
> 
> 如果需要验证，`/sydney/ChatHub` 这个WebSocket接口会返回
> 
> ```json
> "result": {
>     "value": "CaptchaChallenge",
>     "message": "User needs to solve CAPTCHA to continue.",
>     "error": "User needs to solve CAPTCHA to continue.",
>     "serviceVersion": "20230803.43"
> }
> ```
> 
> 然后就会触发验证
> 
> 而且可预见的，获取的 `ConversationID` 如果包含 `BingProdUnAuthenticatedUsers`，那极大概率会触发人机验证
> 
> 所以我现在的思路是直接触发验证的时候，直接过验证，但是目前不知道问题出在哪，一直验证通过，但是会重复验证
> 
> PS：NewBingGoGo的验证码解决方案还是旧版的，也就是Newbing自身的验证码，而不是Cloudflare的验证，但是那个接口现在已经404了，也就是说，饶过验证目前还没有人解决了

拜托检查一下，纯cf部署的时候，这个proxy.go的代理代码似乎并没有被加载运行，造成加载的核心API始终是走www.bing.com路径从而create失败

**Comment by SokWith** [comment]
https://github.com/Harry-zklcdc/go-proxy-bingai/issues/71#issuecomment-1683348084
发现伪bug的原因了，原来是自己人为制造的。
由于纯cf部署的核心api没有运行proxu.go的域名转发，我直接把核心api里面的域名替换了，造成所有的纯cf部署都采用了替换的域名进行二次create句柄。由于这个替换的域名也是cf里面的，所以没有出现跨域错误（如果换成其他非cf域名，也会跨域错误的）。但是，cf的ip目前是不能直接无cookie聊天的，我那个替换的域名里面内置了ID，所以，内置ID生效其他站点就可以使用，内置ID无效域其他站点就跟着无效域了。
目前看来随机cookie的唯一作用是能让create不会返回空了，如何利用好返回的conversationId又是一个问题。还是得分析为什么真实的微软云的无账户conversationId可以使用，而转发ip出来的conversationId则需要验证？

**Comment by Harry-zklcdc** [comment]
> [#71 (comment)](https://github.com/Harry-zklcdc/go-proxy-bingai/issues/71#issuecomment-1683348084) 发现伪bug的原因了，原来是自己人为制造的。 由于纯cf部署的核心api没有运行proxu.go的域名转发，我直接把核心api里面的域名替换了，造成所有的纯cf部署都采用了替换的域名进行二次create句柄。由于这个替换的域名也是cf里面的，所以没有出现跨域错误（如果换成其他非cf域名，也会跨域错误的）。但是，cf的ip目前是不能直接无cookie聊天的，我那个替换的域名里面内置了ID，所以，内置ID生效其他站点就可以使用，内置ID无效域其他站点就跟着无效域了。 目前看来随机cookie的唯一作用是能让create不会返回空了，如何利用好返回的conversationId又是一个问题。还是得分析为什么真实的微软云的无账户conversationId可以使用，而转发ip出来的conversationId则需要验证？

在想新方法了，现在打算把这几个文件直接保存在本地，然后实时替换，这样的话会更方便修改，但是这样的话，通过whistle过人机验证的方法就会失效，盲猜巨硬针对JS完整新有检查，用于检查是否能通过人机验证

**Comment by Harry-zklcdc** [comment]
已完整实现, Commit: be01292b590a53992c0defe77dbf7b046d2ce643, 感谢 @goss1p 的贡献
