### ISSUE TITLE
[Bug] 🐛 最近版本界面的UI在手机上不适配哦。

### ISSUE THREAD

**Issue by ccodingfundddd** [Harry-zklcdc/go-proxy-bingai#72]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/139052477/8a222a22-80f7-4bca-94cc-2199fab5153e)

**Comment by cutexiaoguigui** [comment]
我觉得电脑可以留着，手机就不要了

**Comment by shenmidigua** [comment]
必应官方又改回原版了，反复横跳哦

**Comment by skyfly2000** [comment]
> 考虑如何适配，直接不要这一部分了？

我认为不需要这个部分，直接去除，极简的扁平化设计才是最好的。如果想有类似prompt教程，可以有个链接prompt教程/格式

**Comment by Harry-zklcdc** [comment]
已解决

**Comment by IT-HaoGe** [comment]
![06048789fe72a91e4a0238a27589e4d](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/130531658/57d1a8e7-b25c-4926-8f34-1b6bfd1b07d0)
我倒是觉得去除后有点空，改了点样式后变成这样

**Comment by Harry-zklcdc** [comment]
> [06048789fe72a91e4a0238a27589e4d](https://user-images.githubusercontent.com/130531658/258055535-57d1a8e7-b25c-4926-8f34-1b6bfd1b07d0.jpg) 我倒是觉得去除后有点空，改了点样式后变成这样

也可以，欢迎PR
