### ISSUE TITLE
[Help] 🤔已按要求填写三个cookie，并在newbing上聊天一次，但在演示站还是用不了，求大神指导，感激不尽

### ISSUE THREAD

**Issue by kuugaaaaa** [Harry-zklcdc/go-proxy-bingai#73]
### Describe the help wanted

如题，我填写完三个cookie后演示站的历史记录已经成功同步我在newbing的聊天记录了，但在演示站再提问还是提示无效域，该如何解决，我不会部署，只能用演示站，求各位大神指导一下，感激不尽。

### Steps to behave

1. 在https://www.bing.com/登录账号，获取三个cookie值填入演示站
2. 在https://www.bing.com/的chat提问一次
3. 在演示站提问

### Expected behavior

如题，我填写完三个cookie后演示站的历史记录已经成功同步我在newbing的聊天记录了，但在演示站再提问还是提示无效域，该如何解决，我不会部署，只能用演示站，求各位大神指导一下，感激不尽。

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by kuugaaaaa** [comment]
我想上传一下截图的，但是页面提示报错（Something went really wrong, and we can’t process that file. 
），试了几次都失败

**Comment by shenmidigua** [comment]
https://bing.fishhome.link/web/#/
试试这个 邀请码：fishhome666

**Comment by kuugaaaaa** [comment]
> https://bing.fishhome.link/web/#/ 试试这个 邀请码：fishhome666

还是不行，也是提示无效域

**Comment by kuugaaaaa** [comment]
> https://bing.fishhome.link/web/#/ 试试这个 邀请码：fishhome666

你的这个切换成亚马逊的话不用填cookie都可以用了，但是用默认的服务器（本站那个）填了cookie也还是同样提示无效域，所以说是聊天服务器的问题咯？

**Comment by Harry-zklcdc** [comment]
按一下f12，看一下控制台的console输出

**Comment by kuugaaaaa** [comment]
截图没办法上传，只能复制文字了哈：
1：Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.

2：POST   https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/b/flow/ov1/1429851908:1690982956:DV7sDtDqdl8j2oWoAMpZywrB8A4-u8wdQwBjc_yF8xU/7f0703ae5c02f9fd/2c5036b4868889e   403

3：Uncaught TurnstileError: [Cloudflare Turnstile] invalid_domain.
    at f (api.js:1:5092)
    at X (api.js:1:16905)

就上面三个错误，轮流重复出现。

**Comment by kuugaaaaa** [comment]
> 按一下f12，看一下控制台的console输出

截图没办法上传，只能复制文字了哈：
1：Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.

2：POST https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/b/flow/ov1/1429851908:1690982956:DV7sDtDqdl8j2oWoAMpZywrB8A4-u8wdQwBjc_yF8xU/7f0703ae5c02f9fd/2c5036b4868889e 403

3：Uncaught TurnstileError: [Cloudflare Turnstile] invalid_domain.
at f (api.js:1:5092)
at X (api.js:1:16905)

就上面三个错误，轮流重复出现。

**Comment by kuugaaaaa** [comment]
> > 按一下f12，看一下控制台的console输出
> 
> 截图没办法上传，只能复制文字了哈： 1：Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
> 
> 2：POST https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/b/flow/ov1/1429851908:1690982956:DV7sDtDqdl8j2oWoAMpZywrB8A4-u8wdQwBjc_yF8xU/7f0703ae5c02f9fd/2c5036b4868889e 403
> 
> 3：Uncaught TurnstileError: [Cloudflare Turnstile] invalid_domain. at f (api.js:1:5092) at X (api.js:1:16905)
> 
> 就上面三个错误，轮流重复出现。

加多一个：
GET https://challenges.cloudflare.com/turnstile/v0/g/74ac0d47/api.js net::ERR_QUIC_PROTOCOL_ERROR 200

**Comment by bullkq** [comment]
![0](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/118818378/4203ed02-1c52-46d2-800d-592a44e6fba3)

**Comment by Harry-zklcdc** [comment]
> [0](https://user-images.githubusercontent.com/118818378/257873982-4203ed02-1c52-46d2-800d-592a44e6fba3.jpg)

这个还有bug，我还在修，先用 vercel的演示站

**Comment by kuugaaaaa** [comment]
> 

请问vercel的演示站的网址是？

**Comment by kuugaaaaa** [comment]
> > [0](http://user-images.githubusercontent.com/118818378/257873982-4203ed02-1c52-46d2-800d-592a44e6fba3.jpg)
> 
> 这个还有bug，我还在修，先用 vercel的演示站

请问vercel演示站的网址是？

**Comment by Harry-zklcdc** [comment]
> 请问vercel演示站的网址是？

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/331d6eeb-0b61-4fa5-9f61-63bc39b8a2c3)

**Comment by Harry-zklcdc** [comment]
> 加多一个： GET https://challenges.cloudflare.com/turnstile/v0/g/74ac0d47/api.js net::ERR_QUIC_PROTOCOL_ERROR 200

你这个感觉有问题，都没有创建对话的请求

**Comment by kuugaaaaa** [comment]
> > 请问vercel演示站的网址是？
> 
> ![image](http://user-images.githubusercontent.com/21104213/258033837-331d6eeb-0b61-4fa5-9f61-63bc39b8a2c3.png)

我用的就是这个演示站呀【捂脸】

**Comment by kuugaaaaa** [comment]
已正常使用
