### ISSUE TITLE
[Feature] 🌈 能在后台设置UI界面中聊天记录的显示或关闭的默认状态

### ISSUE THREAD

**Issue by FangZirui-E5** [Harry-zklcdc/go-proxy-bingai#74]
### Describe the problem related to the feature request

由于我采用了共享cookie的方式来使我的站点能够正常使用，但是这样会导致聊天记录也会被共享；且在手机端的UI中没有删除聊天记录的地方，这使得我的朋友在用手机使用了我的站点之后聊天记录无法及时清除。

### Describe the solution you'd like

设计一个能用来更改聊天记录是显示还是关闭的默认值的环境变量

### Describe alternatives you've considered

直接修改源码使聊天记录默认不显示

**Comment by sugar1688** [comment]
> 这个你自行修改前端代码就行

同需要，但是不会整啊，没有编程基础，只会ctrl+c/v，希望能添加进去或给出详细修改方法。

**Comment by FangZirui-E5** [comment]
我也不会（就帮个忙吧）

**Comment by Harry-zklcdc** [comment]
之后有空搞吧，最近先把功能更新了，在解决这些小问题

**Comment by FangZirui-E5** [comment]
好的，谢谢

**Comment by FangZirui-E5** [comment]
现在不需要cookie共享了，就不需要这个功能了
