### ISSUE TITLE
[Feature] 🌈 是否可以移除Google tag还有百度统计的代码

### ISSUE THREAD

**Issue by renqabs** [Harry-zklcdc/go-proxy-bingai#75]
### Describe the problem related to the feature request

移除index.html中Google tag还有百度统计的代码
  
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-MM5J5X8QQC"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag () { dataLayer.push(arguments); }
    gtag('js', new Date());

    gtag('config', 'G-MM5J5X8QQC');
  </script>
  
  <script>
    var _hmt = _hmt || [];
    (function () {
      var hm = document.createElement("script");
      hm.src = "https://hm.baidu.com/hm.js?299c614daa53fbcede70f2d22df0a31b";
      var s = document.getElementsByTagName("script")[0];
      s.parentNode.insertBefore(hm, s);
    })();
  </script>

### Describe the solution you'd like

移除Google tag还有百度统计

**Comment by Harry-zklcdc** [comment]
暂时没有计划，不知道原作者有啥用处

**Comment by renqabs** [comment]
我这边adguard会直接拦截这两个统计的js文件，拦截后也可以正常用，应该是追踪用户的，之前作者的issue里有人提过
