### ISSUE TITLE
[Bug] 🐛 使用非标准443端口  用户登陆后就无法使用

### ISSUE THREAD

**Issue by ImissLC** [Harry-zklcdc/go-proxy-bingai#76]
### Describe the bug

目前的环境是docker部署，然后nginx反代，但是nginx反代最终使用了非标端口8443。

不使用cookie登陆时可以使用聊天。但是登录cookie之后只能使用生成图像和撰写文章，直接聊天会一直卡在尝试连接。

### Steps to reproduce

使用非标准端口443登陆后即可复现，对话会一直尝试连接。

通过浏览器工具可以看到，使用cookie登陆后，一直请求标准443端口，无法连接至后端。（如附上截图）

### Expected behavior

希望能够修正该问题，会自动根据nginx反代回传的端口号修改请求URL。

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/39521028/a2e358ff-16c0-4df2-af81-87a2e2a6b79b)

### Versions

- GoProxiBing Version: 1.11.0

**Comment by ImissLC** [comment]
补充：截图是原作者旧的，但是更新到作者dalao最新版现象依旧。

**Comment by Harry-zklcdc** [comment]
没办法，newbing限制要求443，
这个我尝试吧，只能尝试解决，不能保证一定解决

**Comment by ImissLC** [comment]
> 没办法，newbing限制要求443， 这个我尝试吧，只能尝试解决，不能保证一定解决

感谢大佬，但是我尝试过newbinggogo-web这个项目，使用非标准端口反代就是正常的，是否可以参考一下？

**Comment by Xqh-Cxy** [comment]
> ### Describe the bug
> 目前的环境是docker部署，然后nginx反代，但是nginx反代最终使用了非标端口8443。
> 
> 不使用cookie登陆时可以使用聊天。但是登录cookie之后只能使用生成图像和撰写文章，直接聊天会一直卡在尝试连接。
> 
> ### Steps to reproduce
> 使用非标准端口443登陆后即可复现，对话会一直尝试连接。
> 
> 通过浏览器工具可以看到，使用cookie登陆后，一直请求标准443端口，无法连接至后端。（如附上截图）
> 
> ### Expected behavior
> 希望能够修正该问题，会自动根据nginx反代回传的端口号修改请求URL。
> 
> ### Screenshots
> ![image](https://usercontent.githubfast.com/user-images/39521028/258005460-a2e358ff-16c0-4df2-af81-87a2e2a6b79b.png)
> 
> ### Versions
> * GoProxiBing Version: 1.11.0
> 
> ### Additional context
> _No response_

使用nginx配置基于域名的虚拟主机，域名可以去搜免费二级域名注册（或购买顶级域名），然后解析到你的服务器，nginx可以配置：
server {
listen 443 ssl
server_name <解析的域名>
……
}

**Comment by Harry-zklcdc** [comment]
尝试 Cloudflare Worker 部署一下？ 教程在这 #71
