### ISSUE TITLE
[Bug] 🐛 多了一个 404错误

### ISSUE THREAD

**Issue by ilanks** [Harry-zklcdc/go-proxy-bingai#78]
### Describe the bug

多了一个 404错误，原作者的没这个错误，使页面打开卡顿
https://go-proxy-bingai.xiao-gy.tk/turing/api/v1/zeroinputstarter?lang=zh&region=*&tone=Creative

### Steps to reproduce

https://go-proxy-bingai.xiao-gy.tk/  访问首页看网络请求就可以发现

### Expected behavior

去掉这个错误请求

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by Harry-zklcdc** [comment]
这个似乎是Bing那边的问题，升级新界面之后多了这个，有概率请求成功
