### ISSUE TITLE
作者能否修改一下，或许请教一下怎么修改代码，我自己来弄。如果这是服务器端部署的时候，就自带_U值，我发现我这边只要给了_U值就能用，就不存在网络问题了。

### ISSUE THREAD

**Issue by ccodingfundddd** [Harry-zklcdc/go-proxy-bingai#8]
作者能否修改一下，或许请教一下怎么修改代码，我自己来弄。如果服务器端部署的时候，就自带_U值，我发现我这边只要给了_U值就能用，就不存在网络问题了。

**Comment by yunskyline** [comment]
这你就不认真学习了，以前就自带环境变量，可以设置多个值。并随机使用。那么问题来了，哪里去找那么多用户cookie!//
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/47986399/bb766488-0217-420d-95ad-3e3b41ad80f5)

**Comment by fenger7** [comment]
我这里是随便填个都管用，不需要找那么多用户token,可能是我香港这台服务器的数据中心没有被ban吧。
