### ISSUE TITLE
[Feature] 🌈 bing官方增加了一个gpt-4模式的开关，不知能否跟进

### ISSUE THREAD

**Issue by Nothingness-Void** [Harry-zklcdc/go-proxy-bingai#81]
### Describe the problem related to the feature request

![Screenshot_2023-08-03-17-54-33-820_com microsoft bing](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/55913486/2af805e1-aba7-42bd-9820-08ee56183cc3)

### Describe the solution you'd like

同步官方开关（虽然不知道干啥用的）

**Comment by Nothingness-Void** [comment]
反应了一下，好像是这个开关把原来的 创造 平衡 精准 三个模式给替换掉了 开了GPT-4就是原来的创造（粉色）关掉之后就是平衡（蓝色）且平衡的回答确实是3.5水平

**Comment by Harry-zklcdc** [comment]
那就不更新了，这个按钮很早我就在newbing的配置文件里面发现了，不过不知道怎么启用而已

**Comment by Nothingness-Void** [comment]
> 那就不更新了，这个按钮很早我就在newbing的配置文件里面发现了，不过不知道怎么启用而已

我刚才又玩了玩官方的，发现官方是在设置里面加了个按钮
![Screenshot_2023-08-03-20-21-45-663_com microsoft bing](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/55913486/d44095e3-d1b1-470c-bde9-0e18b0a90631)
![Screenshot_2023-08-03-20-21-47-989_com microsoft bing](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/55913486/788d8f8d-5659-44e5-86a4-0440de2d1586)
可以在三中模式 和GPT-4开关之间切换

**Comment by ningguoxu** [comment]
觉得这个功能挺好的

**Comment by Harry-zklcdc** [comment]
明天我看看，或者下周了，肝累了

**Comment by Harry-zklcdc** [comment]
找不到按钮，电脑版好像还没有

**Comment by shui063** [comment]
> 缺少按钮，电脑版好像还没有

确实

**Comment by 2531178480** [comment]
但是现在官方bing（电脑版）默认就只有3.5了
它答不对4的问题

**Comment by Harry-zklcdc** [comment]
已更新支持
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/a6aeafe0-1cc7-4d2c-9483-e2dd7f74a2cb)

同时 API 服务支持 GPT4-Turbo 模型了
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/bcd3cc52-2ec7-4dcb-ac2f-9f2eedf97964)
