### ISSUE TITLE
[Bug] 🐛 在有历史记录的情况下聊天者的消息框未与输入框对齐

### ISSUE THREAD

**Issue by FangZirui-E5** [Harry-zklcdc/go-proxy-bingai#82]
### Describe the bug

这个问题虽然不是很重要，但是如果能修复就更好了
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129593198/a8842a41-d41f-4ba7-b4ae-5ba428ebb62c)

### Steps to reproduce

把聊天记录给显示出来就能重现了

### Expected behavior

让消息框与输入框对齐

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129593198/a693397c-08b4-473b-9363-dbec35f28ccf)

### Versions

- OS: Windows 10
- Browser & Version: 哪个浏览器都一样
- GoProxiBing Version: 1.11.2

**Comment by Harry-zklcdc** [comment]
这个是屏幕问题😂，看看newbing官网会不会

**Comment by FangZirui-E5** [comment]
我印象里是官网上是正常的😥

**Comment by FangZirui-E5** [comment]
Proton VPN现在连不上，我也没法去验证（我换个时间点再试试）

**Comment by FangZirui-E5** [comment]
在官网上是正常的
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129593198/717c3c36-e4f5-4a9f-a6ac-f8622891f59d)

**Comment by FangZirui-E5** [comment]
@Harry-zklcdc

**Comment by FangZirui-E5** [comment]
好的

**Comment by Harry-zklcdc** [comment]
最新版已解决
