### ISSUE TITLE
[Help] 🤔 

### ISSUE THREAD

**Issue by Skadli** [Harry-zklcdc/go-proxy-bingai#84]
### Describe the help wanted

docker部署的js文件全部加载失败

### Steps to behave

重新在服务器上构建镜像后，运行后一直卡在加载界面

### Expected behavior

希望找到哪里出错了，以及如何修改

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/74969782/40bb58fc-2c2e-4913-8ae4-b8283d829893)

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by Nothingness-Void** [comment]
你是不是每套tls啊 http访问就会卡一直加载

**Comment by Skadli** [comment]
> 你是不是每套tls啊 http访问就会卡一直加载

我本地运行也是一直卡在加载这里
