### ISSUE TITLE
[Feature] 🎉 必应聊天企业版已可用，本项目能否支持

### ISSUE THREAD

**Issue by luckyEason** [Harry-zklcdc/go-proxy-bingai#86]
https://learn.microsoft.com/zh-cn/bing-chat-enterprise/manage

**Comment by Harry-zklcdc** [comment]
有没有什么新特性？

**Comment by luckyEason** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/109937362/940b5496-d30e-4c9d-b36a-e3be417ddc40)
暂时不知道，貌似是今天刚出的

**Comment by luckyEason** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/109937362/fdd0e6f1-3c0f-42dc-8e55-da49945bad45)
他自己回答的

**Comment by skyfly2000** [comment]
<img width="815" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/57341809/ff2b18fc-c38e-43e0-83dc-6c46c2aece5c">
估计会比较难，条件太苛刻了

**Comment by luckyEason** [comment]
> <img width="815" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/57341809/ff2b18fc-c38e-43e0-83dc-6c46c2aece5c">
> 
> 估计会比较难，条件太苛刻了

我有号，E5的

**Comment by Harry-zklcdc** [comment]
我自己有账号，有需要再看看，谢谢

**Comment by Harry-zklcdc** [comment]
![f927367d513240217c2a35589d416e2a](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/8adbd0ed-1469-4925-8ba8-458694d1c42c)

不过可能要对应的Cookie

**Comment by luckyEason** [comment]
嗯

**Comment by Harry-zklcdc** [comment]
已支持
