### ISSUE TITLE
经测试1.11.2版本在已经被微软ban 的服务器上可以正常使用

### ISSUE THREAD

**Issue by skyfly2000** [Harry-zklcdc/go-proxy-bingai#87]
大佬，你真牛！经测试docker部署1.11.2版本部署时加入KievRPSSecAuth值，在已经被微软ban 的服务器上可以正常使用了！感谢大佬的努力付出。

现在又不行了提示：“Sorry, looks like your network settings are preventing access to this feature.”，微软抽风……好了6个小时

**Comment by ccodingfundddd** [comment]
只加入了 KievRPSSecAuth，_U有加吗？加的话是真实的_U吗？还是伪造的。

**Comment by skyfly2000** [comment]
> 只加入了 KievRPSSecAuth，_U有加吗？加的话是真实的_U吗？还是伪造的。

看不懂话么？部署时加入 KievRPSSecAuth值，打开页面加_U和_RwBf可以看到历史对话记录。
还伪造？你不会说话就憋说，小人之心？还是你受的教育有问题？有必要伪造么？伪造的意义是什么？

**Comment by MkStoler** [comment]
> > 只加入了 KievRPSSecAuth，_U有加吗？加的话是真实的_U吗？还是伪造的。
> 
> 看不懂话么？部署时加入 KievRPSSecAuth值，打开页面加_U和_RwBf可以看到历史对话记录。 还伪造？你不会说话就憋说，小人之心？还是你受的教育有问题？有必要伪造么？伪造的意义是什么？

他说的是不对，但是咱们没必要爆粗口。
你说Render是不是把我IP封了？我发现我部署啥也不行，gogo和go-proxy都不行。

**Comment by MkStoler** [comment]
伪造不了，伪造了微软能看出来

**Comment by skyfly2000** [comment]
> > > 只加入了 KievRPSSecAuth，_U有加吗？加的话是真实的_U吗？还是伪造的。
> > 
> > 
> > 看不懂话么？部署时加入 KievRPSSecAuth值，打开页面加_U和_RwBf可以看到历史对话记录。 还伪造？你不会说话就憋说，小人之心？还是你受的教育有问题？有必要伪造么？伪造的意义是什么？
> 
> 他说的是不对，但是咱们没必要爆粗口。 你说Render是不是把我IP封了？我发现我部署啥也不行，gogo和go-proxy都不行。

我测试过腾讯云和 Google 云，发现都被微软ban了，提示连接被阻止；今天早上更新了 1.11.2 发现腾讯云新加坡已经可以用了。docker部署有教程，看这里 #46 。如果还不行一定是哪里做的不对。

**Comment by leikuman** [comment]
> > > > 只加入了 KievRPSSecAuth，_U有加吗？加的话是真实的_U吗？还是伪造的。
> > > 
> > > 
> > > 看不懂话么？部署时加入 KievRPSSecAuth值，打开页面加_U和_RwBf可以看到历史对话记录。 还伪造？你不会说话就憋说，小人之心？还是你受的教育有问题？有必要伪造么？伪造的意义是什么？
> > 
> > 
> > 他说的是不对，但是咱们没必要爆粗口。 你说Render是不是把我IP封了？我发现我部署啥也不行，gogo和go-proxy都不行。
> 
> 我测试过腾讯云和 Google 云，发现都被微软ban了，提示连接被阻止；今天早上更新了 1.11.2 发现腾讯云新加坡已经可以用了。docker部署有教程，看这里 #46 。如果还不行一定是哪里做的不对。

谢谢,测试本地添加变量后可以使用了.

**Comment by Harry-zklcdc** [comment]
> 大佬，你真牛！经测试docker部署1.11.2版本部署时加入KievRPSSecAuth值，在已经被微软ban 的服务器上可以正常使用了！感谢大佬的努力付出。

这个1.9.3的时候就更新了吧，现在多了一个 `_RwBf` 的 Cookie，今天又发现了另一个关键Cookie，但是那个Cookie不用魔法没法获得，在思考解决办法

**Comment by skyfly2000** [comment]
> > 大佬，你真牛！经测试docker部署1.11.2版本部署时加入KievRPSSecAuth值，在已经被微软ban 的服务器上可以正常使用了！感谢大佬的努力付出。
> 
> 这个1.9.3的时候就更新了吧，现在多了一个 `_RwBf` 的 Cookie，今天又发现了另一个关键Cookie，但是那个Cookie不用魔法没法获得，在思考解决办法

昨天还不行，1.11.1 以前的版本一直提示：“Sorry, looks like your network settings are preventing access to this feature.”
如果不是版本的问题就是微软放松了对服务器的管制

**Comment by Harry-zklcdc** [comment]
> 昨天还不行，1.11.1 以前的版本一直提示：“Sorry, looks like your network settings are preventing access to this feature.” 如果不是版本的问题就是微软放松了对服务器的管制

都有可能，但是这几天似乎加强了对**账号风险的等级**的检测，IP的权重稍微下降了一些，主要是行为检测的权重高了一些（比如频繁换IP什么的）

**Comment by skyfly2000** [comment]
> > 昨天还不行，1.11.1 以前的版本一直提示：“Sorry, looks like your network settings are preventing access to this feature.” 如果不是版本的问题就是微软放松了对服务器的管制
> 
> 都有可能，但是这几天似乎加强了对**账号风险的等级**的检测，IP的权重稍微下降了一些，主要是行为检测的权重高了一些（比如频繁换IP什么的）

现在又不行了提示：“Sorry, looks like your network settings are preventing access to this feature.”，微软抽风……好了6个小时

**Comment by ccodingfundddd** [comment]
我把3个参数，全部设置对，被Ban的服务器活过来了。

**Comment by ningguoxu** [comment]
> 

大佬，可以试试把账号登录在https://learn.microsoft.com/en-us/training/modules/implement-common-integration-features-finance-ops/10-exercise-1获取Cookie，这是微软的虚拟机，IP在国外。

**Comment by ningguoxu** [comment]
需要魔法才能获取的那个cookie可以访问https://learn.microsoft.com/en-us/training/modules/implement-common-integration-features-finance-ops/10-exercise-1登录账号，这个是微软的虚拟机，IP在国外。

**Comment by ningguoxu** [comment]
需要魔法才能获取的那个cookie可以访问https://learn.microsoft.com/en-us/training/modules/implement-common-integration-features-finance-ops/10-exercise-1 登录账号，这个是微软的虚拟机，IP在国外。

**Comment by chengdada925** [comment]
> 需要魔法才能获取的那个cookie可以访问https://learn.microsoft.com/en-us/training/modules/implement-common-integration-features-finance-ops/10-exercise-1 登录账号，这个是微软的虚拟机，IP在国外。

每天都要登录虚拟机去过验证，不是解决需人机验证的最佳办法。

**Comment by Harry-zklcdc** [comment]
查看：[wiki/解决-无效域&人机验证](/Harry-zklcdc/go-proxy-bingai/wiki/解决-无效域&人机验证)
