### ISSUE TITLE
[Help] 如何更改sydney.vcanbb.chat这一栏

### ISSUE THREAD

**Issue by xinxin2021** [Harry-zklcdc/go-proxy-bingai#89]
### Describe the help wanted

有没有办法更改服务选择中Cloudflare的`sydney.vcanbb.chat`，或者删掉也行，强迫症看着难受，试过了但是没用

### Steps to behave

已尝试更改过`frontend/public/compose.html` `frontend/src/stores/modules/chat/index.ts` `web/compose.html` `web/assets/index-5bb7d63d.js`，没用

### Expected behavior

我希望能把`sydney.vcanbb.chat`改了或删了

### Versions

- OS: Windows 10
- Browser & Version: Microsoft Edge 115
- GoProxiBing Version: 1.11.2

**Comment by luckyEason** [comment]
朋友，只有web/assets/index-5bb7d63d.js是需要改的，改完后要一键重置

**Comment by Harry-zklcdc** [comment]
> 朋友，只有web/assets/index-5bb7d63d.js是需要改的，改完后要一键重置

不完全对，web是构建出来的前端文件，应该改
https://github.com/Harry-zklcdc/go-proxy-bingai/blob/298bfd0b2310ae40aa19475ea30bc903b937fdf6/frontend/src/stores/modules/chat/index.ts#L25-L43

**Comment by xinxin2021** [comment]
> 朋友，只有web/assets/index-5bb7d63d.js是需要改的，改完后要一键重置

Thanks 忘记重置了（

**Comment by luckyEason** [comment]
> > 朋友，只有web/assets/index-5bb7d63d.js是需要改的，改完后要一键重置
> 
> 
> 
> 不完全对，web是构建出来的前端文件，应该改
> 
> https://github.com/Harry-zklcdc/go-proxy-bingai/blob/298bfd0b2310ae40aa19475ea30bc903b937fdf6/frontend/src/stores/modules/chat/index.ts#L25-L43
> 
> 
> 
> 然后重新构建前端页面，再打包

我没有用二进制文件😁
