### ISSUE TITLE
疑似NewBing回复答案链接Bug

### ISSUE THREAD

**Issue by laogou717** [Harry-zklcdc/go-proxy-bingai#9]
<img width="899" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/128354383/8a3e8266-6c1f-4ebd-920b-e499f96fb79e">
显示的链接点击之后会跳转到这个页面
<img width="1690" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/128354383/b841fe57-577e-488b-9620-57bb64f79810">
不知道是不是bug还是我们需要更改一些什么设置.

**Comment by Harry-zklcdc** [comment]
我这边没有这样的问题, 需要更多信息, 才能判断问题

**Comment by laogou717** [comment]
> 我这篇文章没有这样的问题，需要更多信息，才能判断问题

我复现了这个问题,跟浏览器的版本有关系,google没问题
