### ISSUE TITLE
在更新版本的时候，是否聊天服务器的接口或者接口版本号有所变动，我发现老版本的回答更加准确性。第一张是1.9.1，第二张是v1.11.0

### ISSUE THREAD

**Issue by ccodingfundddd** [Harry-zklcdc/go-proxy-bingai#90]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/139052477/3e136f85-16bf-470e-a950-fce11a3311e0)
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/139052477/0f771755-f2e4-413b-931d-238e18ae0dda)

**Comment by Harry-zklcdc** [comment]
这个不应该是个问题，建议多尝试几次，生成式AI特有的结果不稳定性

接口到现在都没变化

**Comment by ccodingfundddd** [comment]
嗯嗯，好的哈。
