### ISSUE TITLE
提个思路：不知道能不能行？

### ISSUE THREAD

**Issue by ccodingfundddd** [Harry-zklcdc/go-proxy-bingai#92]
继续要cookie等参数，可以在在docker-compose.yml上配上自己的微软账号和密码，刷新时间。到点了，自动去刷新重新取一次参数，或者提供一条命令，自己可以手动去刷新。

**Comment by Harry-zklcdc** [comment]
不能，过不了人机验证

**Comment by Xqh-Cxy** [comment]
> 不能，过不了人机验证
那么手动解决人机验证可以实现吗？

**Comment by FangZirui-E5** [comment]
我看一个叫[Pandora](https://github.com/pengzhile/pandora)的项目的README文件里面有一句话叫做“绕过cloudflare”，不知道这个技术放在go-proxy-bingai上行不行得通？
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/129593198/ee161760-a358-4440-8f48-989d875a9969)

**Comment by Harry-zklcdc** [comment]
> 我看一个叫[Pandora](https://github.com/pengzhile/pandora)的项目的README文件里面有一句话叫做“绕过cloudflare”，不知道这个技术放在go-proxy-bingai上行不行得通？ ![image](https://user-images.githubusercontent.com/129593198/258583086-ee161760-a358-4440-8f48-989d875a9969.png)

估计不太行，我看了一下代码，他是通过ChatGPT的手机版登录实现的，然而手机版的ChatGPT就没有Cloudflare的这个环节

**Comment by FangZirui-E5** [comment]
好吧

**Comment by FangZirui-E5** [comment]
那现在对于“在站内完成人机验证”这一点有没有什么进展啊

**Comment by Harry-zklcdc** [comment]
> 那现在对于“在站内完成人机验证”这一点有没有什么进展啊

看这个 #95

**Comment by FangZirui-E5** [comment]
原来这个就是在站内完成人机验证的基本思路

**Comment by Harry-zklcdc** [comment]
查看：[wiki/解决-无效域&人机验证](/Harry-zklcdc/go-proxy-bingai/wiki/解决-无效域&人机验证)
