### ISSUE TITLE
[Bug] 🐛 

### ISSUE THREAD

**Issue by TIANYUZHOU** [Harry-zklcdc/go-proxy-bingai#93]
### Describe the bug

这是什么报错：![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/53137506/b2744653-81fb-4ea9-9794-4a42f2527e82)

### Steps to reproduce

部署后出现在这个错误，无法进入聊天

### Expected behavior

进入聊天

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by Harry-zklcdc** [comment]
你的机器是国内VPS吧

**Comment by TIANYUZHOU** [comment]
> 你的机器是国内VPS吧

亚马逊 美国的啊

**Comment by Harry-zklcdc** [comment]
> 亚马逊 美国的啊

好像是被封了，那个线路

**Comment by TIANYUZHOU** [comment]
>  
> > 亚马逊 美国的啊
> 
> 好像是被封了，那个线路

啊……
