### ISSUE TITLE
[Help] 🤔 docker本地搭建，用cloudflare的内网穿透可以正常聊天，但是用樱花frp的内网穿透就会出现重新连接

### ISSUE THREAD

**Issue by rakaki** [Harry-zklcdc/go-proxy-bingai#96]
### Describe the help wanted

docker本地搭建，socks5代理
用cloudflare的内网穿透，无需填写任何参数，遇到验证就重置，可以正常聊天。
但是用樱花frp的内网穿透就会出现重新连接（同样都是https）；
想问下两者有什么区别，明明都是https，不过樱花的域名证书是不受信任的， 并且服务器是国内的。
![图片](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/88972415/0275742a-1b29-437d-850f-026ae7e24d18)

### Steps to behave

五

### Expected behavior

因为樱花frp的延迟更低，所以希望用樱花

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by rakaki** [comment]
试了下的确是证书的问题。换用cpolar的穿透，同样是大陆节点，证书可信，可以正常聊天

**Comment by skyfly2000** [comment]
试试nps 反代 [https://github.com/ehang-io/nps](url)

**Comment by Harry-zklcdc** [comment]
不清楚，内网穿透我用的是自己的，frp用过但是不熟悉，nps也是
