### ISSUE TITLE
[Help] 🤔 

### ISSUE THREAD

**Issue by SmartYou1995** [Harry-zklcdc/go-proxy-bingai#97]
### Describe the help wanted

Vercel 搭建完毕，已通过阿里域名进行了绑定。通过自己的域名已经可以访问界面，但是bing连接不了  只能选 Cloudflare 。咋解决呢？

### Steps to behave

无

### Expected behavior

无

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by wurenzhiwen666** [comment]
Vercel不支持websocket，无法使用本站
