### ISSUE TITLE
[Feature] 🌈 readme.md

### ISSUE THREAD

**Issue by wurenzhiwen666** [Harry-zklcdc/go-proxy-bingai#98]
### Describe the problem related to the feature request

希望更新readme.md

### Describe the solution you'd like

更新readme.md

**Comment by Harry-zklcdc** [comment]
在写了，之后教程会更新在wiki页面

**Comment by Harry-zklcdc** [comment]
https://github.com/Harry-zklcdc/go-proxy-bingai/wiki

Readme.md 等更新完后修改

**Comment by Harry-zklcdc** [comment]
已更新
