### ISSUE TITLE
[Bug] 🐛 配置了CF和用户cookie也没法使用

### ISSUE THREAD

**Issue by Pandas886** [Harry-zklcdc/go-proxy-bingai#99]
### Describe the bug
我是用vercel搭建的，还配置自己的cf。
<img width="1324" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/123344357/a065eac3-aa05-49c3-8c2b-71fb3bda6a53">

### Steps to reproduce

我搭建了cf worker。
<img width="1361" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/123344357/771e942f-d757-4319-96f4-c0e605a09375">
然后把地址配置到了服务区里，检测也成功。
<img width="1325" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/123344357/39cc1c15-07a7-4709-9a21-3c2d0b3cc242">
也设置了用户cookie
<img width="1312" alt="image" src="https://github.com/Harry-zklcdc/go-proxy-bingai/assets/123344357/9d7ae187-683a-43fc-90e4-f08891899015">

### Expected behavior

请问还差什么步骤吗，为什么无法使用呢

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version:

**Comment by wcgXi** [comment]
你在必应的官网上在“有创造力”模式下发送一条消息之后再试下！

**Comment by Enzo-K-GUAN** [comment]
有遇到这个吗？ Sorry, looks like your network settings are preventing access to this feature.

**Comment by ohmyivan** [comment]
我也是 用Vercel+CF 搭建不能用。 好像只能用导航里的vps +docker搭建

**Comment by monkey-soft** [comment]
> 我也是 用Vercel+CF 搭建不能用。 好像只能用导航里的vps +docker搭建

我今晚更新版本，使用 Vercel + CF 方式，提示无效域名，估计是 Vercel 的 IP 真不行了

**Comment by 7noemo** [comment]
别闹了，我就是 Vercel 和 cloudflare 的组合。两者都用自定义域名，稳的一批。
无效偶尔出现无效域的时候我就去bing官方聊几句，没一会就恢复了。

**Comment by shui063** [comment]
去官方过人机验证！！！

**Comment by Harry-zklcdc** [comment]
最新版试试
